### ISSUE TITLE
Support for MSVC with Visual Studio project files

### ISSUE THREAD

**Issue by KonanM** [ccache/ccache#1018]
With the new announcement that ccache 4.6 now supports windows I tried it out using Visual Studio project files. There are multiple ways to utilize ccache in that scenario. Here are described two ways: https://stackoverflow.com/questions/30761708/how-to-use-clang-compiler-with-msbuild/ and there is a third way by replacing the cl.exe (e.g. rename to cl-real.exe) by ccache.exe and then set CCACHE_COMPILER cl-real.exe and set CCACHE_COMPILERTYPE to msvc.

When using that I ran into multiple issues - the biggest one being that multiple files are passed to cl.exe 

> [2022-03-01T17:43:46.530839 236620] Multiple input files: <nameA>.cpp and <nameB>.cpp
> 
> [2022-03-01T17:43:46.530839 236620] Failed; falling back to running the real compiler
> 
> [2022-03-01T17:43:46.530839 236620] Executing C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64\cl_real.exe C:\Users\myname\AppData\Local\Temp\tmp8b9e1682df6f4cc7be0e622d8809e8e4.rsp
> 
> [2022-03-01T17:43:46.530839 236620] Result: multiple_source_files

But even when compiling a single cpp file within Visual Studio it fails:

> 
> [2022-03-01T17:49:50.170961 448640] Working directory: Z:/_CM/.cache/build/D/3dmodel
> 
> [2022-03-01T17:49:50.170961 448640] Compiler type: msvc
> 
> [2022-03-01T17:49:50.170961 448640] Not a regular file: 3dmodel_Object.dir\Debug\\
> 
> [2022-03-01T17:49:50.171968 448640] Failed; falling back to running the real compiler
> 
> [2022-03-01T17:49:50.171968 448640] Executing C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64\cl_real.exe C:\Users\kmahdi\AppData\Local\Temp\tmp411f254b56f34aaea604542e60e9d4ef.rsp
> 
> [2022-03-01T17:49:50.171968 448640] Result: bad_output_file

Seems like somehow the file path to the files is slightly messed up with those double backslashes `Not a regular file: 3dmodel_Object.dir\Debug\\`.

I just wanted to point out those issues for anyone wondering who the current support for Visual Studio Project files is and maybe there is a possibility to fix them.

**Comment by orgads** [comment]
#1019

**Comment by orgads** [comment]
By the way, you can use ccache without renaming the original cl. Just place ccache executable in a different directory (e.g. `C:\ccache`), rename it cl.exe, and pass `/p:CLToolPath=C:\ccache` to msbuild.

**Comment by justinpryzby** [comment]
The first problem ("multiple input files") can be worked around by passing /p:UseMultiToolTask=true

**Comment by justinpryzby** [comment]
Another issue is that the symlink way doesn't work on windows (readlink is #ifdefed out).
I've thus far been unable to make it work using CCACHE_COMPILER nor PREFIX.  It does this:

```
Command line: ...\ccache.exe @...\tmp54985e4f766d490d93b03cb4014ea199.rsp
Compiler type: msvc
No input file found
Using command-line prefix ccache.exe cl.exe
Failed; falling back to running the real compiler
```

It looks like the RSP file should have been expanded before checking if there's input source files ?  Or "No input files" is off by one when using CCACHE_COMPILER / PREFIX.  In some configurations that I've tried, msbuild tries to execute the RSP file, thinking that it's the compiler.  I'm sure some of my configurations attempts are wrong, but I cannot find one that works for this.
