### ISSUE TITLE
Ccache does not consider MSVC options in CL and _CL_ variables

### ISSUE THREAD

**Issue by justinpryzby** [ccache/ccache#1022]
### How to reproduce ###

`$CL` and `$_CL_` can specify options in addition to those specified on the command line.
ccache caches the results, but doesn't hash the content of the environment

### Actual behavior ###

I added and the latr removed /showincludes from _CL_ but stdout/stderr was still polluted, which made logs for my prior problem report noisier to look through.

### Expected behavior ###

ccache hashes the environment vars and knows to recompile when it changes.

### Environment ###
4.6 / GIT + patches

+ @orgads

**Comment by jrosdahl** [comment]
Just hashing the variables isn't enough – ccache needs parse the content and potentially rewrite or react to variable contents.
