### ISSUE TITLE
Command line to subordinate cl strange when certain options are used

### ISSUE THREAD

**Issue by BengtGustafsson** [ccache/ccache#1024]
### How to reproduce ###

1. I made a little launcher program (attached, renamed to cl.md to allow upload) which directs ccache to use actual_cl.exe which is a renamed version of Microsoft's cl.exe. This has probably nothing to do with the problem but explains the output from the ccache log shown down below.

2. When using ccache with the command line below Microsoft's cl.exe complains when called by ccache:

```
/permissive- /MP /ifcOutput "cvcommon.dir\Debug\" /GS- /Zc:rvalueCast /W3 /Zc:wchar_t /I"C:\src\honey\externals\CVCommon\cvcommon\include" /I"C:\src\honey\externals\CVCommon\cvcommon\src" /I"C:\src\honey\externals\CVCommon\cvcommon\include\cvcommon" /I"C:\src\honey\externals\CVCommon\xmlnode\include" /I"C:\src\honey\externals\CVCommon\xmlnode\..\cvcommon\include" /Zi /Gm- /Od /Ob0 /Fd"C:\build\honey\bin\Debug\cvcommon.pdb" /Zc:inline /fp:precise /D "_MBCS" /D "_DEBUG" /D "WIN32" /D "_WINDOWS" /D "__SSSE3__" /D "WIN64" /D "DISABLE_DK3_SUPPORT" /D "DISABLE_LICENSE_WRITEBACK" /D "_CRT_SECURE_NO_WARNINGS" /D "_SCL_SECURE_NO_WARNINGS" /D "NOMINMAX" /D "WIN32_LEAN_AND_MEAN" /D "NOSERVICE" /D "NOMCX" /D "NOIME" /D "NOSOUND" /D "NOCOMM" /D "NOKANJI" /D "NORPC" /D "NOPROXYSTUB" /D "NOIMAGE" /D "NOTAPE" /D "_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING" /D "_SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING" /D "_ENABLE_EXTENDED_ALIGNED_STORAGE" /D "CMAKE_INTDIR=\"Debug\"" /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /MDd /openmp /std:c++17 /Fa"cvcommon.dir\Debug\" /EHa /nologo /Fo"cvcommon.dir\Debug\" /Fp"cvcommon.dir\Debug\cvcommon.pch" /diagnostics:column 
```

Error message (not very relevant):

```
Command line error D8037 : cannot create temporary il file; clean temp directory of old il files.
```

When I read about this error message it was totally unrelated, so the cl parsing went horribly wrong.

### Actual behavior ###

The command line in the call to the actual cl.exe is botched up, including some quotes that should not be there, and some that are missing. This is under the assumption that the printout in the .ccache-log file is showing the true command line, (which is not entirely certain):

```
Command line: c:\Program Files\Microsoft Visual Studio\2022\Professional\vc\Tools\msvc\14.30.30705\bin\Hostx64\x64\actual_cl.exe /permissive-" /MP" /ifcOutput" cvcommon.dir\Debug /GS- /Zc:rvalueCast /W3 /Zc:wchar_t /IC:\src\honey\externals\CVCommon\cvcommon\include /IC:\src\honey\externals\CVCommon\cvcommon\src /IC:\src\honey\externals\CVCommon\cvcommon\include\cvcommon /IC:\src\honey\externals\CVCommon\xmlnode\include /IC:\src\honey\externals\CVCommon\xmlnode\..\cvcommon\include /Zi /Gm- /Od /Ob0 /FdC:\build\honey\bin\Debug\cvcommon.pdb /Zc:inline /fp:precise /D _MBCS /D _DEBUG /D WIN32 /D _WINDOWS /D __SSSE3__ /D WIN64 /D DISABLE_DK3_SUPPORT /D DISABLE_LICENSE_WRITEBACK /D _CRT_SECURE_NO_WARNINGS /D _SCL_SECURE_NO_WARNINGS /D NOMINMAX /D WIN32_LEAN_AND_MEAN /D NOSERVICE /D NOMCX /D NOIME /D NOSOUND /D NOCOMM /D NOKANJI /D NORPC /D NOPROXYSTUB /D NOIMAGE /D NOTAPE /D _SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING /D _SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING /D _ENABLE_EXTENDED_ALIGNED_STORAGE /D CMAKE_INTDIR=Debug /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /MDd /openmp /std:c++17 /Facvcommon.dir\Debug" /EHa" /nologo" /Focvcommon.dir\Debug /Fpcvcommon.dir\Debug\cvcommon.pch /diagnostics:column 
```

As can be seen from the attached launcher program file I set CCACHE_COMPILERTYPE to msvc

BTW: I also had to set HOME to something to get ccache to not complaining about not finding it, while setting CCACHE_CACHEDIR explicitly should make the HOME variable unnecessary it still complained. The complaint detailed something about an old compatibility mode which indicates that this may not be of interest for MSVC at all. I think the best way to get the user directory on Windows, if needed, is to call  [GetUserProfileDirectory](https://docs.microsoft.com/en-us/windows/win32/api/userenv/nf-userenv-getuserprofiledirectorya).

### Expected behavior ###

ccache to pass the incoming command line parameters along untouched. My guess is that ccache is doing something like creating an internal data structure of compiler option objects which are used in the hashing, and then generating the arguments to the actual compiler from this data structure. One of these steps is not entirely correct for MSVC.

I noted that the first fail is after /permissive- which with gcc interpretation could look like the next option starts with the - which is actually the last part of the preceding /permissive option. Note also that most of the quotes of file name strings in the incoming command line are removed by ccache. This is fine in this particular case as the paths don't have any spaces, but it could be a clue.

It can also be noted that the quoted quotes of the CMAKE_INTDIR definition in the original command line are not preserved, which could cause problems down the line. This may be the same issue as another recent bug report.

### Environment ###

ccache version 4.6.0

MSVC 2022 on Windows11. Have not tried on 2019 but it does seem unlikely it would accept such a bad command line.
[cl.md](https://github.com/ccache/ccache/files/8244533/cl.md)

**Comment by justinpryzby** [comment]
This may be the same issue as in # 1021.
Could you upload the original commandline before and after ccache ?  And point out which quotes are bungled up ?
It looks to me like INTDIR="DEBUG" is missing backslashes.
I'm afraid github is confusing the issue, so I'm not going to try to compare them further.

**Comment by BengtGustafsson** [comment]
Well, the CMAKE_INTDIR part could partly be the same as #1021, but if you look at the first part of the command lines (even here in the github UI) you can easily see that the first problem is that there is a " directly after the /permissive- option. But then the big problem is that the quoted file path after /ifcOutput lacks an ending quote. The root cause may be the same but my symptoms don't require nested quotes. If you point me at the source file where the parsing takes place I can take a look.

Attached is the command line exactly as ccache sees it (ccache_arguments.txt) as well as the log file containing the command line sent to the actual cl.exe.

[Debug.ccache-log.log](https://github.com/ccache/ccache/files/8254578/Debug.ccache-log.log)
[ccache_arguments.txt](https://github.com/ccache/ccache/files/8254586/ccache_arguments.txt)
.

**Comment by justinpryzby** [comment]
It looks to me like "/permissive- /MP" is being sent as a single argument.
How is that being specified (in a proj XML or in CL environment var or ??) ?
I'm not sure how well I can parse the command line, so I hesitate to guess as to any problems beyond the first.
...but, I think there's an additional problem in ifcOutput, as you said.

I wonder if this is caused by your own cl.cpp.  It loops around args, but makes no attempt to escape backslashes or quotes.
`
    for (int a = 1; a < argc; a++) {
        cmd += " \"";
        cmd += argv[a];
        cmd += "\"\"";
    }
`

**Comment by BengtGustafsson** [comment]
Right. There were bugs. But other issues abound:

- The "properties/C++/command line" that VS claims it uses for compilation is very far from reality, and does not handle the quoting of parameters ending with \ correctly. Unfortunately I didn't know this and used it for testing my cl.exe. In reality the command line is sent via a @<name>.rsp file which does the quoting properly.
- Sending an environment to CreateProcess does not add this to the existing environment but runs the program with _only_ this environment. Replacing this with a number of _putenv calls made it better.
- ccache does not support /Zi which means it doesn't work in the developer scenario, unfortunately. While it may be useful in CI in some cases the turn around time improvement in local builds (which are most often debug builds) is most valuable.
- When ccache reports that the option /Zi is not suppported it is reported as -Zi. This should be easy to fix.

All in all this means that there was no new bug here apart from #1021, I assume support for /Zi is going to be implemented (I don't know why it wouldn't work to just pass it to cl, doesn't seem to affect ccache).

It would be nice to find a solution to the replacement of cl that doesn't involve renaming the existing compiler and replacing it with ccache and setting a bunch of environment variables for it to find the original cl. Especially annoying as the cl.exe used is different depending on the bit count of both host and target, and ccache only reads one environment variable. As far as I can see solving this would need some help from Microsoft and/or cmake.

The attached updated version of my original program seems to work, at least allowing replacement of more than one cl.exe file by it and not requiring that the subordinate actual_cl.exe is in path. (Renamed from .cpp to .txt).
[cl.txt](https://github.com/ccache/ccache/files/8266758/cl.txt)

Feel free to use the code as you please. I'm just waiting for the /Zi support before I can try ccache out for real.

**Comment by justinpryzby** [comment]
On Wed, Mar 16, 2022 at 10:17:13AM -0700, Bengt Gustafsson wrote:
> - ccache does not support /Zi which means it doesn't work in the developer scenario, unfortunately. While it may be useful in CI in some cases the turn around time improvement in local builds (which are most often debug builds) is most valuable.

Note that /Z7 is supported.

> It would be nice to find a solution to the replacement of cl that doesn't involve renaming the existing compiler and replacing it with ccache and setting a bunch of environment variables for it to find the original cl.

I have this working with:

CCACHE_COMPILER: cl.exe
msbuild /p:CLToolExe=c:\ccache\bin\pgccache.exe

It was necessary to rename ccache.exe (not cl.exe) to something else, or else
it skips argv[0], expecting to find the compiler in argv[1], but then (as I
recall) tries to exec the RSP file.

That may be a bug.  In any case, it'd be great to document this better.

**Comment by BengtGustafsson** [comment]
Ok. Do you know of a way to get Visual Studio to put that switch on msbuild when you build from in there? And especially how to get this option set if cmake generates the vcxproj files, which seems more common than not these days.

Did ccache find cl.exe without explicitly adding it to path? Adding one cl.exe to path would make it hard to switch between 32 and 64 bit compilation, unfortunately. But maybe msbuild adds the correct bin directory to path before launching the subordinate compilations, in which case it would work.

**Comment by justinpryzby** [comment]
On Thu, Mar 17, 2022 at 05:06:42AM -0700, Bengt Gustafsson wrote:
> Ok. Do you know of a way to get Visual Studio to put that switch on msbuild when you build from in there? And especially how to get this option set if cmake generates the vcxproj files, which seems more common than not these days.

Actually, I think it should work to set the CL environment variable to the
switches you want.

**Comment by justinpryzby** [comment]
How did you install ccache ?  My renaming exe workaround was necessary when I installed using chocolatey.

**Comment by jrosdahl** [comment]
Is there more to do here now when #1021 is done?

**Comment by justinpryzby** [comment]
On Thu, Mar 17, 2022 at 05:06:42AM -0700, Bengt Gustafsson wrote:
> Ok. Do you know of a way to get Visual Studio to put that switch on msbuild when you build from in there? And especially how to get this option set if cmake generates the vcxproj files, which seems more common than not these days.
> 
> Did ccache find cl.exe without explicitly adding it to path? Adding one cl.exe to path would make it hard to switch between 32 and 64 bit compilation, unfortunately. But maybe msbuild adds the correct bin directory to path before launching the subordinate compilations, in which case it would work. 

Which switch, /p:CLToolExe ?  /p is to specify an arbitrary property of the
project or solution.

I don't actually use VS, except that I'm working with the postgresql project to
expand their testing coverage under cirrus CI, including MSVC.

Our build invocation looks like:
MSBFLAGS: -m -verbosity:minimal "-consoleLoggerParameters:Summary;ForceNoAlign" /p:TrackFileAccess=false -nologo [...]
    - vcvarsall x64
    - msbuild %MSBFLAGS% pgsql.sln

I believe ccache searches the path for CCACHE_COMPILER.  The intended path
would've been set by vcvarsall.
