### ISSUE TITLE
ccache caches preexisting object file when using -fsyntax-only

### ISSUE THREAD

**Issue by nwf** [ccache/ccache#1034]
### How to reproduce and Actual behavior ###

1. Write `null.o`, perhaps by compiling `null.c`, but really, any contents will do just fine.

2. Probe for compiler flags with `-fsyntax-only -x c /dev/null` using `ccache` (around `clang`, in my case).

   `ccache` "helpfully" adds `-o null.o` to the compiler invocation despite the use of `-fsyntax-only`:
   https://github.com/ccache/ccache/blob/1d2ca28a1f1c23e902f32644a4012ba59f76a45b/src/ccache.cpp#L939-L944
   But that's OK since the compiler will ignore it.

3. However, after compilation, `ccache` will not ignore the `null.o` created in step 1 and will, instead, cache it.
   https://github.com/ccache/ccache/blob/1d2ca28a1f1c23e902f32644a4012ba59f76a45b/src/ccache.cpp#L1067-L1078

4. Things are now quite dire: every time a build system repeats its probe from step 2, it will clobber `null.o` when it should have produced no output.

### Expected behavior ###

Given the dedicated support for `-fsyntax-only` since https://github.com/ccache/ccache/pull/685, `ccache` would not have gone looking for an output file in this case (that is, I expected step 3 to produce different results).

The introduction of `-o null.o` in step 3 also seems fairly unusual; I thought `a.out` was the usual name if `-o` was elided.  Is this a `-x c` thing?

### Environment ###
ccache version 4.6  (Debian package 4.6-1 for ppc64el, if that helps.)

For whatever it's worth, while it is definitely unusual to compile `/dev/null` and while `null.c` may be an unusual file name, these both happen in the FreeBSD source tree.  In fact, `sys/kern/dev/null.c` is the implementation of... `/dev/null`, for maximum amusement.  To FreeBSD's credit, this doesn't come up unless you have, like me, forced the use of ccache by pointing its build system at a ccache symlink (through which it cannot see); its `CCACHE_BUILD`s attempt to dodge `ccache` when doing the probing compiles of `/dev/null`.

**Comment by jrosdahl** [comment]
Thanks for the bug report!

> The introduction of -o null.o in step 3 also seems fairly unusual; I thought a.out was the usual name if -o was elided. Is this a -x c thing?

a.out is the default when producing an executable (`$COMPILER example.c`). The default when producing an object file (`$COMPILER -c example.c`) is "source code file base name with a .o extension".
