### ISSUE TITLE
Add documentation for MSVC + multiple files

### ISSUE THREAD

**Issue by justinpryzby** [ccache/ccache#1039]
The documented ways to use ccache are: 1) symlinks to compiler (but symlinks do not work on windows); 2) prefixing the compiler commandline with "ccache" (it's not clear how to make MSVC do that).  I think this means that COMPILER must be set to cl.exe, and the compilertype *must* be set to msvc.  The docs should probably say that for MSVC, since the usual ways don't work.

Also, when I tried to use ccache 4.6 installed by chocolatey, it still didn't work until I also renamed ccache.exe to another name (pgccache.exe) and referenced it by using msbuild /p:CLToolExe=pgccache.exe.  Note that it did not work to copy the chocolatey "shim" exe.  This was very confusing.

Not caching due to "multiple input files" can be avoided around by passing cl.exe /p:UseMultiToolTask=true.
Or by changing the project file to include the filename: <ObjectFileName>...\%(Filename).obj</ObjectFileName>

FYI, I'm trying to use ccache for the postgres project's use of cirrus CI.

@orgads

**Comment by jrosdahl** [comment]
> The documented ways to use ccache are: 1) symlinks to compiler (but symlinks do not work on windows);

I thought they do nowadays? For example, see <https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/>.

> 2) prefixing the compiler commandline with "ccache" (it's not clear how to make MSVC do that).

I don't know either.

Is it possible to specify another compiler than cl.exe? If so perhaps you can create a wrapper script that calls `ccache cl.exe [...]` and configure MSVC to use that script as the compiler?

> I think this means that COMPILER must be set to cl.exe, and the compilertype _must_ be set to msvc.

Isn't it enough to set `CCACHE_COMPILER=cl` or `CCACHE_COMPILER=cl.exe`? Ccache will then guess compiler type from the name "cl".

> The docs should probably say that for MSVC, since the usual ways don't work.

I don't think there's a good place in the manual for specific IDEs or build environments like this. How about putting tips & tricks in a [wiki page](https://github.com/ccache/ccache/wiki)?

> Also, when I tried to use ccache 4.6 installed by chocolatey, it still didn't work until I also renamed ccache.exe to another name (pgccache.exe) and referenced it by using msbuild /p:CLToolExe=pgccache.exe. Note that it did not work to copy the chocolatey "shim" exe. This was very confusing.

I don't quite understand what you mean by this. Why would you need to rename ccache.exe?

**Comment by justinpryzby** [comment]
On Wed, Jun 08, 2022 at 01:54:38AM -0700, Joel Rosdahl wrote:
> > The documented ways to use ccache are: 1) symlinks to compiler (but symlinks do not work on windows);
> 
> I thought they do nowadays? For example, see <https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/>.

I mean that symlinks don't work under ccache under windows, per
guess_compiler().  Maybe that needs to change.

> > 2) prefixing the compiler commandline with "ccache" (it's not clear how to make MSVC do that).
> 
> I don't know either.
> 
> Is it possible to specify another compiler than cl.exe? If so perhaps you can create a wrapper script that calls `ccache cl.exe [...]` and configure MSVC to use that script as the compiler?

I think this works poorly for at least two reasons:
1) there are different cl.exe for building x86 vs x86_64.
2) a script would have overhead of forking another yet another process and
parsing its args, which seem to be very expensive on windows.

> > Also, when I tried to use ccache 4.6 installed by chocolatey, it still didn't work until I also renamed ccache.exe to another name (pgccache.exe) and referenced it by using msbuild /p:CLToolExe=pgccache.exe. Note that it did not work to copy the chocolatey "shim" exe. This was very confusing.
> 
> I don't quite understand what you mean by this. Why would you need to rename ccache.exe?

I think ccache was stripping away all the leading "ccache" arguments.
If I didn't rename it, it found only the RSP file, with no compiler, which of
course fails.

**Comment by jrosdahl** [comment]
> I mean that symlinks don't work under ccache under windows, per guess_compiler().  Maybe that needs to change.

`guess_compiler` only has to do with guessing the compiler type (e.g. gcc, clang or msvc). I suppose you mean `find_compiler`. Right, it's possible that it doesn't work with Windows symlinks, don't know.

> I think this works poorly for at least two reasons:
> 1) there are different cl.exe for building x86 vs x86_64.

(You would of course then have to use one wrapper script for each variant.)

> 2) a script would have overhead of forking another yet another process and
> parsing its args, which seem to be very expensive on windows.

Right.

> Note that it did not work to copy the chocolatey "shim" exe. This was very confusing.

What do you mean by "chocolatey shim exe"?

> I think ccache was stripping away all the leading "ccache" arguments. If I didn't rename it, it found only the RSP file, with no compiler, which of course fails.

OK, now I maybe understand what you're doing: You renamed ccache.exe to pgccache.exe and then use pgccache.exe as the compiler. Then you set `CCACHE_COMPILER` to select the compiler? This makes ccache believe it's masquerading as the compiler "pgcache" but overridden with `CCACHE_COMPILER`. Is that correct? If not, please describe in more detail what you did, what you expected and what didn't work.

Letting ccache masquerading as a compiler like that does seem to work but it's more of a coincidence than how it's supposed to work.

I thought some more about this and I've now implemented support for proper masquerading without using symlinks: 451d92c801d6463bcc54c090b871a1d77f26d9d4. You would then do like this:

1. Copy `ccache.exe` to `somewhere\cl.exe`.
2. Put the directory of the real `cl.exe` in PATH. (Or: Set `CCACHE_PATH`.)
3. Use `somewhere\cl.exe` as the compiler

Do you think that this will solve your problem?

**Comment by justinpryzby** [comment]
On Fri, Jun 10, 2022 at 11:16:42AM -0700, Joel Rosdahl wrote:
> > Note that it did not work to copy the chocolatey "shim" exe. This was very confusing.
> 
> What do you mean by "chocolatey shim exe"?

chocolatey (which I've never used until recently) installs ccache.exe to a
location like:
c:\ProgramData\chocolatey\lib\ccache\tools\ccache-4.6.1-windows-x86_64\ccache.exe

And also installs a "shim" into a location like:
C:\ProgramData\chocolatey\bin

Only the 2nd location is included in the path.
Copying the "shim" does not work, but copying the actual ccache.exe does work.

> > I think ccache was stripping away all the leading "ccache" arguments. If I didn't rename it, it found only the RSP file, with no compiler, which of course fails.
> 
> OK, now I maybe understand what you're doing: You renamed ccache.exe to pgccache.exe and then use pgccache.exe as the compiler. Then you set `CCACHE_COMPILER` to select the compiler? This makes ccache believe it's masquerading as the compiler "pgcache" but overridden with `CCACHE_COMPILER`. Is that correct? If not, please describe in more detail what you did, what you expected and what didn't work.

Yes, correct.

> Letting ccache masquerading as a compiler like that does seem to work but it's more of a coincidence than how it's supposed to work.

That's consistent with my understanding :)
However it was also the only way I got things to work.

> I thought some more about this and I've now implemented support for proper masquerading without using symlinks: 451d92c801d6463bcc54c090b871a1d77f26d9d4. You would then do like this:
> 
> 1. Copy `ccache.exe` to `somewhere\cl.exe`.
> 2. Put the directory of the real `cl.exe` in PATH. (Or: Set `CCACHE_PATH`.)
> 3. Use `somewhere\cl.exe` as the compiler
> 
> Do you think that this will solve your problem?

I checked that that allows compiling postgres (using cirrus ci as a "remote
compiler", as I don't have MSVC at all).  It works without setting
CCACHE_COMPILER.

But actually .. v4.6.1 also works without setting CCACHE_COMPILER, too
I had not gotten this to work until just now.
https://cirrus-ci.com/task/6024421201674240

**Comment by vvainola** [comment]
I have been using ccache by creating two files next to the Visual Studio solution. A symlink named "cl.exe" that points to the ccache.exe and Directory.Build.props with following contents. Path @build_root@ is absolute path to the folder containing the solution.
```
<Project>
    <PropertyGroup>
            <ClToolExe>cl.exe</ClToolExe>
            <ClToolPath>@build_root@</ClToolPath>
    </PropertyGroup>
</Project>
```
If you are calling cl.exe directly, creating just the symlink to the working directory should work because calling cl.exe should pick first the cl.exe in the working directory and ccache will then call real cl.exe.

**Comment by justinpryzby** [comment]
Thanks.  Note that I've started/created:
https://github.com/ccache/ccache/wiki/Compiling-with-ccache-and-MS-Visual-Studio

Feel free to add to it.

**Comment by jrosdahl** [comment]
@justinpryzby wrote:
> But actually .. v4.6.1 also works without setting CCACHE_COMPILER, too I had not gotten this to work until just now. [cirrus-ci.com/task/6024421201674240](https://cirrus-ci.com/task/6024421201674240)

It kind of works with 4.6.1, yes, but only if you don't add the copied ccache.exe to a directory that is in %PATH% (and before the directory with cl.exe) since it then will loop forever. A fix for that is mainly what I implemented in 451d92c801d6463bcc54c090b871a1d77f26d9d4, along with some documentation.

**Comment by akrieger** [comment]
I can only get things to work if I use the impersonation method like @vvainola described. If I set `CLToolExe` to `ccache.exe` I get the following kind of output. Note I'm using Visual Studio 2022 17.3.0 Preview 6.0.

```
1>ccache : error : execute_noreturn of @C:\Users\akrieger\AppData\Local\Temp\tmpb5de0047f7094248b3d8eccbcc2d93d9.rsp failed: No error
```

The commandline according to VS looks like

```
1>    O:\open\personal\ccache-4.6.1\ccache.exe /c /I"O:\open\personal\Cataclysm-DDA\msvc-full-features\..\src" /I"O:\open\personal\Cataclysm-DDA\msvc-full-features\..\src\third-party" /I"O:\open\personal\Cataclysm-DDA\msvc-full-features\vcpkg_installed\x64-windows-static\x64-windows-static\include" /Z7 /nologo /W1 /WX- /diagnostics:column /sdl- /O2 /Oi /D TILES /D _CONSOLE /D SDL_SOUND /D SDL_BUILDING_LIBRARY /D RELEASE /D _SCL_SECURE_NO_WARNINGS /D _CRT_SECURE_NO_WARNINGS /D WIN32_LEAN_AND_MEAN /D LOCALIZE /D USE_VCPKG /D _MBCS /Gm- /EHsc /MT /GS- /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++14 /permissive- /Fo"O:\open\personal\Cataclysm-DDA\msvc-full-features\Cataclysm-lib-vcpkg-static\Release\x64\clzones.obj" /Fd"O:\open\personal\Cataclysm-DDA\msvc-full-features\..\Cataclysm-lib-vcpkg-static-Release-x64.pdb" /external:W1 /Gd /TP /wd4819 /wd4146 /wd26495 /wd26444 /wd26451 /wd4068 /wd6319 /wd6237 /FC /errorReport:prompt /bigobj /utf-8 ..\src\clzones.cpp
```

It doesn't matter if I set the values in `Directory.Build.props`, in a custom property sheet loaded before `Microsoft.Cpp.props`, or in a custom property sheet loaded after `Microsoft.Cpp.props`, the outcome is the same.

If I additionally set `CCACHE_PREFIX` to `cl.exe`, though, it works. This is brittle and means I cannot easily switch from cl.exe to clang-cl.exe without also changing my env vars, which the impersonation method does allow.

**Comment by jrosdahl** [comment]
@akrieger: Thanks for updating the wiki page.

I don't know what the best setup is for Visual Studio, but I do know that using `CCACHE_PREFIX` to specify the compiler is not right. Ccache needs to know about the real compiler since it collects information about it as part of the input hash, and the command specified with `CCACHE_PREFIX` is not considered to be a compiler. The only two ways that are supported are "masquerade as the compiler" and "add ccache as a prefix to the compiler". I have adjusted the wiki page accordingly.

**Comment by akrieger** [comment]
I updated the wiki with an additional blurb about Visual Studio's behavior when the ccache folder is not located under %TEMP% and how that interacts poorly with incremental builds.

**Comment by jrosdahl** [comment]
@justinpryzby: Do you think that we can close this issue now?
