### ISSUE TITLE
CCACHE_BASEDIR does not reproduce absolute paths in dependency file

### ISSUE THREAD

**Issue by comex** [ccache/ccache#1042]
### How to reproduce ###

1. Clone [this gist](https://gist.github.com/comex/a4c8fa3593be54df248ac18bfc447b64).
2. `make`
3. `touch foo.h`
4. `make`

### Actual behavior ###

```
make: `/Users/comex/c/ccache-issue/foo.o' is up to date.
```

### Expected behavior ###

foo.o is rebuilt.

### Why it happens ###

The Makefile uses absolute paths, so the compiler invocation is:
```
ccache cc -c -o /Users/comex/c/ccache-issue/foo.o /Users/comex/c/ccache-issue/foo.c -MD
```

But due to the use of `CCACHE_BASEDIR`, `foo.d` uses relative paths:
```
foo.o: foo.c foo.h
```

Make doesn't know that `foo.o` and `/Users/comex/c/ccache-issue/foo.o` are the same file, so when it reads the depfile, it interprets `foo.o` as some other file the user did not ask to build.  The file the user did ask to build, `/Users/comex/c/ccache-issue/foo.o`, only depends on `/Users/comex/c/ccache-issue/foo.c` (as specified in the makefile itself), so Make thinks it's up-to-date.

This doesn't happen without `CCACHE_BASEDIR`.

This seems like the same fundamental issue as #876, but in that report it was stated that:

> Just to clarify: dependency files are erroneous if absolute paths are used and the dependency file is interpreted from _another working directory inside the project than the working directory inside the project at the time of compilation_.

In this case, however, the working directory is the same at all times.  The symptom is also more serious: failing to perform necessary rebuilds, rather than performing unnecessary ones.

Arguably the dependency file is not "erroneous", in the sense that it correctly states that `foo.o` depends on `foo.c`.  But neither Make nor Ninja automatically treats absolute and relative paths as equivalent.

If this is really working as intended, then a warning should be added to the documentation of `CCACHE_BASEDIR`.

### Environment ###

0b3c5f17de5af6b5f0520295d96eb21c6ebe5a60, macOS

**Comment by jrosdahl** [comment]
Thanks for the bug report and analysis.

No, the behavior is not intended – it's a case that hasn't occurred to me before. I think that it might be fixable, but it's not trivial. I'll have think some more about this.
