### ISSUE TITLE
Ccache fails under fakeroot if /run/user/0/ccache-tmp exists

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#1044]
### How to reproduce ###

1. As root: `mkdir -p /run/user/0/ccache-tmp`
2. `touch test.c`
3. `fakeroot ccache gcc -c test.c`

### Actual behavior ###

```
ccache: error: Failed to create temporary file for /run/user/0/ccache-tmp/tmp.cpp_stdout.vC3Jmv: Permission denied
```

### Expected behavior ###

Compilation succeeds.

### Environment ###

ccache version 4.6.

See also https://github.com/ccache/ccache/issues/984#issuecomment-1081074884.

**Comment by ottok** [comment]
Thanks! Fix looks good.
