### ISSUE TITLE
test.inode_cache failed in concurrent test.

### ISSUE THREAD

**Issue by xkszltl** [ccache/ccache#1045]
### How to reproduce ###

Get a machine with enough cores.
Mine is Ubuntu 18.04 running on 36C/72T machine, and build within ubuntu/debian docker.

Also tried other machines with less core count and different host kernel/filesystems, and haven't seen the issue (mention this because it's an inode test.).

Build with cmake and `CTEST_PARALLEL_LEVEL=$(nproc) ctest`.

More details here:
https://github.com/xkszltl/Roaster/blob/5887c10ba89819ff3e81d04150facd9972b56a1b/pkgs/ccache.sh#L30-L48

### Actual behavior ###

```
98% tests passed, 1 tests failed out of 45

Total Test time (real) =  29.01 sec

The following tests did not run:
         17 - test.ivfsoverlay (Skipped)
         19 - test.modules (Skipped)
         20 - test.multi_arch (Skipped)
         24 - test.nvcc (Skipped)
         25 - test.nvcc_direct (Skipped)
         26 - test.nvcc_ldir (Skipped)
         27 - test.nvcc_nocpp2 (Skipped)
         30 - test.profiling_clang (Skipped)
         32 - test.profiling_hip_clang (Skipped)
         33 - test.readonly (Skipped)
         34 - test.readonly_direct (Skipped)
         35 - test.sanitize_blacklist (Skipped)
         38 - test.secondary_redis (Skipped)
         40 - test.serialize_diagnostics (Skipped)
         44 - test.trim_dir (Skipped)

The following tests FAILED:
         15 - test.inode_cache (Failed)
```

In `build/Testing/Temporary/LastTest.log`:

```
513 15/45 Testing: test.inode_cache
514 15/45 Test: test.inode_cache
515 Command: "/bin/bash" "/tmp/scratch/ccache/test/run" "inode_cache"
516 Directory: /tmp/scratch/ccache/build
517 "test.inode_cache" start time: Apr 05 06:28 UTC
518 Output:
519 ----------------------------------------------------------
520 Compiler:         gcc (/usr/bin/gcc)
521 Compiler version: gcc (Debian 10.2.1-6) 10.2.1 20210110
522 CUDA compiler:    not available
523 
524 Running test suite inode_cache....
525 FAILED
526 
527 Test suite:     inode_cache (line 37)
528 Test case:      Hard link
529 Failure reason: Found 0 (expected 1) hit for test2.c
```

### Expected behavior ###

All passed.
This may be a recent regression as parallel ctest was working before.
Sequential ctest works fine.

Latest release tag v4.6

**Comment by jrosdahl** [comment]
I've seen that error locally (intermittently and very rarely) ever since ccache 4.0 when the inode cache feature was added, so I doubt that it's a regression. For me, it always works the next time I run the tests, and I haven't been able to pinpoint the root cause. Any ideas on how to reproduce the problem more reliably are welcome.

**Comment by xkszltl** [comment]
On an Azure VM (more specifically, F72s_v2 SKU), I've been able to repro it consistently for a few time right before filing this.
My guess would be:
- Too many opened files (setting ulimit may reduce the core count for stable repro in this case)
- Shared files across tests cases. I would suggest for some grep and code review to fix, if any.

Regarding repro, see if you can use `ctest --schedule-random`, or set `CTEST_PARALLEL_LEVEL` to a huge one rather than nproc.

**Comment by xkszltl** [comment]
Just tried, I can get this quite easily with CTEST_PARALLEL_LEVEL=1000 on a smaller machine.

**Comment by xkszltl** [comment]
> For me, it always works the next time I run the tests

FYI, my build script always restarts from scratch, with a reclone of repro, to avoid any left over test files.

**Comment by jrosdahl** [comment]
Thanks. I think I know the problem now.
