### ISSUE TITLE
Improve manifest handling for primary/secondary storage

### ISSUE THREAD

**Issue by bengtj** [ccache/ccache#1049]
We're investigating an issue with high system load in our build cluster caused by looking for files during preprocessing. Then we tested depend mode and the sysload got even worse. It turns out that this was largely an issue with the way manifests are handled in secondary storage.

In short the problem comes from the fact that a manifest file is never updated from secondary storage when there is a manifest for that source file/compiler/flag combination in the local cache. It follows the same method as other files first looking for the local file and then try to fetch it from secondary storage. But as the manifest files are updated with new combinations of header file hashes this does not work well for manifests.

Also, the secondary storage cache manifest files are continuously being overwritten with manifest files based on the local cache manifest for the latest machine that lacked an entry for a header file combination. So the manifest files in secondary storage normally only contains few entries.

We tried a quick fix in calculate_result_and_manifest_key() updating this part in ccache 4.5.1:
```
    const auto manifest_path =
      ctx.storage.get(*manifest_key, core::CacheEntryType::manifest);

    if (manifest_path) {
      LOG("Looking for result key in {}", *manifest_path);
      MTR_BEGIN("manifest", "manifest_get");
      try {
        const auto manifest = read_manifest(*manifest_path);
        result_key = manifest.look_up_result_digest(ctx);
      } catch (const core::Error& e) {
        LOG("Failed to look up result key in {}: {}", *manifest_path, e.what());
      }
      MTR_END("manifest", "manifest_get");
      if (result_key) {
        LOG_RAW("Got result key from manifest");
      } else {
        LOG_RAW("Did not find result key in manifest");
      }
    }
```

To something like this:
1. Look for manifest in local cache only, try to find result key for the set of header files.
2. If no key found, then fetch manifest from secondary cache only and look for result key.
3. If key still not found, then continue with preprocessed hits and real compilation as normal.
4. When manifest is later updated upload the new version of the manifest. Which is now based on the secondary cache manifest with an added entry.

This works so much better in our setup. Entries are now added to the secondary storage manifest whenever header files are changed and other build machines directly takes advantage of this. Before things were quite confusing because the build time on a certain build machine was so dependendant on the state of the manifests in the local cache. As our preprocessed hits are expensive this affected the build times a lot for a long time after a header update.

The solution above works much better BUT it would work even better if step 2 would merge the local manifest with the secondary storage manifest. Clients that are not allowed to update the secondary cache would then be able to accumulate local header file combinations and seamlessly combine them with "upstream" changes. In this case depend mode should work great in our setup.

Thank you for a great piece of software!

**Comment by fabtrie** [comment]
Hallo @bengtj,

a few minutes before you reported this issue, I analysed the exact same behavior. Thank you for reporting this.

Would it be possible for you to share this code? Maybe we even can use it as a basis for creating a pull request.

**Comment by bengtj** [comment]
@fabtrie: Unfortunately this was the last thing I did before leaving for Easter vacation so I do not have the the code now. I'll see what I can do when I get back in a week or so.

It was a quick fix adding an enum parameter to storage.get() to specify if it should work as before, only fetch from primary cacche or only fetch from secondary cache. Then I duplicated the code snippet above and first fetched from primary only and then from secondary only.

But I was really hoping that @jrosdahl would improve on the fix and add merging of manifests. Please :)

**Comment by jrosdahl** [comment]
Sounds like a good idea to improve the manifest handling by merging entries from primary and secondary storage. The current implementation is kind of the simplest possible and there is certainly room for improvement.

I won't have to work on this near-term, though.

**Comment by bengtj** [comment]
I rebased our patch to master friday and I plan to to some testing tomorrow. I'll upload a pull request for that solution after that. There has been a try/catch added in the changed code and I want to be sure that it still is working properly.

It has been running in production with good results since posting this. It fixes almost all problems with the current solution. The case where merging would make a difference are for clients that are not allowed to write to secondary storage. We have this mixed setup and it still works much better with the patch.

The more advanced merging is of course the best so good that this became a feature request. Thank you!

**Comment by bengtj** [comment]
Thank you!
