### ISSUE TITLE
Support -fprofile-abs-path

### ISSUE THREAD

**Issue by Delgan** [ccache/ccache#1060]
### How to reproduce ###

1. Compile program using Ccache+GCC with `-fprofile-abs-path` option

### Actual behavior ###

The file can't be cached: `"Failed; falling back to running the real compiler"`.

### Expected behavior ###

Hi.

I would like to know if this command is purely incompatible with Ccache or is its handling not implemented?

### Environment ###

ccache version 4.6
Ubuntu 18.04

**Comment by ssproessig-thales** [comment]
Add it maybe somewhere around https://github.com/ccache/ccache/blob/master/src/argprocessing.cpp#L185?

**Comment by jrosdahl** [comment]
An unsupported option is not a bug (unless ccache makes the compilation fail or misbehave), so I'm going to convert this issue into a feature request to support `-fprofile-abs-path`.
