### ISSUE TITLE
ccache 4.6 crashes when building texlive-base with CCACHE_BASEDIR

### ISSUE THREAD

**Issue by olegsidorkin** [ccache/ccache#1074]
ccache 4.6 crashes when building texlive-base with the following stacktrace:

```
> (gdb) bt
#0  thr_kill () at thr_kill.S:4
#1  0x0000000800906754 in __raise (s=s@entry=6) at /usr/src/lib/libc/gen/raise.c:52
#2  0x00000008009b8eb9 in abort () at /usr/src/lib/libc/stdlib/abort.c:67
#3  0x00000008007bedc9 in report_failure (err=<optimized out>, thrown_exception=0x801046140) at /usr/src/contrib/libcxxrt/exception.cc:714
#4  0x000000000036b4a7 in nonstd::sv_lite::basic_string_view<char, std::__1::char_traits<char> >::substr (this=0x7fffffff7980, pos=1, n=18446744073709551615) at ./src/third_party/nonstd/string_view.hpp:716
#5  0x00000000003803cd in Util::make_relative_path (base_dir="/data/build/usr/ports/print/texlive-base/work/texlive-20210325-source",
    actual_cwd="/data/build/usr/ports/print/texlive-base/work/texlive-20210325-source/utils/pmx", apparent_cwd="/data/build/usr/ports/print/texlive-base/work/texlive-20210325-source/utils/pmx", path=...)
    at ./src/Util.cpp:889
#6  0x0000000000380dd8 in Util::make_relative_path (ctx=..., path=...) at ./src/Util.cpp:925
#7  0x00000000003391cd in process_preprocessed_file (ctx=..., hash=..., path="/run/user/0/ccache-tmp/tmp.cpp_stdout.YdM9Xj.i") at ./src/ccache.cpp:556
#8  0x0000000000336a30 in get_result_key_from_cpp (ctx=..., args=..., hash=...) at ./src/ccache.cpp:1158
#9  0x000000000032d55b in calculate_result_and_manifest_key (ctx=..., args=..., preprocessor_args=..., hash=..., direct_mode=false) at ./src/ccache.cpp:1797
#10 0x000000000032338a in do_cache_compilation (ctx=..., argv=0x7fffffffd928) at ./src/ccache.cpp:2264
#11 0x000000000031f719 in cache_compilation (argc=43, argv=0x7fffffffd928) at ./src/ccache.cpp:2045
#12 0x000000000031f300 in ccache_main (argc=43, argv=0x7fffffffd928) at ./src/ccache.cpp:2358
#13 0x000000000031e412 in main (argc=43, argv=0x7fffffffd928) at ./src/main.cpp:24
(gdb) up 5
#5  0x00000000003803cd in Util::make_relative_path (base_dir="/data/build/usr/ports/print/texlive-base/work/texlive-20210325-source",
    actual_cwd="/data/build/usr/ports/print/texlive-base/work/texlive-20210325-source/utils/pmx", apparent_cwd="/data/build/usr/ports/print/texlive-base/work/texlive-20210325-source/utils/pmx", path=...)
    at ./src/Util.cpp:889
889     ./src/Util.cpp: No such file or directory.
(gdb) p path
$1 = {data_ = 0x20b38a ".", size_ = 1}
(gdb) up 1
#6  0x0000000000380dd8 in Util::make_relative_path (ctx=..., path=...) at ./src/Util.cpp:925
925     in ./src/Util.cpp
(gdb) p path
$2 = {data_ = 0x7fffffff7ee9 "", size_ = 0}
(gdb)
```

the library is generated by f2c and has lots of lines like

`#line 1 ""`

that are preprocessed to 
`# 1 ""`

and then inc_path becomes empty string,

Ccache tries to invoke [Util::make_relative_path](https://github.com/ccache/ccache/blob/1892e4d3e8ece73a922ac8fe883b4391227d2700/src/ccache.cpp#L557) with empty path,

[original_path](https://github.com/ccache/ccache/blob/1892e4d3e8ece73a922ac8fe883b4391227d2700/src/Util.cpp#L887) becomes an empty string,
[path](https://github.com/ccache/ccache/blob/1892e4d3e8ece73a922ac8fe883b4391227d2700/src/Util.cpp#L890) is replaced with "." because of [special case](https://github.com/ccache/ccache/blob/1892e4d3e8ece73a922ac8fe883b4391227d2700/src/Util.cpp#L445)
and then [substr](https://github.com/ccache/ccache/blob/1892e4d3e8ece73a922ac8fe883b4391227d2700/src/Util.cpp#L892) [throws](https://github.com/ccache/ccache/blob/1892e4d3e8ece73a922ac8fe883b4391227d2700/src/third_party/nonstd/string_view.hpp#L716) exception.

I failed to reproduce the crash manually however make crashes reliably.

my local fix is to bypass all path processing if p == q [somewhere here](https://github.com/ccache/ccache/blob/1892e4d3e8ece73a922ac8fe883b4391227d2700/src/ccache.cpp#L542)

I think test case should be here but I still unable to reproduce it outside texlive package building process.

**Comment by jrosdahl** [comment]
Note: This requires CCACHE_BASEDIR to be set. I update the issue title.

**Comment by olegsidorkin** [comment]
Thanks :)
