### ISSUE TITLE
ccache misbehaves with -iquoute  and -isystem

### ISSUE THREAD

**Issue by nolange** [ccache/ccache#108]
Run the following snippet:

```
echo "int foo() {return 0;}" >/tmp/ctest.cpp
ccache -C
ccache clang -iquote.  -c /tmp/ctest.cpp
ccache -C
CCACHE_CPP2=true ccache clang -iquote.  -c /tmp/ctest.cpp
```

The first ccache call will warn about 
> clang: warning: argument unused during compilation: '-iquote .'

The second will finish without a warning

What happens is, that unlike the correctly supported -I option, the -iquote and -isystem arguments are passed to the compiler together with the preprocessed source.

> Executing /usr/bin/clang -iquote. -fcolor-diagnostics -c -o ctest.o /home/***

-iquote and -isystem should be handled the same way as -I flags (excluded when using preprocessed sources). clang does warn about those unused options, gcc doesnt.

**Comment by nolange** [comment]
The reason seems to be, that those options don`t have the TAKES_CONCAT_ARG set

**Comment by itensionanders** [comment]
Actually, they do now - since 5dc1bd5f5d49950911223bce4b8192ea1042cf19

So upgrading ccache, to version 3.2.5, should take care of this issue for you ?

**Comment by nolange** [comment]
Nope, the fix is not in the released 3.2.5 which I am using through the debian package. Neither the download archive nor the git-tag 3.2.5, nor the debian package.

Probably have to wait until 3.3?

**Comment by itensionanders** [comment]
@nolange : you are right, it is only on master.

Used `git describe` (which showed the merged version) instead of `git branch --all --contains`.

**Comment by jrosdahl** [comment]
Fixed on master.
