### ISSUE TITLE
Cache assembler listing file (`-Wa,-a=file.lst`)

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#1090]
It would be nice if ccache would support caching assembler listing files specified with compiler option `-Wa,-a=file.lst`. See b36a81893c6f and #1083.

**Comment by phush0** [comment]
Activating unconditionally https://github.com/ccache/ccache/commit/b36a81893c6f2cd20087815df2ddeb56dd547813 is making ccache unusable to all embedded projects which are using extensively this options including STM32 CUBE, ESP32 IDF and so on. Until full implementation of this feature please consider using something like sloppiness to activate it by hand.

**Comment by jrosdahl** [comment]
Hi,

> Until full implementation of this feature please consider using something like sloppiness to activate it by hand.

I have now considered this. I'm not going to add a sloppiness setting since it will be obsolete after implementing proper support for assembler listings anyway. I think that it is better to invest the time into supporting the feature for real instead of spending time on workarounds.

> I can not use ccache because of it or manually edit hundreds of projects on my hard drive.

Of course you can! Just use an older ccache version.
