### ISSUE TITLE
Shared cache on Windows no hit

### ISSUE THREAD

**Issue by Esysc** [ccache/ccache#1094]
I recently open a discussion #1084 because I was not sure about my understanding on how `ccache` works. I'm now opening an issue hoping some Windows developers can help to understand. Basically I systematically get no cache hits despite there is no change in the source code. all the details are in the discussion ticket above.
I've read multiple time the documentation and to my understanding `CCACHE_BASEDIR` should aim to transform absolute paths into relatives: https://ccache.dev/manual/4.6.1.html#_configuration_file_syntax ->  base_dir (CCACHE_BASEDIR). The working directory has always the same distance form the root of the drive.

Here is a diff example between 2 builds where the source code is the same.
The diff at line 11 correspond to `### source path`
<details>

```
11c11
< C:/Users/concourse/worker/containers/00001p4nuag/tmp/build/734c03a2/build
---
> C:/Users/concourse/worker/containers/00003of24si/tmp/build/734c03a2/build
276321,276322c276321,276322
< Note: including file:  C:\Users\concourse\worker\containers\00001p4nuag\tmp\build\734c03a2\repo.git\src\myapp_math\include\myapp_math\math.h
< Note: including file:   C:\Users\concourse\worker\containers\00001p4nuag\tmp\build\734c03a2\repo.git\src\myapp_math\include\myapp_math\collection.h
---
> Note: including file:  C:\Users\concourse\worker\containers\00003of24si\tmp\build\734c03a2\repo.git\src\myapp_math\include\myapp_math\math.h
> Note: including file:   C:\Users\concourse\worker\containers\00003of24si\tmp\build\734c03a2\repo.git\src\myapp_math\include\myapp_math\collection.h
276326c276326
< Note: including file:   C:\Users\concourse\worker\containers\00001p4nuag\tmp\build\734c03a2\repo.git\src\myapp_math\include\myapp_math\constants.h
---
> Note: including file:   C:\Users\concourse\worker\containers\00003of24si\tmp\build\734c03a2\repo.git\src\myapp_math\include\myapp_math\constants.h
277096,277097c277096,277097
< Note: including file:   C:\Users\concourse\worker\containers\00001p4nuag\tmp\build\734c03a2\repo.git\src\myapp_math\include\myapp_math\simple.h
< Note: including file:  C:\Users\concourse\worker\containers\00001p4nuag\tmp\build\734c03a2\repo.git\src\myapp_math\include\myapp_math\mathNoStl.h
---
> Note: including file:   C:\Users\concourse\worker\containers\00003of24si\tmp\build\734c03a2\repo.git\src\myapp_math\include\myapp_math\simple.h
> Note: including file:  C:\Users\concourse\worker\containers\00003of24si\tmp\build\734c03a2\repo.git\src\myapp_math\include\myapp_math\mathNoStl.h
```
</details>

### How to reproduce ###

1.  set `CCACHE_BASEDIR` to  parent of current build dir, in my case `set CCACHE_BASEDIR=C:\Users\<ci-user>\worker\containers\<random-id>\tmp\build\734c03a2`
2. set `CCACHE_DIR` inside `CCACHE_BASEDIR`, in my case `set CCACHE_DIR=C:\Users\<ci-user>\worker\containers\<random-id>\tmp\build\734c03a2\ccache` 
3. Build the code `ccache.exe  C:\PROGRA~2\MICROS~1\2019\PROFES~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  ...` , the compiler `-I` are all absolute path.
4. Move to another host, restore cache compilation and repeat steps 1, 2, 3 having `<random-id>` changed in the path.

### Actual behavior ###

Cache is not hit and missed at 99%, It seems that path is not correctly normalized

### Expected behavior ###

Cache hits should be 100%

### Environment ###

`ccache` version 4.6.1

**Comment by jrosdahl** [comment]
Unless you have more concrete reproduction steps to share, I think it would make sense to keep the discussion in #1084 instead of in two places.
