### ISSUE TITLE
Document the reliance on the "modified timestamp"

### ISSUE THREAD

**Issue by rdiez** [ccache/ccache#1095]
There is a cost associated with recording the last access time, so many people disable it as a matter of habit by using mount option 'noatime'.

I did that on my PC because I have a slow disk, and I did not think that it could impact ccache. But reading bits like "Remove files in LRU (least recently used) order" and the documentation for "--trim-method" made me realise of the potential trouble.

ccache's option "--trim-method" allows you to choose between 'atime' and 'mtime', but that is only for "--trim-dir", which is intended for secondary storage. I am guessing that the standard cache cleaning mechanism is hard-wired for 'atime'.

If that assumption is correct, I think it is worth mentioning this matter in the documentation. Otherwise, it is easy to overlook noatime's impact on ccache.

Perhaps ccache could be told to update the atime itself, im case the current mount has disabled automatic updating. I cannot think of any other program in my computer that would need 'atime'.

**Comment by jrosdahl** [comment]
The assumption is incorrect – ccache uses mtime for LRU bookkeeping in the primary storage.

**Comment by rdiez** [comment]
Thanks for the clarification and documentation improvement.
