### ISSUE TITLE
discuss cache and config locations on Windows

### ISSUE THREAD

**Issue by rkitover** [ccache/ccache#1098]
@jrosdahl @cristianadam @Predelnik 

Hi guys, I noticed that the default locations for the cache and configs on Windows right now does not seem ideal.

From the output of `ccache -s -v` I have:

```console
Cache directory:      C:\Users\rkitover\AppData\Roaming/ccache
Primary config:       C:\Users\rkitover\AppData\Roaming/ccache/ccache.conf
Secondary config:     C:/Program Files (x86)/ccache/etc/ccache.conf
```

#### Cache Location

We should be using `AppData\Local` and not `Roaming` for the cache because `Roaming` data can be copied/moved, and this is potentially many gigs that don't need to be. `Local` is available in the `LOCALAPPDATA` environment variable, and we can still fallback to `APPDATA` if for some reason it's not available due to Windows version or whatever.

#### Global Config

Instead of `C:/Program Files (x86)/ccache/etc` we could use `C:\ProgramData\ccache` as `C:\ProgramData` serves the purpose of a global `/etc` on modern Windows versions. This location is generally available in the `ALLUSERSPROFILE` environment variable. I'm not sure here what the fallback should be if any, or if we care about old versions of Windows, the `(x86)` suffix is definitely wrong because I am using a 64 bit build.

If you agree I can work on a PR to make these adjustments.

**Comment by cristianadam** [comment]
There is also a longer discussion at https://github.com/ccache/ccache/issues/1023
