### ISSUE TITLE
Merge ccache-swig into ccache mainline

### ISSUE THREAD

**Issue by iamthad** [ccache/ccache#110]
The ccache-swig fork, which is part of the swig repository at https://github.com/swig/swig/tree/master/CCache, should be merged into the ccache mainline to prevent duplication of effort.

**Comment by jrosdahl** [comment]
Note that ccache has changed a lot since version 2.4 from which ccache-swig was forked many years ago. I don't know anything about how swig works, but if it's easy to make ccache work with swig I'd welcome patch proposals. It's not something I personally will have time or interest to do, though.

**Comment by jrosdahl** [comment]
I'm closing this issue since the ccache project is not interested in driving such a merge. If somebody wants to work on it, please submit patches or pull requests as new issues.

**Comment by iamthad** [comment]
Understood, thank you for the feedback.

**Comment by LecrisUT** [comment]
If I may resurrect it, would it be possible to add the integration as a plugin to ccache?

**Comment by jrosdahl** [comment]
> If I may resurrect it, would it be possible to add the integration as a plugin to ccache?

Ccache doesn't have any plugin framework, so I guess the literal answer is no.

If you want to add SWIG support I think a good start would be to document what the swig fork does differently than the ccache version it's based on. That said, it's likely that non-trivial changes won't be accepted before #956 is done.
