### ISSUE TITLE
ccache can produce false direct hits with clang on NFS disk

### ISSUE THREAD

**Issue by mblythe86** [ccache/ccache#1115]
The root cause is actually a bug in `clang` (https://github.com/llvm/llvm-project/issues/56499 and https://github.com/llvm/llvm-project/issues/56501) where it will exit with a 0/success, but only partial results (or nothing) is written.

That bug is triggered in `ccache` by this code:
https://github.com/ccache/ccache/blob/d1503ebecdb1f9a3de1377e97719ec245a676012/src/ccache.cpp#L1167

There, `ccache` will run the compiler in `-E` preprocessor mode and have it write the output to stdout.  However, before launching the compiler process, `ccache` replaces the 'real' stdout filehandle with a filehandle to an opened file on disk, effectively the same as `$COMPILER -E ...options... > /path/to/some/file` from a shell.

When this is done, and the target disk is full (or has hit a quota limit), the faulty compiler will write an empty or truncated file to disk and exit with a 0/success status.  `ccache` then proceeds, since it doesn't (and can't) know that the compiler should have failed.  When `ccache` reads the truncated/empty file, it receives an empty/incomplete list of the file's \#include dependencies, which is then used to create a faulty entry in a manifest file.

On subsequent compiles, `ccache` will read this manifest file with empty/incomplete dependencies, and may 'direct hit' on this manifest entry when it shouldn't have (i.e. it would have been a miss if the full dependencies were listed in the manifest).

I've worked around this in a local version of `ccache` by altering the preprocessor compiler command to include `-o /path/to/some/file` instead of the stdout redirect.  Both `gcc` and `clang` correctly fail (and subsequently, `ccache` fails) in full-disk and full-quota situations when the `-o` option is used instead of redirecting stdout.

I actually hit this in the 3.3.3 version of ccache, but I can see from the source code that the latest versions are also affected.

**Comment by jrosdahl** [comment]
Thanks for the bug report. Yeah, that's unfortunate. I would be OK with ccache using `-o` for the stdout output as a workaround. It will still have to rely on a file descriptor for the stderr output, though, but that shouldn't be as critical.
