### ISSUE TITLE
-fcolor-diagnostics probing does not work

### ISSUE THREAD

**Issue by def-** [ccache/ccache#1116]
### How to reproduce ###

1. on Arch Linux: `pacman -S ccache`
2. `BUILDENV=(!distcc color ccache check !sign)` in /etc/makepkg.conf
3. Get https://aur.archlinux.org/packages/ddnet
4. Build with `makepkg` 

### Actual behavior ###
```
[1/253] Building C object CMakeFiles/json.dir/src/engine/external/json-parser/json.c.o
FAILED: CMakeFiles/json.dir/src/engine/external/json-parser/json.c.o
/usr/lib/ccache/bin/cc -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -O3 -DNDEBUG -fdiagnostics-color=always -fcolor-diagnostics -fstack-protector-all -fno-exceptions -Wno-implicit-function-declaration -MD -MT CMakeFiles/json.dir/src/engine/external/json-parser/json.c.o -MF CMakeFiles/json.dir/src/engine/external/json-parser/json.c.o.d -o CMakeFiles/json.dir/src/engine/external/json-parser/json.c.o -c /home/deen/ddnet-aur/src/DDNet-16.2.2/src/engine/external/json-parser/json.c
cc: error: unrecognized command-line option ‘-fcolor-diagnostics’
```

### Expected behavior ###
`-fcolor-diagnostics` was detected during probing as working:
```
Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test FLAG_SUPPORTED_fcolor_diagnostics succeeded with the following output:
Change Dir: /tmp/makepkg/ddnet/src/build/CMakeFiles/CMakeTmp
```
But fails when actually building the source code. I'd expect it to consistently fail or consistently succeed.

### Environment ###
ccache version 4.6.1
gcc 12.1.0

This was reported in DDNet in https://github.com/ddnet/ddnet/issues/5628
I see similar bugs in ccache were already fixed: https://github.com/ccache/ccache/issues/711 and https://github.com/ccache/ccache/issues/740

**Comment by jrosdahl** [comment]
Thanks for the bug report. I can confirm that this is a ccache issue.
