### ISSUE TITLE
Single file secondary storage

### ISSUE THREAD

**Issue by afbjorklund** [ccache/ccache#1118]
### Description ###

The cache directory consists of a large number of small files, and can take time to transfer or occupy a large amount of disk.

I was experimenting with packaging up the contents as an archive, and then accessing this archive without unpacking all of it.

First, a "ccache.tar" was created from the ccache directory. The contents are the same as the secondary storage `subdirs`.

Then, this archive is mounted with FUSE. To speed up random access, an index database is created (using SQLite)

It is also totally possible to either: 1) unpack this archive and use the directory 2) transfer it to a web server and use HTTP

But it seemed like an interesting option to try, if it turns out useful then it could be implemented in C++ perhaps ?

-----

Python scripts:

`create-archive ccache.tar`

* https://github.com/ccache/ccache/pull/1117

`ratarmount ccache.tar ccache-mount`

https://github.com/mxmlnkn/ratarmount (pip install ratarmount)

There are some advanced experimental features, like creating an overlay directory that can be commited to archive.

But the default use would be as `|read-only` secondary storage, and the new files would be created in primary only.

This doesn't really require any code changes to ccache, since the FUSE daemon handles the access and database.

So the end result could just be a subsection under the (yet to be created)  "[File Storage](https://github.com/ccache/ccache/wiki/File-storage)" wiki entry, or something ?

**Comment by afbjorklund** [comment]
Note that the .tar archive was more of a canonical way to "export" a cache directory, and not really a way to _access_ it.

I do have a single file implementation since before, but it is probably of limited interest and requires external libraries...
It involved using a .mdb file (variation of the .dbm), which comes prepared and indexed and ready to be memory-mapped.

Currently the recommended way to do that is to use a Redis server, since it would cache the memory between accesses.

i.e. there is a startup cost, when mounting the database. If only accessing one or two files, it can overshadow any speedup.
So if using a database, it best to have a persistent process and then use a socket to access the data from the processes.

**Comment by jrosdahl** [comment]
> The first question was if the proposed tar format was good enough to use a single-file version of the cache, like in documentation.

I don't have bandwidth to think about this, sorry. Especially since it sounds like a quite esoteric use case (exporting and using a read-only archive). I have lots of other things on my to do list that I think have higher priority.

> But if we don't want a fourth (optional) backend, then I will just leave it - and use Redis as the database access ?

My long term goal is actually (once again) to have *zero* backends in ccache and only provide an API and framework. Not sure if and when I will have time to work on that, but adding a fourth backend won't take us further towards that goal.

**Comment by afbjorklund** [comment]
Thanks for the reply.
