### ISSUE TITLE
If user uses config file then all the enviromental variables after setting config file will be ignored. 

### ISSUE THREAD

**Issue by ntosis** [ccache/ccache#1119]
@set CCACHE_DIR=C:\TOOLS\ccache\artifacts
@set CCACHE_LOGFILE=..\..\CcacheEval\ccache_config\ccache.log
**@set CCACHE_CONFIGPATH=..\..\CcacheEval\ccache_config\ccache.conf**
@set CCACHE_DEBUGDIR=..\..\CcacheEval\ccache_config\ccache_debug
@set CCACHE_NOHASHDIR=true
@set CCACHE_CONFIGPATH=..\..\CcacheEval\ccache_config\ccache.conf

All the settings after the line 3 will be ignored and ccache will use the default settings also in the case that config file does not set this options. 

In config file I don't use the setting for NOHASHDIR but instead I use an environmental variable, ccache ignores my settings and use the default option.  If I put the option for the config file at the end of the script then is working correctly. 

It seems that ccache cannot handle options in different positions. 

I use  ccache 4.6.1

Kind Regards,
Nikos

**Comment by jrosdahl** [comment]
Hi,

Do you mean that if you set `CCACHE_CONFIGPATH` then `CCACHE_*` environment variables are not taken into account? I can't reproduce this, so if I'm afraid you need to provide more specific details on how to reproduce the problem to have any chance of getting further troubleshooting the behavior you experience. Please fill in [the form that you got when submitting the bug report](https://github.com/ccache/ccache/blob/e007123076cc3a8210d45b8579b16314f906e0f0/.github/ISSUE_TEMPLATE/bug_report.md) – it's there for a reason. :slightly_smiling_face: See also _[Reporting an issue?](https://github.com/ccache/ccache/blob/master/CONTRIBUTING.md#reporting-an-issue)_.

> All the settings after the line 3 will be ignored and ccache will use the default settings also in the case that config file does not set this options.

Ccache cannot know in which order environment variables are set in a script, so the behavior you describe doesn't make sense to me.

> In config file I don't use the setting for NOHASHDIR but instead I use an environmental variable, ccache ignores my settings and use the default option.

If you run `ccache -p` after setting the variables, what does the output say?

> It seems that ccache cannot handle options in different positions.

Not sure what you mean here.

**Comment by jrosdahl** [comment]
:+1:
