### ISSUE TITLE
Using incbin wrapper library leads to false cache hits

### ISSUE THREAD

**Issue by BobIsOnFire** [ccache/ccache#1120]
### How to reproduce ###
I am using https://github.com/graphitemaster/incbin @ main.

`main.c`:
```c
#include "incbin/incbin.h"

INCTXT(InputFile, "file.txt");

#include <stdio.h>

int main() {
    printf("%s", gInputFileData);
}
```

1. `ccache gcc -c main.c -o main.o && gcc main.o -o main && ./main`
2. Change `file.txt` contents
3. Step 1 once again

### Actual behavior ###
`ccache` on third step recorded a cache hit and loaded `main.o` from the first step.
`./main` outputs on step 1 and 3 are identical.

### Expected behavior ###
Both step 1 and 3 should bail out on incbin as "unsupported code directive".
`./main` outputs on step 1 and 3 should reflect changes in `file.txt`.

### Environment ###
ccache version 4.6.1 (reproduces on master). Does not reproduce on ccache 4.5.1, so this is definitely a regression after #983. 

FYI, on my machine `INCTXT(InputFile, "file.txt")` expands into:

```
__asm__(".section " ".rodata" "\n" ".global " "g" "InputFileData" "\n" ".type " "g" "InputFileData" ", @object\n" ".balign " "16" "\n" "" "g" "InputFile" "Data" ":\n" ".incbin" " \"" "file.txt" "\"\n" ".byte " "0\n" ".global " "g" "InputFileEnd" "\n" ".type " "g" "InputFileEnd" ", @object\n" ".balign 1\n" "" "g" "InputFile" "End" ":\n" ".byte " "1\n" ".global " "g" "InputFileSize" "\n" ".type " "g" "InputFileSize" ", @object\n" ".balign " "16" "\n" "" "g" "InputFile" "Size" ":\n" ".int " "" "g" "InputFile" "End" " - " "" "g" "InputFile" "Data" "\n" ".balign " "16" "\n" ".text\n" ); extern "C" const __attribute__((aligned(16))) char gInputFileData[]; extern "C" const __attribute__((aligned(16))) char *const gInputFileEnd; extern "C" const unsigned int gInputFileSize;
```

I can see that `".incbin"` is a separate literal here (expanded from macro https://github.com/graphitemaster/incbin/blob/main/incbin.h#L82), which does not get captured by any rules introduced in #983.

My workaround would be to add a space at the end of the literal: https://github.com/BobIsOnFire/incbin/commit/633f8dba11bbebf6b5a4786e2bff7fbe183b4e8e, but I would love to see some fix in ccache itself.

**Comment by jrosdahl** [comment]
Thanks for the bug report. I can confirm that this is a regression introduced by #983.

**Comment by BobIsOnFire** [comment]
Thank you! Works as expected @ https://github.com/ccache/ccache/commit/7ee6030bc7b2e6ef321c01854f88ce0fd81c4513
