### ISSUE TITLE
Secondary (system-wide read-only) configuration file not working ?

### ISSUE THREAD

**Issue by aallrd** [ccache/ccache#1127]
Hello,

I am trying to configure `ccache` using the secondary (system-wide read-only) configuration file.
According to [the documentation](https://ccache.dev/manual/4.6.1.html#_configuration), it should be _\<sysconfdir\>/ccache.conf_ (typically _/etc/ccache.conf_ or _/usr/local/etc/ccache.conf_).
I have both files available but `ccache` is not reading any configuration from them.

_/etc/ccache.conf_
```
base_dir = /home
```

The file _/usr/local/etc/ccache.conf_ is the same as the previous one:
```
$ md5sum /usr/local/etc/ccache.conf /etc/ccache.conf
9e9c24bcd17ff3dacf20114b1c4f6cb3  /usr/local/etc/ccache.conf
9e9c24bcd17ff3dacf20114b1c4f6cb3  /etc/ccache.conf
```

```
$ ccache --show-config | grep base_dir
(default) base_dir =
$ ccache --config-path /etc/ccache.conf --show-config | grep base_dir
(/etc/ccache.conf) base_dir = /home
```

I don't have any other variables that could override this configuration to my knowledge:
```
$ env | grep CCACHE
$ ccache --show-config | grep cache_dir
(default) cache_dir = /root/.cache/ccache
$ file /root/.cache/ccache
/root/.cache/ccache: cannot open (No such file or directory)
```

I have compiled `ccache` using a custom prefix, I don't know if that can influence the configuration look up.
I did try to create the _\<prefix\>/etc/ccache.conf_ and _\<prefix\>/usr/local/etc/ccache.conf_ but it did not change anything.

Did I miss something or misunderstood the documentation?

Thank you.

```
$ ccache --version
ccache version 4.6.1
Features: file-storage http-storage redis-storage

Copyright (C) 2002-2007 Andrew Tridgell
Copyright (C) 2009-2022 Joel Rosdahl and other contributors

See <https://ccache.dev/credits.html> for a complete list of contributors.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 3 of the License, or (at your option) any later
version.
```

**Comment by aallrd** [comment]
It turned out to be a CMake quirk related to the installation prefix: https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#special-cases

> The following values of [CMAKE_INSTALL_PREFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html#variable:CMAKE_INSTALL_PREFIX) are special:
[...]
`/opt/...`
For \<dir\> equal to SYSCONFDIR, LOCALSTATEDIR or RUNSTATEDIR, the CMAKE_INSTALL_FULL_\<dir\> is computed by appending the prefix to the value of CMAKE_INSTALL_\<dir\> if it is not user-specified as an absolute path. For example, the SYSCONFDIR value etc becomes /etc/opt/.... This is defined by the [Filesystem Hierarchy Standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html).

I am using a `CMAKE_INSTALL_PREFIX=/opt/...`, and indeed using `strace` showed me that `ccache` was looking for _/etc/\<CMAKE_INSTALL_PREFIX\>/ccache.conf_.

I have added `-DCMAKE_INSTALL_SYSCONFDIR=/etc` to get the expected lookup behvior.

**Comment by jrosdahl** [comment]
A tip for future users having this problem: You can see which location ccache uses for the system-wide (secondary) configuration file with `ccache -sv` (`ccache --show-stats --verbose`).

I've also added a printout to the log now (61c70a6fa956e7f8ae74952d0bda64a4688bd165).
