### ISSUE TITLE
Compiling in different directories: inconsistent depfiles substitution when using sanitizers

### ISSUE THREAD

**Issue by BobIsOnFire** [ccache/ccache#1128]
Background: in our development, we use sysroot to have compiler, libc, libstdc++ and other system dependencies exactly the same in all developers' and CI environments. On top of that, we also use shared cache + secondary storage functionality of ccache to speed up rebuilds everywhere, which had proven to be insanely effective in our use-cases. However, I was quite surprised to notice this very specific bug when running my builds with AddressSanitizer today :)

### Minimal Reproducible Example ###

MRE consists of two identical sandboxes - `dir1` and `dir2`. Sandbox directory structure:
```
/opt/sandbox/dir1
├── llvm
│   ├── bin
│   │   ├── clang -> clang-10
│   │   ├── clang++ -> clang
│   │   ├── clang-10
│   ├── include
│   │   └── ...
│   └── lib64
│       └── ...
├── main.c
└── Makefile
```

`llvm` is a part of sysroot distribution I described earlier, this is where the compiler will run from. To reproduce, you can run `cp -Rp` (`-p` to preserve compiler mtime) to copy LLVM in your system into the sandboxes.

Dummy `main.c`:
```c
int main() {
    return 0;
}
```

`Makefile` has a single compilation rule for `main.c` + it includes clang's auto-generated depfile:
```make
build/main.o: main.c
        mkdir -p build
        CCACHE_NOHASHDIR=1 CCACHE_BASEDIR=$(CURDIR) ccache ./llvm/bin/clang -fsanitize=address -MD -MP -c main.c -o build/main.o

-include build/main.d
```

Ccache variables are set as described in [manual](https://ccache.dev/manual/latest.html#_compiling_in_different_directories).

### How to reproduce ###

1. Check that incremental build works in `dir1`: `cd dir1 && make && make && make`
2. Remove `dir1` sandbox (simulate that step 1 happened on a different host or in a different point in time when `dir1` no longer exists)
3. Check that incremental build works in `dir2`: `cd dir2 && make && make && make`

### Actual behavior ###
Step 1: First `make` run compiles object, writes it into cache. Second and third `make`s do not do anything since `build/main.o` is up-to-date.

Step 3: All three `make` instances run compilation command **each time**, though all three are reading object from cache that was made on step 1.

### Expected behavior ###
I expect incremental build to work the same way on both step 1 and step 3: First `make` run on step 3 should download object from cache, second and third `make`s do not do anything.

I should mention that it works as expected if I include at least one LLVM header file into `main.c`, even if I do not use it:

```c
#include <stddef.h>

int main() {
    return 0;
}
```

### Environment ###
ccache version 4.6.1

As I mentioned in title, the problem is related to base_dir substitutions in depfiles. Have a look at dummy `main.c` depfile when built with ASan + ccache + base_dir:

```make
build/main.o: \
  /opt/sandbox/dir1/llvm/lib64/clang/10.0.1/share/asan_blacklist.txt \
  main.c

/opt/sandbox/dir1/llvm/lib64/clang/10.0.1/share/asan_blacklist.txt:
```

When `dir1` gets removed, `asan_blacklist.txt` rule becomes phony, thus forcing `dir2/build/main.o` to rebuild every time. Having a `main.h` in a sandbox and including it does not solve the problem.

At the same time, when I include `<stddef.h>`, the path gets substituted:

```make
build/main.o: \
 llvm/lib64/clang/10.0.1/share/asan_blacklist.txt \
 main.c llvm/lib64/clang/10.0.1/include/stddef.h \
 llvm/lib64/clang/10.0.1/include/__stddef_max_align_t.h

llvm/lib64/clang/10.0.1/share/asan_blacklist.txt:

llvm/lib64/clang/10.0.1/include/stddef.h:

llvm/lib64/clang/10.0.1/include/__stddef_max_align_t.h:
```

I believe that ccache does not start base_dir substitution in depfiles unless there are headers with absolute paths being searched, am I right?

I also have found a workaround: passing `-no-canonical-prefixes` stops clang from writing absolute paths to its headers/shared files into both object and depfile.

**Comment by jrosdahl** [comment]
> I believe that ccache does not start base_dir substitution in depfiles unless there are headers with absolute paths being searched, am I right?

Yes, 60178b7a8eb8d03b364afb2fb8bd6753924cd9b7 added the `has_absolute_include_headers` variable as a performance optimization to only have to parse/rewrite the dependency file when necessary. This is of course based on the assumption that if no include file has an absolute path then no rewrite is needed, but apparently Clang can insert other paths into the dependency file as well.

**Comment by jrosdahl** [comment]
@BobIsOnFire: Please try and see if 1ee5365507ff3dd3d071f9ccd9380ad5c661ee12 improves the situation.

**Comment by BobIsOnFire** [comment]
Thank you @jrosdahl ! The issue does not reproduce with https://github.com/ccache/ccache/commit/1ee5365507ff3dd3d071f9ccd9380ad5c661ee12.
