### ISSUE TITLE
PCH not detected when using -include in concatenated form

### ISSUE THREAD

**Issue by KaiSalm** [ccache/ccache#1143]
### How to reproduce ###
1. touch header.h and src.cpp
2. create the precompiled header for header.h (gcc header.h)
3. execute "ccache gcc -include ./header.h -c src.cpp"

### Actual behavior ###
Uncacheable in the ccache statistics gets incremented.

### Expected behavior ###
Either Misses or Hits get incremented, depending on whether its the first run or not.

### Environment ###
ccache version 4.6.1 on Ubuntu 22.04

### Notes ###
When using "ccache gcc -include./header.h -c src.cpp" (with no space between -include and the path) it works as expected. 
PS: See the note below, the sloppiness had a typo therefore was not set correctly, still behavior depending on the space is unexpected.

**Comment by KaiSalm** [comment]
In the meantime i experimented further and found that my sloppiness was set up sloppily, and had only one p... I still believe that there is a bug here, since the space should not make a difference and neither any defines nor any time macros are present in the empty header being compiled?

**Comment by jrosdahl** [comment]
Right, ccache doesn't handle the `-includePATH` variant (with no space after `-include`) of the option when looking for precompiled headers. (It's beyond me why anybody would want to use the variant without a space. :slightly_smiling_face:)
