### ISSUE TITLE
ccache 4.6.2 regression when impersonating cl.exe causes spurious 'option 'o' has been deprecated and will be removed in a future release'

### ISSUE THREAD

**Issue by akrieger** [ccache/ccache#1146]
### How to reproduce ###

1. Setup ccache 4.6.2 to impersonate cl.exe
  a. Install ccache somewhere, copy ccache.exe to cl.exe
  b. Set `<CLToolPath>` property to the path to ccache-as-cl.exe.
2. Build in Visual Studio. 

### Actual behavior ###

A lot of this.
```
1>cl : command line  warning D9035: option 'o' has been deprecated and will be removed in a future release
1>cl : command line  warning D9035: option 'o' has been deprecated and will be removed in a future release
1>character_inventory.cpp
1>character_crafting.cpp
1>cl : command line  warning D9035: option 'o' has been deprecated and will be removed in a future release
1>character_armor.cpp
1>cl : command line  warning D9035: option 'o' has been deprecated and will be removed in a future release
```

### Expected behavior ###

Not the above. Note that this is a regression over 4.6.1 which does not cause this.

### Environment ###

ccache version 4.6.2

Visual Studio 2022 17.3.0 Preview 6.0

As an aside, I was unable to get ccache to work as part of a native msbuild project except with the impersonation method. Setting CLToolExe & CLToolPath to point to ccache.exe resulted in errors exec'ing the response file, as if ccache was not trying to invoke cl.exe. Using CCACHE_PREFIX or CCACHE_COMPILER either did not change the outcome or made cl.exe give some default output instead as if invoked with incorrect arguments.

**Comment by jrosdahl** [comment]
Thanks for the bug report. Fix coming up.

> As an aside, I was unable to get ccache to work as part of a native msbuild project except with the impersonation method. Setting CLToolExe & CLToolPath to point to ccache.exe resulted in errors exec'ing the response file, as if ccache was not trying to invoke cl.exe. Using CCACHE_PREFIX or CCACHE_COMPILER either did not change the outcome or made cl.exe give some default output instead as if invoked with incorrect arguments.

Have you seen <https://github.com/ccache/ccache/wiki/MS-Visual-Studio>?

**Comment by akrieger** [comment]
> Have you seen https://github.com/ccache/ccache/wiki/MS-Visual-Studio?

I have. None of the options seemed to work for me. I don't know *why*, because I was following them basically to the T (as far as you can accomplish the same thing multiple ways with MSBuild), but I couldn't figure it out. I'm happy to have gotten at least one way to work.

I'm happy to open issues to discuss the other attempts I made and document the issues I had with them, if you want.

**Comment by akrieger** [comment]
I should say - Alternative 1 is what I described as 'impersonation mode' and is what I did. Alternative 2 only applies to non-msbuild build systems which do string based command concatenation. msbuild requires `$(CLToolPath)$(CLToolExe)` to be a single normal binary which it invokes with a response file argument. Setting `<CLToolExe>ccache.exe cl.exe</CLToolExe>` fails to run.

**Comment by jrosdahl** [comment]
> I'm happy to open issues to discuss the other attempts I made and document the issues I had with them, if you want.

The mentioned wiki page was created by @justinpryzby in the context of #1039. Feel free to contribute to the wiki page.

**Comment by craigscott-crascit** [comment]
FYI, what has been working for me with MSBuild is setting `CLToolPath` to the directory where I have the `ccache.exe` file, and setting `CLToolExe` to `ccache.exe`. Note that I don't rename the `ccache.exe` executable to `cl.exe`. I also see the warning reported in this issue though with this arrangement when using Ccache 4.6.2.
