### ISSUE TITLE
Support clang/clang-cl `--` option

### ISSUE THREAD

**Issue by zero9178** [ccache/ccache#1149]
### How to reproduce ###

1. Create any kind of cpp file (eg. hello world)
2. ccache -z to zero statistics
3. Run `ccache clang-cl /Fotest.o -c -- test.cpp`
4. ccache -s -v

### Actual behavior ###

Not only a cache miss occurs, but the compilation is deemed unachable.

### Expected behavior ###

A cache miss (or hit), followed up by caching the compilation

### Environment ###

ccache version 4.6.2
clang-cl 13.0.1
Windows 10

CMake sadly seems to generate ninja files which contain compile commands of the form `-- source.cpp` at all times. Building these projects leads to 100% cache misses and 100% uncacheable due to preprocessing failed

**Comment by jrosdahl** [comment]
Thanks for the bug report. Since ccache doesn't miscompile this case I don't consider it a bug, so I'll convert it into a feature request to support `--`. Related: #1015.

One thing that would be good to have when implementing support is documentation or a description of what `--` actually _does_. I find no behavior change with or without `--`. Any ideas? Is it only a no-op? If so, why does CMake add it?

**Comment by zero9178** [comment]
> Thanks for the bug report. Since ccache doesn't miscompile this case I don't consider it a bug, so I'll convert it into a feature request to support `--`. Related: #1015.

Thanks!

> One thing that would be good to have when implementing support is documentation or a description of what `--` actually _does_. I find no behavior change with or without `--`. Any ideas? Is it only a no-op? If so, why does CMake add it?

As to why CMake adds it have no clue. As to what `--` does, I sadly didn't find any documentation either so read clang source instead. What it does is that it consumes every command line argument afterwards and interprets it as an input file argument ([0]). This also coincides with the behaviour I am seeing with the ccache executed preprocessor arguments. 
It attempts to run the preprocessor in the above example, by running `"C:\clang\Default\bin\clang-cl.exe" "--" "-E" "test.cpp"`. The issue is that the `--` remains, and hence we get the error: `clang-cl: error: no such file or directory: '-E'`, as it interprets `-E` as an input file to be compiled. 

It seems to me that either the `--` can be dropped entirely, or that it should be moved to the very back of the input options, right before "test.cpp", just like in the normal commandline.

[0] https://github.com/llvm/llvm-project/blob/ba57828e11c52f45420f2027dae0843cf83a57bf/clang/lib/Driver/Driver.cpp#L469

**Comment by jrosdahl** [comment]
> What it does is that it consumes every command line argument afterwards and interprets it as an input file argument ([0]).

Right, that's what one would think it does, analogous to the classic interpretation of `--` by other tools: stop treating arguments as options after `--`. For instance:

```console
% touch -- -example
% rm -- -example
```

However, it's not possible to compile a source file whose name starts with `-` by using `--` with Clang:

```console
% # I like to put my source code in "-foo.c"!
% touch -- -foo.c
% # And now I of course want to compile it.
% clang -c -foo.c
clang: error: unknown argument: '-foo.c'
clang: error: no input files
% # Let's fix it with "--".
% clang -c -- -foo.c
error: unknown argument: '-foo.c'
% # OK, so now we have an input file, but it's still an unknown argument?
% # Also, the error message no longer has a "clang: " prefix.
% # Another try:
% clang -c -- ./-foo.c
% # That of course works, but now "--" is redundant:
% clang -c ./-foo.c
```

So yes, `--` has _some_ effect, but I still fail to see the use.
