### ISSUE TITLE
Crash if using base directory and no or non-existent source file

### ISSUE THREAD

**Issue by vvainola** [ccache/ccache#1155]
### How to reproduce ###

1. Run `ccache.exe cl.exe /?`

### Actual behavior ###

Ccache crashes at https://github.com/ccache/ccache/blob/2500957f3a9525f893f5880243a28c21d652f77a/src/argprocessing.cpp#L1192 because  there is no output object

### Expected behavior ###

Fallback to running cl.exe with /? argument

### Environment ###

Master 2500957f3a9525f893f5880243a 30.8.2022

**Comment by jrosdahl** [comment]
Note: `CCACHE_BASEDIR`/`base_dir` needs to be set to trigger this.
