### ISSUE TITLE
ccache doesn't update mtime for hard linked files on Windows

### ISSUE THREAD

**Issue by akrieger** [ccache/ccache#1175]
If ccache hardlinks objects with an older mtime than sources, Visual Studio will constantly consider the sources out of date and 'rebuild' them on every build or debug invocation. Ideally ccache would update the mtime of the objects to match the timestamp of the most recent invocation to avoid this. One way to hit this is to eg. build, checkout some revision, build, checkout the old revision. Git will update the mtime of the sources but the old objects will have old timestamps.

The only way to avoid this currently is to avoid using hardlinking, which has its own benefits and downsides.

**Comment by akrieger** [comment]
Alternatively, the current behavior might be considered a bug based on this documentation:

Programs that rely on modification times (like make) can be confused if several users (or one user with several build trees) use the same cache directory. The reason for this is that the object files share i-nodes and therefore modification times. If file.o is in build tree A (hard-linked from the cache) and file.o then is produced by ccache in build tree B by hard-linking from the cache, the modification timestamp will be updated for file.o in build tree A as well. This can retrigger relinking in build tree A even though nothing really has changed.

This makes it sound like creating a hardlink is supposed to update the mtime of all links. This behavior might simply be an artefact of hardlink behavior on posix systems, as it seems creating a hardlink to a file on Windows does not update the mtime of the linked-to file.

**Comment by akrieger** [comment]
I noticed a few other mtime weirdnesses the other day. Some files were created with an *empty* mtime (displayed in explorer as blank, treated my Visual Studio as 'newer than'), others were created with basically corrupt mtime over a century in the future. I'll add some screenshots later.

**Comment by akrieger** [comment]
When I deleted the files and reran the build, ccache actually reinvoked the compiler, it didn't seem to find the objects in cache.

**Comment by akrieger** [comment]
Oh, you know what, this might've been a side effect of the issue fixed in 4.6.2 "Made sure to retain mtime/atime when recompressing cache files with -X/--recompress.". I'm unable to reproduce with a clean setup in 4.6.3.

**Comment by jrosdahl** [comment]
I think it's very likely that this is fixed in the upcoming 4.7 release, so I'll mark it as such.
