### ISSUE TITLE
Error when archive ccache for secondary storage in network share "specifying a host ("test.com") is not supported"

### ISSUE THREAD

**Issue by dtnguyen3011** [ccache/ccache#1181]
I found the commit https://github.com/ccache/ccache/commit/cc5c78374e320bc7807f04391b70e43deaa54c94 already implement archive ccache for seconday storage in network share

### How to reproduce ###

1.  CCACHE_DIR=%CCACHE_DRIVELETTER%ccache\vag_mrr_cache
2.  CCACHE_SECONDARY_STORAGE=file://test.com/ismdfs/iad/radar5_ci/ccache/windows/secondary_mrr_cache
3.  CCACHE_RESHARE=true

### Actual behavior ###

[  2%] Building CXX object dc_fw/src/dacore/CMakeFiles/dc_fw_interfaces_lib.dir/__/__/inc/dc_interfaces/per/daddy/params/per_repColdParameters.o
ccache: error: invalid file path "file://test.com/ismdfs/iad/radar5_ci/ccache/windows/secondary_mrr_cache": specifying a host ("test.com") is not supported
ccache: error: invalid file path "file://test.com/ismdfs/iad/radar5_ci/ccache/windows/secondary_mrr_cache": specifying a host ("test.com") is not supported
ccache: error: invalid file path "file://test.com/ismdfs/iad/radar5_ci/ccache/windows/secondary_mrr_cache": specifying a host ("test.com") is not supported
ccache: error: invalid file path "file://test.com/ismdfs/iad/radar5_ci/ccache/windows/secondary_mrr_cache": specifying a host ("test.com") is not supported

### Expected behavior ###

according commit's  https://github.com/ccache/ccache/commit/cc5c78374e320bc7807f04391b70e43deaa54c94 
change then it should be able to write ccache for secondary storage to network share

**Environment**
ccache version 4.6.3
 OS - Windows 10

See also
https://github.com/ccache/ccache/discussions/1114

**Comment by jrosdahl** [comment]
As explained in #1114, support for hostnames in `file://` URLs will be added in version 4.7. Since you use ccache 4.6.3 it of course doesn't work with that version.

**Comment by jrosdahl** [comment]
@dtnguyen3011: 4.7 has been released now. Give it a try.
