### ISSUE TITLE
macOS deployment target/Xcode directory should be hashed

### ISSUE THREAD

**Issue by mrpippy** [ccache/ccache#1205]
On macOS, the system compiler binaries (`/usr/bin/gcc`, `/usr/bin/clang`, etc) are themselves a compiler wrapper that runs the appropriate binary from an installed `Xcode.app` or `CommandLineTools`. `xcode-select` can be used to set the default, or the `DEVELOPER_DIR` environment variable can override the default. ccache should probably hash the DEVELOPER_DIR value, and possibly use compiler checks more thorough than just mtime on macOS since the compilers are a wrapper. 

Also, the `MACOSX_DEPLOYMENT_TARGET` environment variable will set the minimum macOS version that the code is targeted to run on (the equivalent of the `-mmacosx-version-min=` compiler flag). ccache should hash this variable if present, otherwise files targeting different OS versions may be linked together and trigger warnings.

### How to reproduce ###

1. Create a valid C file containing an empty main (`test.c)
2. `% MACOSX_DEPLOYMENT_TARGET=12.0 ccache clang -c -o test.o test.c`
3. `% MACOSX_DEPLOYMENT_TARGET=10.11 ccache clang -c -o test.o test.c`
4. `% MACOSX_DEPLOYMENT_TARGET=10.11 ccache clang -o test test.o`
ld: warning: object file (test.o) was built for newer macOS version (12.0) than being linked (11.0)

### Actual behavior ###

Ccache compiled the file with a 12.0 deployment target and cached the result. On step 3, the cached result was returned even though a different deployment target was specified. And on step 4, during linking that cached result caused a warning (and possible runtime errors/crashes).

### Expected behavior ###

`MACOSX_DEPLOYMENT_TARGET` should be included in the hash (the same way that it would be if `-mmacosx-version-min=` was passed to the compiler)

### Environment ###

ccache version 4.6.1, installed from Homebrew

**Comment by jrosdahl** [comment]
> [...] possibly use compiler checks more thorough than just mtime on macOS since the compilers are a wrapper.

I don't think that ccache ever will be able to properly support scripts that choose the compiler based on variables. The user is expected to set up [compiler_check](https://ccache.dev/manual/4.7.2.html#config_compiler_check) appropriately to identify the compiler.

That said, I can make ccache hash the variables you suggest, but I will not be able to test it. Help welcome. (I don't think that anybody who regularly contributes to ccache uses macOS, so it's state is "best effort".)
