### ISSUE TITLE
Fix and re-enable mingw build

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#122]
I disabled the i586-mingw32msvc build in ddf5ca4d59f2e0ccbc85b53b3692d9a0f34b5f6b since GCC 4.2 apparently is too old for proper C99 support, which is required since e527cccb.

@itensionanders: Since you have been working on the mingw build before, do you have any ideas on what would be the best approach? Would it be possible to go back to using gcc-mingw-w64-i686? Or should we make some ugly workaround like (if possible) ignoring the specific error?

**Comment by itensionanders** [comment]
We can require MinGW-w64, it is not the default on (non-beta) Travis but the old MinGW is horribly broken in other ways (as seen in #119). We probably also need some **real** Windows tests (#69), if we want that OS to be a supported platform ? So I can go with either disabling MinGW or requiring newer "stuff". But having native Windows support is *not* important to me personally. Supporting Linux/Unix is OK. I used [MSYS](http://www.mingw.org/wiki/msys) anyway...

* http://mingw.org
* http://mingw-w64.org

**Comment by jrosdahl** [comment]
I have no personal interest in Windows support either, so let's keep it disabled then until somebody who cares enough shows up. :-)

**Comment by itensionanders** [comment]
Note that I don't have any objections to keeping the *code* compiling with MinGW in the name if portability - that should be doable, possibly after upgrading due to the new GCC requirements...

The problem is keeping the "quicktest" and "test" running, on a foreign system like Windows ? That would probably need "real" Windows (not Wine) and a maintainer plus something like Appveyor

**Comment by itensionanders** [comment]
@jrosdahl : but if you just want the tests running again, you can look at ec41946803b604706e1371c65b15be372373da7e (mingw-w64)

**Comment by mati865** [comment]
While it's a bit outdated you can take a look at https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-ccache

**Comment by afbjorklund** [comment]
The latest changes in #119 will make the MinGW build [run again](https://travis-ci.org/ccache/ccache/builds/216464035), using the Travis VM infrastructure...
So it will run MinGW twice as slow as the other container-based builds, but still half the time of ASAN.

The tests pass on Linux, but there's still work to do to make them pass on Windows.
There's some compatibility with e.g. symlinks, that needs fixing for MSYS2/Cygwin.

Will adress those problems separately (Windows *run-time* support)

This one would be possible to fix now (Windows *compile-time* support)

**Comment by afbjorklund** [comment]
Builds seem to running fine: https://travis-ci.org/ccache/ccache/branches

e.g. https://travis-ci.org/ccache/ccache/builds/560919457 Job 925

* https://travis-ci.org/ccache/ccache/jobs/560919462 Job 925.5 `Compiler: i686-w64-mingw32-gcc C`

* https://travis-ci.org/ccache/ccache/jobs/560919463 Job 925.6 `Compiler: x86_64-w64-mingw32-gcc C`
