### ISSUE TITLE
ccache doesn't understand -coverage (one dash variant of --coverage)

### ISSUE THREAD

**Issue by Bu11etmagnet** [ccache/ccache#123]
[ccache_log.txt](https://github.com/ccache/ccache/files/388129/ccache_log.txt)

Even though -coverage is specified, ccache fails to handle the .gcda file.

    rm url_handler_test*
    make

results in url_handler_test.o and url_handler_test.d , but no url_handler_test.gcda

g++-610-compat is just a shell script which runs
 `exec /usr/local/bin/g++-610 -D_GLIBCXX_USE_CXX11_ABI=0`

**Comment by jrosdahl** [comment]
I guess this is because you're using `-coverage` instead of `--coverage`. The two dash variant is what is documented for GCC, but apparently GCC recognizes the one dash variant as well, so ccache should do that as well.

So for now you could try to use the documented variant instead.

**Comment by jrosdahl** [comment]
Fixed in 86c8b0558953e8b7175ca63740d6895e8076f298.
