### ISSUE TITLE
macOS universal binaries in releases

### ISSUE THREAD

**Issue by alecjacobson** [ccache/ccache#1237]
The [recent releases](https://github.com/ccache/ccache/releases/tag/v4.7.4) include linux and windows binaries. It'd be great if they included universal mac os binaries.

**Comment by jrosdahl** [comment]
I create the precompiled binaries by cross-compiling on my local machine as part of the release process. I don't know how to do that for macOS.

I guess this means that the release process would have to change to download at least the macOS binaries from CI. (I sign release artifacts locally, hence the download part.) I would not be against this, but I would like help from somebody with macOS knowledge to set up such build jobs. For instance, which macOS versions would one typically target for a universal binary?

**Comment by alecjacobson** [comment]
I believe the necessary architectures are `architecture x86_64` and `architecture arm64`. I'm not sure how to do this via cross compile or CI.

**Comment by res0nance** [comment]
I've put up a PR to add MacOS universal binaries to CI.

I picked 10.15 as min supported version as that is the first version that doesn't break existing CI.

**Comment by jrosdahl** [comment]
@alecjacobson: Could you test if https://github.com/ccache/ccache/suites/10644305172/artifacts/531758875 (the result of @res0nance's work in #1240) works for you?

**Comment by jrosdahl** [comment]
> @alecjacobson: Could you test if [ccache/ccache/suites/10648758230/artifacts/532059976](https://github.com/ccache/ccache/suites/10648758230/artifacts/532059976) (the result of @res0nance's work in https://github.com/ccache/ccache/pull/1240) works for you?

I just realized that the workflow artifact at the above mentioned URL is not public. Anyway, I'll include it in the next ccache release.
