### ISSUE TITLE
Support overriding MSVC /Z* options 

### ISSUE THREAD

**Issue by firewave** [ccache/ccache#1239]
Visual Studio applies compiler options from left to right allowing you to override existing one by appending a different option:
```
4>cl : command line warning D9025: overriding '/Zi' with '/Z7' [D:\a\cppcheck\cppcheck\lib\cppcheck.vcxproj]
```

This can also be achieved by via environment variables by specifying `_CL_`: https://learn.microsoft.com/en-us/cpp/build/reference/cl-environment-variables

Unfortunately `ccache` looks at the options as a whole and so you cannot simply override an option:
```
[2023-01-12T18:38:19.220631 4848 ] Compiler type: msvc
[2023-01-12T18:38:19.220631 4848 ] Compiler option -Zi is unsupported
[2023-01-12T18:38:19.220631 4848 ] Failed; falling back to running the real compiler
```

The same might be true for GNU-like compiler which also apply options from left to right but I have no example for that.

**Comment by jrosdahl** [comment]
I don't think there's a way to implement a reliable generic detection for this, so it likely has to be on a case-by-case basis. And I agree that teaching ccache that the last of `/Z7`, `/Zi` or `/ZI` "wins" (if that's indeed the case) would be useful.

> This can also be achieved by via environment variables by specifying `_CL_`: [learn.microsoft.com/en-us/cpp/build/reference/cl-environment-variables](https://learn.microsoft.com/en-us/cpp/build/reference/cl-environment-variables)

Related: #1038

**Comment by firewave** [comment]
I think just limiting it to specific options makes a lot of sense and should (hopefully) also make it easy to implement as well.

It does "win" - hence the compiler warning `D9025`.
