### ISSUE TITLE
Huge performance hit on Windows with many include folders

### ISSUE THREAD

**Issue by Code7R** [ccache/ccache#1245]
### How to reproduce ###

1.  Find or create a Windows project with a few hundreds of include folders with typically 1-2 header files in each
2. Use a modified version of ccache v4.7.4 (the one with Tasking patch from somewhere of the other issues - but that patch is trivial, I checked, it should not affect the build behavior)
3. Configure the project on Windows 10 with ccache involved and compile (default settings)

### Actual behavior ###

When CCache is in the game, it takes very long time in the first run, when content is being cached.
Basically, the overall build time is increased not by 5% but by over 50%. Also, the system sometimes starts behaving sluggish when larger projects are built. This observation is confirmed by Resource Monitor, reporting about 30% of phantom load on "OS tasks", although the CPU load accounted for ccache.exe itself is quite low.

And checking with Process Monitor confirms the suspicion. Typically, where the compiler causes << 100k syscalls, ccache.exe wrapper causes >> 1mio syscalls. For EVERY compilation unit (C file). And we have hundreds of them.

I will attach an example from that, with some obfuscation. That log is filtered on one single header file, and even that makes almost 1000 syscalls. For me it seems like it is doing some kind (expensively implemented) fstat operation on every single header file and doing this hundreds of times, reopening the handle all over again. Smells like a "suboptimal" implementation of the Windows glue layer.
[Logfile.CSV.gz](https://github.com/ccache/ccache/files/10527021/Logfile.CSV.gz)

The second run, however, is about as fast as we know it from Linux.

### Expected behavior ###
CCache should take not cause more OS load than the compiler itself, actually far less.

### Environment ###
Windows 10 22H*
Tasking v6.2r1

ccache version v4.7.4 with Tasking support patch on top

**Comment by jrosdahl** [comment]
Thanks for the bug report.

Yes, this seems to be a regression introduced by #1033 (included in v4.6.1) in combination with 9a05332915d2808f4713437006b3f7c812d9fd74 (included in v4.6.2): a `stat` call is now executed each time a note about an include file is found in the preprocessed output. Such calls are very performant in Linux (and therefore unnoticed until now), but apparently costly on Windows. I'll look into fixing this in ccache 4.8.
