### ISSUE TITLE
Improve MSVC RSP file parsing

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#1247]
From @jacobly0 in https://github.com/ccache/ccache/issues/1233#issuecomment-1411015937:            

> I wrote a script to demonstrate msvc's expansion behavior of at files, and it's clear that my original implementation was missing some details.
> ```sh
> #!/bin/sh
> echo def > atfile.c
> for cl in cl clang-cl; do
>     echo
>     echo "Using compiler $cl:"
>     while read -r def; do
>         if [ -z "$def" ]; then
>             echo
>             continue
>         fi
>         echo -n "$def => "
>         echo "/w /nologo /E /Ddef=$def atfile.c" > atfile.rsp
>         $cl @atfile.rsp 2>&1 | grep --invert '^#\|^atfile\.c$'
>     done <<'EOF'
> \
> \\
> '\\'
> "\\"
> '"\\"'
> "'\\'"
> '''\\'''
> ''"\\"''
> '"'\\'"'
> '""\\""'
> "''\\''"
> "'"\\"'"
> ""'\\'""
> """\\"""
> 
> 
> \'\'
> '\'\''
> "\'\'"
> ''\'\'''
> '"\'\'"'
> "'\'\''"
> ""\'\'""
> '''\'\''''
> ''"\'\'"''
> '"'\'\''"'
> '""\'\'""'
> "''\'\'''"
> "'"\'\'"'"
> ""'\'\''""
> """\'\'"""
> 
> \"\"
> '\"\"'
> "\"\""
> ''\"\"''
> '"\"\""'
> "'\"\"'"
> ""\"\"""
> '''\"\"'''
> ''"\"\""''
> '"'\"\"'"'
> '""\"\"""'
> "''\"\"''"
> "'"\"\""'"
> ""'\"\"'""
> """\"\""""
> EOF
> done
> ```
>
> ```
> $ ./atfile.sh
> 
> Using compiler cl:
> \ => \
> \\ => \\
> '\\' => '\\'
> "\\" => \
> '"\\"' => '\'
> "'\\'" => '\\'
> '''\\''' => '''\\'''
> ''"\\"'' => ''\''
> '"'\\'"' => ''\\''
> '""\\""' => '\'
> "''\\''" => ''\\''
> "'"\\"'" => '\'
> ""'\\'"" => '\\'
> """\\""" => "\"
> 
> 
> \'\' => \'\'
> '\'\'' => '\'\''
> "\'\'" => \'\'
> ''\'\''' => ''\'\'''
> '"\'\'"' => '\'\''
> "'\'\''" => '\'\''
> ""\'\'"" => \'\'
> '''\'\'''' => '''\'\''''
> ''"\'\'"'' => ''\'\'''
> '"'\'\''"' => ''\'\'''
> '""\'\'""' => '\'\''
> "''\'\'''" => ''\'\'''
> "'"\'\'"'" => '\'\''
> ""'\'\''"" => '\'\''
> """\'\'""" => "\'\'"
> 
> \"\" => ""
> '\"\"' => '""'
> "\"\"" => ""
> ''\"\"'' => ''""''
> '"\"\""' => '""'
> "'\"\"'" => '""'
> ""\"\""" => ""
> '''\"\"''' => '''""'''
> ''"\"\""'' => ''""''
> '"'\"\"'"' => ''""''
> '""\"\"""' => '""'
> "''\"\"''" => ''""''
> "'"\"\""'" => '""'
> ""'\"\"'"" => '""'
> """\"\"""" => """"
> 
> Using compiler clang-cl:
> \ => \
> \\ => \\
> '\\' => '\\'
> "\\" => \
> '"\\"' => '\'
> "'\\'" => '\\'
> '''\\''' => '''\\'''
> ''"\\"'' => ''\''
> '"'\\'"' => ''\\''
> '""\\""' => '\'
> "''\\''" => ''\\''
> "'"\\"'" => '\'
> ""'\\'"" => '\\'
> """\\""" => "\"
> 
> 
> \'\' => \'\'
> '\'\'' => '\'\''
> "\'\'" => \'\'
> ''\'\''' => ''\'\'''
> '"\'\'"' => '\'\''
> "'\'\''" => '\'\''
> ""\'\'"" => \'\'
> '''\'\'''' => '''\'\''''
> ''"\'\'"'' => ''\'\'''
> '"'\'\''"' => ''\'\'''
> '""\'\'""' => '\'\''
> "''\'\'''" => ''\'\'''
> "'"\'\'"'" => '\'\''
> ""'\'\''"" => '\'\''
> """\'\'""" => "\'\'"
> 
> \"\" => ""
> '\"\"' => '""'
> "\"\"" => ""
> ''\"\"'' => ''""''
> '"\"\""' => '""'
> "'\"\"'" => '""'
> ""\"\""" => ""
> '''\"\"''' => '''""'''
> ''"\"\""'' => ''""''
> '"'\"\"'"' => ''""''
> '""\"\"""' => '""'
> "''\"\"''" => ''""''
> "'"\"\""'" => '""'
> ""'\"\"'"" => '""'
> """\"\"""" => """"
> 
> ```
>
> It appears that `\'` is never parsed specially, `\\` expands to `\` only when the innermost matching quotes are double quotes, `\"` always expands to `"`, and there is some double quote eliding that I don't fully understand.

**Comment by dionorgua** [comment]
Hi,
I've tried to use `ccache` with msvc (configured via CMake snipplet) and found that ccache (4.8.1) reports ```No input file found``` 

I've tried to debug it locally and found that ccache is confused by followed argument in `rsp` file:

`/std:c++20 /Fo"types.dir\Release\" /Fd"D:\work\<edited>\types.pdb" /external:W0 /Gd /TP /wd4996 /wd4800 /errorReport`

It looks like parser is confused by `/Fo` arg with `\\"` at the end and assumes that everything after `/Fo` is just single argument.

I don't know why it's escaped in such strange manner, who (cmake or msbuild) is generating that strange code and why it works for others.

**Comment by jrosdahl** [comment]
@jacobly0 wrote:

> It appears that \' is never parsed specially, \\ expands to \ only when the innermost matching quotes are double quotes, \" always expands to ", and there is some double quote eliding that I don't fully understand.

Perhaps this documentation can bring clarity?

- <https://learn.microsoft.com/en-us/previous-versions//17w5ykft(v=vs.85)?redirectedfrom=MSDN>
- <https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw?redirectedfrom=MSDN#remarks>
