### ISSUE TITLE
MSVC /Zc: parameters are no longer supported since version 4.8

### ISSUE THREAD

**Issue by srohmen** [ccache/ccache#1262]
### How to reproduce ###

Using MSVC and compiling a source file with any `/Zc:<flag>` parameter (C++ conformance modes), e.g. `/Zc:throwingNew`

### Actual behavior ###

ccache complains about this compiler option:
`Compiler option /Zc:throwingNew is unsupported`

### Expected behavior ###

In version 4.7.4 the conformance options worked just fine.

### Environment ###

ccache version 4.8

I figured out that this issue goes away when I revert d099c1804f56e7a357c8c8473cacf186da0d5d3e.

A brief look into the patch revealed that the simple check for `-Z` wrongly matches the conformance flags as well.

**Comment by jrosdahl** [comment]
Thanks for the bug report.

I'd say that `/Z*` options other than `/Zi`, `/ZI` and `/Z7`  became unsupported (as in "ccache is not able to cache a compilation") in d099c1804f56e7a357c8c8473cacf186da0d5d3e, not broken (as in "ccache produces an incorrect result"), so I'll rename the issue title accordingly.
