### ISSUE TITLE
Version unknown for macOS binary

### ISSUE THREAD

**Issue by awitten1** [ccache/ccache#1270]
### How to reproduce ###

1.  Download mac 4.8 binary from https://ccache.dev/download.html
2. Run `ccache --version`

### Actual behavior ###
Output: `ccache version unknown`

### Expected behavior ###
I expected to see the version.

### Environment ###
4.8 on MacOS

Thank you for the help!

**Comment by jrosdahl** [comment]
This will be fixed in 4.8.1.
