### ISSUE TITLE
`clang-cl` get's passed `-fcolor-diagnostics` after `--` which leads to compiler error

### ISSUE THREAD

**Issue by tru** [ccache/ccache#1273]
### How to reproduce ###

1.  run ccache like this: `ccache.exe debug=true cache_dir=cache direct_mode=true depend_mode=true clang-cl.exe /showIncludes -c -- test.cpp`

### Actual behavior ###

`clang-cl: error: no such file or directory: '-fcolor-diagnostics'; did you mean '-fcolor-diagnostics'?`

Looking in the log:

```
  58   │ [2023-04-06T14:24:44.356352 24752] Running real compiler
  59   │ [2023-04-06T14:24:44.357270 24752] Executing c:\.nuget\packages\llvm.15.0.7-ubi02\tools\bin\clang-cl.exe /showIncludes -c -- test.cpp -fcolor-diagnostics
  60   │ [2023-04-06T14:24:44.374724 24752] Compiler gave exit status 1
```

Removing `/showIncludes` also seems to fix this issue?

### Expected behavior ###

-fcolor-diagnostics have to be added before `--` or not added at all.

### Environment ###

latest master e9d33e4f5edb23c7db661c6cbb451fb45c573f67

windows 11

**Comment by jrosdahl** [comment]
Thanks for the bug report. The issue is related to the depend mode in combination with `--` for Clang-based compilers. (The depend mode will be disabled if you don't pass `/showIncludes` in the clang-cl case which is why it helped to remove it.)

**Comment by tru** [comment]
Happy to help fix this, but I was not sure what the best way to fix it. So if you have some pointers I can give it a shot.

**Comment by jrosdahl** [comment]
Thanks for the offer, but I already have a pending fix.
