### ISSUE TITLE
"Compiler option /Zc:inline is unsupported"  in ccache 4.8

### ISSUE THREAD

**Issue by mszhanyi** [ccache/ccache#1276]
### How to reproduce ###

1.  Install ccache 4.8, No cacheable calls after building.
2.  check the log, there's the error "Compiler option /Zc:inline is unsupported".
3.  It works after reinstalling ccache 4.7.4. 

### Actual behavior ###
No cacheable calls at all (ccache -s)

### Expected behavior ###
4.8 should support /Zc:inline as 4.7.4

### Environment ###

ccache version 4.7.4 and 4.8

Visual Studio 2019, Windows

**Comment by tru** [comment]
See patch in #1263

**Comment by jrosdahl** [comment]
Duplicate of #1262
