### ISSUE TITLE
Windows 64-bit MSBuild CI jobs fail

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#1278]
The [Windows VS2019 64-bit MSBuild](https://github.com/ccache/ccache/actions/runs/4659417272/jobs/8246283413#logs) and [Windows VS2022 64-bit MSBuild](https://github.com/ccache/ccache/actions/runs/4659417272/jobs/8246283873#logs) GitHub actions jobs have started failing on master due to some changes in the CI environment. @rkitover: FYI.

I'm going to disable them for now.

**Comment by rkitover** [comment]
@ruimaciel Different issue, please open an issue if you are having problems with all the details.
