### ISSUE TITLE
Uncacheable with "compiler produced stdout" on MSVC 2022

### ISSUE THREAD

**Issue by mkruskal-google** [ccache/ccache#1280]
### How to reproduce ###

One of our CI tests is seeing this issue:
https://github.com/protocolbuffers/protobuf/blob/main/.github/workflows/test_cpp.yml#L282

### Actual behavior ###

Our ccache report shows:
```
Uncacheable calls:           487 /  487 (100.0%)
  Compiler produced stdout:  487 /  487 (100.0%)
```

### Expected behavior ###

The documentation says that "Compiler produced stdout" is obsolete and now supported behavior.  We expect these calls to be cacheable even if they are producing stdout.  However, it's not clear why simply switching to MSVC 2022 would cause new stdout

### Environment ###

ccache version 4.7, 4.7.4 and 4.8

We only see this when compiling via cmake/ninja on windows machines with MSVC 2022.  MSVC 2019 with the exact same setup works as expected

**Comment by jrosdahl** [comment]
In ccache v4.6 and newer there is no code path that ever sets "Compiler produced stdout" (internal identifier `compiler_produced_stdout`); the last occurence was removed in ef19b0f09684565cb9cbc28b55d5b289cea0b6a0). Thus I suspect that some older ccache version must be involved in your scenario.

> How to reproduce
> One of our CI tests is seeing this issue:
[protocolbuffers/protobuf@main/.github/workflows/test_cpp.yml#L282](https://github.com/protocolbuffers/protobuf/blob/main/.github/workflows/test_cpp.yml?rgh-link-date=2023-05-01T18%3A57%3A24Z#L282)

Sorry, I don't understand how to reproduce the issue given this information.

**Comment by mkruskal-google** [comment]
Yea I couldn't figure out how it leaked in, but when I double-check the version I see:
```
> ccache --version
ccache version 4.7
Features: file-storage http-storage redis+unix-storage redis-storage

Copyright (C) 2002-2007 Andrew Tridgell
Copyright (C) 2009-2022 Joel Rosdahl and other contributors
```

Sorry for the incomplete repro steps, I tried reproducing this on a windows machine and ccache worked fine.  It's only on the github windows-2022 runners that we see this.  What the CI is doing is roughly just:
```
git clone https://github.com/protocolbuffers/protobuf.git && cd protobuf
# Download https://github.com/ccache/ccache/releases/download/v4.7/ccache-4.7-windows-x86_64.zip and place in current directory
git submodule update --init --remote --recursive
cmake . -G Ninja -Dprotobuf_WITH_ZLIB=OFF -Dprotobuf_BUILD_CONFORMANCE=OFF -Dprotobuf_BUILD_SHARED_LIBS=OFF -Dprotobuf_BUILD_EXAMPLES=ON -Dprotobuf_ALLOW_CCACHE=ON -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
ctest --verbose --parallel 20 -C Debug
```

**Comment by jrosdahl** [comment]
OK, great that you found the issue!
