### ISSUE TITLE
Remote cache: path has to be encoded needs to be documented

### ISSUE THREAD

**Issue by z-aki** [ccache/ccache#1281]
### How to reproduce ###

`ccache.conf`

```
remote_storage = file:///Volumes/A%20B
remote_storage = file:///Volumes/A B
```

In case 2, it throws ccache: error: Cannot parse URL B: Path 'B' in 'B' is invalid.
It has to be changed to case 1 ( line online encoders). And that too only for second slash onwards.

### Actual behavior ###

this Isn't documented anywhere

### Expected behavior ###

 NA

### Environment ###

ccache version 4.8

**Comment by jrosdahl** [comment]
Hi,

The manual says that [`remote_storage` is a space-separated list of storage backends](https://ccache.dev/manual/4.8.html#config_remote_storage) and that [a storage backend is specified with a URL](https://ccache.dev/manual/4.8.html#_remote_storage_backends). A URL can never include literal space characters; they must be [percent encoded](https://en.wikipedia.org/wiki/URL_encoding).

I don't think that it makes sense to document details of URL syntax in the ccache manual, in the same way that it doesn't make sense to document the syntax of file paths or compiler arguments.

**Comment by z-aki** [comment]
Okay a small fix, in one of the examples, add a a space:

`file://example.com/shared%20folder`

**Comment by jrosdahl** [comment]
OK, I've improved the example now (a25633df522dede9a0a30e1fcc0df568582a4168).
