### ISSUE TITLE
Add possibility to dump *ccache-log files only

### ISSUE THREAD

**Issue by dsilakov** [ccache/ccache#1285]
### Description ###
Currently debug mode causes ccache to generate 5 files for every object - `.ccache-log` and 4 `.ccache-input*` ones.

It would be useful to have possibility to generate `.ccache-log` only. Maybe add an additional option or add possibility to specify debug level.

Rationale: During our work, we wanted to gather statistics which particular files are taken from cache and which are rebuilt. We used `.ccache-log` files for this but found that in addition to that logs, we get 300+Gb of `.ccache-input*` files which are not required for us but affect the build process (we can simply become out of space).

**Comment by jrosdahl** [comment]
Sounds like a good idea.
