### ISSUE TITLE
compiling ccache-4.8.1 with gcc (Gentoo 12.2.1_p20230428-r1 p2) causes an internal compiler error

### ISSUE THREAD

**Issue by jmbreuer** [ccache/ccache#1289]
### How to reproduce ###

0. have a currently stable (profile 17.1) amd64 gentoo system
1. follow https://github.com/ccache/ccache/blob/master/doc/INSTALL.md up to `make`

### Actual behavior ###

The compile aborts with an internal compiler error. Equivalent logs are already attached to the pertaining gentoo bug report, unless specifically requested I won't repeat them here:

https://bugs.gentoo.org/906942

I verified that the very same thing happens building directly from a pristine source tarball directly out of this project.

### Expected behavior ###

The build of ccache 4.8.1 should complete.

### Environment ###

Gentoo 17.1 (desktop/plasma/systemd) on amd64 hardware, using gcc (Gentoo 12.2.1_p20230428-r1 p2) which is the most current default compiler for that distribution.

### Notes ###

I'm happy to track this further.

ccache 4.7.4 builds correctly on the same system.
It seems perplexing, since the `LOG` macros in `Logging.hpp` haven't really changed since then; and the breaking usage (which is new for 4.8.1 vs 4.7.4) looks fairly innocuous as well: https://github.com/ccache/ccache/blob/17d5c61227130894f0cedb5f5d0c7567f2b2c5a7/src/storage/local/LocalStorage.cpp#L710

I'd welcome any and all background, hints and tips that come to mind - my C++ is a bit rusty, maybe something about this gives someone an "oh, why did it ever work in the first place?" moment. ;-) Or not.

**Comment by jrosdahl** [comment]
Thanks for the bug report.

It seems unlikely that a compiler crash would be a ccache bug. Have you considered reporting the bug to GCC instead?

**Comment by jmbreuer** [comment]
> Thanks for the bug report.
> 
> It seems unlikely that a compiler crash would be a ccache bug. Have you considered reporting the bug to GCC instead?

At this point it's unclear whether it's `gcc` itself, or possibly some gentoo-specific patches.

Since the problem originates with the fmt library in third_party anyway, it's certainly not a ccache issue per se. I'll be taking this back to https://bugs.gentoo.org/906942
