### ISSUE TITLE
Clarify --evict-older-than

### ISSUE THREAD

**Issue by iTrooz** [ccache/ccache#1292]
Would it be possible to clarify what timestamp the option `--evict-older-than` uses ? Does it use the timestamp of *last access* to the file or *last modification* ?

From my limited understanding of the codebase, https://github.com/ccache/ccache/blob/fe03859ebe1e5fdf87b02fba3d70f5854124d453/src/storage/local/LocalStorage.cpp#L277 indicates that the timestamp used is *last modification*.

Could you update the documentation of the option to reflect this ?

(Also, kinda unrelated since this is an improvement issue, but could you justify why you wen with this rather than last access to the file ?)

**Comment by jrosdahl** [comment]
> Would it be possible to clarify what timestamp the option `--evict-older-than` uses ? Does it use the timestamp of _last access_ to the file or _last modification_ ?

"Older than" here means "used less recently than". Perhaps that would be a better wording?

> From my limited understanding of the codebase,
> 
> https://github.com/ccache/ccache/blob/fe03859ebe1e5fdf87b02fba3d70f5854124d453/src/storage/local/LocalStorage.cpp#L277
> 
> indicates that the timestamp used is _last modification_.
>
> Could you update the documentation of the option to reflect this ?

That's correct. However, that's an implementation detail of the local file storage backend: It stores the last _usage_ of the file in the last modification timestamp (mtime), but it _could_ store it in another way. Therefore I would prefer not to document exactly how `--evict-older-than` is implemented, only its effect.
 
> (Also, kinda unrelated since this is an improvement issue, but could you justify why you wen with this rather than last access to the file ?)

As mentioned above, your assumption that it's the last time of modification of the file that is used for eviction is incorrect. It's the last usage (i.e. read) that is used. There are two reasons for not using the last access timestamp (atime):

1. Not all supported file systems have an (enabled) atime field for file entries.
2. atime will be updated when ccache reads file entries with e.g. `--show-compression` to inspect file headers, but that doesn't mean that we want to consider the file "recently used".

**Comment by iTrooz** [comment]
> "Older than" here means "used less recently than". Perhaps that would be a better wording?

Yes, I believe so. At least it would be clearer to me

I now understand better, thank you
Would you like me to submit a PR for this, or do it yourself ?
