### ISSUE TITLE
CCACHE_REMOTE_STORAGE sharding doesn't accept valid ports

### ISSUE THREAD

**Issue by peter-gyarmati** [ccache/ccache#1321]
### How to reproduce ###

1. Try to set `CCACHE_REMOTE_STORAGE="redis://${{ IP }}:*|shards=${{ PORT1 }},${{ PORT2 }},${{ PORT3 }}"` e.g. `$env:CCACHE_REMOTE_STORAGE="redis://10.0.0.4:*|shards=6379,6380,6381"`
 which fails with `ccache : error : Cannot parse URL redis://10.0.0.4:*: Port '*' in 'redis://10.0.0.4:*' is invalid`
2. Set `CCACHE_REMOTE_STORAGE="redis://${{ IP }}*|shards=:${{ PORT1 }},:${{ PORT2 }},:${{ PORT3 }}"` e.g. `$env:CCACHE_REMOTE_STORAGE="redis://10.0.0.4*|shards=:6379,:6380,:6381"` and it works with proper sharding.

### Actual behavior ###
You can't use ports as shards, but you can bypass the URL validation with a dirty hack.

### Expected behavior ###
Shards should work with ports, to allow clustering on the same host (e.g. with Docker containers) and shard parameters should be validated.

### Environment ###

ccache version 4.7.4

**Comment by afbjorklund** [comment]
The main problem is that the `Url` class is used _everywhere_ with the template, so not so easy to replace.

Easier to patch the third party library, to allow having wildcards in the port (allow `*`, even it is not a digit)

**Comment by peter-gyarmati** [comment]
> The main problem is that the `Url` class is used _everywhere_ with the template, so not so easy to replace.
> 
> Easier to patch the third party library, to allow having wildcards in the port (allow `*`, even it is not a digit)

Don't you think validating the shards should be beneficial? With this fix you can set the shards to ports, but still can provide characters like colon in the shards fields. 

I'm not familiar with the code-base, but doesn't this have security implications as a possible vulnerability?

**Comment by jrosdahl** [comment]
@afbjorklund wrote:
> Easier to patch the third party library

Sorry, but I don't think that's a good idea. I want to avoid bundling modified third party libraries unless absolutely necessary.

Instead I suggest expanding the URL pattern into real URLs (stored in a `url` field in `RemoteStorageShardConfig`) and let `Storage::get_shard_url` return that field instead of replacing the `*`. This also fully generalizes the placeholder so that you could have e.g. `remote_storage = *|shards=redis://A,http://B` if wanted.

@peter-gyarmati wrote:
> still can provide characters like colon in the shards fields [...] doesn't this have security implications as a possible vulnerability?

Isn't this equivalent to configuring a bad URL without using shards – what you get is a just non-working configuration? Could you expand a bit on why you think this could have security implications?

**Comment by peter-gyarmati** [comment]
> @afbjorklund wrote:
> 
> > Easier to patch the third party library
> 
> Sorry, but I don't think that's a good idea. I want to avoid bundling modified third party libraries unless absolutely necessary. Also, if we make the `Url` class silently accept `*` as a port we might be bitten when validating URLs in other contexts where `*` is not an acceptable port.
> 
> Instead I suggest expanding the URL pattern into real URLs (stored in a `url` field in `RemoteStorageShardConfig`) and let `Storage::get_shard_url` return that field instead of replacing the `*`. This also fully generalizes the placeholder so that you could have e.g. `remote_storage = *|shards=redis://A,http://B` if wanted.
> 
> @peter-gyarmati wrote:
> 
> > still can provide characters like colon in the shards fields [...] doesn't this have security implications as a possible vulnerability?
> 
> Isn't this equivalent to configuring a bad URL without using shards – what you get is just a non-working configuration? Could you expand a bit on why you think this could have security implications?

Take all this with a grain of salt as I'm not familiar with the codebase, so please correct me if this is not a valid concern. My idea is if you don't validate shards properly - and this is where the context of being familiar with code comes in - based on how you handle it afterwards, people can inject code into it with similar pattern `remote_storage = my-*-remote_storage_url|shards={{ injected_code}}, shard2, shard3`. 

If this is something that's possible it's probably very low risk, but I wanted to raise awareness regardless.
