### ISSUE TITLE
Cache size accounting on ZFS Datasets with compression not working

### ISSUE THREAD

**Issue by Johnnynator** [ccache/ccache#1332]
### How to reproduce ###

1.  Have CCACHE_DIR on a zfs filesystem with compression enabled on the ZFS Dataset
2.  Compile stuff
3.   `ccache -s` and `ccache -x` should report  (roughly(?)) the same cache size and match the File system size

### Actual behavior ###

The cache size is getting reported as `0.0 GiB` and Cache cleanup never happens.

```
 ccache -s
Cacheable calls:    161251 / 234541 (68.75%)
  Hits:              45345 / 161251 (28.12%)
    Direct:          29391 /  45345 (64.82%)
    Preprocessed:    15954 /  45345 (35.18%)
  Misses:           115906 / 161251 (71.88%)
Uncacheable calls:   73290 / 234541 (31.25%)
Local storage:
  Cache size (GiB):    0.0 /    5.0 ( 0.00%)
  Hits:              45345 / 161251 (28.12%)
  Misses:           115906 / 161251 (71.88%)
```

```
ccache -x
Scanning... 100.0% [===================================================================================================]

Total data:           24.1 GiB
Compressed data:      24.1 GiB   (35.5% of original size)
  Original size:      68.0 GiB
  Compression ratio: 2.817 x     (64.5% space savings)
Incompressible data:     0 bytes
```
```
du -sh ccache/
25G     ccache/
```
### Expected behavior ###
Accounted cache size should increase automatically and be the same as the actual on disk size.

### Environment ###
ccache version 4.8.2
OS: Void Linux with zfs-2.1.12 and linux 6.3.13

### Related Issues on external Bugtracker ###

Some people on FreeBSD see3m to be running into the same issue https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261705
They tracked it down to zfs only reporting the file-size initially as 1 block and only updates it later after compression and writing has finished.

**Comment by trofi** [comment]
Yeah, storage becomes more and more complicated.

And to add on top of it even when block size is reported it does not necessarily mean on-disk storage if the deduplication is at play and is able to share data across files within `ccache` cache directory. Some tools use slower `fiemap()` syscall to find out the physical layout on disk for a particular file.

Perhaps it's a good time for `ccache` to give up on blocks accounting and use the logical size with added `likely_size_on_disk()` like windows case does?

**Comment by jrosdahl** [comment]
> Perhaps it's a good time for `ccache` to give up on blocks accounting and use the logical size with added `likely_size_on_disk()` like windows case does?

Yes, that's the only reasonable solution I can think of as well.
