### ISSUE TITLE
GCC: `gcm.cache` output not cached/restored

### ISSUE THREAD

**Issue by torokati44** [ccache/ccache#1333]
### How to reproduce ###

```bash
ccache -cCz
# ...
ls
# foobar.cc
g++ -std=c++20 -fmodules-ts  -c foobar.cc
ls
# foobar.cc  foobar.o  gcm.cache
rm -rf gcm.cache foobar.o
g++ -std=c++20 -fmodules-ts  -c foobar.cc
ls
# foobar.cc  foobar.o
```

```c++
// foobar.cc
module;

#include <iostream>

export module foobar;

export void hello() {
    std::cout << "Hello, world!" << std::endl;
}
```

### Actual behavior ###

The second (cached) invocation of `g++` only produced `foobar.o`, not `gcm.cache`.

### Expected behavior ###

The first and second `g++` invocations are indistinguishable.

### Environment ###

ccache version 4.8.2

g++ (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)

**Comment by torokati44** [comment]
Similarly, when ran after the commands above,
`g++ -std=c++20 -fmodules-ts -fmodule-only -c foobar.cc`
behaves as if `-fmodule-only` wasn't there.
As in, it produces `foobar.o`, which it shouldn't; but doesn't produce `gcm.cache`, which it should.

**Comment by jrosdahl** [comment]
Regarding support for C++20 modules, see #1252.

**Comment by torokati44** [comment]
Thank you for the quick fix! Shouldn't the `-fmodule-only` flag also be added there, in addition to `-fmodule-header`?

**Comment by jrosdahl** [comment]
> Thank you for the quick fix! Shouldn't the `-fmodule-only` flag also be added there, in addition to `-fmodule-header`?

The way I read https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Modules.html is that `-fmodule-only` only has effect when `-fmodules-ts` is also given.

**Comment by torokati44** [comment]
Right, that might be correct, pardon me.
