### ISSUE TITLE
Assertion failure on Windows UNC paths

### ISSUE THREAD

**Issue by mablanchard** [ccache/ccache#1334]
### How to reproduce ###

Requires non-trivial setup with `includedir` being symlinks resolving to remote SMB shares + using `CCACHE_BASEDIR`...
I'm trying to extract a minimal setup to reproduce but that hasn't been easy so far. I have working `ccache` devel. environment to debug/experiment though (ie. ask me anything).

### Actual behavior ###

```
ccache: Util.cpp:672: std::string Util::get_relative_path(std::string_view, std::string_view): failed assertion: util::is_absolute_path(path)
```

### Expected behavior ###

Well, `ccache` to properly detect and resolve UNC Windows paths.

### Environment ###

ccache version 4.8.3
clang-cl version 15.0.3
Windows Server 2022 Standard 21H2
Developer Mode on

**Comment by mablanchard** [comment]
Adding debug prints in `util::is_absolute_path()` gives:

```
dir=S:/[...]/clang15.0.3
path=UNC/[...]/clang15.0.3/lib/clang/15.0.3/include/vadefs.h
````

And indeed, it seems like `ccahe` has no understanding of these `UNC/` paths. Debugging this little further shows that these kind of paths are generated by `GetFinalPathNameByHandle()` at [src/Util.cpp#L1021](https://github.com/ccache/ccache/blob/v4.8.3/src/Util.cpp#L1021C1-L1022).

**Comment by mablanchard** [comment]
It seems like 3cacab8daa1ca13a4f3d93096fe6550989b17182 somehow fixes it! `std::filesystem::canonical()` gives, in `util::is_absolute_path()`:
```
dir=S:/[...]/clang15.0.3
path=///[...]/clang15.0.3/lib/clang/15.0.3/include/vadefs.h
```
Witch is properly handled.

**Comment by jrosdahl** [comment]
> It seems like https://github.com/ccache/ccache/commit/3cacab8daa1ca13a4f3d93096fe6550989b17182 somehow fixes it!

Right, thanks for checking. I'm (very) slowly converting the code to use `std::filesystem::path` to fix issues like these.

**Comment by jrosdahl** [comment]
> Yep, I could see that, should fix a lot of these kind of problems indeed! Speaking of which, do you plan on implementing `util::to_absolute_path()` with `std::filesystem::absolute()`?

Yes, or rather remove it since it won't be needed anymore.
