### ISSUE TITLE
ccache doesn't handle assembler .incbin directives

### ISSUE THREAD

**Issue by tanstafel** [ccache/ccache#136]
With ccache 3.3.x it happens that the linux kernel image is the same after changing the source code and rebuilding it. On some machine I can reproduce this always on some other not. Dunno why.
I already mentioned the issue in #133 and #134 because I assumed there is some relation but now I found out the reason:
What's happening is that arch/x86/boot/compressed/piggy.o is taken from cache even that the arch/x86/boot/compressed/piggy.S files dependencies changed. The file piggy.S includes another file via .incbin directive. In the manual I read in the sectiion "CAVEATS" that this directive is not correcty handled by ccache so its actually documented. You cannot expect that all users of ccache find out and workaround this issue by themself. So that should be fixed because this .incbin seems to be used by at least one large project.

Edited: Initially I mentioned ccache 3.2.x but meant 3.3.x. Sorry.

**Comment by jrosdahl** [comment]
Thanks for investigating this further.

From https://lists.samba.org/archive/ccache/2010q1/000489.html:

> The only reasonable way I see to tackle this is to avoid caching any source
> code that has a string literal containing ".incbin". It would be easy to fool,
> and there will be a few false positives, but maybe it's good enough.

Do you think that would be an OK solution? Six years later I still don't see any other feasible solution.

> With ccache 3.3.x 

Nothing related to .incbin processing has changed between ccache 3.2.x and 3.3.x, so if there's a behavioral difference it has to be that 3.2.x for some reason doesn't even try to cache the object file in question while 3.3.x does.

**Comment by tanstafel** [comment]
The idea of not caching files with .incbin in it is good enough I think. I had this in mind as well.
