### ISSUE TITLE
Running gcc/clang with only the `-arch` argument segfaults

### ISSUE THREAD

**Issue by OldWorldOrdr** [ccache/ccache#1377]
### How to reproduce ###

1. run ccache gcc or clang with the only argument being `-arch`

### Actual behavior ###

```
zsh: segmentation fault (core dumped)  ./ccache gcc -arch
```

### Expected behavior ###

the normal gcc/clang output
```
gcc: error: unrecognized command-line option ‘-arch’
gcc: fatal error: no input files
compilation terminated.
```

```
clang-16: error: argument to '-arch' is missing (expected 1 value)
clang-16: error: no input files
```

### Environment ###

I used the [latest offical binary release](https://github.com/ccache/ccache/releases/download/v4.9/ccache-4.9-linux-x86_64.tar.xz)

The version in arch repos, 4.8.3-1, has a different crash error
```
/usr/include/c++/13.2.1/bits/stl_deque.h:1366: std::deque<_Tp, _Alloc>::reference std::deque<_Tp, _Alloc>::operator[](size_type) [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >; reference = std::__cxx11::basic_string<char>&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
zsh: IOT instruction (core dumped)  ccache gcc -arch
```

**Comment by jrosdahl** [comment]
Thanks for the bug report. The issue has been present since 89aa39f394e0fa4935e6cadd7184e372a37f9506 (ccache 3.3).
