### ISSUE TITLE
Failure to parse due to `#line` directives

### ISSUE THREAD

**Issue by benoit-pierre** [ccache/ccache#1406]
### How to reproduce ###

1. use ccache 4.9.1
2. compile [harfbuzz](https://github.com/harfbuzz/harfbuzz) (e.g.: `meson setup . build && ninja -C build`)

### Actual behavior ###

`ccache -vs` list a number of "Could not read or parse input file" errors. This is because a number of generated headers in `src` have `#line` directives:
```bash
▹ /usr/bin/grep -r -m 1 '^#line' src
src/hb-buffer-deserialize-text-unicode.hh:#line 1 "hb-buffer-deserialize-text-unicode.rl"
src/hb-buffer-deserialize-json.hh:#line 1 "hb-buffer-deserialize-json.rl"
src/hb-ot-shaper-use-machine.hh:#line 1 "hb-ot-shaper-use-machine.rl"
src/hb-ot-shaper-khmer-machine.hh:#line 1 "hb-ot-shaper-khmer-machine.rl"
src/hb-ot-shaper-myanmar-machine.hh:#line 1 "hb-ot-shaper-myanmar-machine.rl"
src/hb-buffer-deserialize-text-glyphs.hh:#line 1 "hb-buffer-deserialize-text-glyphs.rl"
src/hb-ot-shaper-indic-machine.hh:#line 1 "hb-ot-shaper-indic-machine.rl"
src/hb-number-parser.hh:#line 1 "hb-number-parser.rl"
```

And ccache fails to stat those (because of the out-of-tree build). Cf except from the debug log:

```
[2024-02-21T17:24:04.025452 75023] Inode cache hit: ../src/hb-object.hh
[2024-02-21T17:24:04.025651 75023] Too new ctime or mtime of ../src/hb-number-parser.hh, not considering for inode cache
[2024-02-21T17:24:04.025687 75023] Too new ctime or mtime of ../src/hb-number-parser.hh, not considering for inode cache
[2024-02-21T17:24:04.025716 75023] Failed to lstat hb-number-parser.rl: No such file or directory
[2024-02-21T17:24:04.025880 75023] Failed; falling back to running the real compiler
```

### Expected behavior ###

Ignore the stat failures and successfully cache those compilations.

### Environment ###

ccache version 4.9.1

**Comment by benoit-pierre** [comment]
Regression testing with `git bisect` points at 43c3a44aadcb122853ee1e3eb8db00db9d8de68f.

**Comment by jrosdahl** [comment]
Thanks for the bug report.

Ccache does not parse the actual `#line` directives but the resulting output from the preprocessor. After 43c3a44aadcb122853ee1e3eb8db00db9d8de68f non-existent files referenced in the preprocessor output indeed result in "Could not read or parse input file".

I'll fix it so that this case merely disables direct mode instead of bailing out, similar to the previous behavior.

**Comment by benoit-pierre** [comment]
Thanks! Note that even with `CCACHE_NODIRECT=1` it still fails.
