### ISSUE TITLE
ccache lockfiles do not work in msys2

### ISSUE THREAD

**Issue by Kreijstal** [ccache/ccache#1415]
### How to reproduce ###

1. git clone master in msys2
2.  compile
3.  run test suite

### Actual behavior ###

as discussed on #1412
lock loops hangs forever.

### Expected behavior ###

This loop should eventually exit, but it hangs forever, or test should pass.

### Environment ###

ccache version 68c7decaaa1c808ac77636714ab02f3343c7d743 (git master)

msys2 enviroment, no mingw
windows 11
msys2 already knows this https://github.com/msys2/MSYS2-packages/issues/4449

**Comment by jrosdahl** [comment]
Thanks for the bug report.

> msys2 already knows this https://github.com/msys2/MSYS2-packages/issues/4449

I followed the trail and see that you wrote this in https://github.com/msys2/MSYS2-packages/issues/4311#issuecomment-1987177326:

> Ok, so what I've discovered is that ccache tests symlinks, and Msys implements them as copying. Which confuses the test suite.

It's not the test suite that gets confused – it points out that the lockfile implementation is broken on msys2 since is relies on working POSIX semantics for symlinks. Since the lockfile implementation does not work on msys2, ccache does not work properly on msys2 even if you avoid running the test suite.

The fix would be to either implement proper symlink support on msys2 or to implement lockfiles differently on msys2. And since there is already a [proper Windows implementation in place](https://github.com/ccache/ccache/blob/68c7decaaa1c808ac77636714ab02f3343c7d743/src/ccache/util/LockFile.cpp#L357) I suspect that the latter would be easy to do.

**Comment by jrosdahl** [comment]
@Kreijstal: Could you try if latest ccache master works better?

**Comment by Kreijstal** [comment]
```
/home/topkek/git/ccache/src/ccache/util/wincompat.hpp:67:12: fatal error: direct.h: No such file or directory
   67 | #  include <direct.h>
      |            ^~~~~~~~~~
compilation terminated.
```
That's okay, I'll need to figure out how to access win32 from cygwin/msys2, but it seems promising.
https://cygwin.com/cygwin-ug-net/using.html#pathnames-win32-api
I think I'll try solving this issue with this knowledge, thank you.

**Comment by jrosdahl** [comment]
@Kreijstal: Try what happens with

```diff
--- a/src/ccache/util/wincompat.hpp
+++ b/src/ccache/util/wincompat.hpp
@@ -18,7 +18,7 @@
 
 #pragma once
 
-#if defined(_WIN32) || defined(__CYGWIN__)
+#if defined(_WIN32)
 #  include <sys/stat.h>
 
 #  define NOMINMAX 1
```

**Comment by jrosdahl** [comment]
That said, if it doesn't work well to use Win32's `CreateFile` then you could implement `LockFile::do_acquire`  in some way that suits `__CYGWIN__`, for instance with POSIX `open(..., O_WRONLY | O_CREAT | O_EXCL)`.

**Comment by Kreijstal** [comment]
please revert c6a6e6accefe9e79601e56be5f7438cb593ff016, while in theory you could support w32api on cygwin, it is really troublesome. I think I'll try writing some version for cygwin, that being said, do you want it to be upstreamed?

**Comment by jrosdahl** [comment]
> please revert [c6a6e6a](https://github.com/ccache/ccache/commit/c6a6e6accefe9e79601e56be5f7438cb593ff016), while in theory you could support w32api on cygwin, it is really troublesome.

Done.

> I think I'll try writing some version for cygwin, that being said, do you want it to be upstreamed?

I don't mind either way.

**Comment by Kreijstal** [comment]
Okay, I've managed to end the infinite loop by, checking for existence before creating the directory, out of curiosity, I also tested the behaviour of `fs::create_directories` in bare msys2, to see if it was a bug of msys2, but it seems the raw functions do not have this bug, only the wrapper from ccache. This alleviates the biggest issue, maybe this could be a cygwin only fix.

```diff
diff --git a/unittest/test_Util.cpp b/unittest/test_Util.cpp
--- a/unittest/test_Util.cpp
+++ b/unittest/test_Util.cpp

@@ -245,13 +246,13 @@ LockFile::do_acquire(const bool blocking)
     int saved_errno = errno;
     if (saved_errno == ENOENT) {
       // Directory doesn't exist?
-      if (fs::create_directories(m_lock_file.parent_path())) {
+      if (fs::exists(m_lock_file.parent_path())&&fs::create_directories(m_lock_file.parent_path())) {
         // OK. Retry.
         continue;
       }
     }
```

**Comment by jrosdahl** [comment]
>  I also tested the behaviour of fs::create_directories in bare msys2, to see if it was a bug of msys2, but it seems the raw functions do not have this bug, only the wrapper from ccache. 

What do you mean by raw functions in this case?

(`fs::create_directories` just calls `std::filesystem::create_directories` without any added or removed logic.)

**Comment by Kreijstal** [comment]
Sorry for the unclear message before, I discovered, that msys2 symlinks error if destination does not exist. So if location exist, it will symlink, but it will refuse to symlink to nonexistent location. I will send a pull request shortly.
