### ISSUE TITLE
Add support for `-Xpreprocessor -fopenmp` on Apple Clang

### ISSUE THREAD

**Issue by FedericoGnesotto** [ccache/ccache#1434]
Usage of OpenMP with Apple Clang requires the following flags to be passed to the compiler: `-Xpreprocessor -fopenmp`.
When using those flags, ccache emits the error: "Unsupported compiler option for direct mode: -Xpreprocessor" and invokes the preprocessor.
Support for this flag would be much appreciated.

**Comment by res0nance** [comment]
This option does work when direct mode is disabled.

**Comment by FedericoGnesotto** [comment]
> This option does work when direct mode is disabled.
Thanks for answering!
Any possibility to make this work in direct mode too? I would be open to contribute it myself, with some guidance..

**Comment by jrosdahl** [comment]
All uses of -`Xpreprocessor` disable the direct mode as a safety measure since the command line could include things like

    -Xpreprocessor -MF -Xpreprocessor file.d

which ccache needs to understand as

    -MF file.d

Ideally, ccache should handle this in a generic way, and I do have some plans on how to improve argument parsing in general. But I'll add a special case for `-Xpreprocessor -fopenmp` for now.

**Comment by zap150** [comment]
Hi, have you encountered any issues after enablig this? I cannot use Ccache after this update on MacOS ARM/C++ with OpenMP.

**Comment by FedericoGnesotto** [comment]
Hi, no I have not seen this kind of issues, i.e. we can see a much higher number of direct hits in cache now. What I also observed though, is that some unit tests that use openmp are now slower. Any clue why that might be the case?

**Comment by zap150** [comment]
I don't know to be honest. It seems to me that some compilation units do not see `_OPENMP` defined when they should. I am not sure I would be able to provide some minimal working example easily though. We use the Conan llvm-openmp package for our project.

@jrosdahl any ideas how to procceed? Ccache 4.10 seems not to work correctly in some cases.

**Comment by jrosdahl** [comment]
@zap150: I suggest opening a new issue with your best attempt at describing the problem you see. For instance, what errors do you get? Any idea how to reproduce the issue even if it's not a minimal example?
