### ISSUE TITLE
Ccache does not work correctly with Clang coverage with run_second_cpp = false (CCACHE_NOCPP2)

### ISSUE THREAD

**Issue by 0berstmarschall** [ccache/ccache#1441]
I tried to compile code with coverage using clang and ccache according to the [instruction](https://clang.llvm.org/docs/SourceBasedCodeCoverage.html).

I see that the coverage data is saved in a temporary ccache directory, it seems that clang-based coverage does not support compilation with ccache.

### How to reproduce ###

Compile the source code so that ccache covers the source file. Then link object file to executable and run coverage report generation using llvm.

1. ccache clang++ -fprofile-instr-generate -fcoverage-mapping -c foo.cc -o foo.o  
2. ccache clang++ -fprofile-instr-generate -fcoverage-mapping foo.o -o foo
3. LLVM_PROFILE_FILE="foo.profraw" ./foo
4. llvm-profdata-13 merge -sparse foo.profraw -o foo.profdata
5. llvm-cov-13 export -instr-profile=foo.profdata ./foo -format=lcov >> coverage.info

### Actual behavior ###

If compilation of source code was covered by ccache, source files in the coverage report refer to temporary ccache directory:
SF refers to *clang/ccache/tmp/cpp_stdout.tmp.ZzWHVe.ii*:
```
root@674c1a4d14be:/clang# cat coverage.info
SF:/clang/ccache/tmp/cpp_stdout.tmp.ZzWHVe.ii
FN:12,main
FN:9,_Z3fooIiEvT_
FN:9,_Z3fooIfEvT_
FNDA:1,main
```
*llvm-cov-13 show* command failed due to file absence:
```
root@674c1a4d14be:/clang# ls /clang/ccache/tmp/
root@674c1a4d14be:/clang#
root@674c1a4d14be:/clang# llvm-cov-13 show ./foo -instr-profile=foo.profdata
error: /clang/ccache/tmp/cpp_stdout.tmp.ZzWHVe.ii: No such file or directory
warning: The file '/clang/ccache/tmp/cpp_stdout.tmp.ZzWHVe.ii' isn't covered. 
```

Ccache log (see full log below):
```
...
[2024-04-22T12:37:08.186140 906  ] Command line: ccache clang++ -fprofile-instr-generate -fcoverage-mapping -c foo.cc -o foo.o
[2024-04-22T12:37:08.186146 906  ] Hostname: 674c1a4d14be
[2024-04-22T12:37:08.186149 906  ] Working directory: /clang
[2024-04-22T12:37:08.186153 906  ] Compiler type: clang
[2024-04-22T12:37:08.186174 906  ] Set profile directory to .
[2024-04-22T12:37:08.186224 906  ] Source file: foo.cc
[2024-04-22T12:37:08.186228 906  ] Object file: foo.o
...
```
[ccache_successful.txt](https://github.com/ccache/ccache/files/15137184/ccache_ok.txt)

### Expected behavior ###

Without using ccache or in case if the file compilation was not covered by ccache, the coverage report refers to local source files.
I expect to have similar behavior in case when source files compilation covered by ccache, the coverage report should point to existing source files. Below you can see an example of successful attempt when compilation was not covered by ccache.

Steps to reproduce:

1. ccache clang++ -fprofile-instr-generate -fcoverage-mapping foo.cc -o foo 
2. LLVM_PROFILE_FILE="foo.profraw" ./foo
3. llvm-profdata-13 merge -sparse foo.profraw -o foo.profdata
4. llvm-cov-13 export -instr-profile=foo.profdata ./foo -format=lcov >> coverage.info

As you see below, SF points to local file, coverage report generated successfully.
```
root@674c1a4d14be:/clang-no-ccache# cat coverage.info
SF:/clang-no-ccache/foo.cc
FN:5,main
FN:2,_Z3fooIiEvT_
```
Coverage info printed:

```
root@674c1a4d14be:/clang-no-ccache# llvm-cov-13 show ./foo -instr-profile=foo.profdata
    1|     20|#define BAR(x) ((x) || (x))
    2|      2|template <typename T> void foo(T x) {
    3|     22|  for (unsigned I = 0; I < 10; ++I) { BAR(I); }
    4|      2|}
  ------------------
  | _Z3fooIiEvT_:
  |    2|      1|template <typename T> void foo(T x) {
  |    3|     11|  for (unsigned I = 0; I < 10; ++I) { BAR(I); }
  |    4|      1|}
  ------------------
  | _Z3fooIfEvT_:
  |    2|      1|template <typename T> void foo(T x) {
  |    3|     11|  for (unsigned I = 0; I < 10; ++I) { BAR(I); }
  |    4|      1|}
  ------------------
    5|      1|int main() {
    6|      1|  foo<int>(0);
    7|      1|  foo<float>(0);
    8|      1|  return 0;
    9|      1|} 
```

Ccache log (see full log below):
```
...
[2024-04-22T12:31:20.005560 867  ] No -c option found
[2024-04-22T12:31:20.005566 867  ] Failed; falling back to running the real compiler
[2024-04-22T12:31:20.005570 867  ] Executing /usr/bin/clang++ -fprofile-instr-generate -fcoverage-mapping foo.cc -o foo
...
```
[ccache_skip.txt](https://github.com/ccache/ccache/files/15137183/ccache_failed.txt)

Ccache stats:
```
root@674c1a4d14be:/clang-no-ccache# ccache -s
Cacheable calls:      0 /    1 ( 0.00%)
  Hits:               0
    Direct:           0
    Preprocessed:     0
  Misses:             0
Uncacheable calls:    1 /    1 (100.0%)
Local storage:
  Cache size (GB): 0.00 / 5.00 ( 0.00%) 
```

### Environment ###

ccache version 4.7.4 (the same results for ver. master.b358bb27)

Ubuntu clang  13.0.1-++20220120110924+75e33f71c2da-1~exp1~20220120231001.58

Ubuntu 20.04.6 LTS

**Comment by jrosdahl** [comment]
@0berstmarschall: What happens if you change `run_second_cpp` to `true` in `ccache/ccache.conf`?

**Comment by 0berstmarschall** [comment]
@jrosdahl I have the expected behavior with this parameter. Thank you for support.

**Comment by jrosdahl** [comment]
Reopening since the bug still exists.
