### ISSUE TITLE
Direct mode match unexpected cache

### ISSUE THREAD

**Issue by zcfh** [ccache/ccache#1443]
### How to reproduce ###

1.  test code
```c++
// test.cc
#include "test.h"
```
2.  touch test1/test.h test2/test.h
3. compile command
```
$ccache  /home/distcc/clang-11.1.0/bin/clang++ -c test.cc  -Itest1 -Itest2
mv test1 test1.bak
$ccache  /home/distcc/clang-11.1.0/bin/clang++ -c test.cc  -Itest1 -Itest2
mv test1.bak test1
$ccache  /home/distcc/clang-11.1.0/bin/clang++ -c test.cc  -Itest1 -Itest2
```

### Actual behavior ###

In the second compilation, mainfest_key is the same as the first time, but since `test1/test.h` does not exist, it will be reprocessed and compiled, and a new cache will be created. The cached test.h is the expanded from `tetst2/test.h`. When compiling for the third time, the matching cache is the result of the second compilation, but `test1/test.h` has been restored at this time, and the expected result should be the cache of the first compilation.

### Environment ###

ccache version 4.6

**Comment by zcfh** [comment]
I read the code, `look_up_result_digest` matches `m_results` from back to front, and `result_matches` **only detects whether the cached manifest content changes**, and does not detect whether the compiled header file path changes.
Is this for performance reasons? But this produces unintended results.
I tested it and used `-M` to expand all header files. It is much faster than -MD and only takes 50% of the time. I haven't investigated other options yet, maybe there is a faster option to expand all header files with full preprocessing.

**Comment by jrosdahl** [comment]
Thanks for the bug report.

What you describe is known and documented limitation of the direct mode, see [_Caveats_](https://ccache.dev/manual/4.9.1.html#_caveats) in the manual. See also #504.

> I read the code, `look_up_result_digest` matches `m_results` from back to front, and `result_matches` **only detects whether the cached manifest content changes**, and does not detect whether the compiled header file path changes. Is this for performance reasons?

Checking the newest result first is a performance thing, yes: https://github.com/ccache/ccache/blob/1655998d41315faacb56b4bbad79fd98af5e12f7/src/ccache/core/Manifest.cpp#L161

> But this produces unintended results.

While your example would have worked if the results were checked in the order from oldest to newest, there are other equally valid examples where searching newest to oldest is better, so changing the order wouldn't really solve anything.

> I tested it and used `-M` to expand all header files. It is much faster than -MD and only takes 50% of the time. I haven't investigated other options yet, maybe there is a faster option to expand all header files with full preprocessing.

The problem with `-M` is that it's still quite slow (actually equally slow as `-E` with the Clang version I have installed) and it would increase the overhead of a cache miss even further.

----

But! Ccache 4.10 will include an improvement that actually makes your example and some other cases work correctly: b672f7ebad09

**Comment by zcfh** [comment]
Thank you for your answer.
> While your example would have worked if the results were checked in the order from oldest to newest, there are other equally valid examples where searching newest to oldest is better, so changing the order wouldn't really solve anything.

Regarding the detection order, I just want to express that the problem will be triggered in this demo scenario, and I do not want to modify the order.  
> The problem with -M is that it's still quite slow

Regarding -M, I haven't found an option to get the header file faster. If run `-E` again, it is better to use preprocessed mode directly.  

> But! Ccache 4.10 will include an improvement that actually makes your example and some other cases work correctly: https://github.com/ccache/ccache/commit/b672f7ebad0967551d48cf93a65e052fb5cb3049

Regarding this patch, it seems that it can solve part of the problem, I will try to use it.
