### ISSUE TITLE
`cmake -DFETCHCONTENT_FULLY_DISCONNECTED=ON` has no effect

### ISSUE THREAD

**Issue by jirislaby** [ccache/ccache#1456]
https://github.com/ccache/ccache/blob/d8523efc8328cc83b30ddeb3f89038bbd02c74a5/cmake/Dependencies.cmake#L8-L10

In #1429, have you forgotten to do what the message says? IOW `-DFETCHCONTENT_FULLY_DISCONNECTED=ON` has no effect AFAICT.

**Comment by jrosdahl** [comment]
Indeed, thanks for noticing.
