### ISSUE TITLE
Configuration failure with fmt-11.0 due to movement of FMT_VERSION

### ISSUE THREAD

**Issue by hhoffstaette** [ccache/ccache#1477]
### How to reproduce ###

1. install fmt-11.0
2. try to build ccache-4.10.1 using external fmt
3. configuration error!

### Actual behavior ###

```
CMake Error at cmake/FindFmt.cmake:11 (math):
  math cannot parse the expression: " / 10000": syntax error, unexpected
  exp_DIVIDE (2).
Call Stack (most recent call first):
  cmake/Dependencies.cmake:25 (find_package)
  CMakeLists.txt:88 (include)

CMake Error at cmake/FindFmt.cmake:12 (math):
  math cannot parse the expression: " / 100 % 100": syntax error, unexpected
  exp_DIVIDE (2).
Call Stack (most recent call first):
  cmake/Dependencies.cmake:25 (find_package)
  CMakeLists.txt:88 (include)

CMake Error at cmake/FindFmt.cmake:13 (math):
  math cannot parse the expression: " % 100": syntax error, unexpected
  exp_MOD (2).
Call Stack (most recent call first):
  cmake/Dependencies.cmake:25 (find_package)
  CMakeLists.txt:88 (include)
```

### Expected behavior ###

Correct configuration

### Environment ###

ccache version 4.10.1

Reported on Gentoo in: https://bugs.gentoo.org/935291 (detailed logs etc).

**Comment by hhoffstaette** [comment]
As docuemnted on the downstream bug, fmt-11.0 has [changed the location of `FMT_VERSION` to be in `base.h`](https://github.com/fmtlib/fmt/commit/febd8ed5fee269984405c5502a19224c5106c610), so the [version check](https://github.com/ccache/ccache/blob/master/cmake/FindFmt.cmake#L10) does not find anything and croaks.

**Comment by jrosdahl** [comment]
Workarounds until ccache 4.10.2 or 4.11 is released:

- Pass `-D FMT_INCLUDE_DIR=<path-to-include-dir>` and `-D FMT_LIBRARY=<path-to-lib>` to CMake explicitly.
- Pass `-D DEP_FMT=BUNDLED` to CMake to use the bundled Fmt copy instead of the system one.
