### ISSUE TITLE
MSVC: Detect when different short paths point to the same cl.exe to prevent secondary storage misses

### ISSUE THREAD

**Issue by pablo-odorico** [ccache/ccache#1490]
CMake Ninja generator on Windows is using short "8.3 format" paths to call `cl.exe`. These paths may be different on multiple systems even when the full windows path is the same. This causes misses when using secondary storage such as HTTP.

For example, `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe`.

The short path can be `C:\PROGRA~2\MICROS~2\2022\BUILDT~1\VC\Tools\MSVC\1439~1.335\bin\Hostx64\x64\cl.exe` on one system and `C:\PROGRA~2\MIB055~1\2022\BUILDT~1\VC\Tools\MSVC\1439~1.335\bin\Hostx64\x64\cl.exe` on another.
It's common to find several dirs starting with "Microsoft" inside `C:\Program Files (x86)\` and the short naming will depend on the order the software was installed.

A workaround that seems to work is to proactively change the short names on all builders to something like `MICROS~9`: `fsutil file setshortname "c:\Program Files (x86)\Microsoft Visual Studio" MICROS~9`

[I reported this issue](https://discourse.cmake.org/t/cmake-ninja-is-using-windows-short-paths-which-causes-ccache-misses/11332) to CMake, but maybe ccache can handle this?

**Comment by jrosdahl** [comment]
I don't quite understand why there would be cache misses for compilers in differently named folders. The full path to the compiler is not supposed to be part of the input hash (which is what identifies the cache entry), only the compiler name (`cl.exe` in your case). Could the issue be something else, for instance that the compilers have different modification time (see the [compiler_check](https://ccache.dev/manual/4.10.2.html#config_compiler_check) config option)?

I suggest enabling [cache debugging](https://ccache.dev/manual/4.10.2.html#_cache_debugging) and checking what is differs in the different scenarios.
