### ISSUE TITLE
install host-ccache fails in Ubuntu 22.04.1 LTS Docker container hosted on M1

### ISSUE THREAD

**Issue by udance4ever** [ccache/ccache#1500]
### How to reproduce ###

1. set up Docker build environment per [Batocera Linux compilation from source instructions](https://wiki.batocera.org/compile_batocera.linux) on M1 (macOS Sonoma 14.6.1)
2. `make x86_64-build`
3. observe install error on `host-ccache`

### Actual behavior ###

```
mkdir: cannot create //.buildroot-: Permission denied
make: *** [package/pkg-generic.mk:294: /x86_64/build/host-ccache-4.8.2/.stamp_host_installed] Error 1ccachedirectory 
``` 

### Expected behavior ###

installation to complete and not stop make process.

### Environment ###

ccache version 4.8.2

running build in Ubuntu 22.04.1 LTS Docker container running on macOS 14.6.1 (2020 MBP M1 16GB 1TB)

```
$ g++ --version
g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
```

### Other observations

* I can verify this install error **does not** happen while compiling on an actual x86 machine (2015 MBP 8GB)
* It looks like `CMAKE_INSTALL_BINDIR` might be null: (`mkdir -p //.buildroot-ccache`):
https://github.com/ccache/ccache/blob/7a3142ed9f9063d60e736f7dcf4e59eed1c5dd09/CMakeLists.txt#L121C38-L121C58
* Where is `GNUInstallDirs` found? (couldn't find in this repo)
https://github.com/ccache/ccache/blob/dc5bb78d8351c19c3eb2cb18ada184ca66f7ceef/cmake/InstallDirs.cmake#L41
* I think it might alternatively have to do with $HOME == `/` and the root directory in the container not being writable (thus why `mkdir -p //.buildroot-ccache` fails)

**Comment by jrosdahl** [comment]
> Where is `GNUInstallDirs` found? (couldn't find in this repo)

It's a standard CMake module: https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html. I don't know why it doesn't work in the environment you mention.

**Comment by udance4ever** [comment]
I isolated the issue - in the `Makefile` I am using:
```
        @$(DOCKER) run -it --init --rm \
.
.
.
                -v $(CCACHE_DIR):$(HOME)/.buildroot-ccache \
```
with:
```
        @$(DOCKER) run -it --init --rm \
.
.
.
                -v $(CCACHE_DIR):/.buildroot-ccache \
```
because $HOME in macOS (`/Users/udance4ever`) doesn't translate inside the Linux container (in fact, HOME is undefined)

I haven't tested it fully yet but I'm going to close this issue as I don't foresee any issues.

**Comment by udance4ever** [comment]
a fellow developer found an even [more elegant fix](https://github.com/batocera-linux/batocera.linux/pull/12410#issue-2497967311). The TL;DR:

Docker has an `-e HOME` option that creates the mount point & bind mount the ccache directory at $HOME/.buildroot-ccache in the container.
