### ISSUE TITLE
Backslash in Windows path

### ISSUE THREAD

**Issue by RobinMaub** [ccache/ccache#1513]
### How to reproduce ###

1. Use the CLion  or any other tool to build for an embedded platform under windows system
2. load presets (as follows) (or create your own toolchain file)
3. try to build

### Actual behavior ###

An issue is raised because the ccache command exists, showing a “not found” compiler in the PATH:

ccache: error: Could not find compiler "C:\msys64\mingw64\bin\arm-none-eabi-gcc.exe" in PATH

The compiler is in the PATH but the issue comes from the fact that we have backslashes.

I have tried using the following presets:

 {
     "name": "stm32f446-release",
     "displayName": "Release Config",
     "description": "Release build using Ninja generator for STM32F446",
     "generator": "Ninja",
     "binaryDir": "xxx",
     "toolchainFile": “xxx”,
     "cacheVariables": {
       "CMAKE_BUILD_TYPE": "Release",
       "CMAKE_C_COMPILER_LAUNCHER": "ccache",
       "CMAKE_CXX_COMPILER_LAUNCHER": "ccache",
       "CMAKE_TOOLCHAIN_FILE": "xxx",
       "BUILD_VERSION": "dev",
       "BUILD_ID": "$env{USER}",
       "BUILD_TESTING": false,
       "STM32_CHIP": "STM32F446",
       "CONAN_WORKSPACE": true
     },
     "environment": {
       "CC": "arm-none-eabi-gcc",
       "CXX": "arm-none-eabi-g++"
     }
   },

### Expected behavior ###

Paths are correct and compilation possible

### Environment ###

ccache version 4.10

Windows, MSYS2, GCC 13,

**Comment by jrosdahl** [comment]
@RobinMaub: A ccache log file would be handy to find out what happens. You can set [`log_file` in the ccache configuration file](https://ccache.dev/manual/4.10.2.html#config_log_file) (or set environment variable `CCACHE_LOGFILE`) to a suitable filename and then publish the log here.

**Comment by RobinMaub** [comment]
Hi,
Issue is solved by using the mingw64 package instead of the msys2 package!
sorry for disturbing
