### ISSUE TITLE
Diagnostic colors not working if c++ is hardlinked to g++

### ISSUE THREAD

**Issue by Desour** [ccache/ccache#1514]
### How to reproduce ###

1. Be using arch, btw..
2. `/usr/lib/ccache/bin/g++ -c broken.cpp`
3. `/usr/lib/ccache/bin/c++ -c broken.cpp`
4. `/usr/lib/ccache/bin/c++ broken.cpp`

### Actual behavior ###

2. and 4. produce colors.
3. does not produce colors.

### Expected behavior ###

`/usr/lib/ccache/bin/c++ -c main.cpp` makes colors.

### More context ###

On Arch linux, `/usr/bin/c++` seems to be hardlinked to `/usr/bin/g++`, so 4b0be71 does not work here I guess.

If I add a symlink `c++` to `/usr/bin/g++` to my path, colors do work.

Ccache could do more sophisticated checks for guessing the compiler, i.e. check if `<prefix>/c++` and `<prefix>/g++` are the same hardlink, or read `--version` output.

Related issue: #718

### Environment ###

ccache version 4.10.2

OS: Arch Linux

(I have `/usr/lib/ccache/bin/` in my path.)

`ls -i` shows `/usr/bin/c++` and `/usr/bin/g++` have the same inode. So they're hardlinks.

`readlink /usr/lib/ccache/bin/g++`: `/usr/bin/ccache`
`readlink /usr/lib/ccache/bin/c++`: `/usr/bin/ccache`

**Comment by jrosdahl** [comment]
This will be fixed by #958. But since that likely won't be implemented very soon, we could add a simple inode probe as suggested.

**Comment by jrosdahl** [comment]
Also related: #1116.

**Comment by Desour** [comment]
Thanks! :heart: 
(Just wanted to open a PR, but I guess I was too slow. :sweat_smile: https://github.com/ccache/ccache/commit/b0d957f14ad18996260b1a782b973bce6b2c9889 It has a unittest if you want that. :) )

**Comment by jrosdahl** [comment]
Oh, oops. :slightly_smiling_face: Would you like to prepare a PR with your unit test?

**Comment by Desour** [comment]
#1517 :slightly_smiling_face:
