### ISSUE TITLE
Joel Rosdahl's OpenPGP key is not accessible

### ISSUE THREAD

**Issue by malcp** [ccache/ccache#1519]
### How to reproduce ###

1. Go to https://ccache.dev/download.html and follow the instructions on how to verify the release archives.
2. Try to download [Joel Rosdahl's OpenPGP key](https://pgp.key-server.io/pks/lookup?search=0x5A939A71A46792CF57866A51996DDA075594ADB8&fingerprint=on&op=vindex)

### Actual behavior ###

Download of the key is not possible. key-server.io seems to not be hosting an OpenPGP key database anymore.

### Expected behavior ###

I'm able to download Joel Rosdahl's OpenPGP key.

### Environment ###

Not applicable.

**Comment by jrosdahl** [comment]
Replaced the link now. Thanks for the heads up.
