### ISSUE TITLE
ccache: FATAL: Failed to open temporary file

### ISSUE THREAD

**Issue by yogurfrul** [ccache/ccache#154]
I run compile job in different path at the same time ,and I set the same ccache dir for sharing ccahe to improve ccache hit rate.While a low probability error occurs as blow:

`ccache: FATAL: Failed to open /home/chuan/CC_TMP/tmp/tmp.cpp_stderr.031-u10-121-135-116.xxxx.53671: No such file or directory
`
I found this in ccache source code :

` 
hash_delimiter(hash, "cppstderr");  
 if (!hash_file(hash, path_stderr))  {
                fatal("Failed to open %s: %s", path_stderr, strerror(errno));
        }
`
so I think this error comes from the tmp file is deleted when one compile command hit,the problem is who delete the tmp file???the ccahce size is not full.then I found every time one compile command enter ccahe main would run this function ,did I catch the real reason ?How do I fix it?~

`clean_up_tmp_files()`

ps: ccache version 3.1.9
current cache size 69.5 Gbytes
max cache size 100.0 Gbytes
Any help would be appreciated~~~

**Comment by jrosdahl** [comment]
Which type of filesystem is /home/chuan on?

Please consider trying a newer ccache version as well.

**Comment by yogurfrul** [comment]
ext4
thx for your reply and suggestion~
do the problem is one command somehow  delete the tmp_files using by other command？
this problem is a bug of ccache3.1.9？newer ccache fix it？

**Comment by jrosdahl** [comment]
You forgot to answer my question.

> do the problem is one command somehow delete the tmp_files using by other command？

Don't know.

> this problem is a bug of ccache3.1.9？

Don't know.

> newer ccache fix it？

Don't know. :-) That's why it would be useful if you could try a newer version and see if it fixes the problem.

**Comment by yogurfrul** [comment]
:+1: 
haha , my filesystem is /dev/sda3 ,its type is ext4~
if you want to know my system,the answer is  Ubuntu 12.04.1 LTS (GNU/Linux 3.2.0-29-generic x86_64) :）
my job are running on many many machines , wo do not update version except we know newer version is useful.
thx all the same ~

**Comment by jrosdahl** [comment]
> wo do not update version except we know newer version is useful.

And I'm not interested in investing much time into fixing old legacy versions of ccache. Closing this issue now. Please reopen if you can reproduce it with a modern ccache!

**Comment by yogurfrul** [comment]
ok，I will try newer version in one machine ~
thx！

**Comment by silence48** [comment]
I replicated it today, updated to 3.6 and still happens... just letting you know

**Comment by jrosdahl** [comment]
> I replicated it today, updated to 3.6 and still happens... just letting you know

Thanks. You need to supply more information than that to give us any chance of fixing the problem, though.

**Comment by silence48** [comment]
Hey sorry about that. 
It is caused when you run ccache on sudo whether on your current project or not, then run it again without sudo.  if the tmp folders created are created as root, they are owned by root so then in the future if it wants to write a file into one of the root owned folders it can't.  I'm not sure its a ccache issue upon further inspection. I guess it could be fixed by deleting the tmp files after every use? I just added a script to take ownership of the .ccache folder before building.

**Comment by jrosdahl** [comment]
> It is caused when you run ccache on sudo whether on your current project or not, then run it again without sudo.

Right, if multiple users are using the cache you need to make sure that all those users can write to all ccache directories. One way of ensuring this is to set `umask` in the configuration (or the`CCACHE_UMASK` environmen variable) to e.g. `000`.

**Comment by jrosdahl** [comment]
On the other hand, if `$CCACHE_DIR/tmp` is unwritable by the current user, the error message looks similar to this:

`ccache: error: Failed to create temporary file for /home/joel/.ccache/tmp/hashutil.stdout: Permission denied`

I.e., not the same as the one in this bug report.

**Comment by silence48** [comment]
The path in my error was like this
/home/user/.ccache/5/j/63glfh4girken3.f8ej3.tmp
I can post the actual message when i get home.
