### ISSUE TITLE
Bug with cached empty *.o file

### ISSUE THREAD

**Issue by k06a** [ccache/ccache#161]
I don't know how it was happend. Maybe I had terminated compilation at the wrong moment, or Xcode was crashed. Empty `.o` file was cached by `ccache` and clang linker was outraged. I think we should check filesize before adding it to `ccache`'s cache.

**Comment by Bu11etmagnet** [comment]
Zero-sized file is just a special case of a corrupted .o file (albeit an easily detected case).

**Comment by k06a** [comment]
I was made to clean ccache with `ccache -C` to fix corrupted cache. I think it will be great to fix this issue to avoid full cache erasing.

**Comment by afbjorklund** [comment]
This case should have been caught, so it looks like your cache was corrupted somehow ?

``` C
        if (st.st_size == 0) {
                cc_log("Compiler produced an empty object file");
                stats_update(STATS_EMPTYOUTPUT);
                failed();
        }

```

**Comment by k06a** [comment]
@afbjorklund may this problem appeared after file was already cached because of hardlink usage?

**Comment by afbjorklund** [comment]
So, you are using hardlinks for ccache and think that your cache corruption was due to this ?

**Comment by k06a** [comment]
Maybe, really I'm not sure how this happened.

**Comment by afbjorklund** [comment]
But you *are* using CCACHE_HARDLINK ? And your disk didn't have "other problems"...

We've seen some people managed to strip debug objects from the cache, by not being careful.
But truncating the cache object is a new one, wonder how you manage to accomplish that.

It's not hard if you _try_ (e.g. `> test.o`), but how it happens almost by accident I mean ?

This is one of the "usability" issues that makes us really not recommend using hard links.
Having cache on a different disk or compressing the cache, would be some other reasons.

**Comment by k06a** [comment]
Yes, I am using `CCACHE_HARDLINK`. Just checked `Disk Utility` and it discovered some issues that can't be solved on running system. Also maybe Xcode compilation cancellation (Cmd+`.`) can achieve this?

**Comment by jrosdahl** [comment]
Sounds like we could close this issue? @k06a: Do you agree?

**Comment by k06a** [comment]
@jrosdahl yep!
