### ISSUE TITLE
Multiple -fdebug-prefix-map options are not considered correctly when deciding to hash the current directory

### ISSUE THREAD

**Issue by mikecrowe** [ccache/ccache#163]
The OpenEmbedded build system passes multiple -fdebug-prefix-map= options to the compiler in order to map the source directory and sysroots separately.

Unfortunately, ccache appears to only store the last of these arguments. The previous ones are overwritten (and the local copies leak):

```
		if (str_startswith(argv[i], "-fdebug-prefix-map=")) {
			debug_prefix_map = x_strdup(argv[i] + 19);
			args_add(stripped_args, argv[i]);
			continue;
		}
```
The arguments still make it through to the compiler, but only the last is considered when deciding which directory to put into the hash when conf->hash_dir is enabled. This means that the current directory always ends up in the hash even when it has no effect on the generated files.

**Comment by afbjorklund** [comment]
Yeah, this needs to be converted into an array of some-sorts.

**Comment by mikecrowe** [comment]
The fix seems to work for me. Changing my OpenEmbedded build directory no longer invalidates the cached files. (Unfortunately, changing the package version does still invalidate the cached files because the debug-prefix-map destination contains the version number. :( )

**Comment by afbjorklund** [comment]
But if you are interested in encoding the package version in your debuginfo like that, then I suppose that is a feature (or else you would change the remapping, I suppose ?)

**Comment by mikecrowe** [comment]
> But if you are interested in encoding the package version in your debuginfo like that, then I suppose that is a feature (or else you would change the remapping, I suppose ?)

Yes, but that's an upstream OpenEmbedded design decision (which appeared in ecb56a6ae0c870af680da03db9d39703b525fc98 for anyone following along.) I would need to override it locally or persuade them to change it.

**Comment by afbjorklund** [comment]
I suppose there is always `hash_dir = false` otherwise, if you don't care about the subdir.
