### ISSUE TITLE
Idea: Cleanups and statistics on second cache level instead of first

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#168]
As mentioned in #124, it would be interesting to investigate putting the stats files in the 256 second-level cache directories instead of in the 16 first-level cache directories. This would also imply doing cleanups per second-level directory. `cache_dir_levels` should no longer be allowed to be 1.

This will both reduce lock contention when updating stats files and reduce the risk of multiple ccache invocations wanting to clean up the same subdirectory at the same time.

**Comment by blong3748** [comment]
I played around with moving the stats files into the 2nd level cache to reduce lockfile contention back when I made comment on #124 . IIRC I then ran into doing a lot more cleanups than expected - the cleanup alg assumes uniform the directories will get roughly equal allocations of files/size, but md4 hashing did not distribute the files that uniformly - I think some directories were 10x over others.

**Comment by afbjorklund** [comment]
One could also consider doing 256 first-level dirs, like for instance git is doing ?
