### ISSUE TITLE
Windows: unittest hangs on Cygwin, test should support MSYS2

### ISSUE THREAD

**Issue by afbjorklund** [ccache/ccache#170]
Apparently the test suite hangs on Cygwin, due to missing symlink support.

Need to expand on the `_WIN32` used for some test cases.

We should also support "MSYS" as a synonym for Cygwin, in the `uname -s`

This is used by the MSYS2 project: http://www.msys2.org/

**Comment by afbjorklund** [comment]
Also, we probably need to create an "official" Windows test build (using [Appveyor](https://www.appveyor.com)).

As was suggested in:
- #69 
- #169 

Not possible to test all of these issues with Travis, also need to run them on Windows.

**Comment by afbjorklund** [comment]
Fixed on `3.4-maint` and `master` (7951573)

**Comment by afbjorklund** [comment]
I suppose this should be rebased, and then tried on a **real** Windows computer.

Using MSYS2: https://www.msys2.org/

Have access to Windows 7, but would be nice if it could be tested on Windows 10.

Run this: `./misc/build.sh unittest`

You might have to install the needed packages for the **mandatory** zstd support:

`pacman -Sy && pacman -S libzstd-devel`

**Comment by afbjorklund** [comment]
I removed the "windows" label, because this is not really `_WIN32` but POSIX.

**Comment by afbjorklund** [comment]
Tested again, on Windows 7 MSYS2. Still the same issues (unittest hangs), plus a new gperf problem...

It was **not** possible to build from git, since it complained about the `%%` construct for some reason ("junk")

``` Makefile
add_confitems_numbers = \
    perl -pae '$$$$s = 1 if /^%%/; s/ITEM/$$$$n++ . ", ITEM"/e if $$$$s == 1'

$(eval $(call generate_gperf_lookup,confitems,$(add_confitems_numbers)))
$(eval $(call generate_gperf_lookup,envtoconfitems,cat))

```
Building from ccache-3.7.2.tar.gz hangs forever, due to the assumption that symlinks work everywhere.

**Comment by afbjorklund** [comment]
Apparently there is a gperf fix in #443

**Comment by afbjorklund** [comment]
Checking for symlink support in configure would probably be better than using platform macros...

But the fixes in #246 should be able to make it run. Looks like the file-based locks are broken, though ?

Maybe there should be a special "symlink" define ?

Then we could verify the functionality, also on Linux

**Comment by peterbud** [comment]
> It was **not** possible to build from git, since it complained about the `%%` construct for some reason ("junk")

The reason is that the git by default will use CRLF instead of LF for all source files, and the MSYS2 version of gperf unfortunately is not handling inputs with CRLFs properly. Once you save the gperf files as *nix files (using simple LF and NOT CRLF, ie using `unix2dos` or similar) one can build `ccache`.

However the unitest indeed hangs - I have tried on WIn10 with latest MSYS2. I recall that earlier versions were nicely running all tests.

**Comment by afbjorklund** [comment]
Oh, that line ending thing can probably be done by the sed/perl post processing as well then.

**Comment by peterbud** [comment]
So this is the latest I have managed to run using MSYS2:
`PASSED: 3563 assertions, 112 tests, 12 suites
`

```
$ sh ../test/run
Compiler:         gcc (/usr/bin/gcc)
Compiler version: gcc (GCC) 9.1.0
CUDA compiler:    not available

Running test suite base................................................................
Running test suite nocpp2................................................................
Running test suite cpp1.
Skipped test suite multi_arch [multiple -arch options not supported on MSYS_NT-10.0-18362]
Skipped test suite serialize_diagnostics [--serialize-diagnostics not supported by compiler]
Skipped test suite sanitize_blacklist [-fsanitize-blacklist not supported by compiler]
Running test suite debug_prefix_map.
Running test suite split_dwarf....
Running test suite masquerading.
Running test suite hardlink....
Skipped test suite fileclone [file system doesn't support file cloning]
Running test suite direct..........................................
Running test suite direct_gcc.....
Running test suite depend......
Running test suite basedir.....
Running test suite no_compression...
Running test suite readonly...
Running test suite readonly_direct..
Running test suite cleanup..........
Running test suite pch.....................
Running test suite upgrade.
Running test suite input_charset.
Skipped test suite nvcc [nvcc is not available]
Skipped test suite nvcc_direct [nvcc is not available]
Skipped test suite nvcc_ldir [nvcc is not available]
Skipped test suite nvcc_nocpp2 [nvcc is not available]
PASSED

```

**Comment by afbjorklund** [comment]
Confirmed that the new `master` runs the tests OK, on Windows 7 MSYS2.

When building from git, the current workaround is doing:

`dos2unix src/*.gperf`

Can do a small PR, in order to remove any `'\r'` characters...

**Comment by Kreijstal** [comment]
this happened again on master branch
