### ISSUE TITLE
Find a confusing condition

### ISSUE THREAD

**Issue by Qchrlis** [ccache/ccache#171]
// Handle cuda "-optf" and "--options-file" argument.
		if (str_eq(argv[i], "-optf") || str_eq(argv[i], "--options-file")) {
			if (i > argc) {
				cc_log("Expected argument after -optf/--options-file");
				stats_update(STATS_ARGS);
				result = false;
				goto out;
			}
			++i;

where: $(src)/ccache.c.
Why use 'i > argc' ? I think this condition should never be true.

**Comment by White-Tiger** [comment]
why?
Isn't `i` an zero based index and `argc` the actual argument count meaning that argc might be 1 and thus the first argument is `argv[0]` ?
