### ISSUE TITLE
ccache-3.3 doesn't cache compiles when called inside Spack

### ISSUE THREAD

**Issue by junghans** [ccache/ccache#173]
This is LLNL/spack#3761 and was discovered by @healther.

To reproduce this:

1. Get spack with ccache patches:

```
$ cd ~
$ git clone https://github.com/llnl/spack.git
$ cd spack/bin
$ git fetch origin pull/3761/head && git checkout FETCH_HEAD
```
2. Build ccache inside spack:
```
$ ./spack install ccache
```
3. Now there should be a ccache-3.3 installed by Spack, add it to your `PATH`:
```
$ ls ~/spack/opt/spack/linux-*/gcc-*/ccache-3.3.4-*/bin/ccache
$ export PATH=$(echo ${HOME}/spack/opt/spack/linux-*/gcc-*/ccache-3.3.4-*/bin/):${PATH}
$ type -p ccache
```
4. Enable ccache usage inside spack:
```
$ cp ~/spack/etc/spack/defaults/config.yaml ~/.spack/
$ sed -i '/ccache:/s/false/true/' ~/.spack/config.yaml
```
5. Test caching (these should be misses)
```
$ ccache -z
$ ./spack install -v libelf
$ ccache -s
```
6. Rebuild the same package:
```
$ ./spack uninstall libelf
$ ./spack install -v libelf
$ ccache -s
```

With ccache-3.3 there are no hits, with ccache-3.2.9 and ccache-3.1.12 is works.

**Comment by afbjorklund** [comment]
I cannot reproduce this, I get some cache hits even with the spack version (3.3.4) of ccache...
There are some typos in the reproducer above, but those should be pretty obvious when run:

``` bash
export PATH=$(echo ${HOME}/spack/opt/spack/linux-*/gcc-*/ccache-3.3.4-*/bin/):${PATH}
cp ~/spack/etc/spack/defaults/config.yaml ~/.spack/
```
i.e. it was missing to expand the '*' in the path and there was a '/' missing in the copy command.
The cache misses seemed to be from the temp directory finding its way into the conftest.o etc ?

``` bash
$ type -p ccache
/home/anders/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/ccache-3.3.4-5rq2bdv7veycqg6emnbaljbfffoj4tas/bin/ccache
$ ccache --version
ccache version 3.3.4

```

----

first run: (cold cache)
```
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                           236
cache hit rate                      0.00 %
called for link                        2
called for preprocessing             156
compile failed                         4
autoconf compile/link                 42
cleanups performed                     0
files in cache                       478
cache size                           6.1 MB
max cache size                       5.0 GB
```

second run: (warm cache)
```
cache hit (direct)                   118
cache hit (preprocessed)               0
cache miss                           354
cache hit rate                     25.00 %
called for link                        4
called for preprocessing             312
compile failed                         8
autoconf compile/link                 84
cleanups performed                     0
files in cache                       717
cache size                           9.1 MB
max cache size                       5.0 GB

```

----

Anyway, if you want to know what is going on then you need to look at the log file.
And also base dir and debug prefix map, to try and improve the hit ratings later on ?

**Comment by junghans** [comment]
@afbjorklund : it seems not all system have that problem as spack build on top of your system compiler, but I was able to reproduce on Ubuntu using Docker:

```
$ ls docker/
Dockerfile
$ cat docker/Dockerfile
FROM ubuntu
RUN apt-get update
RUN apt-get install -y git gcc g++ curl gfortran python bzip2 make
RUN  git clone https://github.com/llnl/spack.git
WORKDIR spack/bin
RUN git fetch origin pull/3761/head && git checkout FETCH_HEAD
RUN ./spack install ccache
ENV PATH=/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/ccache-3.3.4-5rq2bdv7veycqg6emnbaljbfffoj4tas/bin:$PATH
RUN sed -i '/ccache:/s/false/true/' ../etc/spack/defaults/config.yaml
RUN ccache -z
RUN ./spack install libelf
RUN ccache -s
RUN ./spack uninstall -y libelf
RUN ./spack install libelf
RUN ccache -s
RUN ./spack uninstall -y libelf
RUN ./spack install libelf
RUN ccache -s
$ docker build docker/
```

Last output (after rebuild libelf 3 times) is:
```
 ---> Running in c7ee1f2f0240
cache directory                     /root/.ccache
primary config                      /root/.ccache/ccache.conf
secondary config      (readonly)    /spack/opt/spack/1-ubuntu16-x86_64/gcc-5.4.0/ccache-3.3.4-5rq2bdv7veycqg6emnbaljbfffoj4tas/etc/ccache.conf
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                           354
cache hit rate                      0.00 %
called for link                        3
called for preprocessing              54
compile failed                         6
autoconf compile/link                 57
cleanups performed                     0
files in cache                       667
cache size                           8.9 MB
max cache size                       5.0 GB
 ---> c1edba4e0503
Removing intermediate container c7ee1f2f0240
Successfully built c1edba4e0503
```
which is the original issue.

**Comment by afbjorklund** [comment]
@junghans : Never mind, found out that spack had cached `/usr/lib/ccache/gcc-5` as the compiler to use. So basically I would get 118 misses, and then fall back to the system ccache (that I thought I wasn't using)

**Comment by afbjorklund** [comment]
Reproduces also with master branch (sorry), there are no hits where there should be plenty (118, I think). 

```
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                           118
cache hit rate                      0.00 %
called for link                        1
called for preprocessing              18
compile failed                         2
autoconf compile/link                 21
```

Fails to find anything even after cpp, so probably something with the compiler or other hash header ?

**Comment by afbjorklund** [comment]
@junghans : Your problem is related to the new setting for `hash_dir`, and that you generate debuginfo for a temporary directory into your binaries. The short term workaround is `$CCACHE_NOHASHDIR`...

https://ccache.samba.org/releasenotes.html#_ccache_3_3

i.e. if I look at my `ccache` program created by spack, it has directories like `/tmp/anders/spack-stage/spack-stage-JtmncL/ccache-3.3.4` in it. Previous versions of ccache didn't care about that.

A long time fix would be to remap your debug prefix perhaps ?

**Comment by afbjorklund** [comment]
@jrosdahl: Maybe we should write an explicit log line, when hashing the cwd ?

``` C
		if (cwd) {
			hash_delimiter(hash, "cwd");
			hash_string(hash, cwd);
			free(cwd);
		}
```

We do write `Working directory: `, but not that it is being hashed with debuginfo.

``` C
	// Possibly hash the current working directory.
	if (generating_debuginfo && conf->hash_dir) {
```

Then again, we might also want to suggest to users to _enable_ logging in the first place...
We do say so in the MANUAL* (who reads those anyway, right), but not in the README ?

* https://ccache.samba.org/manual.html#_troubleshooting

**Comment by junghans** [comment]
Fixed in Spack by added `export CCACHE_NOHASHDIR=yes` to `lib/spack/env/cc`
