### ISSUE TITLE
Unsupported compiler option `--coverage`

### ISSUE THREAD

**Issue by masaeedu** [ccache/ccache#192]
Using `ccache` 3.3.4 on CentOS 6.6:

```
# ccache --version
ccache version 3.3.4

Copyright (C) 2002-2007 Andrew Tridgell
Copyright (C) 2009-2017 Joel Rosdahl
...
```

I am seeing several files incrementing the "unsupported compiler options" counter. This has started happening since we enabled `--coverage` compiler and linker flags. Looking at the debug log I see things like this:

```
[2017-08-23T21:07:34.974749 5558 ] Working directory: /var/jenkins_home/workspace/foo/agent/main-Release/agent-soap
[2017-08-23T21:07:34.974760 5558 ] Base directory: /var/jenkins_home/workspace/foo
[2017-08-23T21:07:34.974806 5558 ] Compiler option --coverage is unsupported
[2017-08-23T21:07:34.974825 5558 ] Failed; falling back to running the real compiler
```

From my understanding of [this thread](https://lists.samba.org/archive/ccache/2015q1/001273.html), @afbjorklund implemented support for the `--coverage` option, which was merged in 3.2. Is this assumption flawed?

I am using `--coverage` for `LDFLAGS`, `CXXFLAGS` and `CFLAGS`.

**Comment by masaeedu** [comment]
Durrrr, please ignore this idiot. I was running ccache from a centos 6.6 container with ccache 3.1.6 and tailing the log from a centos 7 container with ccache 3.3.4.

**Comment by afbjorklund** [comment]
You can work around this issue by using the "real" compiler/linker flags instead of `--coverage`. Or upgrade/change ccache, not EPEL.

**Comment by masaeedu** [comment]
@afbjorklund I just built it from source into the container image. The version I had before doesn't support `fprofile-arcs` either, so I was basically SOL. Thanks.

**Comment by Bu11etmagnet** [comment]
Just to show how nice the ccache developers are: #123
