### ISSUE TITLE
Windows binaries

### ISSUE THREAD

**Issue by xoviat** [ccache/ccache#195]
Windows binaries should be compiled on Appveyor using the builtin MSYS2 and uploaded to the web site as a zipfile. Once set-up, there would be minimal maintenance involved.

**Comment by afbjorklund** [comment]
There's a lot of other issues regarding Windows, for instance #122 (et al). I don't think it is lack of binaries that is the biggest problem ? And if you are using MSYS2, wouldn't you just want to use `pacman` then ?

https://github.com/Alexpux/MSYS2-packages/tree/master/ccache

**Comment by xoviat** [comment]
I would not recommend using mingw at all. Mingw w64 should work.

**Comment by afbjorklund** [comment]
The standard Travis environment (12.04 VZ) only had MinGW32, but going to the new Travis environment (14.04 VM) allows us to build with MinGW w64. Twice as slow, but anyway. See #119 for the details.

Still, I didn't see how building/uploading binaries would help ? It would be useful to set up an Appveyor project to actually _run_ the tests (not only compile), but we don't build any Linux or Mac binaries either. But all this was already discussed in #69, and wasn't deemed to be such a high priority for the project then. I'm all for getting the test builds working with MinGW again, but personally not so keen on supporting binaries ?

**Comment by xoviat** [comment]
The difference between Windows and other operating systems is that other operating systems like Linux and Mac have ccache in a package manager. Windows is a bit odd in that respect, but the location where it would be is chocolatey, but it isn't there. The reason it isn't there is that a chocolatey package basically downloads the binary posted on the website. Since there isn't a binary posted on the website no one has made a package.

Now I know your time is valuable. I know you guys don't want to waste it on maintaining Windows binaries. But if I'm right, all this would require is a few hours of configuration on appveyor and uploading the artifacts to the artifacts tab, and then you won't have to touch it again.

**Comment by xoviat** [comment]
Closing as I don't see appveyor being added anytime soon.
