### ISSUE TITLE
ccache randomly fails

### ISSUE THREAD

**Issue by yurivict** [ccache/ccache#200]
Observed on the qTox project, while building the FreeBSD port. See the error message here: https://github.com/qTox/qTox/issues/4753

**Comment by afbjorklund** [comment]
Normally ccache will *not* delete the ccache.conf in the $CCACHE_DIR (only create it, if it is missing)...

Also the error message is weird, normally missing conf would be a warning and not an error (`fatal()`)

Any chance of seeing a $CCACHE_LOGFILE ?

**Comment by yurivict** [comment]
I will try to reproduce it and will post a log.

**Comment by jrosdahl** [comment]
@yurivict: Any progress in reproducing the problem?

**Comment by yurivict** [comment]
No, I didn't come across anything that's failing.
