### ISSUE TITLE
Positive compopt_affects_cpp result treated as option argument presence indicator

### ISSUE THREAD

**Issue by mikedld** [ccache/ccache#203]
Excerpt from `calculate_object_hash` (ccache.c):

```c
                if (!direct_mode && !output_is_precompiled_header
                    && !using_precompiled_header) {
                        if (compopt_affects_cpp(args->argv[i])) {
                                i++;
                                continue;
                        }
                        // ...
                }
```

The inner condition doesn't seem to be always correct in incrementing `i`, neither was it always correct before 2c2b582266fc08f6a18fdba7576b21d7a310e289. Some options (`-nostdinc`, `-nostdinc++`, etc. marked with `AFFECTS_CPP` in compopt.c) don't accept an argument, thus incrementing `i` will lead to next option being wrongfully skipped.

Not sure if this is the only issue of this sort.

**Comment by afbjorklund** [comment]
Some test cases would be nice
