### ISSUE TITLE
EDG based compilers (GHS) invoked with -MT end up invoking linker

### ISSUE THREAD

**Issue by kamathba** [ccache/ccache#209]
Using ccache with a GHS compiler (compatible with other EDG based compilers like older versions of the ARM Compiler, I think v5 or less), we get the following error:

cxarm: Warning: Unknown option "-MQ" passed to linker

EDG front-end based tools us -MD and -MF to specify dependency files (-MF=<filename>). Since ccache doesn't find -MT or -MQ, it adds the -MQ flag, which is not a real option (and apparently the linker gets invoked)

Relevant snippets from ccache.c
```
		if (str_startswith(argv[i], "-MQ") || str_startswith(argv[i], "-MT")) {
			dependency_target_specified = true;

...

		if (!dependency_target_specified) {
			args_add(dep_args, "-MQ");
			args_add(dep_args, output_obj);
		}
```

**Comment by afbjorklund** [comment]
How do you recognize a GHS compiler ? Currently we only "support" GCC, and to some extent Clang.

**Comment by kamathba** [comment]
Ah, got it. Wasn't aware of that. A bunch of different third-party toolchain/tooling vendors license their compiler front-ends from EDG (https://www.edg.com/customers). They tend to have very similar but not identical command line options.

**Comment by afbjorklund** [comment]
As a workaround, you can do a shell wrapper to make it more "gcc-compatible" (drop `-MQ`) perhaps ?

**Comment by jrosdahl** [comment]
I think that passing `-MQ` to the preprocessor actually no longer is necessary after 18a645451194becb832bd1ff4fee1c1e9f3d0dc5. I'll run some tests to confirm this.

**Comment by jrosdahl** [comment]
My bad, it's still needed. The reason for passing `-MQ` to the preprocessor is that the dependency file content will be erroneous without explicit `-MQ` if the object file has a non-standard extension (typically != `.o`).

Here's an idea: Only add `-MQ` if the object file has a non-standard extension. @afbjorklund: Do you see any danger with that?

**Comment by jrosdahl** [comment]
> Here's an idea: Only add -MQ if the object file has a non-standard extension.

Let's try it out.
