### ISSUE TITLE
BASH is an implicit dependency

### ISSUE THREAD

**Issue by jcea** [ccache/ccache#215]
After solving issue #214 , a `make check` fails with 

```
./test.sh[143]: local: not found [No such file or directory]
Running test suite ./test.sh[164]: SUITE_: not found [No such file or directory]
```

This worked after I changed shebang in `test.sh` from `#!/bin/sh` to `#!/bin/bash`.

**Comment by afbjorklund** [comment]
The workaround probably doesn't work for `/usr/local/bin/bash` though...

It seems like dash _does_ implement it, so `checkbashisms` doesn't complain:

```
possible bashism in test.sh line 151 (type):
    if type SUITE_${suite_name}_PROBE >/dev/null 2>&1; then
possible bashism in test.sh line 208 (type):
    if type SUITE_${suite_name}_SETUP >/dev/null 2>&1; then
```

Quickest fix is probably: `#!/usr/bin/env bash`

Or look for bash with autoconf perhaps (Makefile.in).

**Comment by afbjorklund** [comment]
@jcea : maybe this could work for all parties: 	fee885a5ed483252c87c8c0a8b9592880cbe548d

**Comment by jrosdahl** [comment]
> BASH is an implicit dependency

No it isn't. The test suite works on all POSIX shells that also support the `local` and `type` keywords, which in practice means all GNU and BSD /bin/sh shells in use. I normally refuse to support systems with sillly non-POSIX `/bin/sh`s, but maybe I should give in on this one... :neutral_face:

**Comment by jrosdahl** [comment]
I've now slept on this. I'll give in and make test.sh a bash script. :slightly_smiling_face:

**Comment by jrosdahl** [comment]
> @jcea : maybe this could work for all parties: fee885a

Applied, thanks!

@jcea: Please try and see if latest master works well for you.
