### ISSUE TITLE
Keep use relative path to obj dir for gcda to increase hit when changing build path

### ISSUE THREAD

**Issue by tof1a** [ccache/ccache#219]
https://github.com/ccache/ccache/blob/2b045cbccd40b78c8a7db0be05e21f4db77cebe6/ccache.c#L1576-L1579

When using coverage, a hash is done on the coverage path of the gcda file.
Today if no profile_dir is provided, the object dir is used, but ccahe covert is path in a real (absolute) path which do not allow to have a hit when we change build path (different user or server for instance).

SO, if we remove the else and the code inside which convert dir from obj dir when no profile_dir is provided, in order the relative path for obj dir is kept, then we will have a direct hit when we change the path where obj are generated.

**Comment by jrosdahl** [comment]
The logic was introduced in 02d3f078bd2495b8db2264ae0b2c692b4c5ba1bd, seemingly on purpose. @afbjorklund: Do you remember details about this?

**Comment by tof1a** [comment]
Indeed I see in the comment: "_Make sure to hash this path to avoid cache hits with another absolute path._", but what is the pb here ?

**Comment by tof1a** [comment]
pullrequest #220 opened

**Comment by afbjorklund** [comment]
@jrosdahl: Yeah sure.

When I first did the coverage support, I noticed the `.gcno` was using a relative path and thought I was OK. But later on, it was discovered that the `.gcda` was always using an absolute path in the `.o` file.
And this is why we are caching the path to the gcda ("data") - but notice this is **not** the gcno ("notes"). Anyway, the object file contains a hardcoded reference to where the output is created - at runtime.

So if I have two directories, each with their own identical source code, I will get _different_ results:

/tmp/foo/
test.c
test.gcno: test.c
test.o: /tmp/foo/test.gcda

/tmp/bar/
test.c
test.gcno: test.c
test.o: /tmp/bar/test.gcda

This means that if they were to share cache (same hash), they would write the wrong output file...

**Comment by tof1a** [comment]
I have done more investigation based on your suggestions and here my outcomes:
ccache will reuse compiled object that should be identical. In case you are using gcov, object are compiled to generate coverage information at compilation time. In order to be portable, the path where those coverage information should be written is define with an absolute path for a generated object.
This native mechanism makes incompatible, the generated objects with ccache as the an object generated by a user in a specific path will not be reusable by an other user !
The idea then to solve the pb and make ccache working properly is to say to the compiler to not use an absolute path for all generated coverage object but to use a relative path (that was the goal of this change).
It will be important that this relative path is relative from a "central" path for the project for all generated object and we will see after why.
Then generated coverage objects will be compatible with ccache as this relative path with be identical wherever the user is compiling.
The following pb is then when the user will run test to generate coverage information, the path from where the test are run is not at all the same than the one defined at the time of compilation (tha is the reason why ccache use realpath, but it makes ccache almost useless as there is almost no change to have direct hits).
So we need at execution time of the test which generate coverage information to convert this relative path to absolute path, and hopefully gcov allow us that (https://gcc.gnu.org/onlinedocs/gcc/Cross-profiling.html#Cross-profiling)
That is why it is very important to have the relative path for all objects relative to a common absolute path when generating coverage objects.
So based on those founding I guess it is impossible to have ccache to use properly and "transparently" when gcov is used. Nevertheless with some understanding and tuning we can make it work properly with current implementation.
The idea is to use the existing --fprofile-dir= of gcov to specify a relative path from a common folder for all generated object wherever they are.
On my side I add the following CPP flag:
--fprofile-dir=$(subst ${CCACHE_BASEDIR},.,$(CURDIR))
Then all generated coverage object will be generated with relative path to ${CCACHE_BASEDIR}, and at execution time I will convert this relative path to th absolute path using following environment variables:
export GCOV_PREFIX_STRIP=1
export GCOV_PREFIX=${CCACHE_BASEDIR}
Thanks to that we will be able to reuse coverage object from ccache from other users who have build in different path due to the fact that the object in ccache where stored with relative path only.
This is possible because in case of --fprofile-dir option is defined, ccache with not call the realpath function. Not sure that was done on purpose but hopefully as it allow us to make it work.
My advice is then to not change ccache (I will reject my pool request), as it cannot be transparent due to the fact that we must specify some variables at execution time.
So either people will continue to use ccache as of today and they will have cache miss as it is the safer, but they can use this setting with cautious and make it work.
Hope it will help other that want to have ccache working with gcov.
