### ISSUE TITLE
Improve debuggability of cache misses

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#226]
### Background

Sometimes it's hard to understand why you don't get cache hits when you think you should. The only documented way to debug is to set `log_file` and inspect the log. However, the log file doesn't really tell much about why a cache miss occurred since that depends on what has been hashed. A related minor nuisance is that logs from parallel ccache invocations will be intermingled in the log.

There is an undocumented way of debugging what has been hashed: build ccache with `-DCCACHE_DEBUG_HASH` set and set `CCACHE_DEBUG_HASH` at runtime. All data that is hashed will then be appended to a file called `ccache-debug-hash.bin` in the current working directory. It works to inspect that file if you execute a single compilation with ccache, move the file away, execute a compilation once more and compare the resulting file with the moved file. But for a real scenario, when you build a full source tree, that method is not practical.

### What to do

Here is an idea on how to make it easier to debug cache misses and also ccache in general: **Store logs and hashed data next to the output object file.** This will make it easy to compare two different builds: just compare two logs and/or hashed data files for the same object file in the two different build trees.

Perhaps something like this:

1. Add a suitable configuration option, maybe just a boolean named `debug` (`CCACHE_DEBUG`).
2. If set, save all logs (from `cc_log`) in a buffer until `cc_process_args` (which sets  `output_obj`) has returned.
3. Write all buffered logs to `output_obj.ccache-log` or similar and keep appending new logs to that file.
4. Write all hashed data to `output_obj.ccache-input` or similar.
5. To make it easier to interpret the `.ccache-input` file, consider adding some headings that delimit data hashed by `calculate_common_hash`, `calculate_object_hash` in preprocessor and direct mode and `hash_source_code_file` (called from `manifest_get`), and maybe more.
6. Remove the `CCACHE_DEBUG_HASH` stuff from `mdfour.c`.
7. Make sure to document the new feature properly.

**Comment by tdihp** [comment]
I'm wondering whether saving each state of the hash update instead of the entire hashed data, along with why it's changed (CWD, compiler binary, extra file, etc), would be a cheaper solution while able to identify the first difference of a cache miss.

**Comment by jrosdahl** [comment]
> I'm wondering whether saving each state of the hash update instead of the entire hashed data, along with why it's changed (CWD, compiler binary, extra file, etc), would be a cheaper solution while able to identify the first difference of a cache miss.

Should be possible, but I don't see that it would gain much with something that is slightly cheaper. I'm thinking that if you want to debug cache miss behavior, you want as much information as possible. If you see that the hashes start to differ at some point, but you don't see exactly why, won't you just think "but why?"? :slightly_smiling_face:

**Comment by afbjorklund** [comment]
I did both: added the original binary input but also a new readable text version of the same information.

**Comment by jrosdahl** [comment]
Implemented by @afbjorklund in #279.

**Comment by afbjorklund** [comment]
Would be nice to get some comments on whether this is helpful, so if you have any - please share.
Either post a short link to this issue, or use the mailing list. We do need some help with documentation.
