### ISSUE TITLE
Unexpected cache misses: wrong interplay between hash_dir and base_dir?

### ISSUE THREAD

**Issue by egawrilow** [ccache/ccache#228]
Hello,

ccache systematically produces cache misses and consequently triggers recompilation where it should not do so.  The ccache version is 3.2.4, it comes from Ubuntu-16.04 package. The setup is as follows (unnecessary details omitted):

```
cwd=TopDir1/build/Release
export CCACHE_BASEDIR=TopDir1
command=ccache g++ -o TopDir1/build/Release/Component/Module.o -MMD \
  -MT TopDir1/build/Release/Component/Module.o \
  -MF TopDir1/build/Release/Component/Module.o.d \
  -I TopDir1/Component/include \
  TopDir1/Component/src/Module.cc
```

and the same in another directory TopDir2.  All relevant paths in compiler commands are absolute.
Both directories contain identical source code and compiler options.

The configuration of ccache:
```
hash_dir=true
sloppiness=file_macro, include_file_mtime, include_file_ctime
```
The cache size is sufficiently large to encompass the entire project.
Nevertheless, when compiling the second project after the first one, there is not a single cache hit, everything is compiled from scratch.

In the logfile I see completely different hash codes produced for the same files from both projects, both in direct mode and for preprocessed files.  But the produced preprocessed files are identical, I verified that by manually running the g++ -E commands from the logfile.  All absolute paths in the commands are correctly substituted by relative ones so that there is really no difference between the sources in both projects.

My only suspicion now is that ccache takes the cwd as a whole without chopping off the base_dir prefix when it computes the hash code.  This would be disastrous because I can't set hash_dir=false, there are other build subtrees (e.g. build/Debug) that should be cached without interference. Is it a known issue or limitation by design? Should I create different cashes as a workaround?

Thanks in advance for any help!

**Comment by egawrilow** [comment]
Now I've looked into the implementation and realized that the combination of base_dir with hash_dir=true is simply pointless.  Reset hash_dir to false and everything works fine.  Would be nice to place such a warning somewhere in the docs.  Sorry for noise!

**Comment by jrosdahl** [comment]
As you already found out, this is by design (and I wouldn't call it a limitation).

Documentation has improved in later ccache versions, see e.g. hash_dir in _[Configuation settings](https://ccache.samba.org/manual/3.4.1.html#_configuration_settings)_ and _[Compiling in different directories](https://ccache.samba.org/manual/3.4.1.html#_compiling_in_different_directories)_ in the manual. I can't improve the manual for ccache 3.2.4 in Ubuntu 16.04, though...

> This would be disastrous because I can't set hash_dir=false, there are other build subtrees (e.g. build/Debug) that should be cached without interference. 

I'm curious to know why you (thought you) had to set `hash_dir = false`. What behavior did you want to avoid? Could the documentation be clearer in some way?

**Comment by egawrilow** [comment]
> why you (thought you) had to set hash_dir = false

I thought I had to set hash_dir=true, and this was a bad idea.  I've been wrongly assuming that the source file path plays a predominant role in the decision what to cache and what to evict from the cache, therefore I thought that I have to disambiguate the object files produced from the same source with different compiler flags.  But in fact ccache works completely content-based, like git or docker.  Theoretically it's even possible to populate the entire cache with innumerate versions of the same object file.  It was this late "insight" that I haven't acquired from the docs but only by watching the logfiles and finally reading the source code (fortunately, it's small enough to get a rough picture within one day).

Anyway, thanks for kind response!
