### ISSUE TITLE
Bundled zlib fails to build

### ISSUE THREAD

**Issue by achow101** [ccache/ccache#229]
Building ccache 3.4.1 on Ubuntu without the `zlib1g-dev` package installed or configuring with `--with-bundled-zlib` results in a failed build.

Output of make:
````
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/main.o src/main.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/args.o src/args.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/ccache.o src/ccache.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/cleanup.o src/cleanup.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/compopt.o src/compopt.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/conf.o src/conf.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/counters.o src/counters.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/execute.o src/execute.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/exitfn.o src/exitfn.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/hash.o src/hash.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/hashutil.o src/hashutil.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/language.o src/language.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/lockfile.o src/lockfile.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/manifest.o src/manifest.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/mdfour.o src/mdfour.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/stats.o src/stats.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/unify.o src/unify.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/util.o src/util.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/version.o src/version.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/getopt_long.o src/getopt_long.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/hashtable.o src/hashtable.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/hashtable_itr.o src/hashtable_itr.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/murmurhashneutral2.o src/murmurhashneutral2.c
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./src/zlib -g -O2 -Wall -W -c -o src/snprintf.o src/snprintf.c
make: *** No rule to make target 'zlib/adler32.o', needed by 'zlib/libz.a'.  Stop.
````

**Comment by afbjorklund** [comment]
Probably need a Travis test for this configuration ?

**Comment by StarNeit** [comment]
Hello.

I have got same error now.

`checking for zlib >= 1.2.3... no
checking for gzdopen in -lz... no
configure: WARNING: using bundled zlib
checking whether byte ordering is bigendian... no
checking for inline... inline
checking for extern inline... no
configure: Developer mode disabled
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
configure: WARNING: unrecognized options: --disable-dependency-tracking
configure: now build ccache by running make
Building native_ccache...
make[1]: Entering directory `/home/ubuntu/build/lux/depends/work/build/x86_64-w64-mingw32/native_ccache/3.4.1-e615dd67a3d'
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/main.o sr$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/args.o sr$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/ccache.o $
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/cleanup.o$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/compopt.o$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/conf.o sr$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/counters.$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/execute.o$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/exitfn.o $
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/hash.o sr$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/hashutil.$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/language.$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/lockfile.$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/manifest.$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/mdfour.o $
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/stats.o s$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/unify.o s$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/util.o sr$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/version.o$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/getopt_lo$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/hashtable$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/hashtable$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/murmurhas$
gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSCONFDIR=/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/etc -I. -I./src -I/home/ubuntu/build/lux/depends/x86_64-w64-mingw32/native/include     -I./src/zlib -g -O2 -Wall -W -c -o src/snprintf.$
make[1]: *** No rule to make target `zlib/adler32.o', needed by `zlib/libz.a'.  Stop.`



Could you please let me know how can I fix this error?

**Comment by afbjorklund** [comment]
Please update to 3.4.2, and open a new ticket if that doesn't solve the problem...

**Comment by StarNeit** [comment]
Ok, I've identified the issue. It is because one of the dependencies recently had a version bump which now appears to be a problem.

`sudo apt install zlib1g-dev`

thank you.
