### ISSUE TITLE
Show date last usage/hit times in stats

### ISSUE THREAD

**Issue by rwst** [ccache/ccache#249]
I just had the situation that I could not tell if ccache was used at all. A simple useful information would have helped: the date the last usage/hit was made, which could be printed by `ccache -s`.

**Comment by afbjorklund** [comment]
Last access time is easy (basically it's the mtime of the most recently updated `stats`file), but time-of-last-hit would probably require adding another field to the structure... But you could of course just enable the log ?

**Comment by afbjorklund** [comment]
Something like this, perhaps:
```
stats zero time                     Mon Apr  9 20:29:13 2018
stats updated                       Mon Apr  9 20:33:26 2018
cache hit (direct)                     1
cache hit (preprocessed)               0
cache miss                             0
cache hit rate                    100.00 %
```
https://github.com/ccache/ccache/compare/master...afbjorklund:updated

**Comment by jrosdahl** [comment]
Applied 2ecc71590cc9a32c041335dac6918bfe1bb656bb to master, thanks!
