### ISSUE TITLE
Setting CCACHE_COMPRESS env variable results in a failure on ccache execution

### ISSUE THREAD

**Issue by tanty** [ccache/ccache#251]
Recently upgrade in Debian Testing to ccache 3.4.2-1

Check this command line:
`$ CCACHE_COMPRESS=0 ccache -s`
`ccache: error: invalid boolean environment variable value "0"`

According to the included man page:

> Boolean values
>       Some settings are boolean values (i.e. truth values). In a configuration file, such values must be set to the string true or false. For the corresponding environment variables, the semantics are a bit different: a set environment variable means “true” (even if set to the empty string), the following case-insensitive negative values are considered an error (rather than surprising the user): 0, false, disable and no, and an unset environment variable means “false”. Each boolean environment variable also has a negated form starting with CCACHE_NO. For example, CCACHE_COMPRESS can be set to force compression and CCACHE_NOCOMPRESS can be set to force no compression.

**Comment by tanty** [comment]
FTR, this works OK:
`$ CCACHE_NOCOMPRESS=1 ccache -s`

**Comment by afbjorklund** [comment]
This sentence:
> the following case-insensitive negative values are considered an error (rather than surprising the user): 0

is supposed to read:
_"don't do that"_

Some users were expecting `CCACHE_COMPRESS=0` to be the same as `CCACHE_NOCOMPRESS=1`. So an explicit warning was added, to warn them that it is not the case. Currently compression is not on by default.

See #182

**Comment by tanty** [comment]
Mmm ... confusing indeed. I read it and didn't catch the true meaning of that sentence. I'd suggest to improve the man page but, clearly, this report is invalid.

**Comment by jrosdahl** [comment]
> Mmm ... confusing indeed. I read it and didn't catch the true meaning of that sentence. I'd suggest to improve the man page but, clearly, this report is invalid.

That's funny, I think it's crystal clear, but then again I'm the one who wrote it...

@tanty: Do you have a suggestion on a formulation that you would have grasped right away?
