### ISSUE TITLE
Test suite fails on windows

### ISSUE THREAD

**Issue by lighta** [ccache/ccache#252]
Running the test suite fail at one point.
Test suite:     debug_prefix_map
Test case:      Multiple -fdebug-prefix-map
Failure reason: Relocation (name) not found in test.o

See https://gist.github.com/lighta/6d2b1bfb1bdd6289640999d6416ef53d for more data.

**Comment by peterbud** [comment]
There is a work underway to make all test suites work on MSYS2 and Cygwin: #246

**Comment by afbjorklund** [comment]
Basically it has been this way for a while (#170). The particular failure is because `objdump -g` doesn't produce the expected output on all platforms, especially those not using the ELF executable format...

**Comment by jrosdahl** [comment]
Closing as a duplicate; see above.
