### ISSUE TITLE
Create symlinks instead of copy obj files to speed up

### ISSUE THREAD

**Issue by skryv-softserveinc** [ccache/ccache#254]
COW FS's may use `cp --reflink` alternatively

**Comment by afbjorklund** [comment]
Maybe related to #213 (it talks about btrfs) ? Note that ccache has support for hardlinks already...

If you would create symlinks to the cache and the cache is cleaned, the symlink would be dangling.

**Comment by jrosdahl** [comment]
As explained by @afbjorklund, creating symlinks isn't a good idea. Closing as a duplicate of #213.
