### ISSUE TITLE
Environment variable or configuration option to store statistics in a different location

### ISSUE THREAD

**Issue by BenLubar** [ccache/ccache#262]
Example use case: I have a build server that might be building multiple versions of a program simultaneously, or building a pull request in a sandbox with read-only access to ccache. It would be nice to be able to display statistics about cache hits and misses for each individual build.

**Comment by afbjorklund** [comment]
I think this would be a very good feature, currently the log is the only way to get per-build information.
But the default log is way too verbose (more of a debugging feature), I even started on a "stats log"*...

* one that would _only_ output the "Result:".

**Comment by afbjorklund** [comment]
Current workaround:
``` console
$ export CCACHE_LOGFILE=$PWD/.ccache.log
```

Display results:
``` console
$ egrep -o "Result: .*" .ccache.log  | sort | uniq -c
```

As mentioned the downside is that it generates a lot of output, which slows the build and fills the disk...
But at least you would be able to show statistics for each individual build, even accumulated if wanted.

**Comment by afbjorklund** [comment]
One idea that I had previously, was to add a "stats-only" log file. This way it would not be as bloated as the verbose log, but not have the locking issues of the stats. Think I even had some old code doing this...

**Comment by afbjorklund** [comment]
Here it was: https://github.com/ccache/ccache/compare/master...afbjorklund:statslog-3.1

**Comment by afbjorklund** [comment]
`export CCACHE_STATSLOG=$PWD/.stats.log`

`ccache --log-stats`
