### ISSUE TITLE
Reduce deps for memcached

### ISSUE THREAD

**Issue by ahoarau** [ccache/ccache#264]
To `make install` the `memcached` branch it seems that you need to install 
```
apt-get install --no-install-recommends asciidoc xsltproc docbook-xml docbook-xsl
```
Is there any way to remove those deps with a configuration option (something like --no-docs ) ?

**Comment by afbjorklund** [comment]
I don't think you _need_ those packages, and if so they are required by the man pages - not memcached.
Just put those packages there for completeness, you can avoid the need by using just `make test`* ?
I suppose another way to avoid it would be to actually make a release (dist tarball), with the doc files...

* and then copy the `ccache` binary yourself, to /usr/local/bin/ccache

But anyway, to build the `dev/memcached` branch (`--enable-memcached`) you only need memcached:
`sudo apt install libmemcached-dev libmemcached-tools memcached`
You only need the tools and server if you plan to run the ccache tests, not on the actual ccache clients...

Remember to run `./configure --enable-memcached` to enable the feature

----
Should probably add some more details, on how to set up memcached/moxi and memcachedb/couchbase ?

https://developer.couchbase.com/documentation/server/5.0/install/install-intro.html

In order to use couchbase, one has to set the username/password for the "bucket" (since it _requires_ SASL).

https://blog.couchbase.com/sasl-memcached-now-available/

**Comment by afbjorklund** [comment]
Hmm, apparently I forgot to cherry-pick the sasl support to `dev/memcached`: e049385eff9d62b51a4d861d09a52067dda74985

Anyway, it is not required either by the regular memcached - but only by couchbase...

`CCACHE_MEMCACHED_USERNAME`

`CCACHE_MEMCACHED_PASSWORD`

**Comment by ahoarau** [comment]
> But since it doesn't fail the install anyway, I'm not sure that it is needed ?

Actually the install does fail if we dont have asciidoc installed on the system. Consider this minimal dockerfile : 

```dockerfile
FROM alpine
RUN apk add --no-cache autoconf git g++ libmemcached-dev make
RUN git clone https://github.com/ccache/ccache.git -b dev/memcached --depth=1
WORKDIR ccache
RUN ./autogen.sh
RUN ./configure --enable-memcached --prefix=/usr
RUN make -j$(nproc)
RUN make install
```

This returns at the end : 

```bash
 ---> c59d048c7aef
Step 8/8 : RUN make install
 ---> Running in 5433304def45
asciidoc -a revnumber=unknown -d manpage -b docbook -o - doc/MANUAL.adoc | \
  perl -pe 's!<literal>(.*?)</literal>!<emphasis role="strong">\1</emphasis>!g' >doc/MANUAL.xml
/bin/sh: asciidoc: not found
a2x --doctype manpage --format manpage doc/MANUAL.xml
make: a2x: Command not found
make: *** [dev.mk:175: doc/ccache.1] Error 127
The command '/bin/sh -c make install' returned a non-zero code: 2

```

**Comment by afbjorklund** [comment]
My bad, it was only the install that was ignored (`-` in make) - not the actual creation of doc/ccache.1

**Comment by afbjorklund** [comment]
Also note:
If you make a _real_ Alpine package (apk), then those would only be in "makedepends" and not "depends"
https://git.alpinelinux.org/cgit/aports/tree/main/ccache/APKBUILD
Once a release (dist) has been made, the rendered manual pages will be available in the source tarball...
https://www.samba.org/ftp/ccache/ccache-3.4.2.tar.xz

But the easiest workaround is probably to split the "install" target up into several subtargets ?

**Comment by ahoarau** [comment]
I only used alpine because its the smallest docker image that's it, I honestly know nothing about alpine :)
```dockerfile
FROM ubuntu
RUN apt-get update
RUN apt-get install -y -qq autoconf git g++ libmemcached-dev make
RUN git clone https://github.com/ccache/ccache.git -b dev/memcached --depth=1
WORKDIR ccache
RUN ./autogen.sh
RUN ./configure --enable-memcached --prefix=/usr
RUN make -j$(nproc)
RUN make install
```
It's the same with ubuntu, debian etc...
> But the easiest workaround is probably to split the "install" target up into several subtargets ?
Or verify in the configure that asciidoc is installed so the `make install` wont fail ?

**Comment by afbjorklund** [comment]
Well, building the manpage does require asciidoc. It's even in the documentation :-)

What you are asking for is that it should skip installing the manpage, if asciidoc (or a prerendered doc/ccache.1) is missing. And that would probably be better than failing the regular install target...

Will see if we can do something about that. How did memcached work out, BTW ?

**Comment by martinm82** [comment]
Regarding the dependency to libmemcached. What about adding the least amount of code from libmemcached to the sources as it is done with zlib. I would prefer to have just one executable with as least dependencies to the system. I tried it but the project structure of libmemcached is quite strange and it wasn't that easy to strip out the important stuff.

I am building for macOS and for rolling it out on macOS nodes I did not want to depend on a library that needs to be installed with brew. So I extended the Makefile.in and created a new target (make package) that will create an app bundle and than a dmg for easier installations on macs.

**Comment by afbjorklund** [comment]
If you want to avoid the dependency, you can do static linking ? Don't want to bundle it, but I suppose we can give some hints on how to build/install. Just using apt/brew is probably easiest for most people, though...

**Comment by afbjorklund** [comment]
Forgot that it is pain to do static linking of C++ libraries, and it seems that lilbmemcached-1.0.18 needs a couple of patches before it will behave on all platforms. So still better if someone else maintains that... ?

* https://bugs.launchpad.net/libmemcached/+bug/883267 (debian)
* https://bugs.launchpad.net/libmemcached/+bug/1245562 (homebrew)

**Comment by ahoarau** [comment]
> Will see if we can do something about that. How did memcached work out, BTW ?

Memcached seemed to work great. I think It's missing a `download_ccache.py` file to eventually save the cache on the disk. As far as I understand, it is lost once I kill the deamon..

**Comment by afbjorklund** [comment]
@ahoarau : that is correct, it is stored in memory. there are some alternatives, like memcachedb or couchbase or redis, that will persist your cache to disk... But the default memcached will _not_ do that.

**Comment by jrosdahl** [comment]
@ahoarau: Have you received a good enough answer to your question?

**Comment by ahoarau** [comment]
@jrosdahl I don't think the issue has found a solution to the `make install` problem needing asciidocs to run.
