### ISSUE TITLE
Dead links on ccache.samba.org in ccache Documentation->Installation

### ISSUE THREAD

**Issue by warmsocks** [ccache/ccache#276]
There are two Installation links on the Documentation page for ccache on samba.org that point to dead locations on github.

* To reproduce:

1.  Point browser at https://ccache.samba.org/documentation.html
2. Under "Installation" click on each of 
  2a.  "From a Git source repository"
  2b.  "From a release archive"
5.  Note that both 404 (not found)

* Instead, the links should point to the actual location of the desired files on github.  "doc" appears to be missing from URLs:

```
https://github.com/ccache/ccache/blob/master/INSTALL.md 
```
should be
```
https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
```
and

```
https://github.com/ccache/ccache/blob/master/INSTALL-from-release-archive.md
```
should be
```
https://github.com/ccache/ccache/blob/master/doc/INSTALL-from-release-archive.md
```

* Happens with multiple versions of multiple browsers on multiple platforms:
Firefox 60.* and Chrome 67.* on Mac OSX 10.11.6 and CentOS 7.5

* Which version of ccache you use.
3.4.2.  While the version is not relevant to this bug, it's an awesome program.   We're using ```-fstack-usage```, so thank you for the recent addition of caching .su files.

**Comment by afbjorklund** [comment]
The layout of the git repository was rearranged in 4aa357782e48626c4c604c680d4bd83324d1ea41

**Comment by jrosdahl** [comment]
Fixed now, thanks!
