### ISSUE TITLE
Please update the section on cache statistics, and Is it possible to upgrade existing ccaches?

### ISSUE THREAD

**Issue by Ximalas** [ccache/ccache#285]
It would be nice if the section on cache statistics is updated to describe these two, although they are fairly obvious:

```text
stats zero time                     Mon Apr  9 20:29:13 2018
stats updated                       Mon Apr  9 20:33:26 2018
```

Also, is it possible to upgrade existing ccaches to display these two pieces of information? Using the timestamp for the directory ${CCACHE_DIR}/0 as the initial value would be acceptable (to me).

**Comment by Ximalas** [comment]
Here's a sample from a ccache that has been in existence since Mon Jan  1 23:52 2018.

```text
# ccache --show-stats
cache directory                     /var/cache/ccache
primary config                      /var/cache/ccache/ccache.conf
secondary config      (readonly)    /usr/local/etc/ccache.conf
cache hit (direct)               1195290
cache hit (preprocessed)          393955
cache miss                       1466139
cache hit rate                     52.01 %
called for link                   197479
called for preprocessing           29851
multiple source files                646
compiler produced stdout               7
compile failed                     47541
ccache internal error                 28
preprocessor error                 20171
can't use precompiled header           6
couldn't find the compiler            42
bad compiler arguments             11689
unsupported source language          293
autoconf compile/link             235731
unsupported compiler option         4133
unsupported code directive           128
no input file                    7421119
cleanups performed                     0
files in cache                   3779957
cache size                         126.4 GB
max cache size                     225.0 GB
```
Hum, I don't see a zero time nor the time when this ccache was last updated.
Yes, I'm running the latest version of ccache.
```text
# ccache -V
ccache version 3.4.2

Copyright (C) 2002-2007 Andrew Tridgell
Copyright (C) 2009-2018 Joel Rosdahl

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 3 of the License, or (at your option) any later
version.
```

**Comment by afbjorklund** [comment]
Sorry, but the "stats updated" was added _after_ v3.4.2 was relased... (v3.4.2-28-g7ea35e0)
And the "stats zero time" is only updated when the cache is cleared (created or zeroed out)

**Comment by Ximalas** [comment]
I see. I'll happy wait for the next version.

**Comment by afbjorklund** [comment]
It _would_ be possible to set the timestamp explictly, but haven't seen a request for the feature...
e.g. use the ctime to replace any timestamp of 0, similar to how we are using the mtime for updated

**Comment by afbjorklund** [comment]
Like so: 17d182c888e97e944261e4c3828ed72beae1c6cb

**Comment by Ximalas** [comment]
That looks nice. Thank you.

**Comment by jrosdahl** [comment]
> Like so: 17d182c

I don't quite understand. Should the commit summary say "with" instead of "without"? And if so, is it really meaningful to use the stats files' ctime? The stats files are recreated each time they are updated, so their ctimes won't say when they were first created. Or am I missing something?

**Comment by Ximalas** [comment]
It should probably say "with". My original idea was to use the ctime of the directory 0/0. As far as I can tell, that ctime doesn't change at all. Maybe this is just a bad idea altogether.

All we need to do as users is to zero our stats, and then the zero time will appear in the output. All we lose are our impressive numbers for a few days. I have a ccache on my builder at work doing a hit rate of close to 68 %.

**Comment by jrosdahl** [comment]
> My original idea was to use the ctime of the directory 0/0. As far as I can tell, that ctime doesn't change at all. Maybe this is just a bad idea altogether.

A directory's ctime (n.b.: it means "last status change", not "creation time") changes whenever the directory's ownership/permissions/etc. change and also whenever the directory content changes, i.e. when a file is added or deleted. So looking at ctime won't do what you want here.

> All we need to do as users is to zero our stats, and then the zero time will appear in the output.

Why do you want the zero time stat to appear if you've never called `ccache -z`?

I actually think that it would be more logical to let ccache say `stats zeroed ... never` (or not show the line at all) until after the first `ccache -z`.

**Comment by Ximalas** [comment]
I think `stats zeroed ... never` is better, at least for scripting purposes.

**Comment by jrosdahl** [comment]
> I think stats zeroed ... never is better

Other lines in the output are hidden until they contain a useful value, so I'm leaning towards not displaying it. For instance, the "max cache files" and "max cache size" values are not shown if they are 0 (= disabled) and various counters only show up when they are > 0.

> at least for scripting purposes.

`ccache -s` is primarily meant to be a human interface. Perhaps we should add a machine-parsable version of it, where all counters are printed?

**Comment by Ximalas** [comment]
If the zero time is only to appear after you have run `ccache -z`, then it's a bit confusing when it's already being displayed for a brand new, empty ccache. This is what triggered me, how to lure `ccache -s` into showing the zero time without actually clearing the stats. Yes, I'm probably very confused and dead wrong. All in all this isn't a huge issue.

**Comment by jrosdahl** [comment]
> If the zero time is only to appear after you have run ccache -z, then it's a bit confusing when it's already being displayed for a brand new, empty ccache.

Agreed, but I'll make it not be displayed for a brand new ccache as well.
