### ISSUE TITLE
Bail out on compiler option -save-temps=obj

### ISSUE THREAD

**Issue by cpenev** [ccache/ccache#299]
Currently ccache bails out in the presence of -save-temps but does not bail out in the presence of -save-temps=obj

```
$ ./ccache-3.4.2/ccache /bin/gcc -x c -c -save-temps=obj main.c
$ ls
ccache-3.4.2  ccache-3.4.2.tar.bz2  main.c  main.o
$ ./ccache-3.4.2/ccache /bin/gcc -x c -c -save-temps main.c
$ ls
ccache-3.4.2  ccache-3.4.2.tar.bz2  main.c  main.i  main.o  main.s
$
```

**Comment by afbjorklund** [comment]
I don't think the compopts handle any `=`, so probably just add the whole thing as an exception.

What uses `-save-temps=obj` ?

**Comment by cpenev** [comment]
Thank you for the quick response Anders. Does it make sence to add begins_with("-save-temps=") as an exception?

I am not sure how side spread the use of -save-temps=obj is. Some motivation behind the option exists here:

https://gcc.gnu.org/ml/gcc/2010-03/msg00386.html

There is also -save-temps=cwd. I am not sure if there are any plans to support further options in the near future.

**Comment by afbjorklund** [comment]
Added cwd as well, seems like it will be enough for now.

**Comment by afbjorklund** [comment]
It uses `bsearch`, so can't really add any logic to it...

**Comment by cpenev** [comment]
Understood. Thanks for adding obj/cwd.
