### ISSUE TITLE
ccache doesn't like backslashes on Windows

### ISSUE THREAD

**Issue by rcdailey** [ccache/ccache#304]
I need to be able to specify the absolute path to the compiler to ccache on windows. My setup:

* Dev platform: Android NDK
* Compiler: Clang
* Host OS: Windows
* MinGW64 version of ccache.exe
* Build system: CMake + Ninja

I set up ccache in CMake as follows:

```
find_program( CCACHE ccache )
if( CCACHE AND NOT WIN32 )
    message( STATUS "Using ccache: ${CCACHE}" )
    set( ENV{CCACHE_BASEDIR} ${CMAKE_BINARY_DIR} )
    set( CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE} )
    set( CMAKE_C_COMPILER_LAUNCHER ${CCACHE} )
endif()
```

When I build on Linux OS with normal clang, this works fine. However, on NDK it does not:

> λ ninja -v -j1
[1/896] C:/msys64/usr/bin/ccache.exe C:\android\android-ndk-r17b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi --gcc-toolchain=C:/android/android-ndk-r17b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=C:/android/android-ndk-r17b/sysroot  -DANDROID -IE:/code/frontend2/source/Core/ThirdParty/uri/source/src -IE:/code/frontend2/source/Core/ThirdParty/uri/source/include -isystem C:/android/android-ndk-r17b/sources/cxx-stl/llvm-libc++/include -isystem C:/android/android-ndk-r17b/sources/android/support/include -isystem C:/android/android-ndk-r17b/sources/cxx-stl/llvm-libc++abi/include -isystem C:/android/android-ndk-r17b/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=15 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -Qunused-arguments -std=c++11 -Os -DNDEBUG    -Wno-inconsistent-missing-override -MD -MT Core/ThirdParty/uri/source/src/CMakeFiles/network-uri.dir/uri.cpp.o -MF Core\ThirdParty\uri\source\src\CMakeFiles\network-uri.dir\uri.cpp.o.d -o Core/ThirdParty/uri/source/src/CMakeFiles/network-uri.dir/uri.cpp.o -c E:/code/frontend2/source/Core/ThirdParty/uri/source/src/uri.cpp
FAILED: Core/ThirdParty/uri/source/src/CMakeFiles/network-uri.dir/uri.cpp.o
C:/msys64/usr/bin/ccache.exe C:\android\android-ndk-r17b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi --gcc-toolchain=C:/android/android-ndk-r17b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=C:/android/android-ndk-r17b/sysroot  -DANDROID -IE:/code/frontend2/source/Core/ThirdParty/uri/source/src -IE:/code/frontend2/source/Core/ThirdParty/uri/source/include -isystem C:/android/android-ndk-r17b/sources/cxx-stl/llvm-libc++/include -isystem C:/android/android-ndk-r17b/sources/android/support/include -isystem C:/android/android-ndk-r17b/sources/cxx-stl/llvm-libc++abi/include -isystem C:/android/android-ndk-r17b/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=15 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -Qunused-arguments -std=c++11 -Os -DNDEBUG    -Wno-inconsistent-missing-override -MD -MT Core/ThirdParty/uri/source/src/CMakeFiles/network-uri.dir/uri.cpp.o -MF Core\ThirdParty\uri\source\src\CMakeFiles\network-uri.dir\uri.cpp.o.d -o Core/ThirdParty/uri/source/src/CMakeFiles/network-uri.dir/uri.cpp.o -c E:/code/frontend2/source/Core/ThirdParty/uri/source/src/uri.cpp
ccache: error: Could not find compiler "C:\android\android-ndk-r17b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe" in PATH
ninja: build stopped: subcommand failed.

For some reason, even though CMake is giving ccache the full path to the compiler, it's saying it's not on PATH.

**Comment by rcdailey** [comment]
This is a CMake problem, ccache doesn't like backslashes in the path to the compiler. Changing these to forward slash corrects the problem.

**Comment by rcdailey** [comment]
Actually sorry I'm going to reopen. After looking at the CMake side some more, it's clear to me that it would be simpler if ccache just supported backslashes.

**Comment by peterbud** [comment]
It's a known issue, thee are PRs already to make it work properly in MSYS2, see #246 
If those are merged, we can also tackle the MINGW64 remaining issues.

**Comment by afbjorklund** [comment]
Will see what I can do about cleaning out those patches, like @peterbud says getting `__CYGWIN__` back up should be simple enough and `_WIN32` can be done - just more work with the weird DOS paths and all...

It seems to be using a healthy mix of everything, so I guess it would have to be prepared for whatever:
`C:/msys64/usr/bin/ccache.exe` (forward slashes)
`C:\android\android-ndk-r17b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe` (backward slashes)
And both of those on the _same_ command-line, and also with some `C:` and `E:` drives for good measure.

**Comment by rcdailey** [comment]
Some of the parameters to Clang also have back slashes. I'll have to get
you a snippet of that on Tuesday.

**Comment by hasselmm** [comment]
Have you checked if it's really backslashes and not path length exceeding the artificial 260 chars limit that's so hard to overcome on Windows?

https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/

**Comment by rcdailey** [comment]
If it is the path limit it's still something to be verified and fixed.
Unfortunately I can't tell what the issue is from where it's being used.

**Comment by jrosdahl** [comment]
See also #447.

**Comment by jrosdahl** [comment]
@rcdailey: Any news?

**Comment by rcdailey** [comment]
I am no longer in a position to contribute to this issue. I'll go ahead and close it.
