### ISSUE TITLE
Issue when using ccache on NFS

### ISSUE THREAD

**Issue by vaneyli** [ccache/ccache#309]
1: sudo mount -t nfs -o rw,soft,timeo=10,retry=3 scm-nfs.yun-inc.com:/workspace/scm-nfs-ccache /workspace/scm-nfs-ccache   
2: I meet the compiler process with "D" STAT and the build is paused
3: ccache is  3.4.2

 sudo cat /proc/25755/stack
[<ffffffff8116915e>] sleep_on_page+0xe/0x20
[<ffffffff81168ee6>] wait_on_page_bit+0x86/0xb0
[<ffffffff81169021>] filemap_fdatawait_range+0x111/0x1b0
[<ffffffff8116b04f>] filemap_write_and_wait_range+0x3f/0x70
[<ffffffffa077d1ef>] nfs4_file_fsync+0x5f/0xa0 [nfsv4]
[<ffffffff81211662>] vfs_fsync_range+0x42/0xb0
[<ffffffff812116ec>] vfs_fsync+0x1c/0x20
[<ffffffffa0569f0a>] nfs_file_flush+0x7a/0xb0 [nfs]
[<ffffffff811dd6e4>] filp_close+0x34/0x80
[<ffffffff811fde88>] put_files_struct+0x88/0xe0
[<ffffffff811fdf87>] exit_files+0x47/0x50
[<ffffffff8107d858>] do_exit+0x2b8/0xa60
[<ffffffff8107e07f>] do_group_exit+0x3f/0xa0
[<ffffffff8108efd0>] get_signal_to_deliver+0x1d0/0x6d0
[<ffffffff81014417>] do_signal+0x57/0x6c0
[<ffffffff81014adf>] do_notify_resume+0x5f/0xb0
[<ffffffff8164673d>] int_signal+0x12/0x17
[<ffffffffffffffff>] 0xffffffffffffffff

thanks

**Comment by afbjorklund** [comment]
This sounds like an nfs issue, rather than a ccache issue ? Which system version was used ?

**Comment by vaneyli** [comment]
Thanks,  I used the Alibaba Group Enterprise Linux Server release 7.2 (Paladin), I think you are right, it's the may the the bug of NFS

**Comment by afbjorklund** [comment]
That sounds like some variant of RHEL, maybe there is a system upgrade that would help ?

Yeah, there are some mentions on NFS but no real documentation in the manual or anything.

I have some tips, but basically putting your primary key doesn't really work - for performance reasons.

Should expand on https://github.com/ccache/ccache/issues/124#issuecomment-242641982 - some of these issues are common to every shared file system too
