### ISSUE TITLE
Cleanup "cppcheck"

### ISSUE THREAD

**Issue by afbjorklund** [ccache/ccache#323]
Doesn't seem to like the unittest macros:

```
[unittest/test_conf.c:401]: (error) Resource leak: log
[unittest/test_conf.c:424]: (error) Resource leak: log
[unittest/test_args.c:23]: (style) The function 'suite_args' is never used.
[unittest/test_argument_processing.c:63]: (style) The function 'suite_argument_processing' is never used.
[unittest/test_compopt.c:23]: (style) The function 'suite_compopt' is never used.
[unittest/test_conf.c:47]: (style) The function 'suite_conf' is never used.
[unittest/test_counters.c:22]: (style) The function 'suite_counters' is never used.
[unittest/test_hashutil.c:24]: (style) The function 'suite_hashutil' is never used.
[unittest/test_lockfile.c:23]: (style) The function 'suite_lockfile' is never used.
[unittest/test_hash.c:23]: (style) The function 'suite_mdfour' is never used.
[unittest/test_stats.c:24]: (style) The function 'suite_stats' is never used.
[unittest/test_util.c:22]: (style) The function 'suite_util' is never used.
```

**Comment by jrosdahl** [comment]
I don't get the style warnings the latest cppcheck (1.85). The resource leak ones looks like a bug in cppcheck, though.

**Comment by afbjorklund** [comment]
You are right, no errors with 1.85

**Comment by afbjorklund** [comment]
I don't think the resource leak (missing `fclose`) was a bug, but I also don't think it was important.

Fix: 8ac756d16a3aedb73088c509df77fbb84c7b7d10

**Comment by jrosdahl** [comment]
> The resource leak ones look like a cppcheck bug.

Had a closer look at these. It's not a bug since the macro can return early.

**Comment by jrosdahl** [comment]
Mid-air collision...

**Comment by afbjorklund** [comment]
Actually the fix was probably worse, not sure what happens to those buffers after fclose ?

**Comment by jrosdahl** [comment]
I'm not sure why cppcheck triggers in these two cases and not in the multitude of other tests where memory is leaked if a check fails. I'll just filter out the warnings since I don't think that it's worth the effort to write leak-free code for failing tests.

**Comment by jrosdahl** [comment]
> My new cppcheck version seems to hate gperf ?

I'm pretty sure cppcheck hated it before as well, but now it informs you about it.
