### ISSUE TITLE
gcc-8 -ffile-prefix-map support

### ISSUE THREAD

**Issue by osctobe** [ccache/ccache#325]
Since gcc-8 there is -fmacro-prefix-map which translates __FILE__ strings in addition to mapping debug-info paths. See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70268

-ffile-prefix-map combines -fmacro-prefix-map and -fdebug-prefix-map into one option.

-fmacro-prefix-map will affect preprocessed output, so can be ignored in command-line hash. -ffile-prefix-map is then equivalent to -fdebug-prefix-map.

**Comment by jrosdahl** [comment]
Closed via #326.
