### ISSUE TITLE
Clang integrated assembler breaks hard linked cache entries.

### ISSUE THREAD

**Issue by tzik** [ccache/ccache#331]
ccache doesn't work well with clang integrated assembler. Here is a reproduction below. `expected.o` and `actual.o` at the last line should match. Both ccache and clang here are ToT as of today

```bash
#!/bin/bash
export CCACHE_DIR="${PWD}/ccache"
export CCACHE_HARDLINK=1
ccache -C

echo '.octa 0x0' > failcase.s
ccache clang -c failcase.s -o failcase.o
cp failcase.o expected.o

echo '.octa 0x1' > failcase.s
ccache clang -c failcase.s -o failcase.o

echo '.octa 0x0' > failcase.s
ccache clang -c failcase.s -o failcase.o
cp failcase.o actual.o

cmp expected.o actual.o
```

IIUC, this happens because:
 - At the first compilation, clang creates `failcase.o` and writes the content, and ccache stores it as a cache entry using a hard link.
 - At the second compilation, clang **overwrites** `failcase.o`, and the stored cache entry, as they share the same backing file.
 - At the third compilation, ccache gives the stored cache entry as the result, which is overwritten by the previous compilation.

I'm not sure this should be fixed at clang side or ccache side, but either of them should unlink the output file at the beginning of the compilation.

**Comment by tzik** [comment]
https://bugs.llvm.org/show_bug.cgi?id=39782 is a corresponding clang side report.

**Comment by afbjorklund** [comment]
It should be fixed in clang, but we can do a workaround in ccache...

**Comment by jonnyyu** [comment]
Another way is to support clone besides hardlink.

**Comment by afbjorklund** [comment]
@jonnyyu : if you are looking for clone support, you can find it here: #296

To be honest, both `hard_link` and `reflink` are a bit disappointing, speedwise.
At this point in time, they seem to be mostly about saving **space** rather than time ?

And they come with a wide range of different caveats, making them hard to use...

**Comment by jrosdahl** [comment]
This sounds like yet another reason for discontinuing the error-prone hardlink support...
