### ISSUE TITLE
ccache not effective on multi cpu

### ISSUE THREAD

**Issue by hkrpavan** [ccache/ccache#336]
ccache  seems to be not working effectively on multiple cores particularly with cache hit cases.

I created a scenario where all my compilations fall under direct ccache hit. Some how gmake is forking one ccache call at a time. Is there a locking contention going on? Mine is 15 CPU machine with 90 GB RAM.
I did try unsetting CCACHE_STATS and writing to CCACHE log files. Didn't help.

**Comment by afbjorklund** [comment]
It is true that make works by forking the compiler, but should still be able to run multiple jobs at the same time... Normally you would use something like `make -j $NPROC`, where $NPROC is the number of processing units. For instance the output from the `nproc` command.

**Comment by hkrpavan** [comment]
Of course with -j make forking the compiler calls in parallel. This is visible in top command and ps -xvf.
When used ccache with compiler i always see one instance of ccache gcc call at any given point of time.

**Comment by hkrpavan** [comment]
Hmm.. this seems to be strange. I am using ccache 3.4.2. While generating ccache i.e., initial builds with no cache, i see multiple CPUs being using by compiler/ccache but subsequent builds whose ccache is fully available i just notice one core being utilized.

**Comment by afbjorklund** [comment]
@hkrpavan : which is platform is this ? We had some issues on the Mac platform earlier, but nobody was able to troubleshoot the cause of the issues at that time. Haven't heard of any such serializing issues on Linux, but need some more details/reproducers.

**Comment by hkrpavan** [comment]
Thank you for your support. This turned out to be a Makefile problem. GNUMake is using sed in foreach function in a macro, strangely build parallelizes with out ccache, when ccache was used it goes to serial mode. I replaced make's foreach function with shell function and it worked.

Here is the problematic macro just in case if it helps for any one in future.

$(foreach ale_stgr,$1,$(shell echo $(ale_stgr) | sed ':r;s%[^/.]\+/\.\.\(/\|$$\)%%;t r'))
