### ISSUE TITLE
ccache 3.5 release archive is missing getopt_long.c

### ISSUE THREAD

**Issue by ccotter** [ccache/ccache#340]
The ccache 3.5 download link on https://ccache.samba.org/download.html is missing getopt_long.c, but the 3.5 tag on this repo and master show the file present. Was this a minor oversight when creating the source code release packages, or has there been any effort to remove it from the ccache source (it doesn't look that way from what I can tell)?

**Comment by afbjorklund** [comment]
It's a bug, the file needs to be listed as a "dist file" - but its actual usage is conditional.

**Comment by jrosdahl** [comment]
(Regression in #315 which was first included in 3.5, so no previous ccache versions are affected.)

**Comment by jrosdahl** [comment]
> Sounds like a typical bugfix, for 3.5.1 ?

My plan is to release 3.6 quite soon and not bother making a 3.5.1. Does that sound reasonable?
