### ISSUE TITLE
Compilation failures when Fortran modules are involved

### ISSUE THREAD

**Issue by boegel** [ccache/ccache#342]
(follow-up for discussion in #90)

When `ccache` is used with `gfortran`, compilation fails when a cached result is picked up that requires Fortran modules that were generated at compilation time but which are not included in the cache, for example:

```
Fatal Error: Can't open module file 'f77_blas.mod' for reading at (1): No such file or directory
make[2]: *** [input_constants.o] Error 1
```

To avoid this happening, `ccache` should not cache the compilation result when Fortran module files (`*.mod`) were generated, since a cache miss is much more desirable than a failing compilation due to a cache hit that provides an incomplete set of compilation artifacts.

cc @melven

**Comment by afbjorklund** [comment]
Most likely you will need to contribute a patch for this, how to detect that particular case ?

a.k.a. "nobody knows Fortran"

**Comment by boegel** [comment]
I'm happy to try and help out, time permitting, but I'm certainly no Fortran expert either (I do know a couple of people I can reach out to for help though).

I'm also clueless w.r.t. the inner workings of `ccache`. Any suggestions for a good place in the codebase to start looking into for this?

**Comment by jrosdahl** [comment]
As noted in #90, another option would be to revert the Fortran support (c0875cf).

**Comment by jrosdahl** [comment]
I will revert the Fortran support now. We can add it back if we find people with time and interest of maintaining Fortran stuff.

**Comment by fcasson** [comment]
I have interest in the Fortran use case.  From what I understand, the reason this is hard is that you need the dependency tree to be provided across all the source files that may interact via modules.  This information should be available from cmake. builds.  Has anyone looked into trying to get dependency graph out of cmake and pass it to ccache for the Fortran use case?

I also saw this tool:  https://perso.univ-rennes1.fr/edouard.canot/f90cache/ but it also needs the dependency tree given to it.  I'd prefer to use ccache as it looks a lot better maintained.
