### ISSUE TITLE
Incomplete GCC dependency file rewrite on preprocessed cache hit

### ISSUE THREAD

**Issue by gjasny** [ccache/ccache#351]
Hello,

in my project I noticed ninja to complain about a dirty build tree at the install target due to non-existent files. I (hopefully) tracked it down to ccache not pruning the basedir information enough from the GCC dependency file (`.d`). The attached test case shows the problem:

It creates a project where the unsanitized dependency file looks like this:
```
/Users/gregorj/Git/Experimental/ccache-deps-bug/s2/b/foo.nc.o: \
  /Users/gregorj/Git/Experimental/ccache-deps-bug/s2/foo.cpp \
  /Users/gregorj/Git/Experimental/ccache-deps-bug/s2/foo.h
```

On first ccache build (miss) that file gets rewritten to:
```
b/foo.o: foo.cpp ./foo.h
```

Moving the project and thus the basedir from `s1` to `s2` gives a preprocessed hit and this dependency file:
```
b/foo.o: foo.cpp /Users/gregorj/Git/Experimental/ccache-deps-bug/s2/foo.h
```

As you can see ccache forgot to rewrite the full path to the header.

Thanks,
Gregor

**Comment by gjasny** [comment]
```
#!/bin/bash

#set -x
set -e

export PROJECT_ROOT="${PWD}"

rm -rf cache s1 s2
mkdir -p cache s1/b

cat << EOF > s1/foo.h
#pragma once
int foo();
EOF

cp -a s1 s2

cat << EOF > s1/foo.cpp
#include "${PROJECT_ROOT}/s1/foo.h"

int foo() { return 42; }
EOF

cat << EOF > s2/foo.cpp
#include "${PROJECT_ROOT}/s2/foo.h"

int foo() { return 42; }
EOF

sleep 2

export CCACHE_DIR="${PROJECT_ROOT}/cache"
export CCACHE_BASEDIR="${PROJECT_ROOT}/s1"
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_COMPRESS=true
export CCACHE_LOGFILE="${PROJECT_ROOT}/cache.log"
#export CCACHE_MEMCACHED_ONLY=true
#export CCACHE_MEMCACHED_CONF="--SERVER=localhost"
#export CCACHE_NOCACHE=true

rm -f "${CCACHE_LOGFILE}"

: ${CCACHE:=ccache}
: ${CXX:=c++}

#"${CCACHE}" --print-config

pushd s1
"${CCACHE}" "${CXX}" -c "${PROJECT_ROOT}/s1/foo.cpp" -o "${PROJECT_ROOT}/s1/b/foo.o" -MD -MT "${PROJECT_ROOT}/s1/b/foo.o" -MF "${PROJECT_ROOT}/s1/b/foo.o.d"
popd

pushd s2
export CCACHE_BASEDIR="${PROJECT_ROOT}/s2"
"${CXX}" -c "${PROJECT_ROOT}/s2/foo.cpp" -o "${PROJECT_ROOT}/s2/b/foo.nc.o" -MD -MT "${PROJECT_ROOT}/s2/b/foo.nc.o" -MF "${PROJECT_ROOT}/s2/b/foo.nc.o.d"
"${CCACHE}" "${CXX}" -c "${PROJECT_ROOT}/s2/foo.cpp" -o "${PROJECT_ROOT}/s2/b/foo.o" -MD -MT "${PROJECT_ROOT}/s2/b/foo.o" -MF "${PROJECT_ROOT}/s2/b/foo.o.d"
popd

"${CCACHE}" --show-stats

echo "======"
echo "--- first ccache"
cat "${PROJECT_ROOT}/s1/b/foo.o.d"
echo "--- second ccache"
cat "${PROJECT_ROOT}/s2/b/foo.o.d"
echo "--- second pure ccompiler"
cat "${PROJECT_ROOT}/s2/b/foo.nc.o.d"
```

**Comment by gjasny** [comment]
I added a test case for the issue

**Comment by gjasny** [comment]
I misread `s2` in `/Users/gregorj/Git/Experimental/ccache-deps-bug/s2/foo.h` for `s1`. Because that's what we see in CI.

**Comment by jrosdahl** [comment]
Hi @gjasny,

Yes, ccache rewrites the .d file on a cache miss as a side effect of rewriting the .d file for storing it in the cache. However, on a preprocessed cache hit the .d file is kept as is like the preprocessor created it. And on a direct cache hit, the .d file with relative paths will be taken from the cache. This is somewhat asymmetrical, but I don't see that there would be a problem.

Did you find a solution to your problem elsewhere than in ccache?

**Comment by gjasny** [comment]
Hi Joel,

I tweaked the test case code a little bit more and was able to reproduce it with the memcached branch and an active memcache server in #352. 

Thanks,
Gregor
