### ISSUE TITLE
-gsplit-dwarf link to .dwo file gets broken in cached build

### ISSUE THREAD

**Issue by andrey-utkin** [ccache/ccache#356]
So that if you build same thing two times but save the results into different, or randomized, filepaths, in the second case the path to `.dwo` file is invalid. This becomes apparent when the first set of built files gets removed.

I can't think of any mitigation of this except for disabling caching in such case.

**Comment by jrosdahl** [comment]
Thanks for the bug report! Ccache should be handling `-gsplit-dwarf` just like `-g` when it comes to absolute paths (like described in [_Compiling in different directories_ in the manual](https://ccache.samba.org/manual/latest.html#_compiling_in_different_directories), but it doesn't. No need to disable caching.

**Comment by andrey-utkin** [comment]
If you added just cwd to the hash, I think it's still not enough. You need to hash also output path parameter. I can try to edit your test to demonstrate the issue I see here.

**Comment by jrosdahl** [comment]
> If you added just cwd to the hash, I think it's still not enough. You need to hash also output path parameter.

I see. That was not clear to me from your first description.

**Comment by jrosdahl** [comment]
@andrey-utkin: Does ac4da5410dc5 look good to you? If so, could you perhaps test it in your context?

**Comment by jrosdahl** [comment]
@andrey-utkin: I merged this to master now. Still interested in hearing your opinion on the follow-up fix.
