### ISSUE TITLE
Why unlink an existing manifest in dependency mode?

### ISSUE THREAD

**Issue by pavsa** [ccache/ccache#361]
Hello,

I ran into a cache miss problem that should not happen.

The scenario is:
1. Depend mode is enabled
1. There is one local source file in which is included one local header file
1. Run the compilation with ccache gcc ... with dependency file generation explicitly in gcc parameters
1. Change something in the header file that causes the compiled object to be different.
1. Run the compilation again
1. Cache should now contain one manifest file, two object files - but it contains only one. The first manifest file with the result of the first compilation got deleted, then recreated again during the second compilation. 

This causes a problem if you have unchanged source file along with compilation parameters and other information that goes into generating the hash for the manifest file, but you have different sets of header contents each time. Only the last compiled one will survive in the cache, the rest will be deleted.

The offending line is here:

https://github.com/ccache/ccache/blob/7abac8f2cd1a0173784a16cfe8113392780323eb/src/ccache.c#L1485

What is the reason for not allowing another version of object file with different contents of headers to exist in dependency mode? I removed the unlink and it works as expected.

By the way, this works properly in the direct mode, but I never want to run the preprocessor, if it fails, run the compiler directly. We always generate dependency files during compilation.

**Comment by afbjorklund** [comment]
Can you write a test case for this ? To me it sounds reasonable.

**Comment by pavsa** [comment]
#362

**Comment by pavsa** [comment]
I’ve moved this to other pull request  #363

**Comment by jrosdahl** [comment]
Fixed by #363.
