### ISSUE TITLE
Cleanup based on mtime?

### ISSUE THREAD

**Issue by danrbailey** [ccache/ccache#367]
Hi,

I've been noticing an issue for a while that we're getting sporadic ccache misses. I recently switched on CCACHE_DEBUG to try and track this down further (thanks for this new mode, it's a great idea!). 

It appears that we're getting manifest files cleaned up using LRU when they shouldn't be, which is causing the cache miss. We're using Ccache 3.5 and have a large max cache size (50G) without limiting the number of files in the cache.

Having a look through the codebase, my guess is that the manifest mtime is only updated when adding or removing to the manifest. I believe that the preferred logic would be for it to be updated whenever a cache from the manifest is read instead? Otherwise we get an old (but heavily-used) manifest file being cleaned up because it hasn't needed to be modified.

This would be consistent with the fact that the behavior appears to be as expected with no redundant ccache misses when first clearing the cache. However, this issue only starts to happen when the cache size reaches the limit and the implicit cleanup starts to take place.

Does that make sense or have I mis-understood something in the codebase?

**Comment by afbjorklund** [comment]
It seems your analysis is correct, and that the mtime needs to be updated on _all_ the required files.

So when there is a direct hit and the manifest is use, it needs a: `update_mtime(manifest_path);`

**Comment by danrbailey** [comment]
Thanks Anders. I wonder if there's a performance penalty with updating mtime on all files? Maybe it would be feasible to use atime, although I'm not sure how portable this would be.

Another approach I'm considering is using a manual cleanup process that looks at a directory of ccache.log files and sporadically parses these to figure out all the files that have been written or accessed in the last 10 cache files (for example). This would likely have the benefit of reducing the maximum file size to a lower value than the 50G we currently have set and offloading the cleanup to a post-process would be nice too. Any thoughts?

**Comment by jrosdahl** [comment]
Cool, this appears to be a thinko that has been present in the code ever since I implemented the direct mode almost ten years ago. :slightly_smiling_face: Thanks for noticing!

> I believe that the preferred logic would be for it to be updated whenever a cache from the manifest is read instead?

Yep, correct.

> I wonder if there's a performance penalty with updating mtime on all files?

There will be an extra syscall, but we do that for the other cache files already.

> Maybe it would be feasible to use atime, although I'm not sure how portable this would be.

Too unportable I'm afraid.

> Another approach I'm considering [...] Any thoughts?

The current cache cleanup mechanism is not very optimal for several reasons. For instance, several ccache processes may race to clean up the same subdirectory, and the way the cleanup works (stat-ing all files in one of the 16 subdirectories) is relatively costly. I have some ideas on how to improve it, but I have sadly not had time to pursue them.

**Comment by danrbailey** [comment]
Thanks for fixing so quickly Joel!

One more quick question related to this - is it possible to disable the automatic cleanup mechanism (if we did want to roll our own)?

**Comment by jrosdahl** [comment]
> is it possible to disable the automatic cleanup mechanism (if we did want to roll our own)?

Sure, just set cache size to unlimited (`ccache -M 0`). After you have run your own cleaning mechanism you can run `ccache -c` to recalculate the _files in cache_ and _cache size_ counters if you want. Or combine the steps by using `CCACHE_MAXSIZE=50G ccache -c` as the cleaning mechanism once in a while.
