### ISSUE TITLE
Turn off compression of manifest files if compression=false is specified

### ISSUE THREAD

**Issue by jfikar** [ccache/ccache#375]
I was experimenting with btrfs compressions, especially zstd, which seems to be faster than the ccache built-in gzip. However, I discovered that the .manifest files are always gzip compressed even if I specify compression=false in the conf file.

I understood, you want to [compress .manifest files by default](https://github.com/ccache/ccache/pull/275), but doesn't it mean no compression= specified in the conf file? Shouldn't the user be able to turn off the .manifest file compression somehow?

**Comment by jrosdahl** [comment]
It would indeed be possible to add an option to disable compression of manifests, but since I plan to rewrite how files are stored and compressed in the cache (see #218), I don't think that we should add such an option at this time.

**Comment by afbjorklund** [comment]
There is some code to do this in my "compression" branch. Note that the original ccache code uses gzopen a lot, so unless your compression library also provides such a wrapper there's a lot of code affected here...

See #118

I did not evaluate zstd, but settled for using lz4. (I am mostly optimizing for performance, normally)

**Comment by afbjorklund** [comment]
Actually the code was a _lot_ older than compression, is was part of the "database" work:

https://github.com/ccache/ccache/compare/3.1-maint...afbjorklund:database-3.1 #diff-3333f85857b1f8a88f0b53fd6302bb71

That is, it was the file itself that was the problem rather than the actual compression...

But apparently zstd already has a compatible zlibWrapper included: [libWrapper/gzlib.c](https://github.com/facebook/zstd/blob/ea0b5fc193882230055827370bf0657b502eb06c/zlibWrapper/gzlib.c)

**Comment by afbjorklund** [comment]
I'm not sure that there was any plans to change the manifests in the rewrite, only the object etc ?
Not sure that there exists any need for the user to turn off compression of the manifest, actually.

**Comment by jrosdahl** [comment]
> I'm not sure that there was any plans to change the manifests in the rewrite, only the object etc ?

I wouldn't say plan since we/I haven't decided on a plan yet, but in my mind it certainly is an option to make the `compression` setting a master switch for compression (or not) of both result files and manifest files.

**Comment by afbjorklund** [comment]
Turning off the compression for manifest files is certainly doable (just use the "transparent" mode of gzio), but a better option would be to enable compression for _all_ files instead - switching the default level to "1".

The manifest files use the default compression level ("6"), which is reasonable for those small files. But for large objects, I prefer to use "1" in the critical path and optionally do "9" recompression during off-hours.

> Shouldn't the user be able to turn off the .manifest file compression somehow?

If we want to implement this feature, it's more or less inserting a single byte in the mode:

``` C
	f2 = gzdopen(fd2, compress_manifest ? "wb" : "wbT");
```

**Comment by jrosdahl** [comment]
Fixed as a side effect of 1bb7f769cdda.
