### ISSUE TITLE
Hardlinked dep files don't work well with automake 

### ISSUE THREAD

**Issue by tzik** [ccache/ccache#378]
On an example below, the second `mv` failed with `mv: 'foo.d.tmp' and 'foo.d' are the same file` message. The ccache version here was [latest](https://github.com/ccache/ccache/commit/6d71b6179a6e3bf26e2c17162254cdddd66c297b) as of today.

```bash
#!/bin/bash
cd "$(dirname "$0")"

export CCACHE_DIR="${PWD}/ccache"
export CCACHE_HARDLINK=1

rm -rf "${CCACHE_DIR}" foo.{c,h,d,d.tmp}

touch foo.h foo.c
sleep 1s

# ccache stores foo.d.tmp by a hardlink.
ccache gcc -c -MMD -MF foo.d.tmp -include foo.h foo.c
mv foo.d.tmp foo.d

# ccache pulls foo.d.tmp by a hardlink.
# The resulting foo.d.tmp points the same inode to foo.d.
ccache gcc -c -MMD -MF foo.d.tmp -include foo.h foo.c

# mv rejects to override a file if the dest and src file points the same inode.
mv foo.d.tmp foo.d
```

We can see this pattern of build in [automake](https://github.com/autotools-mirror/automake/blob/596e9e130f38ae068ac6150b2d62eafd544900f6/lib/am/depend2.am#L97) and automake-generated build systems.

I'm not sure if we should fix this in ccache side ([again](https://github.com/ccache/ccache/issues/331)), but if we do, just avoiding the hardlink on deps file at [get_file_from_cache](https://github.com/ccache/ccache/blob/6d71b6179a6e3bf26e2c17162254cdddd66c297b/src/ccache.c#L1253) and [its caller](https://github.com/ccache/ccache/blob/6d71b6179a6e3bf26e2c17162254cdddd66c297b/src/ccache.c#L2245) should work.

**Comment by afbjorklund** [comment]
We see the same kinds of failure, when people try to strip the object file (or whatever). The dep file _might_ be enough to warrant a special case, but just as with the previous bug it suggests removing hardlinks...

**Comment by jrosdahl** [comment]
@tzik: I'd say just stop using the hardlink mode... :slightly_smiling_face:
