### ISSUE TITLE
Object verification assumes that header sizes are stored in the manifest

### ISSUE THREAD

**Issue by pavsa** [ccache/ccache#382]
Setup:
depend mode, no sloppiness enabled.

I stumbled on a cache miss and I was investigating why. Turns out, I have this header that has `__DATE__` in it. It is then included in some source file.  

Generated manifest for this source file, which includes this header, has incorrect field size in "File info entry": 25 bytes more than the real file. I assume that is macro expansion to a real date here:

https://github.com/ccache/ccache/blob/5a17c1a62dea3dc40d585430a17889a4afe3e217/src/hashutil.c#L106-L116

But the stored size in manifest comes not from the actual header file size, but from the number of bytes hashed, which is now different with the date expansion.

This logic now causes cache miss when checking the header for stat change, as number of bytes hashed is compared to raw file size:

https://github.com/ccache/ccache/blob/5a17c1a62dea3dc40d585430a17889a4afe3e217/src/manifest.c#L380-L382

Solution might be to store real file size, then do the macro expansion during hashing and then check the hashes, which should be equal provided the date is still the same.

**Comment by jrosdahl** [comment]
> https://github.com/ccache/ccache/blob/5a17c1a62dea3dc40d585430a17889a4afe3e217/src/manifest.c#L380-L382

For reference, that quick exit was added as a drive-by improvement in aa16483c4792a, which means that the bug was introduced in 3.3.5.
 
> Solution might be to store real file size, then do the macro expansion during hashing and then check the hashes, which should be equal provided the date is still the same.

Sounds reasonable. Would you like to give it a try?

**Comment by pavsa** [comment]
> > [ccache/src/manifest.c](https://github.com/ccache/ccache/blob/5a17c1a62dea3dc40d585430a17889a4afe3e217/src/manifest.c#L380-L382)
> >     
> >     
> >         Lines 380 to 382
> >       in
> >       [5a17c1a](/ccache/ccache/commit/5a17c1a62dea3dc40d585430a17889a4afe3e217)
> >     
> >     
> >     
> >     
> > 
> >         
> >           
> >            if (fi->size != st->size) { 
> >         
> > 
> >         
> >           
> >            	return 0; 
> >         
> > 
> >         
> >           
> >            }
> 
> For reference, that quick exit was added as a drive-by improvement in [aa16483](https://github.com/ccache/ccache/commit/aa16483c4792a030646b36ce3edd5c5dd935c919), which means that the bug was introduced in 3.3.5. So I'd say that the bug is the assumption that the manifest contains file sizes instead of "hashed content" sizes.
> 
> > Solution might be to store real file size, then do the macro expansion during hashing and then check the hashes, which should be equal provided the date is still the same.
> 
> Sounds reasonable. Would you like to give it a try?

Yes, I will give it a try. Thanks for the better title :)

**Comment by pavsa** [comment]
Now I've looked in to it, it's not trivial. The best solution I thought of would be to throw out this condition:
https://github.com/ccache/ccache/blob/5a17c1a62dea3dc40d585430a17889a4afe3e217/src/manifest.c#L380-L382

It makes no sense to keep it, as all other writes and comparisons with ```size``` are hashed content size. 
But that causes problems for the heuristics in the code that follows it, as they rely on the file size match:
https://github.com/ccache/ccache/blob/e1c5d0b5a4a1325c855e6937a32578dded018e60/src/manifest.c#L431-L434
That would have to be thrown out too.

To have a fail fast condition for file size and also mtime/ctime slopiness, we would have to store the actual file size in a new field in the manifest entry, besides the hashed content size. 

Should I go in this direction? I see no other way to correctly solve this.

**Comment by afbjorklund** [comment]
Or maybe the other way around  ? I would instinctively expect it to record the original size/mtime if the header, rather than a modified version...

**Comment by pavsa** [comment]
But then you have no information stored about hashed content length, which you then can't compare in this condition:
https://github.com/ccache/ccache/blob/e1c5d0b5a4a1325c855e6937a32578dded018e60/src/manifest.c#L431-L434

**Comment by afbjorklund** [comment]
What I meant was that it could go into the new header, but maybe you are right...

We have one size that is part of the key, and one size that is referring to the file.

**Comment by pavsa** [comment]
Yes. We either have to add a new field to store the raw file size, or drop sloppiness based on stat, as it is unreliable.

**Comment by jrosdahl** [comment]
> Yes. We either have to add a new field to store the raw file size, or drop sloppiness based on stat, as it is unreliable.

For the record, there's also a third option: Don't hash the current date in `hash_source_code_string` and let callers fail the comparison if the function returns `HASH_SOURCE_CODE_FOUND_DATE`.

I would prefer adding a new field for the actual file size.

**Comment by pavsa** [comment]
I would prefer too, that's not much overhead. How complex is adding another field?

**Comment by jrosdahl** [comment]
Not that complex, I think. Something like:

* Bump `MANIFEST_VERSION` to 2.
* Add the new field to `struct file_info`.
* Update `read_manifest` and `write_manifest` accordingly. `read_manifest` should still be able to handle version 1 files for usage via `manifest_dump`. (Note that it won't be called via `manifest_get` for version 1 manifests since the version is part of the hash used to look up the manifest file.)
* And, of course, set and use the new field in `verify_object`.

**Comment by pavsa** [comment]
I will try to do it.

**Comment by jrosdahl** [comment]
> I will try to do it.

Great!

I have thought some more about the manifest format and I think that it could be a good idea to bundle this fix with two other manifest changes while we're at it, see #404. Granted, if we do so the fix for this particular problem will have to wait for a while, but maybe that's OK? If not, we can bump the version several times, but it would be nice not having to do that.

**Comment by afbjorklund** [comment]
Actually I was more leaning towards the other option, of not changing the header while it was being hashed. But as long as the original checksum and file size is available in the manifest, I am fine...

**Comment by jrosdahl** [comment]
> not changing the header while it was being hashed

What do you mean with the above?

**Comment by afbjorklund** [comment]
> > not changing the header while it was being hashed
> 
> What do you mean with the above?

date expansion and such

**Comment by jrosdahl** [comment]
OK. I would be fine with that as well, but I think that it's kind of elegant to be able to cache code with `__DATE__` in it.

**Comment by jrosdahl** [comment]
Regarding bumping the manifest version: the assumption I make here is of course that we still want to be able to use `ccache --dump-manifest` to inspect manifest files created by earlier ccache versions. But maybe that is unnecessary; it's mostly relevant only for debugging ccache itself, and it could be easy enough to just compile an older version of ccache for the purpose of dumping an older manifest. And when/if we drop support for zlib, we won't be able to read manifest version 1 files anyway without repacking them using external tools...

So if we drop `ccache --dump-manifest` support for older manifest versions, there is no need to bundle several manifest format changes into one. Opinions, @pavsa and @afbjorklund?

**Comment by pavsa** [comment]
I would not bother with previous versions. Hash is different, so no cache hits.

**Comment by jrosdahl** [comment]
> I would not bother with reading previous versions. [...] It's a cache, not a database. 

Yes? At least I want to be able to inspect data that was created by older ccache versions, so I (and others who want to dump an older manifest) need to bother. So the question is not if it should be possible but *how* it should be possible. :slightly_smiling_face:

> Hash is different, so no cache hits, cache would be rebuilt.

(That's irrelevant for this discussion.)
