### ISSUE TITLE
Always invoke compile when static analysis option (`--analyze`) present

### ISSUE THREAD

**Issue by cleeland** [ccache/ccache#388]
The clang toolset offers integrated static analysis via the `--analyze` command line option.  When this option is present, `ccache` should either ALWAYS invoke the compiler or should cache the static analysis results and report those back (IMHO it would be simpler and more correct to always invoke the compiler).

**Comment by cleeland** [comment]
FWIW, I found this issue trying to debug erratic static analysis reports over time: 53 bugs one day, 100 the next day, 75 the day after, etc..., all without much change in the actual source.  As it turned out, ccache was just doing its job a lot of the time and offering a cached version of the object file and never invoking the compiler.

**Comment by afbjorklund** [comment]
It would be nice if clang analyzer results could be cached, but like you say: disable in the interim
i.e. analyzing is even _slower_ than compiling, so there is even greater potential for caching...

IIRC, the default output is a `.plist` file ?

**Comment by cleeland** [comment]
`.plist` is the default, but clang offers the `--analyzer-output<arg>` option to choose alternative output formats (see https://clang.llvm.org/docs/ClangCommandLineReference.html)

**Comment by cleeland** [comment]
In my case, I am using the `scan-build` wrapper, which internally selects `html`, so even if plist were cached it likely wouldn't help me.

**Comment by afbjorklund** [comment]
Yeah, that is even worse (as in: even more different formats to take care of). And multiple outputs, too.

**Comment by cleeland** [comment]
Pragmatically, I'm not sure there's much value in caching the results.  In my experience, static analysis happens across the entire project on a scheduled basis, e.g., daily or weekly, in which case you probably just want to go ahead and analyze the entire corpus.  The other way it happens is when a developer makes material changes to files and is building in his/her workspace, in which case even ccache will be very likely to invoke the compiler.

**Comment by afbjorklund** [comment]
Some managers are keen on running coverage and analyzers on _every_ commit, no matter the cost...

**Comment by afbjorklund** [comment]
Something simple like that, in the meantime ?

**Comment by afbjorklund** [comment]
Darnit, `scan-build` seems to be using `-analyze`.

The secret password is `CCC_ANALYZER_VERBOSE`

**Comment by cleeland** [comment]
Hmmmm...which version  of clang?  I have clang versions 4 through 9 installed on my ubuntu workstation, and each version's `scan-build` has a line [similar to what's in github](https://github.com/llvm-mirror/clang/blob/master/tools/scan-build/bin/scan-build#L1337) where the script passes `--analyze`.

**Comment by afbjorklund** [comment]
Maybe it just lies in the `@PrintArgs` output... I can also see `--analyze` in the actual code (and options)

``` console
$ export CCC_ANALYZER_VERBOSE=1
$ make analyze
scan-build --use-cc=gcc ./configure
scan-build: Using '/usr/lib/llvm-3.8/bin/clang' for static analysis
configure: configuring ccache
...
```

```
'/usr/lib/llvm-3.8/bin/clang' '-cc1' '-triple' 'x86_64-pc-linux-gnu' '-analyze' '-disable-free' '-disable-llvm-verifier' '-main-file-name' 'main.c' '-analyzer-store=region' '-analyzer-opt-analyze-nested-blocks' '-analyzer-eagerly-assume' '-analyzer-checker=core' '-analyzer-checker=unix' '-analyzer-checker=deadcode' '-analyzer-checker=security.insecureAPI.UncheckedReturn' '-analyzer-checker=security.insecureAPI.getpw' '-analyzer-checker=security.insecureAPI.gets' '-analyzer-checker=security.insecureAPI.mktemp' '-analyzer-checker=security.insecureAPI.mkstemp' '-analyzer-checker=security.insecureAPI.vfork' '-analyzer-checker=nullability.NullPassedToNonnull' '-analyzer-checker=nullability.NullReturnedFromNonnull' '-analyzer-output' 'plist' '-w' '-mrelocation-model' 'static' '-mthread-model' 'posix' '-fmath-errno' '-masm-verbose' '-mconstructor-aliases' '-munwind-tables' '-fuse-init-array' '-target-cpu' 'x86-64' '-momit-leaf-frame-pointer' '-dwarf-column-info' '-debugger-tuning=gdb' '-resource-dir' '/usr/lib/llvm-3.8/bin/../lib/clang/3.8.0' '-D' 'HAVE_CONFIG_H' '-D' 'SYSCONFDIR=/usr/local/etc' '-I' '.' '-I' './src' '-I' './unittest' '-internal-isystem' '/usr/local/include' '-internal-isystem' '/usr/lib/llvm-3.8/bin/../lib/clang/3.8.0/include' '-internal-externc-isystem' '/usr/include/x86_64-linux-gnu' '-internal-externc-isystem' '/include' '-internal-externc-isystem' '/usr/include' '-O2' '-fdebug-compilation-dir' '/home/anders/ccache' '-ferror-limit' '19' '-fmessage-length' '0' '-fobjc-runtime=gcc' '-fdiagnostics-show-option' '-vectorize-loops' '-vectorize-slp' '-analyzer-display-progress' '-analyzer-output=html' '-o' '/tmp/scan-build-2019-04-22-182434-29083-1' '-x' 'c' 'src/main.c'
```

Suppose I could go back to my original commit, stupid perl.

**Comment by cleeland** [comment]
Gah.  It's both.  Sigh.

Looks like when `clang`-the-command-line-tool invokes `clang`-the-actual-compiler, it transforms `--analyze` to `-analyze`.

Behold:
```
$ clang --analyze -v path/to/sourcefile.cxx 
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /opt/rh/devtoolset-4/root/usr/lib/gcc/x86_64-redhat-linux/5.3.1
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Selected GCC installation: /opt/rh/devtoolset-4/root/usr/lib/gcc/x86_64-redhat-linux/5.3.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
 "/usr/bin/clang-4.0" -cc1 -triple x86_64-unknown-linux-gnu -analyze -disable-free -disable-llvm-verifier -discard-value-names -main-file-name MDCImpl.cxx -analyzer-store=region -analyzer-opt-analyze-nested-blocks -analyzer-eagerly-assume -analyzer-checker=core -analyzer-checker=apiModeling -analyzer-checker=unix -analyzer-checker=deadcode -analyzer-checker=cplusplus [...]
```

**Comment by afbjorklund** [comment]
Better safe than sorry

**Comment by cleeland** [comment]
Thanks for super-quick action on this!
