### ISSUE TITLE
"-g0" or "-g1" after "-gsplit-dwarf" with clang leads to painful cache misses or reuses old dwo

### ISSUE THREAD

**Issue by hwti** [ccache/ccache#393]
The interaction between `-glevel` and `-gsplit-dwarf` is complex.

With gcc :
 - `-g0 -gsplit-dwarf`, `-g1 -gsplit-dwarf`, `-gsplit-dwarf`, `-g -gsplit-dwarf` => a dwo, and level 2
 - `-g3 -gsplit-dwarf` is the same as `-gsplit-dwarf -g3`
 - `-gsplit-dwarf -g0` produces no debug info, but still a dwo !
 - `-gsplit-dwarf -g1` => a dwo, and level 1

With clang :
 - `-g0 -gsplit-dwarf`, `-g1 -gsplit-dwarf`, `-gsplit-dwarf`, `-g -gsplit-dwarf` => a dwo, and level 2
 - `-g3 -gsplit-dwarf` is the same as `-gsplit-dwarf` (clang has no level 3, at least currently)
 - `-g0` or `-g1` (and the alternative `-gline-tables-only`) after `-gsplit-dwarf` disable it (no dwo produced)

So with `clang -c test.c -gsplit-dwarf -g0` ccache alternates between two behaviors :
 - no manifest, preprocess, compilation, failure since there is no dwo, so "Failed; falling back to running the real compiler" (second compilation)
 - no manifest, preprocess, the cache contains an object file but no dwo, so the cache contents are removed and "Failed; falling back to running the real compiler"
In this case the result is correct, but this is always an expensive cache miss (the preprocessor is always called, and we compile one or two times).

Note that if there is an old dwo remaining in the build directory, it will be cached, which is incorrect (but the object file will not reference it).

Given the behavior is different between gcc and clang is different, I don't know if ccache can do anything. But at least we could document the issue, so the user knows that appending `-g0` / `-g1` to reduce or disable debuginfo breaks the cache and has performance issues with clang (this is already suboptimal with gcc, so filtering-out `-gsplit-dwarf` was already a good idea, but the ccache+clang issue make it much more important, and depending on the buildsystem it might be difficult).

**Comment by hwti** [comment]
With clang, adding `-###` to show the driver options is often useful when debugging those king of issues, since the `-g*` options are parsed by the front-end and transformed into :
 - `-enable-split-dwarf` (or not)
 - `-debug-info-kind=limited` (for `-g2`/`-g3`),  `-debug-info-kind=line-tables-only` (for `-g1` / `-gline-tables-only`), or nothing (for `-g0`)

With this I just saw `-gsplit-dwarf -g1 -gdwarf-3` (or `-gsplit-dwarf -g1 -gdwarf`) is like `-gsplit-dwarf`, so it produces a dwo !
It seems consistent with gcc : `-gdwarf` or `-gdwarf-version` ensures the debug level is at least 2.
So to determine whether clang would generate a dwo or not, we need to check the debug level at the end.

**Comment by jrosdahl** [comment]
What do you think of this idea?

If we have a cache miss and we have seen `-gsplit-dwarf`:
    1. Remove any preexisting .dwo.
    2. Run the compiler.
    3. Check if the compiler produced a .dwo. If yes, store it. If no, don't store it. Be happy either way.

In other words: Probe for a .dwo instead of trying to calculate if it will be produced by the compiler. The only downside I see is that ccache will remove an existing .dwo even if the compiler won't produce one (the `-gsplit-dwarf -g0` case for clang), but that's maybe acceptable?

**Comment by hwti** [comment]
The behavior in case of compilation failure already varies :
 - gcc leaves the old .o and .dwo
 - clang removes the .o and leaves the .dwo

I don't think any build system would depend on the old compiler outputs to be present after a build failure, so it would be acceptable if we remove the .dwo. It also makes sure we never cache a .dwo left by an older build (which can happen with the current code).

But what would be the behavior for cache lookup ? Could ccache assume that if there is no .dwo alongside the .o in the cache the compiler didn't produce one ?
For example, with `ccache clang -c test.c -gsplit-dwarf -g0`, in case of a preprocessed match, ccache fails since it finds a .o in the cache but no .dwo.
This would produce incorrect results if the cached .dwo in was lost due to a bug or a filesystem corruption, but since there is no manifest in this case I suppose the same issue already exists for other output files (.stderr, ...).

**Comment by jrosdahl** [comment]
> But what would be the behavior for cache lookup ? Could ccache assume that if there is no .dwo alongside the .o in the cache the compiler didn't produce one ?
> [...]
> I suppose the same issue already exists for other output files (.stderr, ...).

Right, that is slightly problematic. The .stderr file is optional, but if any of the other files is missing that will be detected since ccache knows what to except. Except for the .dwo, apparently.

Also, this will be a non-issue when #218 has been implemented since ccache then will record metadata that says what parts a result comprises.

**Comment by Trass3r** [comment]
For the record, `clang-11 -gsplit-dwarf -g1` seems to produce a -g1 dwo now.
