### ISSUE TITLE
'-MF /dev/null' fails due to file rename: ccache: error: Failed to create temporary file for /dev/null.tmp: Permission denied

### ISSUE THREAD

**Issue by trofi** [ccache/ccache#397]
Minimal reproducer:
```
$ ccache /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -pipe -c -MF /dev/null -MQ /dev/null -MMD -MP -x c /dev/null -o /dev/null
ccache: error: Failed to create temporary file for /dev/null.tmp: Permission denied

$ /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -pipe -c -MF /dev/null -MQ /dev/null -MMD -MP -x c /dev/null -o /dev/null
<ok>
```

Originally observed when built `git-2.21.0` using `ccache-3.7`. `git` seems to probe `-MF` feature support this way:
https://github.com/git/git/blob/14c0f8d3ab6c36672189cd2dd217f4617d12ccba/Makefile#L1220-L1224

**Comment by afbjorklund** [comment]
We have some checks for -o /dev/null, probably need to extend those for -MF /dev/null too

**Comment by afbjorklund** [comment]
Even better would be to have some release tests for high-profile projects, such as kernel or git.

**Comment by jrosdahl** [comment]
Thanks for the report.

Just a note on the reproducer: `ccache /usr/bin/gcc -O2 -pipe -c -MF /dev/null -MQ /dev/null -MMD -MP -x c /dev/null -o /dev/null` is not enough to trigger the problem with an empty ccache, but `ccache /usr/bin/gcc -O2 -pipe -c -MF /dev/null -MQ /dev/null -MMD -MP -x c /dev/null` (without `-o /dev/null`) is.

**Comment by afbjorklund** [comment]
There might be a slight problem with the implementation, I think we are skipping the name of the output file when we hash the arguments ? That might mean that we _could_ get a cache hit, that is missing the dep ?

**Comment by afbjorklund** [comment]
If that is indeed the case, then we should make sure to hash "/dev/null" (as a special case). Will add a test for it to verify, just something that I missed when I looked it through - similar to that logging and relpath...
