### ISSUE TITLE
Number of files according to stats goes out of sync after auto-cleanups

### ISSUE THREAD

**Issue by atomsymbol** [ccache/ccache#402]
Hello. I am having long-term issues with ccache stats going out of sync compared to actual filesystem contents. I created a shell script that can be used to at least partially reproduce this issue.

Steps to reproduce the issue:

1. Create an empty directory
2. Copy http://atom-symbol.net/f/2019-05-01/ccache-test.sh to the directory
3. Run `ccache-test.sh`
4. Compare printed "files in cache" counts

Example `ccache -s` output:

    files in cache 87

Expected output:

    files in cache 103

There is also minor discrepancy in the "cleanups performed" field. With a single `ccache -s; ccache -c; ccache -s` it can change from 34 to 37.

ccache version 3.7
Filesystem: ext4

**Comment by afbjorklund** [comment]
This is a known issue, about the stats going out of sync when the cache is loaded. A "clean" syncs it.

About the cleanups, that is because it actually counts the number of "buckets" (there are 16 of those)

**Comment by atomsymbol** [comment]
> This is a known issue, about the stats going out of sync when the cache is loaded. A "clean" syncs it.

The test I posted doesn't involve any concurrent ccachedir access, so it is unexpected for ccache to miscount.

Is there a place in the source code you can point me to so that I can attempt to fix this?

> About the cleanups, that is because it actually counts the number of "buckets" (there are 16 of those)

OK

**Comment by afbjorklund** [comment]
I think the main issue is that the cache is **not** locked during cleanup, so more files can enter.

This is not something we actually want to do, but we could do deltas instead of absolute values ?

``` C
	stats_set_sizes(dir, files_in_cache, cache_size);
```

See 403cb007c751ed59987148674716f3061c5f1079 for some previous code regarding this

Will take a look at your test, it sounds strange that a 1-job cache should "lose" any files...

**Comment by afbjorklund** [comment]
The test output is a bit misleading, where it actually does both cleaning and "counting".
But I can confirm that we are indeed losing files, even on a single-threaded job like this one...

Improved it by increasing the CCACHE_MAXSIZE before the final clean (to not hit anything)

```
========

cache directory                     ccachedir
primary config                      ccachedir/ccache.conf
secondary config      (readonly)    /usr/local/etc/ccache.conf
stats updated                       Wed May  1 18:28:32 2019
cache hit (direct)                   155
cache hit (preprocessed)               9
cache miss                            92
cache hit rate                     64.06 %
cleanups performed                    29
files in cache                        90
cache size                         368.6 kB
max cache size                     500.0 kB

00f1f637d2505e9165c9b1268094beda  ccache-test.sh.log
64 unique C files
104 files in cache
104 files in cache
426k	totalt cache size at block granularity (1k = 1000 bytes)
67k	totalt cache size at byte granularity (1k = 1000 bytes)

========

Cleaned cache
cache directory                     ccachedir
primary config                      ccachedir/ccache.conf
secondary config      (readonly)    /usr/local/etc/ccache.conf
stats updated                       Wed May  1 18:28:33 2019
cache hit (direct)                   155
cache hit (preprocessed)               9
cache miss                            92
cache hit rate                     64.06 %
cleanups performed                    29
files in cache                       104
cache size                         426.0 kB
max cache size                       1.0 MB

104 files in cache
104 files in cache
426k	totalt cache size at block granularity (1k = 1000 bytes)
67k	totalt cache size at byte granularity (1k = 1000 bytes)
```

This means that there are 14 files "missing", i.e. 90 to 104.

**Comment by afbjorklund** [comment]
The reason for this discrepancy is a bug in the stats framework, which is causing it to update the **object**  directory when it adds a **manifest**. Then next time it does a cleanup/count, these ghost files are "lost"...

Problem is that the `stats` are kept in the same structure as the cache, and then there is a global variable `stats_file` that chooses which file to use. It is never updated for the manifest, which has a different dir.

``` C
	stats_file = format("%s/%c/stats", conf->cache_dir, object_name[0]);
```

Found through good ole printf debugging, adding flush() and looking at STATS_NUMFILES updates:
```
[2019-05-01T20:47:41.812544 27410] Stored in cache: 2.o -> ccachedir/5/7/3102233169e6acb7a05e44c94337fa-369.o (copied)
[2019-05-01T20:47:41.812553 27410] stats_update_size: 1 files
[2019-05-01T20:47:41.812557 27410] ADD ccachedir/5/7/3102233169e6acb7a05e44c94337fa-369.o
[2019-05-01T20:47:41.812561 27410] STATS ccachedir/5/stats 1
[2019-05-01T20:47:41.812579 27410] Acquired lock ccachedir/5/stats.lock
[2019-05-01T20:47:41.812622 27410] Releasing lock ccachedir/5/stats.lock
[2019-05-01T20:47:41.812626 27410] Unlink ccachedir/5/stats.lock
[2019-05-01T20:47:41.812835 27410] Added object file hash to ccachedir/4/d/bb4bee6d05b16a29d2c48610252af5-288.manifest
[2019-05-01T20:47:41.812844 27410] stats_update_size: 1 files
[2019-05-01T20:47:41.812848 27410] ADD ccachedir/4/d/bb4bee6d05b16a29d2c48610252af5-288.manifest
[2019-05-01T20:47:41.812851 27410] STATS ccachedir/5/stats 2
```

It is the bundling of the counter updates that causes this, and manifest should probably be separate.

**Comment by jrosdahl** [comment]
Cool finding! I guess a PR will show up soon? :slightly_smiling_face:

**Comment by atomsymbol** [comment]
@afbjorklund I was examining the source code as well and expected that it might be caused by global variables like `stats_file`.

There is also the `counter_updates` global variable which might be causing issues.

**Comment by afbjorklund** [comment]
@jrosdahl : Hopefully, there are some corner cases left (3 files gone still?)

@atomsymbol : Yeah, that variable is in turn used by `stats_update_size`

**Comment by afbjorklund** [comment]
The problem was that `counter_updates` was never freed, after flush.

**Comment by atomsymbol** [comment]
Thanks.
