### ISSUE TITLE
Switch from MD4 to BLAKE2b and bump manifest on-disk format

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#412]
### Background

MD4 is old technology that works very well for ccache's purposes as far as we know. However, the much more modern BLAKE2b algorithm has ~more or less exactly the same performance as~ ≈25% worse performance than MD4 (at least for large files on 64-bit systems) and has much better hash characteristics.

### What to do

- Switch from MD4 to BLAKE2b.
  - Determine a suitable digest size. Maybe 160 or 192 bits would be a good sweet spot? (Using a very large digest size leads to unnecessarily long key sizes in file names and internal data structures.)
   - ~Bundle libb2 for optional usage, just like we do with zlib.~ Do like what's done for libzstd instead.
- Don't include the size of hashed data in keys anymore.
- ~Bump manifest version to 3.~ No longer needed since we no longer strive to have a `--dump-manifest` that can understand all different versions. Keep version 2 as is on master; the latest released version of ccache (3.7.2 at the time of writing) has manifest version 1.

**Comment by jrosdahl** [comment]
@pavsa wrote in https://github.com/ccache/ccache/issues/404#issuecomment-489449909:

> But is faster though?

The reason for switching was not to make it faster, only safer. I thought that the performance was very similar. But...

> I've done a simple benchmark of 1GB of data: [...]

When I benchmarked MD4 vs BLAKE2b previously, I got very similar performance results for the two algorithms, but I can't reproduce it now so I must have made some mistake. And I think I know what it was: I used an md4sum program I had laying around based on ccache's code. But it was compiled a long time ago, and compilers have probably advanced a bit since then...

When comparing `ccache --hash-file` from master with the same command with ccache compiled from #406, I get a slowdown as well: libb2's BLAKE2b is around 50% slower than ccache's MD4 implementation on my system. That's a bit disappointing. :slightly_frowning_face:

**Comment by jrosdahl** [comment]
@afbjorklund has made a prototype of this in #406.

**Comment by pavsa** [comment]
libb2 (if compiled with --enable-fat) runtime selection of optimized code. 
I have retested it (on a different machine now, that is has older cpu) with that enabled and also tested md5+sha1 from openssl:

blake2b: time took 1.4s   758.5 MB/s
MD4 time took 0.9s   1150.6 MB/s
MD5 time took 1.5s   673.7 MB/s
SHA1 time took 1.4s   758.5 MB/s

So I think we will have a hard time finding anything faster than md4.

**Comment by afbjorklund** [comment]
There is a reason why we stuck with md4+size, instead of sha-1...

**Comment by jrosdahl** [comment]
> I have retested it (on a different machine now, that has older cpu) with that enabled and also tested md5+sha1 from openssl:

Thanks for the tests.

> So I think we will have a hard time finding anything faster than md4.

Again I would like to point out that finding something faster than MD4 was not the goal. I would have been OK with a slight slowdown, but 50% slower might be a bit too much.

That leaves us with three options:

1. Cancel the switch, at least for now.
2. Switch anyway, accepting the slower hash.
3. Support both MD4 and BLAKE2b, pushing the choice of more speed or more safety to the user. Downside: Increases code complexity.

I'm leaning towards option 1. What do y'all think?

**Comment by pavsa** [comment]
> Again I would like to point out that finding something faster than MD4 was not the goal. I would have been OK with a slight slowdown, but 50% slower might be a bit too much.
> 
I know, I should have said something with comparable speed. 

> That leaves us with three options:
> 
>     1. Cancel the switch, at least for now.
> 
>     2. Switch anyway, accepting the slower hash.
> 
>     3. Support both MD4 and BLAKE2b, pushing the choice of more speed or more safety to the user. Downside: Increases code complexity.
> 
I still don't understand where did they come up with the numbers they have 
> 
> I'm leaning towards option 1. What do y'all think?

How fast is md4 in ccache? compared to the one in openssl?

**Comment by jrosdahl** [comment]
> How fast is md4 in ccache? compared to the one in openssl?

On my system, `ccache --hash-file /dev/shm/largefile` is consistently ever so slightly faster than `openssl md4 /dev/shm/largefile`.

**Comment by pavsa** [comment]
> 
> 
> > How fast is md4 in ccache? compared to the one in openssl?
> 
> On my system, `ccache --hash-file /dev/shm/largefile` is consistently ever so slightly faster than `openssl md4 /dev/shm/largefile`.

We should probably stay with md4 for now. 

But another more important question:
How much of a bottleneck is hashing though? 

I remember I once tracked CPU usage with ```top``` while doing clean build with everything in cache (100% hit rate, no compilations, only linking was still done) on a machine with 24 cores (48 threads) and cpu usage was split about 45-50% user space 50-55% kernel. I assume the kernel spent most of the cpu time serving IO requests.
Has anyone looked at it on their systems? 
I suggested a possiblee solution for this in #377 . This might reduce also IO load on kernel, but I have no numbers to compare.

**Comment by afbjorklund** [comment]
I think the optimization flags used are important here too, I get very different results when optimizing...

When looking at the standard `-O2 -g` the MD4 is faster than when looking at the `-O3 -march=native`

# -O2 -g
![plotcycles-O2](https://user-images.githubusercontent.com/10364051/57312167-50670680-70ed-11e9-99e5-a79c57cfc886.png)
[plotcycles-O2.pdf](https://github.com/ccache/ccache/files/3153351/plotcycles-O2.pdf)

# -O3 -march=native
![plotcycles-O3](https://user-images.githubusercontent.com/10364051/57312256-78566a00-70ed-11e9-909b-9ef6f2dad9d9.png)
[plotcycles-O3.pdf](https://github.com/ccache/ccache/files/3153352/plotcycles-O3.pdf)

So the b2 library should probably be compiled with more aggressive optimization flags ?

Adopted from https://github.com/BLAKE2/BLAKE2/tree/master/bench (i.e. I added md4)

**Comment by afbjorklund** [comment]
@pavsa : think I already commented this above, but openssl/md4.h and mdfour.h are very comparable...
There's some minor benefits from being able to compile the functions next to the rest, but not very much.
![plotcycles](https://user-images.githubusercontent.com/10364051/57318123-e0ab4880-70f9-11e9-9f0a-387632f2d2b9.png)

**Comment by jrosdahl** [comment]
@afbjorklund: Thanks for the graphs! But I guess the performance of small inputs like up to 256 bytes is not as important as more realistic file sizes, say 1 kB up to 10 MB or so?

**Comment by pavsa** [comment]
I just cannot get close to md4 performance no matter what, even with -march=native and -O3.

1GB block of memory being hashed: 
MD4:     0.9675s   1058.4MB/s
MD5:     1.6543s   619.0MB/s
SHA1:    1.2061s   849.0MB/s
blake2b: 1.3472s   760.1MB/s

Setup:
kaby lake xeon / ubunu in virtual machine:

libb2 compiled with ./configure --enable-native
which has -O3 / -march=native and full vectorization enabled (from output during compilation of libb2):

gcc -DHAVE_CONFIG_H -I. -DSUFFIX= ../src/ -fopenmp -O3 -march=native -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -fopenmp -MT libb2_la-blake2s.lo -MD -MP -MF .deps/libb2_la-blake2s.Tpo -c blake2s.c  -fPIC -DPIC -o .libs/libb2_la-blake2s.o

gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1~18.04) 

libb2 statically linked with this test program:

```

#include <time.h>
#include <blake2.h>
#include <string.h>
#include <stdio.h>
#include <malloc.h>
#include <openssl/md4.h>
#include <openssl/md5.h>
#include <openssl/sha.h>

static unsigned char *input;
static int testSize = 1024 * 1024 * 1024;

static void sha1test() {
	unsigned char out[SHA_DIGEST_LENGTH];
	SHA_CTX c;

	clock_t begin = clock();

	SHA1_Init(&c);
	SHA1_Update(&c, input, testSize);
	SHA1_Final(out, &c);

	clock_t end = clock();

	double time_spent = (double) (end - begin) / CLOCKS_PER_SEC;
	printf("SHA1:    %.4fs   %.1fMB/s\n", time_spent, (testSize / 1024.0 / 1024.0) / time_spent);
}

static void md4test() {
	MD4_CTX c;
	unsigned char out[MD4_DIGEST_LENGTH];

	clock_t begin = clock();

	MD4_Init(&c);
	MD4_Update(&c, input, testSize);
	MD4_Final(out, &c);

	clock_t end = clock();

	double time_spent = (double) (end - begin) / CLOCKS_PER_SEC;
	printf("MD4:     %.4fs   %.1fMB/s\n", time_spent, (testSize / 1024.0 / 1024.0) / time_spent);
}

static void md5test() {
	MD5_CTX c;
	unsigned char out[MD5_DIGEST_LENGTH];

	clock_t begin = clock();

	MD5_Init(&c);
	MD5_Update(&c, input, testSize);
	MD5_Final(out, &c);

	clock_t end = clock();

	double time_spent = (double) (end - begin) / CLOCKS_PER_SEC;
	printf("MD5:     %.4fs   %.1fMB/s\n", time_spent, (testSize / 1024.0 / 1024.0) / time_spent);
}

static void blake2test() {
	unsigned char out[BLAKE2B_OUTBYTES];

	clock_t begin = clock();

	blake2b(out, input, NULL, sizeof(out), testSize, 0);

	clock_t end = clock();

	double time_spent = (double) (end - begin) / CLOCKS_PER_SEC;
	printf("blake2b: %.4fs   %.1fMB/s\n", time_spent, (testSize / 1024.0 / 1024.0) / time_spent);
}

int main(int argc, char **argv) {
	input = malloc(testSize);
	for (int i = 0; i < 5; ++i) {
		printf("-----\n");
		md4test();
		md5test();
		sha1test();
		blake2test();
	}
	return 0;
}



```

**Comment by afbjorklund** [comment]
It will be more interesting to compare a real compilation, 1kB and 1GB are both equally unrealistic.
Note that there were more data (up to 4kB), but it got boring when plot on the cycles/byte graph...

**Comment by pavsa** [comment]
Here's my tests of smaller sizes:

1 000 000 x 1kB hashing:

MD4:     0.9786s   
MD5:     1.6130s   
SHA1:    1.1781s   
blake2b: 1.2780s  

1 000 000 x 4kB hashing:

MD4:     3.6674s  
MD5:     6.2054s  
SHA1:    4.3705s  
blake2b: 5.0089s

**Comment by afbjorklund** [comment]
Even though it is not faster, the implementation seems to show that BLAKE2 gives result that are comparable to MD4 but is more resistant to collisions (not that we have ever seen one in ccache)

``` console
$ ./misc/performance --checksum=md4 gcc c++_includes.cc 
Compilation command: gcc c++_includes.cc -c -o c++_includes.o
Compilercheck: mtime
Checksum: md4
Compression: off
Hardlink: off
Nostats: off
Without ccache:                               7.06 s (100.00 %) ( 1.00 x)
With ccache, preprocessor mode, cache miss:   8.23 s (116.57 %) ( 0.86 x)
With ccache, preprocessor mode, cache hit:    1.22 s ( 17.27 %) ( 5.79 x)
With ccache, direct mode, cache miss:         8.52 s (120.73 %) ( 0.83 x)
With ccache, direct mode, cache hit:          0.19 s (  2.75 %) (36.36 x)
With ccache, depend mode, cache miss:         8.59 s (121.63 %) ( 0.82 x)
With ccache, depend mode, cache hit:          0.27 s (  3.87 %) (25.82 x)
$ ./misc/performance --checksum=blake2b gcc c++_includes.cc 
Compilation command: gcc c++_includes.cc -c -o c++_includes.o
Compilercheck: mtime
Checksum: blake2b
Compression: off
Hardlink: off
Nostats: off
Without ccache:                               6.58 s (100.00 %) ( 1.00 x)
With ccache, preprocessor mode, cache miss:   8.25 s (125.37 %) ( 0.80 x)
With ccache, preprocessor mode, cache hit:    1.23 s ( 18.66 %) ( 5.36 x)
With ccache, direct mode, cache miss:         8.43 s (128.10 %) ( 0.78 x)
With ccache, direct mode, cache hit:          0.29 s (  4.38 %) (22.81 x)
With ccache, depend mode, cache miss:         8.27 s (125.73 %) ( 0.80 x)
With ccache, depend mode, cache hit:          0.27 s (  4.18 %) (23.95 x)
```

But as noted earlier, we need more tests if we are to make any generic recommendations...
So probably keep md4+size as the default hash key, for now ? Keep blake2b as an alternative.

**Comment by jrosdahl** [comment]
@afbjorklund: Yeah, it might be hard to reliably measure a slowdown for real compilations since the hashing speed is dwarfed by other things.

Hm, but what if I try with the ≈8 MB "sqlite amalgamation" source file...

```
MD4:
Without ccache:                             2.5049 s (100.0000 %) (  1.0000 x)
With ccache, preprocessor mode, cache miss: 2.6551 s (105.9963 %) (  0.9434 x)
With ccache, preprocessor mode, cache hit:  0.1208 s (  4.8225 %) ( 20.7362 x)
With ccache, direct mode, cache miss:       2.6177 s (104.5028 %) (  0.9569 x)
With ccache, direct mode, cache hit:        0.0176 s (  0.7038 %) (142.0875 x)
With ccache, depend mode, cache miss:       2.6063 s (104.0481 %) (  0.9611 x)
With ccache, depend mode, cache hit:        0.0178 s (  0.7113 %) (140.5892 x)

BLAKE2b:
Without ccache:                             2.4949 s (100.0000 %) (  1.0000 x)
With ccache, preprocessor mode, cache miss: 2.6064 s (104.4697 %) (  0.9572 x)
With ccache, preprocessor mode, cache hit:  0.1243 s (  4.9821 %) ( 20.0721 x)
With ccache, direct mode, cache miss:       2.6282 s (105.3464 %) (  0.9492 x)
With ccache, direct mode, cache hit:        0.0207 s (  0.8309 %) (120.3578 x)
With ccache, depend mode, cache miss:       2.6363 s (105.6685 %) (  0.9464 x)
With ccache, depend mode, cache hit:        0.0202 s (  0.8086 %) (123.6663 x)
```

So cache hit from ≈0.0177 s to ≈0.0204 s. :scream:

> So probably keep md4+size as the default hash key, for now ? Keep blake2b as an alternative.

I think I'm fine either way, but I have started leaning towards BLAKE2b again due the improved "sleep good at night" factor; a slowdown likely won't be noticable except in benchmarks. Choices, choices...

**Comment by afbjorklund** [comment]
I went the other way, and tested with xxHash - just to get some comparison. The XXH64 is the new CRC32, so it definitely lacks the factor (even though it passes SMHasher). Author says it's 50x faster than MD5...

https://github.com/ccache/ccache/compare/master...afbjorklund:xxhash

* http://cyan4973.github.io/xxHash/

The idea here is to see how much of the compilation actually depends on the hash checksum used. Using a simple checksum would be the "0x" and the current checksum would be the "1x" level.

md4:
```
Without ccache:                              92.97 s (100.00 %) ( 1.00 x)
With ccache, preprocessor mode, cache miss: 100.56 s (108.16 %) ( 0.92 x)
With ccache, preprocessor mode, cache hit:    5.56 s (  5.98 %) (16.71 x)
With ccache, direct mode, cache miss:       102.58 s (110.34 %) ( 0.91 x)
With ccache, direct mode, cache hit:          0.59 s (  0.64 %) (156.53 x)
With ccache, depend mode, cache miss:       102.49 s (110.24 %) ( 0.91 x)
With ccache, depend mode, cache hit:          0.63 s (  0.68 %) (147.57 x)
```

xxh64 (x 2):
```
Without ccache:                              91.56 s (100.00 %) ( 1.00 x)
With ccache, preprocessor mode, cache miss: 101.12 s (110.45 %) ( 0.91 x)
With ccache, preprocessor mode, cache hit:    5.90 s (  6.44 %) (15.52 x)
With ccache, direct mode, cache miss:        99.96 s (109.18 %) ( 0.92 x)
With ccache, direct mode, cache hit:          0.37 s (  0.40 %) (247.34 x)
With ccache, depend mode, cache miss:        98.61 s (107.71 %) ( 0.93 x)
With ccache, depend mode, cache hit:          0.44 s (  0.48 %) (206.78 x)
```

Talked about it in #40 and #41, so this is just a performance comparison.

**Comment by pavsa** [comment]
> 
> 
> I went the other way, and tested with xxHash - just to get some comparison. The XXH64 is the new CRC32, so it definitely lacks the factor (even though it passes SMHasher). Author says it's 50x faster than MD5...
> 
> [afbjorklund/ccache@blake2...afbjorklund:xxhash](https://github.com/afbjorklund/ccache/compare/blake2...afbjorklund:xxhash)
> 
>     * http://cyan4973.github.io/xxHash/
> 
> 
> The idea here is to see how much of the compilation actually depends on the hash checksum used. Using a simple checksum would be the "0x" and the current checksum would be the "1x" level. For sqlite3.c:
> 
> md4:
> 
> ```
> Without ccache:                              92.97 s (100.00 %) ( 1.00 x)
> With ccache, preprocessor mode, cache miss: 100.56 s (108.16 %) ( 0.92 x)
> With ccache, preprocessor mode, cache hit:    5.56 s (  5.98 %) (16.71 x)
> With ccache, direct mode, cache miss:       102.58 s (110.34 %) ( 0.91 x)
> With ccache, direct mode, cache hit:          0.59 s (  0.64 %) (156.53 x)
> With ccache, depend mode, cache miss:       102.49 s (110.24 %) ( 0.91 x)
> With ccache, depend mode, cache hit:          0.63 s (  0.68 %) (147.57 x)
> ```
> 
> xxh64 (x 2):
> 
> ```
> Without ccache:                              91.56 s (100.00 %) ( 1.00 x)
> With ccache, preprocessor mode, cache miss: 101.12 s (110.45 %) ( 0.91 x)
> With ccache, preprocessor mode, cache hit:    5.90 s (  6.44 %) (15.52 x)
> With ccache, direct mode, cache miss:        99.96 s (109.18 %) ( 0.92 x)
> With ccache, direct mode, cache hit:          0.37 s (  0.40 %) (247.34 x)
> With ccache, depend mode, cache miss:        98.61 s (107.71 %) ( 0.93 x)
> With ccache, depend mode, cache hit:          0.44 s (  0.48 %) (206.78 x)
> ```
> 
> Talked about it in #40 and #41, so this is just a performance comparison.

How to test this? 
I clean built with empty cache the project I am on and summed up all the size parts of the .o files in the cache and there's total of about 26GB of hashed content in one build, so there might not be that much slowdown (that work is divided all available cores). For md4 at 1GB/s it's only 26 seconds of hash time.

**Comment by afbjorklund** [comment]
@pavsa : the command used was `./misc/performance --checksum=xxh64 --verbose gcc sqlite3.c`

But as mentioned above it was mostly an experiment to see how much hashing time we actually have
(the theory here being that XXH64 is "free", but not safe enough from hash collision - less so than MD4)

If we switch, it is not for performance reasons. But if timings are "similar", that's not too bad (128 -> 512)

**Comment by jrosdahl** [comment]
_Originally posted by @afbjorklund in https://github.com/ccache/ccache/issues/413#issuecomment-502358546_:

> We had some nasty surprises when trying out the BLAKE2 checksum, based on what the author/vendor claimed.

Which surprises do you refer too? I have not interpreted the results like that.

**Comment by afbjorklund** [comment]
> Which surprises do you refer too? I have not interpreted the results like that.

As in when the performance numbers didn't match the nice graphs on the web site :-)
For one you had to use very aggressive optimization, and even then there was a gap.

Then again I was probably a bit naive too, we are going from 128 to 512 bits after all ?
Like you say above, the reason for changing is not performance but collision resistance.

**Comment by afbjorklund** [comment]
Rebased the implementation, preparing for replacement (rather than complement)

**Comment by afbjorklund** [comment]
What is the status of this one ?

**Comment by afbjorklund** [comment]
As feared, using BLAKE2b library is nowhere as portable as bundled MD4.

**Comment by jrosdahl** [comment]
> What is the status of this one ?

I have not thought much about this issue lately; I guess I'm kind of lukewarm about it. I would be fine with postponing or closing it for now since there are so many other (more important) things to think about. What's your take on this?

**Comment by afbjorklund** [comment]
I think the code is done... (minus cleanup and manifests versions etc) The only part that was tricky was to disable all the native optimizations for the cross-compile in Travis. Most likely the user want to build their libzstd and libb2 with much more aggressive optimizations (`-O3 -march=native`) than the rest of ccache ?

Also, one question was if you wanted to change digest size (currently at 160 bits).

**Comment by jrosdahl** [comment]
I did some experiments on my own system (Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz, Ubuntu 19.04) by hashing a large file in /dev/shm with different tools multiple times and noting the best case:

Algorithm | Speed
--------- | -----
ccache with bundled MD4 | 1083 GB/s
ccache with system libb2 | 800 GB/s
ccache with in-tree libb2 --enable-native | 784 GB/s
b2sum | 754 GB/s
ccache with in-tree libb2 --disable-native | 726 GB/s
md5sum | 654 GB/s
sha1sum | 537 GB/s
sha512sum | 358 GB/s

The results are based on 35bfe76 from #445.

I think that this is clearly good enough even for libb2 --disable-native, at least on my system.

> Also, one question was if you wanted to change digest size (currently at 160 bits).

I'm fine with 160 bits. We can easily bump it in the future.

**Comment by jrosdahl** [comment]
I merged your PR now. I'll update the documentation!

**Comment by afbjorklund** [comment]
Thanks for merging and doing the testing!

I guess that just like with zstd, those results are "good enough". And it should be more future-proof ?
I mean I went with lz4 and md4 because those were the fastest, not because of their produced results.
