### ISSUE TITLE
 Switch from zlib to zstd

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#413]
### Background

zstd is better than zlib in all aspects, and with negative compression levels it's as good as lz4 even for compression performance. The low overhead means that we can enable compression by default without negative consequences for the absolute majority of users.

### What to do

- Add zstd support.
  - ~Bundle libzstd for optional usage, just like we do with zlib.~ Let's try not bundling it.
- Remove zlib support.
  - **Rationale**:  Not keeping support for zlib means less dependencies and less complex code.

_**Edit:** Changed from lz4 to zstd according to discussion below._

**Comment by jrosdahl** [comment]
Related old pull request with broader scope: #118.

**Comment by afbjorklund** [comment]
This could probably also do with some benchmarks.

**Comment by afbjorklund** [comment]
Not sure if a rebase is needed, seems that the old code still works "good enough" without it...
There's some strange things going on with latest LZ4 versions, so I've stayed on the previous:

LZ4 v1.9.1
LZ4 v1.9.0
> Warning : this version has a known bug in the decompression function which makes it read a few bytes beyond input limit. Upgrade to v1.9.1 is recommended.

LZ4 v1.8.3
LZ4 v1.8.2
> This is maintenance release, mainly triggered by a data corruption that can only occur in v1.8.2, at level 9 (only), for some "large enough" data blocks (> 64 KB)

**LZ4 v1.7.5**

The main reason for staying with gzip (-1) as default was that the difference was not "big enough",
adding a new compression meant invalidating the cache - and everyone has gzip, noone has lz4.

**Comment by afbjorklund** [comment]
Rebased the old code: #421 (could be cleaned up further, but #118 had too much cruft in it now)

**Comment by afbjorklund** [comment]
The performance seems to again vary a lot, so thankful for someone else testing it out as well...

**Comment by afbjorklund** [comment]
Hmm, the above was **only** headers - and the stderr and manifest are still using gzip compression...

Seems like there might be some merit to the [later versions of LZ4](https://github.com/lz4/lz4/releases/tag/v1.8.2) and the special path for short files:

![plotcycles](https://user-images.githubusercontent.com/10364051/57486741-062d8300-72af-11e9-941f-af28335886f8.png)

**Comment by afbjorklund** [comment]
If we want to do this for the manifest and result files, we need some kind of [gzFile](https://www.zlib.net/manual.html#Gzip) replacement...
Either work with a local memory buffer, or something implementing a similar stdio buffer interface.

Earlier implementations only used alternative compressions for the cache files, **not** the manifest.
So it worked directly on the individual files, rather than attempting to do any stream compression.

**Comment by jrosdahl** [comment]
It should be relatively straight-forward to implement lz4 support now after a41ea79dba74 and fa398dec3ff7.

Since the compression abstraction already is done and does not impose much complexity on other code, I'm now positive to keep zlib support in addition to lz4. I'm now also OK with keeping support for **not** compressing since it's essentially of no implementation cost. @afbjorklund: Opinions?

**Comment by shawnl** [comment]
zstd fills all the use cases of both lz4 and gzip. I think you should go straight to zstd, as then the compression setting means alot more. With gzip the setting means hardly anything (and everyone uses -9).

**Comment by shawnl** [comment]
There also is the possibility of fixing hard-link mode by updating mtimes when a hard link gets a cache hit. (so it doesn't confuse make/ninja)

if hard link mode worked, then only heavier compression levels really make much sense, as you can't hard link with compression (unless you have transparent compression, but that is a differn't matter entirely)

**Comment by jrosdahl** [comment]
> zstd fills all the use cases of both lz4 and gzip.

That's a bold claim. My impression from when I looked at different alternatives is that zstd was better than gzip/libz in all aspects, but it did not match lz4 when it comes to speed. Do you have more information or insights than what's indicated by benchmarks and articles found on the net?

Yes, I think that replacing zlib with zstd makes sense. I also think that it makes sense to let the default compression method be the fastest method available so that we can say that the performance overhead is negligible.

Note that since a compression abstraction now is in place, the complexity cost of having several algorithms to choose from is less than what I originally imagined when I wrote this issue. I'll update the issue description to reflect this.

> (and everyone uses -9).

Off topic, of course, but have you ever run `tar -xzf foo.tar.gz something`? Then you've used gzip without using -9. My guess is that more people use the default -6 level than anything else.

**Comment by jrosdahl** [comment]
> There also is the possibility of fixing hard-link mode by updating mtimes when a hard link gets a cache hit. (so it doesn't confuse make/ninja)

I don't understand what you mean. The mtime is already updated when there is a cache hit. That's one of the problems with the hard link mode. What do you mean should/could be done?

Or did you mean to say _"fixing hard-link mode by **not** updating mtimes [on] a cache hit"_? If so, yes, that would of course be possible, but it would be a backward incompatible change that I would like to avoid if possible.

> if hard link mode worked, then only heavier compression levels really make much sense

That line of reasoning doesn't cover all use cases. For instance:

* The cache can be on another file system, so hard links cannot be used.
* The cache can, in the future, be stored in some other way, e.g. memcached, so hard links cannot be used.
* One might not want to use hard links because modifying a hard-link object file in place will corrupt the cache entry.
* One might not want to use hard links because they have the above mentioned mtime problem.

**Comment by jrosdahl** [comment]
@shawnl: Your suggestion about zstd piqued my interest to have a look at zstd again.

I now learned that zstd has a `--fast=#` (AKA "negative levels") option. I'm not sure if I missed that when I evaluated different algorithms a little over a year ago or if it's something new, but from some quick experiments they look very promising. I've mostly looked at compression performance since that's what I'm most interested in in this case; decompression speed doesn't feel like an issue. On a test corpus of a large file containing various concatenated object files which I hope are representative, `zstd --fast=4` beat `lz4 -1` on compression speed while at the same time producing a slightly smaller file! Decompression speed was not as high as lz4, but near enough.

I've now changed my mind and agree that it looks like zstd fits all use cases I see for ccache regarding compression. Unless @afbjorklund disagrees (@pavsa maybe has an opinion as well?), I think that we'll go with zstd instead (and remove zlib support).

**Comment by pavsa** [comment]
I am all for it if it's faster (both compression/decompression) at more or less the same compression ratio and has integrity checks.

**Comment by shawnl** [comment]
@jrosdahl yes, zstd was based on a fairly recent breakthough in mathamatics, which is why it can be so much better than older compression methods https://en.wikipedia.org/wiki/Finite_State_Entropy

**Comment by afbjorklund** [comment]
> zstd fills all the use cases of both lz4 and gzip. I think you should go straight to zstd, as then the compression setting means alot more. With gzip the setting means hardly anything (and everyone uses -9).

I found that the compression level (1 or 9) impacts the gzip performance **greatly**, but the question for ccache was more if compression time mattered _at all_. It's mostly about the decompression time, usually.

As usual, some actual implementation and benchmarks would make things less theoretical. We had some nasty surprises when trying out the BLAKE2 checksum, based on what the author/vendor claimed.

**Comment by afbjorklund** [comment]
These were the ones that I tried: (in 2016)
* gzip
* lz4f
* lzop
* snappy-c

The net result was switching gzip level (to 1)

**Comment by pavsa** [comment]
zstd seems to use fundamentally new and faster algorithm. Such breakthroughs in algorithms are rare, so if the implementation is solid, we should definitely go for it. 

I can confirm it is both faster and more achieves better compression ratio compared to zlib (used by gzip) in my simple tests with 800MB of object files:

GZIP compress (-3): 26.381s  / Size: 302MB
GZIP decompress 12.598s

ZSTD compress (-2): 10.971s / 290M
ZSTD compress (-3): 13.298s / Size 278MB
ZSTD compress (-10): 55.501s / Size 248MB
ZSTD decompress: almost the same at at all levels ~8.6s

**Comment by afbjorklund** [comment]
> zstd seems to use fundamentally new and faster algorithm. Such breakthroughs in algorithms are rare, so if the implementation is solid, we should definitely go for it.

Please do. Here is a nice article that compares the difference between the three:
https://code.fb.com/core-data/smaller-and-faster-data-compression-with-zstandard/
> "Some algorithms and implementations commonly used today are zlib, lz4, and xz. Each of these algorithms offers different trade-offs: lz4 aims for speed, xz aims for higher compression ratios, and zlib aims for a good balance of speed and size."

FWIW, both LZ4 and Zstd are actually from the same author (Yann Collet) :-)

One nice bonus point is that it features a zlib wrapper:
https://github.com/facebook/zstd/tree/dev/zlibWrapper

**Comment by afbjorklund** [comment]
> I've mostly looked at compression performance since that's what I'm most interested in in this case; decompression speed doesn't feel like an issue. 

My reasoning for *not* looking at compression speed, is that when we get a cache miss we spend a lot of CPU (and time) for the compilation anyway. So unless it is totally awful (looking at you, xz) and doesn't give too bad compression rates, I don't think it is that important. Instead I focus on the more common cache hit scenario, and thus the decompression speed. Then again I typically see 90% cache hits, YMMV.

> I've now changed my mind and agree that it looks like zstd fits all use cases I see for ccache regarding compression. Unless @afbjorklund disagrees (@pavsa maybe has an opinion as well?), I think that we'll go with zstd instead (and remove zlib support).

From my investigation, it seems that you could simply **keep** the zlib support (in code) and use zstd where available. I don't think that we need to for instance bundle zstd with ccache, but just use it as a library. It also means that it would include support for the manifest files as well, since I never got around to writing another compression wrapper (for gzio) they are currently not covered by the `compression_type` setting.

----

Can give it a try, but a _lot_ has changed on `master`.

Apparently we dropped the checksum (gzip → zlib) and are now hardcoding (enum) the algorithm ?

So I don't think that #118 or #421 is relevant anymore, and might as well look at `COMPR_TYPE_ZSTD`

But with the above wrapper, it shouldn't be too bad.

**Comment by afbjorklund** [comment]
Using a larger and newer library is going to make distribution somewhat more cumbersome.
This is why we bundled zlib before, and why I bundled lz4 with the previous implementation.

For instance one would have to figure out how to install it on Mac and Win, and on Travis...
i.e. Travis run on Ubuntu 14.04, whereas the "libzstd-dev" package first appeared in 16.04

https://packages.ubuntu.com/search?keywords=libzstd-dev&searchon=names&suite=all&section=all

I suppose one _could_ fix the automation, but for now I just left it to run with zlib instead:

```
checking for zlib >= 1.2.3... yes
checking for gzdopen in -lz... yes
checking zstd.h usability... no
checking zstd.h presence... no
checking for zstd.h... no
checking for ZSTD_versionString in -lzstd... no
configure: WARNING: disabling zstd functionality
```

**Comment by jrosdahl** [comment]
@afbjorklund wrote:
> the question for ccache was more if compression time mattered at all. It's mostly about the decompression time, usually.

OK, I see where you're coming from. I have a slightly differrent view: The reason why I care more (or rather _also_) about compression performance is that I want to enable compression by default for ccache, and I want to be able to say that it's negligible in _all_ use cases, not only high cache hit use cases. I think that a good compression rate is nice but not that important for ccache's use cases; compressing down to say 25 % instead of 33 % doesn't matter too much IMO. But yes, YMMV.

When I evaluated compression algorithms in early 2018 (not for ccache but for another similar tool), I chose lz4 over lzo, snappy, zstd and other modern algorithms because of its extreme compression performance. That's why I decided on lz4 for ccache as well. But since zstd now has the negative (--fast) levels available, it's almost as good as lz4 even for compression, and not having support for several algorithms is good for various reasons, not least documentation.

> From my investigation, it seems that you could simply keep the zlib support (in code) and use zstd where available. I don't think that we need to for instance bundle zstd with ccache, but just use it as a library.

I don't think that we should keep zlib support since it's inferior in all cases. I think that we should bundle (parts of) zstd.

> It also means that it would include support for the manifest files as well

It's on my to do list to introduce the same kind of header for manifest files as well (see the to do list I sent to you in private mail).

@afbjorklund wrote:
> Apparently we dropped the checksum (gzip → zlib) and are now hardcoding (enum) the algorithm ?

No, zlib has a checksum as well, just another slightly weaker one. Yes, the result file header contains information about which algorithm and level was used to compress the file. The motivation for this can be read in ebaff190e.

> So I don't think that #118 or #421 is relevant anymore, and might as well look at COMPR_TYPE_ZSTD

Agreed.

**Comment by jrosdahl** [comment]
Issue description updated after above discussion.

**Comment by afbjorklund** [comment]
> > It also means that it would include support for the manifest files as well
> 
> It's on my to do list to introduce the same kind of header for manifest files as well (see the to do list I sent to you in private mail).

Right, wrote that before I had checked (the todo and the code changes for result)

**Comment by jrosdahl** [comment]
> Right, wrote that before I had checked (the todo and the code changes for result)

Check. I'm actively working on that and some other refactoring of the result file code, so expect some more minor changes to land on master as well soon.

**Comment by afbjorklund** [comment]
Fun fact:

| Algo  | kLOC |
| ----- | ---- |
| lz4   | 6    |
| zlib  | 12   |
| zstd  | 60   |

It would be nice if we had some better way of vendoring libraries than to import the source code ?

**Comment by shawnl** [comment]
lzo is much smaller than even lz4, but you can't compare based on lines of code because there is so much per-processor junk (6K in that case).

**Comment by jrosdahl** [comment]
> It would be nice if we had some better way of vendoring libraries than to import the source code ?

I agree that it would be nice not to have to bundle code. Something like [Meson subprojects](https://mesonbuild.com/Subprojects.html) would be nice.

For autotools, maybe we could make configure bail out if it can't find libzstd and offer a `--with-zstd-from-internet` option that downloads a release archive via wget/curl and unpacks it in the source tree? I guess it's not how configure scripts traditionally work, but it would solve the Travis problem.

**Comment by pavsa** [comment]
or as a git submodule from their repository?

**Comment by jrosdahl** [comment]
> or as a git submodule from their repository?

That won't be helpful for people building from a release archive.

**Comment by afbjorklund** [comment]
Implementation done, and rebased.

**Comment by llunak** [comment]
> For instance one would have to figure out how to install it on Mac and Win, and on Travis...
> i.e. Travis run on Ubuntu 14.04, whereas the "libzstd-dev" package first appeared in 16.04

Travis provides both 14.04 and 16.04, so unless you need to test on 14.04, this is not a problem (and even for 14.04 it's possible to get it from an extra repo, although there's not an official one). Icecream has recently added zstd support and it builds in Travis (including Mac).

**Comment by shawnl** [comment]
El dom., 23 de jun. de 2019 14:13, Luboš Luňák <notifications@github.com>
escribió:

> For instance one would have to figure out how to install it on Mac and
> Win, and on Travis...
> i.e. Travis run on Ubuntu 14.04, whereas the "libzstd-dev" package first
> appeared in 16.04
>
> Travis provides both 14.04 and 16.04, so unless you need to test on 14.04,
> this is not a problem (and even for 14.04 it's possible to get it from an
> extra repo, although there's not an official one). Icecream has recently
> added zstd support
>
Why wasn't distcc ever told about this? What is the documentation of the
protocol. I have zstd patches for distcc, including protocol documentation.

**Comment by llunak** [comment]
> Why wasn't distcc ever told about this?

Why should it? Distcc is practically an unrelated project to Icecream. (And in case you want to discuss this further, -> https://github.com/icecc/icecream/ , this discussion is about ccache.)

**Comment by shawnl** [comment]
El dom., 23 de jun. de 2019 15:13, Luboš Luňák <notifications@github.com>
escribió:

> Why wasn't distcc ever told about this?
>
> Why should it? Distcc is practically an unrelated project to Icecream.
>
You didn't answer either of my questions. You implemented a new protocol,
but did you document it?

**Comment by llunak** [comment]
I've told you what to do if you want to discuss that. It's off-topic here and I don't want to take part in hijacking this discussion.

**Comment by jrosdahl** [comment]
> Travis provides both 14.04 and 16.04, so unless you need to test on 14.04, this is not a problem (and even for 14.04 it's possible to get it from an extra repo, although there's not an official one). Icecream has recently added zstd support and it builds in Travis (including Mac).

Thanks @llunak, that's useful to know. (And thanks for not continuing the discussion about distcc here.)

**Comment by kreuzerkrieg** [comment]
What if you submit a good chunk of `ccache` files to [Squash](https://quixdb.github.io/squash-benchmark/) as new corpus and just see results? Or in case the dataset is too big just roll your own server for running these benchmarks - https://github.com/quixdb/squash-benchmark-web/
