### ISSUE TITLE
Use RocksDB instead of dirs/files hierarchy

### ISSUE THREAD

**Issue by socketpair** [ccache/ccache#422]
Using RocksDB as a disk storage backend will reduce iops greatly.

**Comment by afbjorklund** [comment]
Thank you for your suggestion, this _could_ be a new storage plugin after #414 has been implemented.

I'm personally more looking towards LMDB* than the LevelDB family, mostly for performance reasons...

* http://www.lmdb.tech/bench/inmem/

Basically same reason why Memcached instead of Redis, there's a lot of features ccache doesn't need.

----

Note that *all* memory-mapped based databases are going to have an issue with their startup cost.

With the current forking model of ccache, it is very important that they start up and shut down quickly...

**Comment by socketpair** [comment]
AFAIK RocksDB is the better regarding read and write amplification. For small C files, direct compilation may be even faster than reading many scattered data + writing scattered data (with appropriate fsync()s). So I would benchmark. For example, Ceph storage cluster uses RocksDB for their key-value storage.

**Comment by pavsa** [comment]
> AFAIK RocksDB is the better regarding read and write amplification. For small C files, direct compilation may be even faster than reading many scattered data. Also, writing scattered data (with appropriate fsync()s) is very important too. So I would benchmark. For example, Ceph storage cluster uses RocksDB for their key-value storage. Before that, they used dirs/files hierarchy on XFS.

Wouldn't there be a problem with the opening/closing time cost with these embedded databases? They cannot store anything in memory as they do not run in a separate process. Every time ccache starts, you would need to open the database, then do some transactions, then close it. All the db management will need to happen during the time ccache runs. 

With the file IO, kernel does that work for you. The same with databases that run in a dedicated process (memcached, ...).

There might be one use case for embedded dbs though - #377 - for caching the hashes of already hashed files during single build.

**Comment by socketpair** [comment]
Seems, you are right :( I did not consider startup time.

Possibly, the fastest way is to use some long-running DB over UNIX-socket (redis/memcached/e.t.c)

**Comment by afbjorklund** [comment]
Yes, these are the main reasons why we have the current two databases (and the main reason for memcached is distribution). This is also why investigating a ccache library (or daemon) is interesting in the long run... Then it could keep a lot more state.

**Comment by jrosdahl** [comment]
Thanks for the suggestion! We'll keep it in mind in the future.

**Comment by afbjorklund** [comment]
I don't think it would be that hard to add, the C API looked rather straightforward.

``` C
extern ROCKSDB_LIBRARY_API char* rocksdb_get(
    rocksdb_t* db, const rocksdb_readoptions_t* options, const char* key,
    size_t keylen, size_t* vallen, char** errptr);

extern ROCKSDB_LIBRARY_API void rocksdb_put(
    rocksdb_t* db, const rocksdb_writeoptions_t* options, const char* key,
    size_t keylen, const char* val, size_t vallen, char** errptr);
```

So it _could_ be used instead of the regular DB, similar to redis instead of Memcached...

But they need to wait on the API from #414, rather doing copy/paste of the current code.

**Comment by afbjorklund** [comment]
There is a new secondary storage backend using DBM over RPC now, using https://dbmx.net/tkrzw/

If you want support for RocksDB _explicitly_, it can be configured as a storage engine for Redis with [ardb](https://github.com/yinqiwen/ardb)
