### ISSUE TITLE
Support truly forcing which compiler to use

### ISSUE THREAD

**Issue by SebastianBoe** [ccache/ccache#432]
### Description ###

Hi, ccache chooses the compiler to launch according to the following priority:

```
      # 1. Compiler specified on the command line with an absolute path
      # 2. Compiler specified with the CCACHE_CC env var
      # 3. Compiler specified on the command line with a relative path
```
But I need ccache to force a different compiler even though there is a compiler specified on the command line with an absolute path. So I need this priority:

```
      # 1. Compiler specified with the CCACHE_CC env var
      # 2. Compiler specified on the command line
```

Or a new variable and have this priority:

```
      # 0. Compiler specified with the CCACHE_CC_FORCED env var
      # 1. Compiler specified on the command line with an absolute path
      # 2. Compiler specified with the CCACHE_CC env var
      # 3. Compiler specified on the command line with a relative path
```

For background, the reason for needing this is that I am developing a CMake-based build system, and in CMake I can change the env vars (like CCACHE_CC) on a per-source file basis, but I can't change the compiler, and the compiler must have an absolute path.

I would like to know if a patch that supported either approach would be accepted.

**Comment by jrosdahl** [comment]
(Note: `CCACHE_CC` is a deprecated alias of `CCACHE_COMPILER`.)

I think that it would be reasonable to let `CCACHE_COMPILER` have highest priority even in the absolute path case. Such a patch would likely be accepted, especially if it comes with a suitable test case. :slightly_smiling_face:

**Comment by SebastianBoe** [comment]
>  Such a patch would likely be accepted, especially if it comes with a suitable test case. 

Great, thank you for the reply.

**Comment by mumpitzstuff** [comment]
You could set the compiler path before cmake is started with: ccache --set-config=compiler=<path>/gcc
