### ISSUE TITLE
Support kyototycoon backend

### ISSUE THREAD

**Issue by shawnl** [ccache/ccache#435]
https://github.com/alticelabs/kyoto/blob/master/README.md

**Comment by shawnl** [comment]
see https://github.com/ccache/ccache/pull/58

kyototycoon supports memcached protocol

**Comment by jrosdahl** [comment]
Sounds interesting to investigate in the future.

**Comment by afbjorklund** [comment]
PR #58 is closed, but you could use _any_ server that speaks memcached - such as Kyoto Tycoon.

We used Couchbase since it was easier (?) to set up, but more documentation is always good...

**Comment by afbjorklund** [comment]
Related info: https://charlesleifer.com/blog/kyoto-tycoon-in-2019/

There's some interesting features, such as the built-in persistence.

**Comment by afbjorklund** [comment]
Blocked on #414 for API

But now (68e42bd71650d003cb8f01d6572020015ecc2e58) it can use the C++ API:
https://fallabs.com/kyototycoon/api/ (remote)
https://fallabs.com/kyotocabinet/api/ (local)
At any rate, don't need to use memcached.

See also https://github.com/coleifer/kt (python)

**Comment by afbjorklund** [comment]
The new API is completed, so there is nothing stopping doing an implementation also for Kyoto Tycoon/Cabinet...

Seems that it now lives at https://dbmx.net/kyototycoon/ and https://dbmx.net/kyotocabinet/ (decendent of FAL Labs)

However, it seems that when using the Redis backend the same features can be achieved - but more supported ?

Using "[Ardb](https://github.com/yinqiwen/ardb)" provides a similar mapping as KT, using redis (instead of memcached) and RocksDB (instead of KC).

**Comment by shawnl** [comment]
There is a successor to Kyoto cabinet now that should be used, but I would
highly recommend that over redis. These databases are extremely solid, so
much so that Kyoto cabinet only had to release once after a few years
because of a new version of GCC giving a warning (because C++ is a meh
language), but otherwise it was just so stable compared to all those VC
fast fast fast people.

**Comment by afbjorklund** [comment]
It is mostly about the client and the protocol, the server is up to the user.

**Comment by afbjorklund** [comment]
Added a draft, for comparison... Not sure it is noteworthy/available enough, for inclusion ?

But it could be interesting to run some benchmarks, to see how it compares with the others.

It would be a complement to the existing backends:
* storage::secondary::FileStorage (such as NFS)
* storage::secondary::HttpStorage (such as NGINX)
* storage::secondary::RedisStorage (such as Redis)

Replacing the primary storage has not been discussed or considered, it is file-based for now.

Some older comparisons between databases are available here: http://www.lmdb.tech/bench/

**Comment by shawnl** [comment]
El lun., 12 jul. 2021 19:50, Anders Björklund ***@***.***>
escribió:

> Added a draft, for comparison... Not sure it is noteworthy/available
> enough, for inclusion ?
>
> But it could be interesting to run some benchmarks, to see how it compares
> with the others.
>
> It would be a complement to the existing backends:
>
>    - storage::secondary::FileStorage (such as NFS)
>    - storage::secondary::HttpStorage (such as NGINX)
>
>
I think this is the only needed backend. Http is a good protocol (HTTP/1.1
that is). Memcached is also a reasonable protocol, but HTTP is suitable and
the others are shit. Especially NFS is a horrible protocol. Not too
familiar with redis.

**Comment by afbjorklund** [comment]
The main reason for replacing memcached protocol with redis was that it allows values bigger than 1M.
The client is also easier to work with, but it is expected that the overall performance is slightly lower...

It remains to be seen, having implementations available means that benchmarks can be performed ?
Note that you don't _have_ to use NFS (any network file system would do), just that it is a common choice.

**Comment by shawnl** [comment]
All I am saying about NFS is that it is a protocol that comes out of Sun
Microsystems, and it was designed by committee and sucks ass.

**Comment by afbjorklund** [comment]
Looks like Kyoto Tycoon was abandoned again in 2017 (after being left since 2012) ?
There are some minor bug fixes for Kyoto Cabinet, I guess I will add those to the others...

Since it is not available as packages in any distribution, that also makes adoption less likely.

This _could_ become a problem for ccache, which is looking for authentication (while optional)

> Kyoto Tycoon's security model is based on serving clients on a internal network as,
> by design, it provides no authentication mechanism. 
----

While the storage backend "works", I'm not sure if it adds anything over Http and Redis ?

So far it seems that both the protocol (HTTP) and the database (KC) is somewhat slower.
That is, for performance it is better to use Redis and RocksDB*. Otherwise, NGINX/DAV.

\* of course one could also go for (not open-source) Redis Enterprise and Redis on Flash

**Comment by shawnl** [comment]
El mié., 14 jul. 2021 21:58, Anders Björklund ***@***.***>
escribió:

> Looks like Kyoto Tycoon was abandoned again in 2017 (after being left
> since 2012) ?
> There are some minor bug fixes for Kyoto Cabinet, I guess I will add those
> to the others...
>
> Since it is not available as packages in any distribution, that also makes
> adoption less likely.
>
> This *could* become a problem for ccache, which is looking for
> authentication (while optional)
>
> Kyoto Tycoon's security model is based on serving clients on a internal
> network as,
> by design, it provides no authentication mechanism.
>
> ------------------------------
>
> While the storage backend "works", I'm not sure if it adds anything over
> Http and Redis ?
>
> So far it seems that both the protocol (HTTP) and the database (KC) is
> somewhat slower.
> That is, for performance it is better to use Redis and RocksDB*.
> Otherwise, NGINX/DAV.
>
Yes, http and dav are great protocols, and the Kyoto libre family of
software is a great backend for that. Memcached is also a great protocol.
If you want security I think wireguard would be a reasonable way to get it,
but that doesn't belong in ccache, but we could help the user set it up.

**Comment by afbjorklund** [comment]
I moved memcached (and memcachedb) into a separate maintenance project:

https://github.com/afbjorklund/memccache

I think the redis protocol is a reasonable substitute for memcached protocol...
Once the new release is out, it would be interesting to run some benchmarks.

----

It is theoretically possible to make a memcached backend also for ccache 4.x.

You could also make a redis pluggable server for Kyoto Tycoon (like [memcached](https://dbmx.net/kyototycoon/spex.html#tips_pluggableserver))

But it is unlikely that memcachedb (or lz4) will make their way back into master.
The theory is that RocksDB and Zstandard will be "good enough" to replace them.

**Comment by jrosdahl** [comment]
Closing this now. Since Ccache will support HTTP and Redis protocols it should be possible to use those to access a server that uses Kyoto Cabinet or any other database backend.
