### ISSUE TITLE
Note in autogen.sh refers to autoconf.sh

### ISSUE THREAD

**Issue by chrstphrchvz** [ccache/ccache#449]
In the note added to autogen.sh: https://github.com/ccache/ccache/blob/41ce399ce1a33fd7211754e77fb4a5ddcb1d9eea/autogen.sh#L7-L8

Should it refer to "autogen.sh" rather than a non-existent "autoconf.sh"?

**Comment by jrosdahl** [comment]
Yes, will fix. Thanks!
