### ISSUE TITLE
ccache is ignoring trailing -Wno-error

### ISSUE THREAD

**Issue by brenoguim** [ccache/ccache#451]
### How to reproduce ###
main.cpp:
```
int main() { bool b; return b; }
```

$ ccache g++ -c -Wall -Werror -Wno-error main.cpp

### Actual behavior ###
ccache doesn't seem to pass `-Wno-error` down to the compiler, causing it to fail with:
```
cc1plus: all warnings being treated as errors
```

### Expected behavior ###
Expected compilation to succeed despite warning since `-Wno-error` was passed.

### Environment ###
ccache version 3.7.2
GCC 6.3.0

The issue doesn't happen with ccache 3.2.4
...

**Comment by jrosdahl** [comment]
Thanks for the report.

This is a regression in 3.7.2: a side effect of 5d8585b588fb is that `-Werror ... -Wno-error` will be passed as  `-Wno-error ... -Werror` to the compiler.
