### ISSUE TITLE
Empty/nonexisting cache dir not created/populated properly

### ISSUE THREAD

**Issue by hhoffstaette** [ccache/ccache#452]
### How to reproduce ###

1. update to 3.7.2
2. delete cache dir
3. build using ccache

### Actual behavior ###

The cache dir is created but not populated properly; only the first level of directories
is created (i.e. cachedir/0, cachedir/1 etc.); secondary directories and the CACHEDIR.TAG
are not created or written, hence no caching happens.

### Expected behavior ###

Properly created cachedir hierarchy & cached build artefacts.

### Environment ###

Found this after updating to 3.7.2 on Gentoo. Existing cachedirs seem to work fine
with 3.7.2. After nuking my cache dirs I wondered why a package was no longer
being cached when building. Downgrading to 3.7.1 immediately fixed the problem.

**Comment by afbjorklund** [comment]
Cannot reproduce this, could it be something with different umask settings or something ?

No obvious changes between 3.7.1 and 3.7.2 that should explain this either: ([Compare](https://github.com/ccache/ccache/compare/v3.7.1...ccache:v3.7.2))

**Comment by hhoffstaette** [comment]
Nothing else changed; all I can tell you is that 3.7.2 does not properly create new cache dirs, while it immediately started fixing itself & worked after downgrading. Took me quite a while to figure out since existing properly initialized cachedirs seem to work.

**Comment by afbjorklund** [comment]
Do you have any special ccache configuration, it (`v3.7.2`) creates all the directories here.

```
/tmp/ccache/
├── 0
│   ├── 3
│   │   └── cbbe6d1710a5fca97fe7cc5fcfea85-188.manifest
│   └── stats
├── 1
│   ├── 0
│   │   └── 066a3f1308f635a823b92939c8a3de-17195.o
│   ├── CACHEDIR.TAG
│   └── stats
├── ccache.conf
└── tmp

5 directories, 6 files
```

With the default configuration, just changed the `CCACHE_DIR` and did a test compile.

**Comment by hhoffstaette** [comment]
Nothing special:
```
$cat /var/tmp/portage/.ccache/ccache.conf 
cache_dir=/var/cache/ccache/portage
max_size = 1G
```
The file is used properly and has been working fine since I started using ccache.

**Comment by afbjorklund** [comment]
Yeah, that does look like a pretty vanilla configuration - just a slightly smaller max size.

Mystery 🤔

**Comment by afbjorklund** [comment]
Can you set the CCACHE_DIR to something new and set CCACHE_LOGFILE too

Then do a compilation or two, and see if there is anything being printed to the log ?

**Comment by hhoffstaette** [comment]
Well, crap. Trying to reproduce this with my user (instead of the system's build system) seems to work, after emptying the cache dir and building a dummy .c it is properly populated with both 3.7.1 and 3.7.2. I'll change the title and see if I can find what's really going on.

**Comment by hhoffstaette** [comment]
> Can you set the CCACHE_DIR to something new and set CCACHE_LOGFILE too

Not easily due to the how ccache is integrated with portage (Gentoo's package manager).
There *might* be a chance that this is caused by umasks (since portage runs in a sandbox), however all this used to work fine before cleaning out the cache dirs. It would be helpful if the initialization process (say --clear or --zero-stats) would initialize everything properly right away, not just halfway.

**Comment by hhoffstaette** [comment]
So apparently this really was a sandbox/umask/permissions problem. Sorry for the false alarm & thanks for the help.
