### ISSUE TITLE
Test suite fails on Apple Mojave with Xcode 11 command line tools 

### ISSUE THREAD

**Issue by 00003481** [ccache/ccache#468]
run a normal installation ...
sh autogen.sh
configure
make
make check

second stage of make check fails with the usual clang error 
  TEST     ../ccache.git/test/run
WARNING: Compiler gcc not supported (version: Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1) -- not running tests

rerun using

[enrico@enrico-mbp ccache.bin]$CC=clang ../ccache.git/test/run
Compiler:         clang (/usr/bin/clang)
Compiler version: Apple clang version 11.0.0 (clang-1100.0.33.8)
CUDA compiler:    not available

Running test suite base....................................................................
Running test suite nocpp2....................................................................
Running test suite cpp1.
Running test suite multi_arch..
Running test suite serialize_diagnostics...
Running test suite sanitize_blacklist...
Running test suite debug_prefix_map.dwarfdump: Unknown command line argument '-r0'.  Try: '/Library/Developer/CommandLineTools/usr/bin/dwarfdump -help'
dwarfdump: Did you mean '-r'?
dwarfdump: Unknown command line argument '-r0'.  Try: '/Library/Developer/CommandLineTools/usr/bin/dwarfdump -help'
dwarfdump: Did you mean '-r'?

FAILED

Test suite:     debug_prefix_map
Test case:      Mapping of debug info CWD
Failure reason: Relocation (dir) not found in test.o

ccache -s:
cache directory                     /Users/enrico/Downloads/Darwin/ccache.bin/testdir.2038/.ccache
primary config                      /Users/enrico/Downloads/Darwin/ccache.bin/testdir.2038/ccache.conf
secondary config (readonly)         
stats updated                       Sun Sep 15 19:36:30 2019
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                             1
cache hit rate                      0.00 %
cleanups performed                     0
files in cache                         2
cache size                           0.0 MB
max cache size                       5.0 GB

Test data and log file have been left in testdir.2038
[enrico@enrico-mbp ccache.bin]$

WORKS on Apple High Sierra with Xcode 10 ( command line tools - as usual )

Question 1 How to bypass the test to see if there are more quirks

Question 2 is the error a show stopper for the install

Question 3 what can I do to help debug the problem

anyway find attached the testdir.2038 content
[testdir_2038.tar.gz](https://github.com/ccache/ccache/files/3614088/testdir_2038.tar.gz)

best regards
enrico

**Comment by jrosdahl** [comment]
>  (version: Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1)

The above means that https://github.com/ccache/ccache/blob/4642591a0ccb8394e884d18d7c44370b5c2e2e0f/test/run#L333 returns something unexpected on your system. What's the output of `gcc --version` on your system?

> Running test suite debug_prefix_map.dwarfdump: Unknown command line argument '-r0'. Try: '/Library/Developer/CommandLineTools/usr/bin/dwarfdump -help'
> dwarfdump: Did you mean '-r'?

This means that

https://github.com/ccache/ccache/blob/4642591a0ccb8394e884d18d7c44370b5c2e2e0f/test/run#L117

doesn't work. What's the output of `xcrun dwarfdump -help`?

> Question 1 How to bypass the test to see if there are more quirks

You can remove the test suites from "all_suites" in `test/run`, or you can comment out individual test cases in `test/suites/*.bash`.

> Question 2 is the error a show stopper for the install

Probably not.

> Question 3 what can I do to help debug the problem

You'll can add debug messages in the test scripts, or you can run something like `bash -x test/run` to get a log of the commands that are actually run.

**Comment by 00003481** [comment]
Follow on...

I was able to bypass the failing test by removing it from the all_suites list

seems that XCODE and  friends enforce the rule of the man page for dwarfdump  -r N
fixed the run script changing -r0 to -r 0, still it chokes 

here is the log 

[enrico@enrico-mbp ccache.git]$CC=clang ./test/run
Compiler:         clang (/usr/bin/clang)
Compiler version: Apple clang version 11.0.0 (clang-1100.0.33.8)
CUDA compiler:    not available

Running test suite base....................................................................
Running test suite nocpp2....................................................................
Running test suite cpp1.
Running test suite multi_arch..
Running test suite serialize_diagnostics...
Running test suite sanitize_blacklist...
Running test suite debug_prefix_map.
FAILED

Test suite:     debug_prefix_map
Test case:      Mapping of debug info CWD
Failure reason: Relocation (dir) not found in test.o

ccache -s:
cache directory                     /Users/enrico/Downloads/Darwin/ccache.git/testdir.77779/.ccache
primary config                      /Users/enrico/Downloads/Darwin/ccache.git/testdir.77779/ccache.conf
secondary config (readonly)         
stats updated                       Sun Sep 15 22:29:57 2019
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                             1
cache hit rate                      0.00 %
cleanups performed                     0
files in cache                         2
cache size                           0.0 MB
max cache size                       5.0 GB

Test data and log file have been left in testdir.77779

find attached the content of testdir.77779

[testdir_77779.tar.gz](https://github.com/ccache/ccache/files/3614261/testdir_77779.tar.gz)


I am not proficient in bash 


what does the statement 
if ! objdump_cmd test.o | grep_cmd "dir" src/test.c >/dev/null 2>&1; then
try to achieve

looks like ( but I might be wrong ) that the statement passed two arguments to the grep_cmd,
but for APPLE only one is processed

**Comment by 00003481** [comment]
I will post a fix after having tested on
Mojave XCODE 11
High Sierra XCODE 10
El Capitan XCODE 8

**Comment by 00003481** [comment]
fixed in my latest pull request #469

**Comment by jrosdahl** [comment]
Please keep this bug open until it has been fixed.

**Comment by jrosdahl** [comment]
@00003481: Can this issue be closed now after 28c27dad8a5f or is something more needed?

**Comment by 00003481** [comment]
Yes the issue can be closed,

To be sure I just rerun everything from scratch

Ccache at commit 1e5a684058e99ba4cec3c5da80226aca8d8fac0f

Mojave   10.14.6

Xcode 11.0.0 

Command Line Tools 11.0.0 

Ccache build and all the tests run to success 

Using clang 9.0.0 from llvm.org <http://llvm.org/> 

Ccache builds, but the test debug_prefix_map fails 

Rerunning the test without  debug_prefix_map     runs to success

I am investigating

Enrico
