### ISSUE TITLE
Building aosp-10 bionic leads to ld.lld: error: undefined symbol: stpcpy_a9

### ISSUE THREAD

**Issue by stefanhh0** [ccache/ccache#489]
### How to reproduce ###

1. To set up the basic build environment have look at the build guide here:
https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-10-0-0 you have to follow the instructions to:
https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-10-0-0#tutorial-step-3
2. tutorial-step-4 and following will be handled by my script. Execute the shell script contained in [build-4.14-ccache.tar.gz](https://github.com/ccache/ccache/files/3834599/build-4.14-ccache.tar.gz) 
build script updated: Nov 12 07:00

### Actual behavior ###

```
[ 66% 72657/109596] //bionic/libc:libc link libc.so [arm]
FAILED: out/soong/.intermediates/bionic/libc/libc/android_arm_armv8-a_cortex-a73_core_shared_com.android.runtime.debug/unstripped/libc.so
prebuilts/clang/host/linux-x86/clang-r353983c/bin/clang++  @out/soong/.intermediates/bionic/libc/libc/android_arm_armv8-a_cortex-a73_core_shared_com.android.runtime.debug/unstripped/libc.so.rsp -Wl,--whole-archive  out/soong/.intermediates/external/jemalloc_new/libjemalloc5/android_arm_armv8-a_cortex-a73_core_static_com.android.runtime.debug/libjemalloc5.a out/soong/.intermediates/bionic/libc/libc_init_dynamic/android_arm_armv8-a_cortex-a73_core_static_com.android.runtime.debug/libc_init_dynamic.a out/soong/.intermediates/bionic/libc/libc_common_shared/android_arm_armv8-a_cortex-a73_core_static_com.android.runtime.debug/libc_common_shared.a -Wl,--no-whole-archive  out/soong/.intermediates/bionic/libdl/libdl_android/android_arm_armv8-a_cortex-a73_core_static_com.android.runtime.debug/libdl_android.a prebuilts/clang/host/linux-x86/clang-r353983c/lib64/clang/9.0.3/lib/linux/libclang_rt.builtins-arm-android.a prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/lib/libatomic.a out/soong/.intermediates/build/soong/libgcc_stripped/android_arm_armv8-a_cortex-a73_core_static_com.android.runtime.debug/libgcc_stripped.a out/soong/.intermediates/bionic/linker/ld-android/android_arm_armv8-a_cortex-a73_core_shared_com.android.runtime.debug/ld-android.so out/soong/.intermediates/bionic/libdl/libdl/android_arm_armv8-a_cortex-a73_core_shared_com.android.runtime.debug/libdl.so  -o out/soong/.intermediates/bionic/libc/libc/android_arm_armv8-a_cortex-a73_core_shared_com.android.runtime.debug/unstripped/libc.so -nostdlib -Wl,--gc-sections -shared -Wl,-soname,libc.so -target armv7a-linux-androideabi -Bprebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--build-id=md5 -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined-version -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_stripped.a -fuse-ld=lld -Wl,--pack-dyn-relocs=none -Wl,--no-undefined -Wl,--icf=safe -Wl,--hash-style=gnu -Wl,-m,armelf -Wl,-z,muldefs -Wl,--hash-style=both  -Wl,--version-script,out/soong/.intermediates/bionic/libc/libc.arm.map/gen/libc.arm.map -Wl,--symbol-ordering-file,bionic/libc/symbol_ordering
ld.lld: error: undefined symbol: strcpy_a9
>>> referenced by dynamic_function_dispatch.cpp:0 (bionic/libc/arch-arm/dynamic_function_dispatch.cpp:0)
>>>               dynamic_function_dispatch.o:(strcpy) in archive out/soong/.intermediates/bionic/libc/libc_common_shared/android_arm_armv8-a_cortex-a73_core_static_com.android.runtime.debug/libc_common_shared.a

ld.lld: error: undefined symbol: stpcpy_a9
>>> referenced by dynamic_function_dispatch.cpp:0 (bionic/libc/arch-arm/dynamic_function_dispatch.cpp:0)
>>>               dynamic_function_dispatch.o:(stpcpy) in archive out/soong/.intermediates/bionic/libc/libc_common_shared/android_arm_armv8-a_cortex-a73_core_static_com.android.runtime.debug/libc_common_shared.a
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
06:59:15 ninja failed with: exit status 1
```
It was working fine when I was using ccache version 3.7.4-1 on Debian testing

### Expected behavior ###

The build should run without any error. When setting USE_CCACHE=0 the build succeeds.

### Environment ###

ccache version 3.7.5-1 on Debian testing. 

The debian maintainer of the ccache package requested to open as well a bug here. See as well the debian bug:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944399
The bug was originally reported by me here:
https://github.com/sonyxperiadev/bug_tracker/issues/492

The sources and build uses quite some space:
stefan@mars:~/android/source$ du -hs .
258G    .

ccache stats after initial build (ccache was cleared before):
stefan@mars:~/android/source$ ccache -s
cache directory                     /home/stefan/.ccache
primary config                      /home/stefan/.ccache/ccache.conf
secondary config      (readonly)    /etc/ccache.conf
stats updated                       Tue Nov 12 06:29:41 2019
stats zeroed                        Sat Nov  9 00:52:50 2019
cache hit (direct)                   194
cache hit (preprocessed)            5523
cache miss                         28697
cache hit rate                     16.61 %
called for link                        1
called for preprocessing              26
unsupported code directive             1
cleanups performed                     0
files in cache                     90898
cache size                          13.6 GB
max cache size                      53.7 GB

Building it on a 4 core machine (Intel(R) Core(TM) i5-6300HQ CPU @ 
2.30GHz) takes 02:24:20.

The full stdout/stderr output of the build script including the error message: [build.log.tar.gz](https://github.com/ccache/ccache/files/3834636/build.log.tar.gz)

Hope you can reproduce the issue. If you need any assistance I'd be happy to help.

Best regards
Stefan

**Comment by jrosdahl** [comment]
This turned out to be a interesting bug. It only manifests itself when using the opt-in `sloppiness = file_macro` mode, which the Android build apparently does by default. See the commit message of 404eedde2b8c for details.

**Comment by jrosdahl** [comment]
Fixed in v3.7.6.

**Comment by stefanhh0** [comment]
@jrosdahl thanks a lot for fixing this so quickly. Great job!

**Comment by svillar** [comment]
JFR I submitted https://github.com/lilles/icecc-chromium/pull/9 a bit ago after hitting the very same issue building Chromium
