### ISSUE TITLE
Chocolatey package for ccache

### ISSUE THREAD

**Issue by fireundubh** [ccache/ccache#490]
### Description ###
Can you [create a Chocolatey package](https://chocolatey.org/docs/createpackages) for ccache?

If you get a Chocolatey package up, we'll be a step closer to [getting ccache pre-installed in GitHub Actions' virtual environments](https://github.com/actions/virtual-environments).

**Comment by jrosdahl** [comment]
Doesn't sound like a bad idea. It would however require somebody (≠ me) to take a more active role in driving and maintaining Windows aspects of ccache. See also #447.

**Comment by cristianadam** [comment]
You can have a look at my [CMake fork](https://github.com/cristianadam/ccache). I just added a Windows Github actions  build. I will have a look at having a release binary package.

**Comment by rkitover** [comment]
I would suggest making a nuget package instead, and using the nuget wrapper for chocolatey.

If it were in the nuget repositories, installing it from e.g. cmake would be trivial.

**Comment by jrosdahl** [comment]
See also https://github.com/chocolatey-community/chocolatey-package-requests/issues/626.

**Comment by Xav83** [comment]
The chocolatey package is now validated and available [here](https://chocolatey.org/packages/ccache) 😄

**Comment by jrosdahl** [comment]
OK, thanks for the update. I've added a link to it on https://ccache.dev/download.html now.

**Comment by cristianadam** [comment]
In the meantime Microsoft has announced their own package manager - winget. 

The list of packages is here https://github.com/microsoft/winget-pkgs/tree/master/manifests, cmake is there. Would be nice to have ccache there too.

**Comment by Xav83** [comment]
@cristianadam You may want to create a new issue for that 😉
