### ISSUE TITLE
Result line not always logged

### ISSUE THREAD

**Issue by dyadav7** [ccache/ccache#500]
Hi

The file.o.ccache-log generated in environment CCACHE_DEBUG=1 shows the result of ccache. The status line is missing when CCACHE_READONLY is also set to 1.  
If CCACHE_DEBUG is enabled then "Result " status line should always be added to log file in all the cases. This will help in finding the cache status easily using grep command.

Sample status line:

```
[2020-01-01T07:27:53.978542 37482] Result: cache hit (direct)
[2020-01-02T07:25:48.496956 24117] Result: cache miss
[2020-01-01T07:27:53.842134 37150] Result: cache hit (preprocessed)
```

Regards
Deepak

**Comment by jrosdahl** [comment]
Thanks for the suggestion! The result line is actually only missing when there is a cache miss (and read-only mode is enabled), not for cache hits. There are other cases where no result line is logged as well. I'll try to go through them all and fix.
