### ISSUE TITLE
CCACHE_DIRECT cannot be set to "false" anymore

### ISSUE THREAD

**Issue by sdettmer** [ccache/ccache#502]
Hi,

since a while CCACHE_DIRECT cannot be set to false anymore. If was working with version 3.2.4 and as a team mate reports 3.2.7, but not with 3.5.1a and also not with most recent 3.7.7. Man page tells that CCACHE_DIRECT must be "true" or "false", with true being default, but setting to "false" leads to an error `ccache: error: invalid boolean environment variable value "false"`.

How to reproduce:

```
$ tar xzvf ccache-3.7.7.tar.gz
$ cd ccache-3.7.7/
$ ./configure
$ nice make -j8

# works:
$ echo "int main() { return 0; }" > true.c
$ ./ccache gcc -c true.c

# Looking up CCACHE_DIRECT in man page:
$ man doc/ccache.1 |grep CCACHE_DIRECT
       direct_mode (CCACHE_DIRECT or CCACHE_NODIRECT, see Boolean values above)

# But does not work:
$ CCACHE_DIRECT=false ./ccache gcc -c true.c
ccache: error: invalid boolean environment variable value "false"
``` 

As a workaround, `CCACHE_NODIRECT=true` probably could be used, but I did not yet test whether it works. What seems incorrect is that there is no error when using invalid values as for example:

```
$ CCACHE_NODIRECT=error ./ccache gcc -c true.c
# no error message is printed
```

**Comment by sdettmer** [comment]
Just in case it helps,
I ran "git bisect" to find the commit causing the effect: e7906f46 seems to be the first "bad" commit:

```
$ git clone https://github.com/ccache/ccache.git
$ cd ccache

# Note: I was unable to build master, because with libb2 --with-libb2-from-internet does not 
#  compile. When I extract, configure and make the downloaded version, it does work, since libb2 
#  configure detects correctly that my compiler needs -std=c99, but when called from ccache, it does 
#  not. Then gcc bails out with an error that selected standard does not allow "for (int x...") and 
#  suggests passing -std=c99.

$ cat ./check-direct.sh
./autogen.sh || exit 125
./configure -q || exit 125
make -j24 || exit 125
CCACHE_DIRECT=false ./ccache gcc -c true.c || exit 1
echo "This version may work"

$ git checkout v3.7.7
$ ./check-direct.sh
[...]
ccache: error: invalid boolean environment variable value "false"

$ git bisect start
$ git bisect bad

$ git checkout v3.2.7
$ ./check-direct.sh
[...]
This version may work

$ git bisect good
Bisecting: 380 revisions left to test after this (roughly 9 steps)

$ git bisect run ./check-direct.sh
[...]
Bisecting: 189 revisions left to test after this (roughly 8 steps)
[...]

e7906f4682f4a56e1cfca7581845a7e0b5b7ce65 is the first bad commit
commit e7906f4682f4a56e1cfca7581845a7e0b5b7ce65
Author: Mostyn Bramley-Moore <mostyn@antipode.se>
Date:   Fri Jun 23 20:20:54 2017 +0200

    Fail if boolean env vars are set with common negative strings
    
    Boolean environment variables have strange semantics: if the variable
    is set then the configuration setting is considered "true".  This means
    users can easily be mistaken that eg CCACHE_DISABLE=false means that
    the "disable" setting is set to false.
    
    To avoid too much backwards-incompatibility, we now exit with an error if
    some common negative-sounding (case-insensitive) values:
    "0", "false", "disable", "no".
    
    All other values (including the empty string) are still considered to mean
    "true".
    
    Resolves https://github.com/ccache/ccache/issues/182

:100644 100644 6205667d03ef9d8ea2727accc819819f2937e01a 01dafae2fd5c49a08b71f6f367bf2574c18dc45e M      MANUAL.txt
:100644 100644 1b94f119afa9f4c23ea8ab450c180cb5f1aedc10 c46d555430aa9b57bbdef4891b8bd77e065fb917 M      NEWS.txt
:100644 100644 cfa2874af096d4de319f4ba3a9842727b6714bb6 6a0a9e66f5e44850de3d787c7071c9dd8471e9af M      conf.c
:040000 040000 36a279e73a6b048310836f9c8fc473a6b7ff2ebc 45a410e52f797e93f1e2e4cf37ebdf86f33d097c M      test
bisect run success
```
 
just in case it helps

**Comment by sdettmer** [comment]
Ohh. My. God.

I missed the documentation section:

>    Boolean values
>       Some settings are boolean values (i.e. truth values). In a configuration file, such values must be set to
>       the string true or false. **For the corresponding environment variables, the semantics are a bit different**: a
>       set environment variable means “true” regardless of the value (even if set to the empty string), and an
>       unset environment variable means “false”. **Each boolean environment variable also has a negated form starting
>       with CCACHE_NO**. For example, CCACHE_COMPRESS can be set to force compression and CCACHE_NOCOMPRESS can be
>       set to force no compression.

So 

>        direct_mode (CCACHE_DIRECT) [boolean]
>           If true, the direct mode will be used. The default is true. See THE DIRECT MODE.

confused me, since CCACHE_DIRECT is not boolean (but "true if set").

I propose to consider to rephrase as:

>        direct_mode  [boolean] (CCACHE_DIRECT|CCACHE_NODIRECT)
>          If true, the direct mode will be used. The default is true. See THE DIRECT MODE.

or similar.

**Comment by sdettmer** [comment]
I think the error message is misleading. Apparently this issue is related to #182

**Comment by sdettmer** [comment]
Could the error message `invalid boolean environment variable value`  be changed?

(I cannot push for a pull request) because company network blocks outside SSH)

on v3.7.7 commit 26912b28

```
commit 86df2d296ee77e1c2cc51c2b68847efb41c48d10
Author: Steffen Dettmer <steffen.dettmer@rail.bombardier.com>
Date:   Tue Jan 7 12:21:00 2020 +0100

    Improving error message when environment variable is set to a boolean false

diff --git a/src/conf.c b/src/conf.c
index 92fe34b..17666df 100644
--- a/src/conf.c
+++ b/src/conf.c
@@ -40,7 +40,7 @@ find_env_to_conf(const char *name)
 static enum handle_conf_result
 handle_conf_setting(struct conf *conf, const char *key, const char *value,
                     char **errmsg, bool from_env_variable, bool negate_boolean,
-                    const char *origin)
+                    const char *origin, const char *env_name)
 {
        const struct conf_item *item = find_conf(key);
        if (!item) {
@@ -57,7 +57,8 @@ handle_conf_setting(struct conf *conf, const char *key, const char *value,
                // enabled.
                if (str_eq(value, "0") || strcasecmp(value, "false") == 0
                    || strcasecmp(value, "disable") == 0 || strcasecmp(value, "no") == 0) {
-                       fatal("invalid boolean environment variable value \"%s\"", value);
+                       fatal("invalid environment variable value \"%s\" for \"CCACHE_%s\"\n"
+               "\t(did you mean setting \"CCACHE_NO%s=true\"?)", value, env_name, env_name);
                }
 
                bool *boolvalue = (bool *)((char *)conf + item->offset);
@@ -218,7 +219,7 @@ conf_read(struct conf *conf, const char *path, char **errmsg)
                bool ok = parse_line(buf, &key, &value, &errmsg2);
                if (ok && key) { // key == NULL if comment or blank line.
                        hcr =
-                               handle_conf_setting(conf, key, value, &errmsg2, false, false, path);
+                               handle_conf_setting(conf, key, value, &errmsg2, false, false, path, "");
                        ok = hcr != HANDLE_CONF_FAIL; // unknown is OK
                }
                free(key);
@@ -275,7 +276,7 @@ conf_update_from_environment(struct conf *conf, char **errmsg)
                char *errmsg2 = NULL;
                enum handle_conf_result hcr = handle_conf_setting(
                        conf, env_to_conf_item->conf_name, q, &errmsg2, true, negate,
-                       "environment");
+                       "environment", env_to_conf_item->env_name);
                if (hcr != HANDLE_CONF_OK) {
                        *errmsg = format("%s: %s", key, errmsg2);
                        free(errmsg2);
```

**Comment by sdettmer** [comment]
This changes error message for noobs like me to be:
```
ccache: error: invalid environment variable value "false" for "CCACHE_DIRECT"
        (did you mean setting "CCACHE_NODIRECT=true"?)
```

What do you think?

**Comment by jrosdahl** [comment]
> Could the error message invalid boolean environment variable value be changed?
> [...]
> This changes error message for noobs like me to be:
>
> ccache: error: invalid environment variable value "false" for "CCACHE_DIRECT"
>         (did you mean setting "CCACHE_NODIRECT=true"?)
> What do you think?

Yes, improving the error message sounds like a good idea, and also the manual as you suggested. Thanks!

I won't apply your patch as is though since it doesn't work well for the `CCACHE_NODIRECT=0` case, but I'll implement a variant of it and touch up the docs.

**Comment by jrosdahl** [comment]
> > ```
> >    direct_mode (CCACHE_DIRECT) [boolean]
> >       If true, the direct mode will be used. The default is true. See THE DIRECT MODE.
> > ```
> 
> confused me, since CCACHE_DIRECT is not boolean (but "true if set").
> 
> I propose to consider to rephrase as:
> 
> > ```
> >    direct_mode  [boolean] (CCACHE_DIRECT|CCACHE_NODIRECT)
> >      If true, the direct mode will be used. The default is true. See THE DIRECT MODE.
> > ```
> 
> or similar.

That was already done in ccache 3.2.5 (see f6dfd815f) some four years ago. Does that formulation look good enough?

**Comment by jrosdahl** [comment]
> ```
> # Note: I was unable to build master, because with libb2 --with-libb2-from-internet does not 
> #  compile. When I extract, configure and make the downloaded version, it does work, since libb2 
> #  configure detects correctly that my compiler needs -std=c99, but when called from ccache, it does 
> #  not. Then gcc bails out with an error that selected standard does not allow "for (int x...") and 
> #  suggests passing -std=c99.
> ```

Reported as #505.
