### ISSUE TITLE
ccache find the wrong cache

### ISSUE THREAD

**Issue by vaneyli** [ccache/ccache#504]
I'm using the ccache version 3.4.2+15_gc90c1ef.   I find a bug:
1:  There are two files:  main.c   and b_test/head.h
2:  Run ccache gcc main.c -Ia_test/ -Ib_test/ -c -o main.o.   It works well.
3:  I add an error file:   a_test/head.h
4:  Run gcc main.c -Ia_test/ -Ib_test/ -c -o main.o.   It failed for the error a_test/head.h.
 But the step 2 still works well for it thought that gcc still use the b_test/head.h

Thanks

**Comment by ahufan** [comment]
.
├── a_test
│   └── test.h.bak
├── b_test
│   └── test.h
└── main.c

test.h.bak:
int myadd(int a, int b, int c);

b_test/test.h:
int myadd(int a, int b);

main.c:
#include <stdio.h>
#include "test.h"

int main()
{
	printf("1+2=%d\n",myadd(1,2));

	return 0;
}

command:
1. ccache gcc main.c -Ia_test/ -Ib_test/ -c -o main.o
2. mv a_test/test.h.bak a_test/test.h
3. ccache gcc main.c -Ia_test/ -Ib_test/ -c -o main.o

step 3 will hit dirtect. but run "gcc main.c -Ia_test/ -Ib_test/ -c -o main.o" will be error.

**Comment by jrosdahl** [comment]
Thanks for the bug report.

This is not a bug but a known and documented limitation of ccache. From https://ccache.dev:

>There are some known corner cases where ccache can fail to detect that source code files have changed since a previous compilation. These limitations are listed under [caveats](https://ccache.dev/manual/latest.html#_caveats) in the manual. 

The [caveats section in the manual](https://ccache.dev/manual/latest.html#_caveats) in turn says this:

> The direct mode fails to pick up new header files in some rare scenarios. See THE DIRECT MODE above.

The [direct mode section](https://ccache.dev/manual/latest.html#_the_direct_mode) then says:

> There is a catch with the direct mode: header files that were used by the compiler are recorded, but header files that were not used, but would have been used if they existed, are not. So, when ccache checks if a result can be taken from the cache, it currently can’t check if the existence of a new header file should invalidate the result. In practice, the direct mode is safe to use in the absolute majority of cases.

If you would like ccache to handle this corner case you will have to disable the direct mode.

Do you have any suggestion on how to make the documentation clearer?
