### ISSUE TITLE
Building --with-libb2-from-internet fails if the C compiler needs -std=c99

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#505]
### How to reproduce ###

1. Configure  with `./configure --with-libb2-from-internet CC=gcc-4.7`.
2. Build with `make`.

### Actual behavior ###

Failed build:

```
[...]
make[3]: Entering directory '.../ccache/src/third_party/libb2/src'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc-4.7 -DHAVE_CONFIG_H -I.  -DSUFFIX=  ../src/  -fopenmp  -O3 -march=native  -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -fopenmp -MT libb2_la-blake2sp.lo -MD -MP -MF .deps/libb2_la-blake2sp.Tpo -c -o libb2_la-blake2sp.lo `test -f 'blake2sp.c' || echo './'`blake2sp.c
libtool: compile:  gcc-4.7 -DHAVE_CONFIG_H -I. -DSUFFIX= ../src/ -fopenmp -O3 -march=native -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -fopenmp -MT libb2_la-blake2sp.lo -MD -MP -MF .deps/libb2_la-blake2sp.Tpo -c blake2sp.c -o libb2_la-blake2sp.o
blake2sp.c: In function ‘blake2sp_init’:
blake2sp.c:74:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
blake2sp.c:74:3: note: use option -std=c99 or -std=gnu99 to compile your code
```

### Expected behavior ###

Successful build.

### Environment ###

* ccache master (87a4c8e6 at the time of writing).
* GCC 4.7.

**Comment by AlexanderLanin** [comment]
I came across the same problem in #573 and just bumped required C version to 99 as blake doesn't compile without it. This should support everything from gcc 4.5 which is 10 years old next week.

**Comment by jrosdahl** [comment]
> I came across the same problem in #573 and just bumped required C version to 99 as blake doesn't compile without it. This should support everything from gcc 4.5 which is 10 years old next week.

That's fine since ccache already requires C99 [since version 3.3](https://ccache.dev/releasenotes.html#_ccache_3_3).
