### ISSUE TITLE
Changing the value to -o results in ccache miss with option -MMD

### ISSUE THREAD

**Issue by dyadav7** [ccache/ccache#523]
### How to reproduce ###

1. g++ -MMD -o <dir1>/file.o -c file.cpp
2. Change the path passed to -o in above command - g++ -MMD -o <dir2>/file.o -c file.cpp
3. The above command results in ccache miss. It should also results in ccache hit.

### Actual behavior ###

ccache miss happened.

### Expected behavior ###

I wanted the ccache hit in 2nd g++ command line.

### Environment ###

ccache version 3.6

Copyright (C) 2002-2007 Andrew Tridgell
Copyright (C) 2009-2019 Joel Rosdahl

...

**Comment by jrosdahl** [comment]
Thanks for the bug report.

This is not a bug but intended behavior since `g++ -MMD -o a.o -c file.cpp` and  `g++ -MMD -o b.o -c file.cpp` don't produce the same result: `a.d` and `b.d` will be different.

**Comment by jrosdahl** [comment]
I wrote a new issue for improving this: #524.
