### ISSUE TITLE
Parameter -o=K=V does not work (--set-config=K=V works)

### ISSUE THREAD

**Issue by mumpitzstuff** [ccache/ccache#529]
### How to reproduce ###

1. ccache -o=disable=false

### Actual behavior ###

ccache: error: unknown configuration option ""

### Expected behavior ###

should work

### Environment ###

ccache version 3.7.7

### Workaround ###
ccache --set-config=disable=false

works like expected

**Comment by jrosdahl** [comment]
There are three equivalent supported spellings for this particular option:

1. `-o K=V`
2. `--set-config K=V`
3. `--set-config=K=V`

This means that `-oK=V` doesn't work which actually is the expected and intended behavior. I understand where the confusion comes from, though – the documention:

```
    -o, --set-config=K=V      set configuration item K to value V
```

The reason why the help text looks like that is that it's the standard (or at least common) way for GNU programs to describe options. See for instance `-S, --suffix=SUFFIX` in the [mv(1) man page](http://www.man7.org/linux/man-pages/man1/mv.1.html).

But I actually agree that this format isn't super good. I'll see if I can improve the ccache help text.
