### ISSUE TITLE
Recompression with -X <level> leads to errors on Windows

### ISSUE THREAD

**Issue by mumpitzstuff** [ccache/ccache#530]
### How to reproduce ###

1. ccache -X 6

### Actual behavior ###

In the logfile i can see a lot of such errors:
[.590345 21180] can't rename file C:\workspace\PRP_RH850\.ccache/0/0/bc6fa48a05eef2e131dc61603c637e04686ef5.result.tmp.unknown.21180.FzP5tM to C:\workspace\PRP_RH850\.ccache/0/0/bc6fa48a05eef2e131dc61603c637e04686ef5.result OS returned error: ../src/legacy_util.cpp failed with error 183: Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist.

### Environment ###

master branch

**Comment by jrosdahl** [comment]
I can't reproduce this. Somebody running Windows who can help out?

**Comment by jrosdahl** [comment]
Background: The error message comes from [`x_rename`](https://github.com/ccache/ccache/blob/aa64164acb6caf45e9eb5c3ca563d12ccb67ed3b/src/legacy_util.cpp#L1264) which is in its `_WIN32` version is supposed to remove the destination file before moving the source file to the destination path.

**Comment by mumpitzstuff** [comment]
It seems a backslash is missing here.

PRP_RH850.ccache
must be
PRP_RH850\.ccache

Can it be that \. is interpreted as escaped dot? This would be wrong and could be the reason of the problem.

**Comment by jrosdahl** [comment]
> PRP_RH850.ccache
> must be
> PRP_RH850\.ccache

Not sure I understand. Do you mean that you have set `CCACHE_DIR` to `C:\workspace\PRP_RH850\.ccache`?

What output do you get from `ccache -p`?

**Comment by mumpitzstuff** [comment]
Exactly. `ccache -p` shows me the correct path. I only see the wrong path if I try to run the recompression command (the error is written to the ccache log file). Today I tried to replace all backslashes in all paths of the config with slashes. But recompression seems to be broken somehow anyway. I will try to dive deeper next week.

**Comment by cristianadam** [comment]
I was able to reproduce the issue.

With this patch I was able to get better errors:
```patch
--- src/legacy_util.cpp
+++ src/legacy_util.cpp
@@ -1267,9 +1267,8 @@ x_rename(const char* oldpath, const char* newpath)
   return rename(oldpath, newpath);
 #else
   // Windows' rename() refuses to overwrite an existing file.
-  unlink(newpath); // Not x_unlink, as x_unlink calls x_rename.
   // If the function succeeds, the return value is nonzero.
-  if (MoveFileA(oldpath, newpath) == 0) {
+  if (MoveFileExA(oldpath, newpath, MOVEFILE_REPLACE_EXISTING) == 0) {
     LPVOID lp_msg_buf;
     DWORD dw = GetLastError();
     FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM
```
This meant that the read file was not closed after recompression and then it tried to move it, which on Windows is an error. On *Nix you can get away with it.

The following patch fixes the problem:
```diff
--- src/compress.cpp
+++ src/compress.cpp
@@ -116,6 +116,8 @@ recompress_file(const std::string& stats_file,
   reader->finalize();
   writer->finalize();
 
+  file.close();
+
   uint64_t old_size =
     Stat::stat(cache_file.path(), Stat::OnError::log).size_on_disk();
   atomic_new_file.commit();
```
I'll open a MR shortly.

**Comment by cristianadam** [comment]
One can get binaries from my fork build: https://github.com/cristianadam/ccache/actions/runs/35648553
