### ISSUE TITLE
ccache-3.7.7: make check FAILED CCACHE_NOHASHDIR

### ISSUE THREAD

**Issue by sdettmer** [ccache/ccache#531]
### How to reproduce ###

1. tar xzf ccache-3.7.7.tar.gz
2. cd ccache-3.7.7/
3. ./configure
4. make clean all check

### Actual behavior ###
```
PASSED: 528 assertions, 110 tests, 10 suites
  TEST     ./test/run
Compiler:         gcc -std=gnu99 (/usr/bin/gcc -std=gnu99)
Compiler version: gcc (Debian 4.9.2-10) 4.9.2
CUDA compiler:    not available

Running test suite base...............................
FAILED

Test suite:     base
Test case:      CCACHE_NOHASHDIR
Failure reason: Expected "cache hit (preprocessed)" to be 2, actual 1

ccache -s:
cache directory                     /local/users/sdettmer/work/cmake-toolchain-1.8/ccache-3.7.7/testdir.2864/.ccache
primary config                      /local/users/sdettmer/work/cmake-toolchain-1.8/ccache-3.7.7/testdir.2864/ccache.conf
secondary config      (readonly)    
stats updated                       Thu Feb  6 15:21:09 2020
cache hit (direct)                     0
cache hit (preprocessed)               1
cache miss                             2
cache hit rate                     33.33 %
cleanups performed                     0
files in cache                         2
cache size                           8.2 kB
max cache size                       5.0 GB

Test data and log file have been left in testdir.2864
Makefile:146: recipe for target 'test' failed
make: *** [test] Error 1
```

### Expected behavior ###

All test should pass.

### Environment ###

ccache version 3.7.7
```
$ gcc --version
gcc (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ uname -a
Linux dehetucks3 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux

$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### More Information ###

I cleant cache.log before the (first?) failing test:
```
$ diff -u test/suites/base.bash.dist test/suites/base.bash
--- test/suites/base.bash.dist  2020-02-06 15:19:27.000000000 +0100
+++ test/suites/base.bash       2020-02-06 15:19:33.250741520 +0100
@@ -417,6 +417,7 @@
     # -------------------------------------------------------------------------
     TEST "CCACHE_NOHASHDIR"
 
+    rm -rf ../.ccache/ ../ccache.log
     mkdir dir1 dir2
     cp test1.c dir1
     cp test1.c dir2
```

and in the hope to help diagnostics:

```
$ cd testdir.2864 
$ (cd run/dir1 && /usr/bin/gcc -std=gnu99 -g -E test1.c > E )
$ (cd run/dir2 && /usr/bin/gcc -std=gnu99 -g -E test1.c > E )
$ diff -u run/dir*/E
--- run/dir1/E  2020-02-06 15:26:03.661476213 +0100
+++ run/dir2/E  2020-02-06 15:26:07.045602761 +0100
@@ -1,5 +1,5 @@
 # 1 "test1.c"
-# 1 "/local/users/sdettmer/work/cmake-toolchain-1.8/ccache-3.7.7/testdir.2864/run/dir1//"
+# 1 "/local/users/sdettmer/work/cmake-toolchain-1.8/ccache-3.7.7/testdir.2864/run/dir2//"
 # 1 "<built-in>"
 # 1 "<command-line>"
 # 1 "/usr/include/stdc-predef.h" 1 3 4

$ (cd run/dir1 && /local/users/sdettmer/work/cmake-toolchain-1.8/ccache-3.7.7/ccache /usr/bin/gcc -std=gnu99 -g -E test1.c > CCE )
$ (cd run/dir2 && /local/users/sdettmer/work/cmake-toolchain-1.8/ccache-3.7.7/ccache /usr/bin/gcc -std=gnu99 -g -E test1.c > CCE )

$ diff -u run/dir*/CCE
--- run/dir1/CCE        2020-02-06 15:27:45.069264846 +0100
+++ run/dir2/CCE        2020-02-06 15:27:40.581097317 +0100
@@ -1,5 +1,5 @@
 # 1 "test1.c"
-# 1 "/local/users/sdettmer/work/cmake-toolchain-1.8/ccache-3.7.7/testdir.2864/run/dir1//"
+# 1 "/local/users/sdettmer/work/cmake-toolchain-1.8/ccache-3.7.7/testdir.2864/run/dir2//"
 # 1 "<built-in>"
 # 1 "<command-line>"
 # 1 "/usr/include/stdc-predef.h" 1 3 4
```
```

**Comment by sdettmer** [comment]
$ tar czvf testdir.2864-issue-531.tar.gz testdir.2864

[testdir.2864-issue-531.tar.gz](https://github.com/ccache/ccache/files/4165577/testdir.2864-issue-531.tar.gz)

**Comment by jrosdahl** [comment]
If you apply the following patch and then run the test suite again, what's the output?

```patch
--- a/test/suites/base.bash
+++ b/test/suites/base.bash
@@ -425,15 +425,18 @@ base_tests() {
     CCACHE_NOHASHDIR=1 $CCACHE_COMPILE -c test1.c -g
     expect_stat 'cache hit (preprocessed)' 0
     expect_stat 'cache miss' 1
-    CCACHE_NOHASHDIR=1 $CCACHE_COMPILE -c test1.c -g
+    CCACHE_DEBUG=1 CCACHE_NOHASHDIR=1 $CCACHE_COMPILE -c test1.c -g
     expect_stat 'cache hit (preprocessed)' 1
     expect_stat 'cache miss' 1
 
     cd ../dir2
-    CCACHE_NOHASHDIR=1 $CCACHE_COMPILE -c test1.c -g
+    CCACHE_DEBUG=1 CCACHE_NOHASHDIR=1 $CCACHE_COMPILE -c test1.c -g
     expect_stat 'cache hit (preprocessed)' 2
     expect_stat 'cache miss' 1
 
+    diff -u ../dir1/test1.o.ccache-input-text test1.o.ccache-input-text
+    exit 1
+
     # -------------------------------------------------------------------------
     TEST "CCACHE_NLEVELS"
 
```

**Comment by sdettmer** [comment]
Output on console seem to be same:

Test suite:     base
Test case:      CCACHE_NOHASHDIR
Failure reason: Expected "cache hit (preprocessed)" to be 2, actual 1

ccache -s:
cache directory                     /local/users/sdettmer/work/cmake-toolchain-1.8/ccache-3.7.7-bug/testdir.29793/.ccache
primary config                      /local/users/sdettmer/work/cmake-toolchain-1.8/ccache-3.7.7-bug/testdir.29793/ccache.conf

I attached the testdir.

[testdir.29793-issue-531.tar.gz](https://github.com/ccache/ccache/files/4170970/testdir.29793-issue-531.tar.gz)

**Comment by sdettmer** [comment]
_(ohh ps: I applied your patch on top of my change "rm -rf ../.ccache/ ../ccache.log")_

**Comment by jrosdahl** [comment]
I can reproduce the problem now by having a symlink in the current working directory path. I guess some part of ` /local/users/sdettmer/work/cmake-toolchain-1.8/ccache-3.7.7-bug` is a symlink?

**Comment by sdettmer** [comment]
(I tried to test with Git version, since there is no ccache-3.7.8 yet, but this does not compile for me `blake2s.c:173:3: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code`, gcc (Debian 4.9.2-10) 4.9.2)

**Comment by sdettmer** [comment]
(with master version the error changes to:
```
In file included from src/CacheFile.hpp:23:0,
                 from src/Util.hpp:23,
                 from src/AtomicFile.cpp:21:
src/Stat.hpp: In constructor ‘Stat::Stat()’:
src/Stat.hpp:97:43: error: missing initializer for member ‘stat::st_dev’ [-Werror=missing-field-initializers]
 inline Stat::Stat() : m_stat{}, m_errno(-1)
                                           ^
src/Stat.hpp:97:43: error: missing initializer for member ‘stat::st_ino’ [-Werror=missing-field-initializers]
```
)

**Comment by jrosdahl** [comment]
> (I tried to test with Git version, since there is no ccache-3.7.8 yet, but this does not compile for me `blake2s.c:173:3: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code`, gcc (Debian 4.9.2-10) 4.9.2)

Looks like you have tried a master-based version, but if you want to try what will become 3.7.8 then have a look at the 3.7-maint branch. (The bug on master is tracked in #505, by the way.)

> src/Stat.hpp:97:43: error: missing initializer for member ‘stat::st_dev’ [-Werror=missing-field-initializers]
> inline Stat::Stat() : m_stat{}, m_errno(-1)

This is [a problem with GCC <5](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=36750). To work around it you can disable dev mode with `touch dev_mode_disabled` after `./autogen.sh`.

**Comment by sdettmer** [comment]
Thank you for your support! **I can confirm that the 3-7-maint branch works fine!** Thank you!

_Reproducing the problem with one version **before** the fix:_
```
git checkout 3.7-maint^{/"Closes #531"}^
rm -rf b && ./autogen.sh && mkdir b && ( cd b && ../configure && nice make -j && make check )
...
Test case:      CCACHE_NOHASHDIR
Failure reason: Expected "cache hit (preprocessed)" to be 2, actual 1
```

_Proving **fix** solves the problem:_
```
git checkout 3.7-maint^{/"Closes #531"}
rm -rf b && ./autogen.sh && mkdir b && ( cd b && ../configure && nice make -j && make check )
...
PASSED
```

So I can confirm the fix works on my symlinked file system:
```
ls -ld /local
lrwxrwxrwx 1 root root 11 Jul  7  2017 /local -> /srv/local/
```

**Comment by sdettmer** [comment]
I'm sorry that I bother you again.
Due to our exciting proprietary IT infrastructure (everything is on a symlink), this change is essential for us and I would like to pass it to my team, preferably as an official release.

Is there a rough release date planned?

I would like to know if I should pass a Git version build from the maint-3.7 branch to my team or better wait for the next release. It would be helpful to have a rough idea how that could be; if it is a matter of days I would love to wait and use an official release of course.

**Comment by jrosdahl** [comment]
I'll try to make a 3.7.8 release some time later this week. No promises though.
