### ISSUE TITLE
ccache on OSX becomes slower when you have many CPU cores

### ISSUE THREAD

**Issue by bratell-at-opera** [ccache/ccache#54]
I hope I will be able to make sense in this bug report because there is a lot of things I don't quite understand myself.

We have OSX build machines with 8 physical cores, or 16 logical cores, and we see a 25% reduction in fully cached build speed if we try to use 16 build threads (7 minutes instead of 5 minutes). Reducing the number of threads to 8 seems to make cached builds fast again, but that will obviously hurt non-cached builds badly.

We noticed this already last year but didn't really debug very deeply. The only thing I can find from back then is "in the slow builds with ccache, effectively all time was spent in open() trying to acquire a file system lock".

**Comment by White-Tiger** [comment]
Just a blind guess as I'm just a "user", but
do you see a speed up when you disable stats?
https://ccache.samba.org/manual.html#_configuration
`stats = false` *(or CCACHE_STATS)*

It would at least prevent the stats lock...

**Comment by jrosdahl** [comment]
Hey Daniel, long time no see!

> We noticed this already last year but didn't really debug very deeply.

Which ccache version are we talking about?

> The only thing I can find from back then is "in the slow builds with ccache, effectively all time was spent in open() trying to acquire a file system lock".

Locking (in non-ancient ccache versions) is done by creating symlinks, so "open() trying to acquire a file system lock" doesn't make much sense to me.

**Comment by bratell-at-opera** [comment]
Long time indeed!

We mostly use a one year old version, home built for clang support (I think), but people using their local ccache report the same thing (and I don't have a mac). Do you think something might have improved since last year?

The locking is in the filesystem itself. More than likely OSX is at least partly to blame but I don't think our chances to fix OSX are high.

@White-Tiger: Good theory, but it doesn't seem to have helped.

@all 
So assuming the problem is that OSX misbehaves (spinlocks) if many processes at the same time try to write to (or read from?) the same file, and that file is not the stats file. What other file could it be? Some index file?

**Comment by jrosdahl** [comment]
> We mostly use a one year old version,

That's not quite specific enough. There were some non-trivial changes in 3.2 which came out about one year ago.

> So assuming the problem is that OSX misbehaves (spinlocks) if many processes at the same time try to write to (or read from?) the same file, and that file is not the stats file. What other file could it be? Some index file?

There are no other shared files than the stats files for ccache < 3.2. For ccache >= 3.2, there is also the configuration file ($CCACHE_DIR/ccache.conf).

Perhaps the filesystem pressure you're seeing is for some directory like $CCACHE_DIR/tmp?

**Comment by keleftheriou** [comment]
I can confirm I am experiencing the same issue with ccache 3.2.5 on a machine with 6 physical, 12 "logical" cores. It definitely feels like an issue of contention around synchronization from multiple processes, but I haven't dug deeper. The following results are from the same xctool invocation, with cache fully warmed up in all cases, and only changing the -jobs N parameter. Notice how -jobs 6 performs better than the default (-jobs 12):

-jobs 1
real	3m1.955s
user	1m22.250s
sys	1m36.211s

-jobs 3:
real	1m34.390s
user	1m27.685s
sys	2m19.862s

-jobs 6:
real	1m28.048s
user	1m34.683s
sys	4m37.792s

-jobs 12 (default):
real	1m43.405s
user	1m50.187s
sys	8m39.827s

-jobs 24:
real	1m42.055s
user	1m53.450s
sys	10m0.779s

**Comment by keleftheriou** [comment]
I should also add here that when invoking with -jobs 1, the wall time to compile each file is ~50-80 ms, and with -jobs 12 (same as no -jobs argument for my machine) I see an order of magnitude longer times, ~500-800ms.

**Comment by itensionanders** [comment]
Think that someone needs to fire up `dtrace`, if we are to shed some light on what is happening here...

Using `-ftime-report` on *individual* compiles might also give some information about what is happening ?  Unfortunately the ccache log does not have too many compile specifics, but does have timestamps.

**Comment by itensionanders** [comment]
Something like:
`sudo dtruss -f xctool`

**Comment by afbjorklund** [comment]
This is again something that would require an actual mac in order to reproduce.

**Comment by jrosdahl** [comment]
I'm closing this issue due to lack of feedback. Feel free to suggest reopening it!

**Comment by bratell-at-opera** [comment]
Yes, no more information. Worse problems have shadowed this. I suspect the OSX kernel scaling badly so maybe it will fix itself.

**Comment by romanrm** [comment]
It seems like this is an issue even on Linux. CCache seems to have some sort of locking overhead. Compiling the kernel on a 8-core machine with -j 12, I get 35% overall CPU idle in top. It's not bottlenecked by IO either (iowait 0% since this is on NVMe SSD). Maybe CCache worked well enough in the era of slow HDDs and low core counts, but the scalability is very disappointing.

**Comment by afbjorklund** [comment]
@romanrm : are you able to use `perf` or other tracing tool, and open a new issue?

**Comment by TyrantDante** [comment]
i got the same problem, normal build cost 2s ,but ccache cost 4.5s
