### ISSUE TITLE
hash_dir problem?

### ISSUE THREAD

**Issue by AlexanderLanin** [ccache/ccache#557]
### How to reproduce ###
I'm not 100% sure how I got into this problem. What I have:

1. Run `ccache --set-config hash_dir=false`
2. Verify with `ccache -p | grep hash_dir`
3. Run `export CCACHE_LOGFILE=/tmp/cache.debug`
4. Run some compilation and abort after a second.
5. Run `grep hash_dir /tmp/cache.debug`

### Actual behavior ###

    alex@DESKTOP:~/llvm/build-debug$ grep hash_dir /tmp/cache.debug 
    [2020-03-07T22:14:41.804031 6677 ] Config: (environment) hash_dir = true
    [2020-03-07T22:14:41.804329 6680 ] Config: (environment) hash_dir = true
    [2020-03-07T22:14:41.804435 6681 ] Config: (environment) hash_dir = true

### Expected behavior ###
hash_dir set to false

### Environment ###
ccache version 3.4.1

**Comment by AlexanderLanin** [comment]
Result with master.6aba3fb3 is different, but not really better.

    alex@DESKTOP:~/llvm/build-debug$ grep hash_dir /tmp/cache.debug
    [2020-03-07T22:27:21.889455 8687 ] Config: (/home/alex/.ccache/ccache.conf) hash_dir = true
    alex@DESKTOP:~/llvm/build-debug$ ccache -p | grep hash_dir
    (/home/alex/.ccache/ccache.conf) hash_dir = false

Here is /home/alex/.ccache/ccache.conf:

    max_size = 15G
    compression = true
    base_dir = /home/alex
    hash_dir = false

**Comment by jrosdahl** [comment]
I can't reproduce this.

> [2020-03-07T22:14:41.804031 6677 ] Config: (environment) hash_dir = true

"environment" indicates that the environment variable `CCACHE_HASHDIR` has been set. Older RedHat/CentOS/Fedora versions used to set it in some central shell init file – perhaps that's the issue?

**Comment by AlexanderLanin** [comment]
Ubuntu 18. But anyway it wouldn't quite explain why it's picked up in one case but not the other (run from same bash). The case with current master reports '/home/alex/.ccache/ccache.conf' in both cases. One time false, one time true. Definitely no config chance in between.

I'll try to reproduce this and add some debug output here and there.

**Comment by AlexanderLanin** [comment]
Cannot reproduce anymore.
