### ISSUE TITLE
Support clang -ivfsoverlay option

### ISSUE THREAD

**Issue by manuyavuz-pointr** [ccache/ccache#567]
Hi,

Is it possible to support `-ivfsoverlay` option for clang?
Option reference: https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-ivfsoverlay-arg

This option is mainly used by Xcode when ObjC/C++ modules are enabled. I was trying out recent `-fmodules` addition (#482), but got `multiple input files` error because `ccache` thinks the value of `-ivfsoverlay` (`all-product-headers.yaml` file which is generated by Xcode) is an input file along with actual source file.

If it's only about updating `compopts` in `compopt.cpp` file, I can submit a PR.

Thanks!

**Comment by jrosdahl** [comment]
> If it's only about updating compopts in compopt.cpp file, I can submit a PR.

If the file content (`all-product-headers.yaml` in your example) does not affect the compilation output, then it's only a matter of adding an entry to `compopt.cpp`, yes.

**Comment by jrosdahl** [comment]
@manuyavuz-pointr: Are you happy with the answer or do you want more information or feedback?
