### ISSUE TITLE
Linker error: unresolved Lockfile::~Lockfile()

### ISSUE THREAD

**Issue by Josko** [ccache/ccache#569]
### How to reproduce ###

1. Clone the current master branch.
2. Compile and link on Windows. (Using MinGW here)

### Actual behavior ###

What happens is that the linker cannot resolve Lockfile member methods, due to them not being in the checkout when searched for.

I noticed there is `Lockfile.cpp` and `lockfile.cpp` and it seems that on case-insensitive filesystems the older one wins. I only do have one such file. Possible cause is c181fdd983376014e6c27b6e0b64af9a7e0eb7e3.

### Expected behavior ###
Successful linking to produce ccache.exe

### Environment ###

ccache version master a7eb7b383e6a96a48fa3a611f66b139c7c06610b
Windows 10
MinGW 8.3.0 x64

PS. I can submit a PR/Patch if my take on this is correct.

**Comment by jrosdahl** [comment]
Oops, thanks for the notice.
