### ISSUE TITLE
Ignoring /Fo option for clang-cl (Windows)

### ISSUE THREAD

**Issue by remculib** [ccache/ccache#574]
### How to reproduce ###

1.  `ccache.exe clang-cl  /Fotest-ccache-clang-cl.cpp.obj -c test.cpp`

2. 
 ```
$ dir 
test.cpp
test.o
```

### Actual behavior ###

It seems the ccache ignores [**/Fo option**](https://docs.microsoft.com/en-us/cpp/build/reference/fo-object-file-name?view=vs-2019). 
 

### Expected behavior ###

ccache had to make the **test-ccache-clang-cl.cpp.obj** object file, but it does **test.o** file instead of that.
If you run that command without ccache:
 `clang-cl  /Fotest-ccache-clang-cl.cpp.obj -c test.cpp`
```
$  dir
 test.cpp
 test-ccache-clang-cl.cpp.obj
```

The **test-ccache-clang-cl.cpp.obj** file was made as expected

I checked that behaviour for MSVC compiler:
`$ ccache.exe cl  /Fotest-ccache-msvc-cl.cpp.obj -c test.cpp`
```
$ dir
test.cpp 
test-ccache-msvc-cl.cpp.obj
```
That is OK

### Environment ###

ccache version 3.7.9

Windows 7 OS

**Comment by jrosdahl** [comment]
Hi,

ccache neither supports MSVC nor clang-cl. I've updated https://ccache.dev/platform-compiler-language-support.html to mention that now.

> I checked that behaviour for MSVC compiler:
> $ ccache.exe cl /Fotest-ccache-msvc-cl.cpp.obj -c test.cpp
> 
> $ dir
> test.cpp 
> test-ccache-msvc-cl.cpp.obj
> 
> That is OK

It only appears to work with MSVC because ccache fails to run the MSVC preprocessor and then falls back to running the real compiler. This gives the correct end result, but nothing will be cached.

**Comment by remculib** [comment]
Hi,
Thank you for answer!
I am sorry. I have not seen the platform supported page.

I think to close the issue. Ok?

**Comment by jrosdahl** [comment]
Sure, no problem.
