### ISSUE TITLE
Can't cache nvcc objects when compiling with "-Werror all-warnings"

### ISSUE THREAD

**Issue by allisonvacanti** [ccache/ccache#598]
Compiling a simple test program with `nvcc -Werror all-warnings -c test.cu` will never hit the cache.

`-Werror all-warnings` is how nvcc promotes warnings to errors. `ccache` seems to be pulling `-Werror` out and leaving the `all-warnings` bit in when trying to preprocess the file, causing the preprocessor to fail.

If that option is removed, the cache hits fine.

### How to reproduce ###

```
av@torsey /tmp/ccache-issue$ cat test.cu
#include <cstdio>
#include <cuda_runtime.h>

__global__ void kernel() { printf("Hello from CUDA.\n"); }

int main()
{
  printf("Hello from C++.\n");
  kernel<<<1, 1>>>();
  cudaDeviceSynchronize();
  return 0;
}

av@torsey /tmp/ccache-issue$ ls -l `which nvcc`
lrwxrwxrwx 1 av av 45 Mar 11 08:26 /home/av/code/utils/ccache-install/bin/nvcc -> /home/av/code/utils/ccache-install/bin/ccache

av@torsey /tmp/ccache-issue$ ccache --version
ccache version master.a1964c68

av@torsey /tmp/ccache-issue$ ccache -z
Statistics zeroed

av@torsey /tmp/ccache-issue$ nvcc -Werror all-warnings -c test.cu -o test
av@torsey /tmp/ccache-issue$ ccache -s
cache hit (direct)                     0
cache miss                             1

av@torsey /tmp/ccache-issue$ nvcc -Werror all-warnings -c test.cu -o test
av@torsey /tmp/ccache-issue$ ccache -s
cache hit (direct)                     0
cache miss                             2
```

### Actual behavior ###

```
[2020-05-25T18:22:18.262585 13191] Command line: nvcc -Werror all-warnings -c test.cu -o test
[2020-05-25T18:22:18.262601 13191] Hostname: torsey
[2020-05-25T18:22:18.262609 13191] Working directory: /tmp/ccache-issue
[2020-05-25T18:22:18.262639 13191] all-warnings is not a regular file, not considering as input file
[2020-05-25T18:22:18.262684 13191] Source file: test.cu
[2020-05-25T18:22:18.262692 13191] Object file: test
[2020-05-25T18:22:18.262710 13191] Trying direct lookup
[2020-05-25T18:22:18.263078 13191] Looking for result name in /home/av/code/build/ccache/e/6/b09e044b637d34e7133aa9075e6db550e291c3.manifest
[2020-05-25T18:22:18.263094 13191] No such manifest file
[2020-05-25T18:22:18.263101 13191] Did not find result name in manifest
[2020-05-25T18:22:18.263520 13191] Running preprocessor
[2020-05-25T18:22:18.263530 13191] Executing /usr/local/cuda/bin/nvcc all-warnings -E test.cu
[2020-05-25T18:22:18.277663 13191] Preprocessor gave exit status 1
[2020-05-25T18:22:18.277814 13191] Failed; falling back to running the real compiler
[2020-05-25T18:22:18.277827 13191] Executing /usr/local/cuda/bin/nvcc -Werror all-warnings -c test.cu -o test
[2020-05-25T18:22:18.277841 13191] Result: preprocessor error
```

### Expected behavior ###

I expected the file to be cached.

### Environment ###

ccache master at 1964c68

### Additional Info ###

The complete list of options for `-Werror` are [here](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#generic-tool-options-Werror). These should all be handled.

**Comment by allisonvacanti** [comment]
If anyone else runs into this, it looks like this workaround can be used for the `all-warnings` case:

```
 nvcc -Xcudafe --promote_warnings [...]
```

**Comment by jrosdahl** [comment]
> If anyone else runs into this, it looks like this workaround can be used for the `all-warnings` case:
> 
> ```
>  nvcc -Xcudafe --promote_warnings [...]
> ```

Or, I assume, the double-dash form `--Werror all-warnings`?

(Just like for the [`-xHost` problem](https://github.com/ccache/ccache/pull/587) it is from ccache's perspective unfortunate that NVCC has chosen to reuse GCC options and change their semantics.)

**Comment by jrosdahl** [comment]
I wrote:

> Or, I assume, the double-dash form `--Werror all-warnings`?

Well, only if ccache learns that `--Werror` takes an argument. Done in 7bfae2087a53.

I'm not super stoked about adding special code paths for the single-dash `-Werror` option for NVCC since that will increase code complexity for little gain; we should encourage usage of `--Werror` or the `-Xcudafe ...` solution instead. @allisonvacanti: Do you think this sounds reasonable?

**Comment by allisonvacanti** [comment]
That works for me and my immediate usecase, but is not ideal.

Since these flags aren't easily changed without modifying a project's build system, it'd really be best to support both versions. Otherwise users of a project that applies `-Werror` must manually edit the project and file bugs against upstream if they want to cache the outputs from that project. That's a bit of a headache.

So it's a potentially annoying but acceptable workaround. 

Also -- sorry about the comment spam in this issue >.< I hadn't realized that github would ping the issue every time I rebased a branch...

**Comment by jrosdahl** [comment]
Fair enough. It looks like the implementation is easier than I first thought.
