### ISSUE TITLE
Tests fail when compiled with clang 3.4 - 4.0

### ISSUE THREAD

**Issue by AlexanderLanin** [ccache/ccache#601]
This was discovered on CMake branch of #573, I do not know whether there is any relation to switching to CMake. Probably not!

### How to reproduce ###
Option 1) Install clang 3.4. Other dependencies unknown.
Option 2) Based on cmake branch run: `CC=clang CXX=clang++ CMAKE_PARAMS="-DUSE_LIBZSTD_FROM_INTERNET=ON -DUSE_LIBB2_FROM_INTERNET=ON" ./docker.sh ubuntu-14-trusty`

#### producttest.split_dwarf:
`unknown argument: '-fdebug-prefix-map=/source/testdir.8800/run/dir1=.`

#### producttest.modules:
Compiler:         clang (/usr/bin/clang)
Compiler version: Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
CUDA compiler:    not available

Running test suite modules.
FAILED

Test suite:     modules
Test case:      preprocessor output
/source/test/run: line 38: printf: `_': invalid format character
Failure reason: File test1.preprocessed.cpp does not contain: #pragma clang module import Test1. Actual content: # 1 "test1.cpp"

### Scope?
Is Ubuntu 14 even in Scope? Do we care? More precisely clang 3.4. It was released ~2013.

### Attachments
[testdirs.tar.gz](https://github.com/ccache/ccache/files/4742973/testdirs.tar.gz)

**Comment by jrosdahl** [comment]
> Is Ubuntu 14 even in Scope? Do we care? More precisely clang 3.4. It was released ~2013.

I'd say that Ubuntu 14 with GCC 4.8.4 is in scope, but not with Clang 3.4.

**Comment by AlexanderLanin** [comment]
"clang" in Ubuntu 14 defaults to 3.4.
However 3.5, 3.6, 3.8 and 3.9 are also available.
I'll retest with those versions.
