### ISSUE TITLE
"Directory is not hashed if using -gz" test fails with GCC 6

### ISSUE THREAD

**Issue by AlexanderLanin** [ccache/ccache#602]
### How to reproduce ###

Option 1) Install Debian 9.
Option 2) Based on cmake branch from #573 run: `./docker.sh debian-9-stretch`

### Actual behavior ###

    The following tests FAILED:
          2 - producttest.base (Failed)
          3 - producttest.nocpp2 (Failed)

[testdirs.tar.gz](https://github.com/ccache/ccache/files/4741077/testdirs.tar.gz)

     2/31 Test  #2: producttest.base ....................***Failed    1.69 sec
    Compiler:         gcc (/usr/bin/gcc)
    Compiler version: gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
    CUDA compiler:    not available
    
    Running test suite base..................................
    FAILED
    
    Test suite:     base
    Test case:      Directory is not hashed if using -gz
    Failure reason: Expected "cache hit (preprocessed)" to be 2, actual 1
    
    ccache -s:
    cache directory                     /source/testdir.1382/.ccache
    primary config                      /source/testdir.1382/ccache.conf
    secondary config (readonly)         
    stats updated                       Sat Jun  6 22:19:50 2020
    cache hit (direct)                     0
    cache hit (preprocessed)               1
    cache miss                             2
    cache hit rate                     33.33 %
    cleanups performed                     0
    files in cache                         2
    cache size                           0.0 MB
    max cache size                       5.0 GB
    
    Test data and log file have been left in testdir.1382 / testdir.failed
    
          Start  3: producttest.nocpp2
     3/31 Test  #3: producttest.nocpp2 ..................***Failed    1.70 sec
    Compiler:         gcc (/usr/bin/gcc)
    Compiler version: gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
    CUDA compiler:    not available
    
    Running test suite nocpp2..................................
    FAILED
    
    Test suite:     nocpp2
    Test case:      Directory is not hashed if using -gz
    Failure reason: Expected "cache hit (preprocessed)" to be 2, actual 1
    
    ccache -s:
    cache directory                     /source/testdir.2734/.ccache
    primary config                      /source/testdir.2734/ccache.conf
    secondary config (readonly)         
    stats updated                       Sat Jun  6 22:19:52 2020
    cache hit (direct)                     0
    cache hit (preprocessed)               1
    cache miss                             2
    cache hit rate                     33.33 %
    cleanups performed                     0
    files in cache                         2
    cache size                           0.0 MB
    max cache size                       5.0 GB
    
    Test data and log file have been left in testdir.2734 / testdir.failed

**Comment by paolostivanin** [comment]
Same on openSUSE Tumbleweed when updating to 3.7.10

**Comment by jrosdahl** [comment]
Thanks for the bug report.
