### ISSUE TITLE
"ccache -c" (version 3.7.9) hangs on MSYS2

### ISSUE THREAD

**Issue by bwijen** [ccache/ccache#603]
$ ccache --version
ccache version 3.7.9

Copyright (C) 2002-2007 Andrew Tridgell
Copyright (C) 2009-2020 Joel Rosdahl

$ ccache -s (works)
$ ccache -c (hangs)
$ ccache -z (hangs)

Please note that ccache version 3.7.7 does work as expected.

**Comment by jrosdahl** [comment]
Hi there,

We need more information to understand what the issue might be, at the very least which steps are needed to reproduce the issue.

What do you mean by "ccache 3.7.9 on msys2"? Did you compile it yourself? If so, how? Or did you use a prebuilt version? If so, from where?

Tip: If you choose the _Bug report_ option on https://github.com/ccache/ccache/issues/new/choose you'll get a bug report template that asks for things like these.

**Comment by bwijen** [comment]
Hi Joel,

After you question for more information, I have tried to reproduce.
I have downloaded msys2 version 20200602 and installed ccache (v 3.7.9)
However this works perfectly.

I will try to reproduce again at work (where our setup is slightly different)
and get back to you...

Ben...

**Comment by bwijen** [comment]
The problem seems to be the runtime upgrade to 3.1.5-3.

### How to reproduce ###
1. Install: msys2-x86_64-20200602.exe from [msys2.org](https://www.msys2.org)
2. Check: ccache -z is working
3. Run: pacman -Syu (update to msys2-runtime-3.1.5-3)
4. Check: ccache -z hangs

### Actual behavior ###
```
$ ccache -z
<hangs>
```
### Expected behavior ###
```
$ ccache -z
Statistics zeroed
```

### Environment ###
ccache version 3.7.9
Windows 10 / msys2 20200602 / msys2-runtime-3.1.5-3

**Comment by peterbud** [comment]
For me it's working fine even after full updating msys2 to 3.1.5-3
```
$ pacman -Qi msys2-runtime
Name            : msys2-runtime
Version         : 3.1.5-3
Description     : Posix emulation engine for Windows
...

```

```
$ ccache --version
ccache version 3.7.9

Copyright (C) 2002-2007 Andrew Tridgell
Copyright (C) 2009-2020 Joel Rosdahl
...

```

```
$ ccache -z
Statistics zeroed

```

**Comment by bwijen** [comment]
Using CCACHE_LOGFILE=ccache.log:
```
[2020-06-16T10:43:21.972685 11397] === CCACHE 3.7.9 STARTED =========================================
[2020-06-16T10:43:21.973623 11397] Unlink /home/xxx/.ccache/stats via /home/xxx/.ccache/stats.ccache.rm.tmp
[2020-06-16T10:43:21.973647 11397] x_unlink failed: No such file or directory
[2020-06-16T10:43:21.982604 11397] lockfile_acquire: symlink /home/xxx/.ccache/0/stats.lock: No such file or directory
[2020-06-16T10:43:21.983039 11397] lockfile_acquire: symlink /home/xxx/.ccache/0/stats.lock: No such file or directory
[2020-06-16T10:43:21.983447 11397] lockfile_acquire: symlink /home/xxx/.ccache/0/stats.lock: No such file or directory
```

That last line repeats indefinitely, hence the hang...

**Comment by peterbud** [comment]
Your log helped me: you are using the MSYS2 version, and yes, with that I see the same issue. Interestingly the MINGW64 version works fine. You can install it with `pacman -S mingw-w64-x86_64-ccache`

**Comment by jrosdahl** [comment]
Thanks.

Does ccache 3.7.7 work with msys2-runtime-3.1.5-3? I don't see any changes between ccache 3.7.7 and 3.7.9 that should affect the lockfile behavior for the non-win32 case.

I strace or something similar available in msys2? If so I suggest posting a syscall trace.

----

Hm.... I just found https://github.com/msys2/MSYS2-packages/blob/master/ccache/ccache-3.4.2-msys.patch which disables test cases related to symlinks. Doesn't MSYS2 support symlinks? If so ccache's locking is completely broken. But why did it work (or appear to work) before then?

**Comment by peterbud** [comment]
Symlinks are not supported in MSYS2 AFAIK. Symlinks are “emulated” by copying files and directories. This can be surprising, to say the least.

**Comment by jrosdahl** [comment]
OK. Then it sounds like the lockfile routines should use files instead of symlinks for MSYS2. Regardless, it feels like there is a bug in the MSYS2 runtime. Should we close this issue?

**Comment by bwijen** [comment]
@jrosdahl: You are probably right.
I will create a MCVE for msys2 and open an issue there...

**Comment by mingwandroid** [comment]
> Symlinks are not supported in MSYS2 AFAIK. Symlinks are “emulated” by copying files and directories. This can be surprising, to say the least.

Symlinks are fully supported in MSYS2 if you set the MSYS env var appropriately: https://superuser.com/a/1044337

**Comment by bwijen** [comment]
> Symlinks are fully supported in MSYS2 (including `ln -s`) if you set the MSYS env var appropriately: https://superuser.com/a/1044337

On linux:
> ln -s foo bar

Successfully leaves me with a bar pointing to a nonexistent foo
As `foo` is not treated as a path, but content for the symlink

On MSYS2 (with `MSYS=winsymlinks:nativestrict` and run as admin):
> ln -s foo bar
> ln: failed to create symbolic link 'bar': No such file or directory

As `foo` **is** treated as a path and does not exist.
Note this does work:
> touch foo
> ln -s foo bar

It looks like the symlink target will never exist (and therefore will always fail on msys2)
https://github.com/ccache/ccache/blob/1523ce64c0677a44939ec49343fa04c94b6e2cda/src/Lockfile.cpp#L44-L47

I'm now thinking this is not fixable in the msys2 runtime.
As it can either copy symlinks or use windows symlinks, both of which will not work with non-existing targets.

**Comment by bwijen** [comment]
As I was wondering why this has worked before I have now tested an old msys2-runtime (3.1.5-1) which works, while (3.1.6-1) does not.

So, while symlinks are indeed supported by MSYS2, they are broken with msys2-runtime 3.1.6-1
I have now created: msys2/MSYS2-packages#2052

So, this is not an ccache issue.

**Comment by jrosdahl** [comment]
> I have now created: [msys2/MSYS2-packages#2052](https://github.com/msys2/MSYS2-packages/issues/2052)
> 
> So, this is not an ccache issue.

Thanks.

If it doesn't work out to fix MSYS2 I guess it would be possible to make ccache use ordinary lock files instead of symlinks for MSYS2. (The primary reason for using symlinks is that it saves a couple of system calls.)
