### ISSUE TITLE
Replace XXH64 with XXH3?

### ISSUE THREAD

**Issue by erijo** [ccache/ccache#612]
XXH3 is the new version of [xxHash](https://github.com/Cyan4973/xxHash) which, according to the creators themselves:
> The new algorithm is much faster than its predecessors for both long and small inputs...

The hash is not yet officially released:
> XXH3 has now reached "release candidate" status. If everything remains fine, its format will be "frozen" and become final. After which, return values of XXH3 and XXH128 will no longer change in future versions. XXH3's return values will be officially finalized upon reaching v0.8.0.

I've done a [test switch](https://github.com/erijo/ccache/tree/xxh3) and a simple performance comparison with master (using `../misc/performance /usr/bin/g++ -std=c++11 -I../src -I. ../src/ccache.cpp`):

master:
```
Without ccache:                             1.1885 s (100.0000 %) (  1.0000 x)
With ccache, preprocessor mode, cache miss: 1.2636 s (106.3222 %) (  0.9405 x)
With ccache, preprocessor mode, cache hit:  0.0882 s (  7.4190 %) ( 13.4788 x)
With ccache, direct mode, cache miss:       1.2629 s (106.2667 %) (  0.9410 x)
With ccache, direct mode, cache hit:        0.0123 s (  1.0313 %) ( 96.9686 x)
With ccache, depend mode, cache miss:       1.3072 s (109.9887 %) (  0.9092 x)
With ccache, depend mode, cache hit:        0.0125 s (  1.0528 %) ( 94.9887 x)
```

xxh3:
```
Without ccache:                             1.1654 s (100.0000 %) (  1.0000 x)
With ccache, preprocessor mode, cache miss: 1.2527 s (107.4882 %) (  0.9303 x)
With ccache, preprocessor mode, cache hit:  0.0876 s (  7.5122 %) ( 13.3117 x)
With ccache, direct mode, cache miss:       1.2614 s (108.2318 %) (  0.9239 x)
With ccache, direct mode, cache hit:        0.0118 s (  1.0156 %) ( 98.4625 x)
With ccache, depend mode, cache miss:       1.2559 s (107.7648 %) (  0.9279 x)
With ccache, depend mode, cache hit:        0.0119 s (  1.0187 %) ( 98.1689 x)
```

The performance improvement seems minor, but a bit more testing is probably needed.

**Comment by jrosdahl** [comment]
Sure, why not. I suggest waiting for the stable version first.

**Comment by jrosdahl** [comment]
> Sure, why not. I suggest waiting for the stable version first.

Available now.

**Comment by erijo** [comment]
Long overdue, but now I have at least updated my branch with the stable version of XXH3. Will post a PR later.

**Comment by erijo** [comment]
I ran a new performance measurement comparing master@f4194dd9:
```
Without ccache:                             1.8890 s (100.0000 %) (  1.0000 x)
With ccache, preprocessor mode, cache miss: 1.9913 s (105.4151 %) (  0.9486 x)
With ccache, preprocessor mode, cache hit:  0.1019 s (  5.3957 %) ( 18.5331 x)
With ccache, direct mode, cache miss:       1.9933 s (105.5184 %) (  0.9477 x)
With ccache, direct mode, cache hit:        0.1039 s (  5.5016 %) ( 18.1764 x)
With ccache, depend mode, cache miss:       1.9929 s (105.4970 %) (  0.9479 x)
With ccache, depend mode, cache hit:        0.1040 s (  5.5062 %) ( 18.1613 x)
```
To this PR:
```
Without ccache:                             1.8885 s (100.0000 %) (  1.0000 x)
With ccache, preprocessor mode, cache miss: 1.9938 s (105.5751 %) (  0.9472 x)
With ccache, preprocessor mode, cache hit:  0.1035 s (  5.4808 %) ( 18.2455 x)
With ccache, direct mode, cache miss:       1.9968 s (105.7346 %) (  0.9458 x)
With ccache, direct mode, cache hit:        0.1056 s (  5.5932 %) ( 17.8788 x)
With ccache, depend mode, cache miss:       1.9971 s (105.7510 %) (  0.9456 x)
With ccache, depend mode, cache hit:        0.1056 s (  5.5911 %) ( 17.8857 x)
```

The performance seems to be identical, so that alone doesn't seem to be a reason to switch. But perhaps switching to the latest version can be good for other reasons.

I'll simply leave it to you Joel to decide :)

**Comment by jrosdahl** [comment]
It's easy to see a slight but consistent improvement by using `ccache --checksum-file ...` on a large enough file. It probably doesn't matter much in practice, but I see no downside in using the latest version.
