### ISSUE TITLE
color_diagnostics test suite fails in some situations

### ISSUE THREAD

**Issue by AlexanderLanin** [ccache/ccache#616]
### How to reproduce ###

One of these:
* execute `misc/build-in-docker debian-10-buster`
* execute `misc/build-in-docker ubuntu-16-xenial`
* see GitHub actions run here: https://github.com/AlexanderLanin/ccache/actions/runs/156887338 (see testdir.11032 in zip file)

### Actual behavior ###
```
Running test suite color_diagnostics.
FAILED

Test suite:     color_diagnostics
Test case:      Colored diagnostics automatically disabled when stderr is not a TTY (run_second_cpp=true)
Failure reason: File test1.output does not contain: [. Actual content: test1.c:1:5: warning: no previous prototype for 'foo_1' [-Wmissing-prototypes]
 int foo_1(int x) { return x; }
     ^~~~~
test1.c:2:2: warning: #warning "Warning from preprocessor" [-Wcpp]
 #warning "Warning from preprocessor"
  ^~~~~~~
```

### Expected behavior ###
Pass

### Environment ###
ccache from current master

**Comment by jrosdahl** [comment]
Thanks for the bug report.
