### ISSUE TITLE
The -fdirectives-only option is not passed to the compiler when run_second_cpp=true

### ISSUE THREAD

**Issue by deriamis** [ccache/ccache#617]
### How to reproduce ###

This is most visible when you are using `-fdirectives-only` where it can cause a failure, such as when using ccache as a frontend to Icecream >= 1.2 and GCC as the remote compiler.

1. Use GCC as your compiler for a project
2. Specify the -fdirectives-only option on the compiler command line
3. Watch the option get passed no matter what

### Actual behavior ###

This is straightforward behavior - because ccache doesn't know `-fdirectives-only` is a preprocessor-specific flag, it gets passed to the compiler even when it should not, such as when `run_second_cpp=1`. If you are using ccache as a frontend to Icecream, which in later versions passes `-fdirectives-only` to the preprocessor when remote preprocessing is enabled, the flag can cause a compilation failure when it's also passed to the compiler (specifically GCC in this case).

### Expected behavior ###

The flag should not have been passed to the compiler (should have only been passed to the preprocessor), and compilation should have succeeded.

### Environment ###

ccache version 3.7.7

Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

gcc (GCC) 8.2.0

ICECC 1.3.1

**Comment by jrosdahl** [comment]
Thanks for the bug report.

I don't quite understand the issue, though. The reproduction steps only say that the option is passed to the compiler, not why that would be a problem.

>  `-fdirectives-only` […] gets passed to the compiler even when it should not, such as when `run_second_cpp=1`

Do you mean `run_second_cpp = false`? `1` is not a valid value for `run_second_cpp` and `true` means "don't compile the preprocessed output" and it that case `-fdirectives-only` should definitely be passed to the compiler, right?

> If you are using ccache as a frontend to Icecream, which in later versions passes -fdirectives-only to the preprocessor when remote preprocessing is enabled, the flag can cause a compilation failure when it's also passed to the compiler (specifically GCC in this case).

Why can that flag cause a compilation failure? Please provide details.

> The flag should not have been passed to the compiler (should have only been passed to the preprocessor), and compilation should have succeeded.

Why not? And what compilation do you refer to?

That said, it's seems perfectly OK to avoid passing `-fdirectives-only` to the compiler if `run_second_cpp` is `false`, but I would like to understand why sending `-fdirectives-only` to the compiler is a problem in the first place.

**Comment by deriamis** [comment]
> Thanks for the bug report.
> 
> I don't quite understand the issue, though. The reproduction steps only say that the option is passed to the compiler, not why that would be a problem.

Sorry for the delayed reply. The reason for the lack of good information is that neither the GCC docs nor the bug report to GCC that describes the problem go into much detail. I've been trying to figure out how all of this works and get a good repro for you to make it more clear. The GCC bug report I am referring to is here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88475

> > `-fdirectives-only` […] gets passed to the compiler even when it should not, such as when `run_second_cpp=1`
> 
> Do you mean `run_second_cpp = false`? `1` is not a valid value for `run_second_cpp` and `true` means "don't compile the preprocessed output" and it that case `-fdirectives-only` should definitely be passed to the compiler, right?

I do. However, I have learned more about the problem since I wrote this, and I believe the actual issue is that `-fdirectives-only` needs to be passed to the compiler, but *only* if `-fdirectives-only` was passed to the preprocessor (or `-E -fdirectives-only` was passed to `gcc`) *and* the source preprocessed with `-fdirectives-only` is being compiled. So I was incorrect - this affects both preprocessing and compiler steps, so it needs to be in both places.

> > If you are using ccache as a frontend to Icecream, which in later versions passes -fdirectives-only to the preprocessor when remote preprocessing is enabled, the flag can cause a compilation failure when it's also passed to the compiler (specifically GCC in this case).
> 
> Why can that flag cause a compilation failure? Please provide details. 

Try this:
test.cpp
```c++
#define DECLARE const auto
#include <string>
#include <iostream>
int main()
{

    DECLARE vert = R"(#hello)";
    std::cout << vert << std::endl;
    return 0;
}
```
This works because gcc "ignores" `-fdirectives-only` without either `-E` or `-fpreprocessed`:
`g++ -fdirectives-only test.cpp -o test #succeeds`

This works because we are using the flags correctly with separate preprocessing:
```bash
g++ -fdirectives-only -E test.cpp -o test.ii #prepares the preprocessed source
g++ -fdirectives-only -c test.ii -o test
g++ -fpreprocessed -fdirectives-only -c test.ii -o test
```

These fail:
```bash
g++ -fdirectives-only -E test.cpp -o test.ii # prepares the preprocessed source
g++ -c test.ii -o test #fails
g++ -fpreprocessed -c test.ii -o test #fails
```

> > The flag should not have been passed to the compiler (should have only been passed to the preprocessor), and compilation should have succeeded.
> 
> Why not? And what compilation do you refer to?
> 
> That said, it's seems perfectly OK to avoid passing `-fdirectives-only` to the compiler if `run_second_cpp` is `false`, but I would like to understand why sending `-fdirectives-only` to the compiler is a problem in the first place.

Based on the above, I revise my statement. I think there's probably a complex interaction with icecream here, and I am not sure yet whether a change only to icecream fixes it or whether something is needed on the ccache side as well. I'm also working on the icecream side of this issue, so I'll update this once I have more information there.

**Comment by deriamis** [comment]
Note, there is a separate issue that `gcc -E` behaves differently from `cpp` in that `gcc -E` is less forgiving of things like undefined preprocessor directives than `cpp` is. I think it might be a good idea to have ccache use `cpp` where it's available and matches the compiler version, or at least add a way to make that happen at runtime. What do you think?

**Comment by jrosdahl** [comment]
Thanks.

To sum up ccache's current behavior if `-fdirectives-only` is in the command line:

* If `run_second_cpp = true` (the default), ccache doesn't pass `-fdirectives-only` to the preprocessor or the compiler. (This was implemented in #188. I guess the assumption was that `-fdirectives-only` is only relevant when compiling preprocessed code which doesn't happen when `run_second_cpp = true`.)
* If `run_second_cpp = false`, ccache passes `-fdirectives-only` to both the preprocessor and the compiler.

This matches the cases you listed as _"[...] using the flags correctly with separate preprocessing"_, so no problem here. Correct so far?

How is `-fdirectives-only` related to Icecream? How have you integrated ccache and Icecream?

> Note, there is a separate issue that `gcc -E` behaves differently from `cpp` in that `gcc -E` is less forgiving of things like undefined preprocessor directives than `cpp` is. I think it might be a good idea to have ccache use `cpp` where it's available and matches the compiler version, or at least add a way to make that happen at runtime. What do you think?

That doesn't sound feasible since ccache can't tell which preprocessor should be used in the general case.

It sounds like using `cpp` instead of `gcc -E` is solution to a not yet defined or understood problem?

**Comment by deriamis** [comment]
We're still doing testing, but it looks like we understand a few behavior modes, all apparently caused by Icecream's handling of `-fdirectives-only`. We've nailed down a few details so far:

* If Icecream fails to preprocess the source for any reason, it retries locally without `-fdirectives-only` (the comment in the source says it's to work around failures potentially caused by the flag)
* We can repro both of the behavior modes reliably without Icecream being involved. I'll demonstrate below.

test.cpp:
```c++
#define expand(x) x
#define test(...) \
    expand(_test_2(__VA_ARGS__))

#define _test_2(Expression)                 \
    doSomething((Expression))

template <typename T>
inline bool doSomething(
    const T& testOK) {
    if (!testOK) {
        return false;
    }
    return true;
}


int main()
{
    bool condition = true;
    return test(!condition || condition == condition);
}
```

In the first behavior mode, Icecream drops `-fdirectives-only` during the preprocessing step:
```bash
$ g++ -Wall -E test.cpp -o test.ii
$ g++ -fdirectives-only -Wall -c test.ii -o test
test.cpp: In function ‘int main()’:
test.cpp:21:49: warning: self-comparison always evaluates to true [-Wtautological-compare]
     return test(!condition || condition == condition);

```
Note, for this file in particular, if we don't preprocess with `-fdirectives-only`, we always get a tautological comparison error.

In the second behavior mode, Icecream drops `-fdirectives-only` during the compile step:
```bash
$ g++ -fdirectives-only -Wall -c test.ii -o test
$ g++ -Wall -c test.ii -o test
test.cpp: In function ‘int main()’:
test.cpp:21:41: warning: self-comparison always evaluates to true [-Wtautological-compare]
     return test(!condition || condition == condition);
                               ~~~~~~~~~~^~~~~~~~~~~~
test.cpp:21:12: error: ‘test’ was not declared in this scope
     return test(!condition || condition == condition);
            ^~~~
```
Passing `-fdirectives-only` in the compile step for the second mode would have succeeded. So, what we're seeing here so far is that Icecream is incorrectly dropping the flag when it should not be. The reason why they did that is ostensibly to address issues like this source:
```c++
#include <cstring>

int main()
{
    return std::strlen(R"(
#hello
)");
}
```

If I try preprocessing with `-fdirectives-only`, it fails:
```bash
g++ -fdirectives-only -Wall -Werror -E test.cpp -o test.ii
test3.cpp:6:2: error: invalid preprocessing directive #hello
 #hello
  ^~~~~
```

However, if I don't preprocess with `-fdirectives-only`, it succeeds even if I pass it to the compiler along with the preprocessed source:
```bash
$ g++ -fdirectives-only -Wall -c test.ii -o test  #succeeds
$ g++ -Wall -c test.ii -o test  #also succeeds
```

This mode is actually due to a GCC bug in how preprocessing differs between cpp (which GCC calls when passed the -E option) and the integrated preprocessor. I'm going to update the bug separately there.

Based on what we understand so far and what you have said, I think we can take away the following:
* Passing `-fdirectives-only` to the compiler is always the safest choice, so don't remove it from the compiler flags - in fact, it should be added if it's not there.
* `-fpreprocessed` should be passed to the compiler whenever the compiler receives preprocessed source.
* `-fdirectives-only` should be given to the preprocessor for all separate preprocessing unless there is a preprocessor error, in which case preprocessing should be retried with the flag removed.

I'm working with Icecream separately on their handling of the flag. I think ccache might be able to help avoid it, though. I'll submit a patch for the above.

**Comment by jrosdahl** [comment]
@deriamis: Have you been successful in investigating this further?
