### ISSUE TITLE
Cache size effectiveness curve

### ISSUE THREAD

**Issue by shawnl** [ccache/ccache#622]
If ccache has the information to invalidate oldest cache entries, then it probably has enough information to gather statistics on how old each hit is, which would let it calculate a curve of the effectiveness of the cache relative to time, in order to get a better image on how much the hit rate will raise/lower with a bigger/smaller cache.

**Comment by jrosdahl** [comment]
I think that you need to provide much more details about your idea if you want feedback or anybody to act on the idea.

**Comment by shawnl** [comment]
My suspicion is that cache hits are generally on recent compiles. If this is true, then the effectiveness of the cache goes down the larger the cache is, and there might be a way of calculating a "sweat spot".

**Comment by AlexanderLanin** [comment]
If I get your idea right, it's that old cache entries are probably irrelevant. But I think this highly depends on your use case. For example when I switch to a release branch which is months old and have to add some bugfix to that old branch I benefit from the old cache. I'm not even sure it's project/product specific how often one has to do that. Maybe it's related to the project phase. You probably never do that before any releases and you probably do that all the time once you have to maintain a dozen different released versions.

**Comment by jrosdahl** [comment]
@shawnl: Thanks for the clarification. Sure, there might exist some method to gather statistics for hinting the user about a good cache size, but without concrete ideas I'm afraid this won't end up anywhere (unless somebody gets excited by the idea, of course :slightly_smiling_face:). Do you have any concrete ideas?

I agree with @AlexanderLanin that use cases may vary a lot (maybe those 1 year old cache entries will become very valuable, maybe not) so it feels hard to predict much in the general case.
