### ISSUE TITLE
Unable to compile the latest ccache repository

### ISSUE THREAD

**Issue by dyadav7** [ccache/ccache#625]
### How to reproduce ###

Using gcc version 5.4.0 (GCC) 
cmake version 3.17.2

```
setenv CC     /../../gcc/5.4.0-static/bin/gcc
setenv CXX   /../../gcc/5.4.0-static/bin/g++

rm -rf build
mkdir build
cd build
cmake -DZSTD_FROM_INTERNET=ON ..
make
```

### Actual behavior ###

Got error : unrecognized command line option "-mavx2"

```console
$ make
...
[  3%] Building ASM object src/third_party/blake3/CMakeFiles/blake3.dir/blake3_avx2_x86-64_unix.S.o
cc1: error: unrecognized command line option "-mavx2"
make[2]: *** [src/third_party/blake3/CMakeFiles/blake3.dir/build.make:127: src/third_party/blake3/CMakeFiles/blake3.dir/blake3_avx2_x86-64_unix.S.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:792: src/third_party/blake3/CMakeFiles/blake3.dir/all] Error 2
make: *** [Makefile:183: all] Error 2
```

#### Another error message ####

Determining if the function pthread_create exists in the pthreads failed with the following output:

```
Change Dir: /home/deepaky/temp/ccache/orig/ccache/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_3cb18/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_3cb18.dir/build.make CMakeFiles/cmTC_3cb18.dir/build
gmake[1]: Entering directory `/home/deepaky/temp/ccache/orig/ccache/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_3cb18.dir/CheckFunctionExists.c.o
/zin/tools/gcc/5.4.0-static/bin/gcc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_3cb18.dir/CheckFunctionExists.c.o   -c /zin/plat/local.zincon/cmake-3.17.2/share/cmake-3.17/Modules/CheckFunctionExists.c
Linking C executable cmTC_3cb18
/zin/plat/local.zincon/cmake-3.17.2/bin/cmake -E cmake_link_script CMakeFiles/cmTC_3cb18.dir/link.txt --verbose=1
/zin/tools/gcc/5.4.0-static/bin/gcc  -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_3cb18.dir/CheckFunctionExists.c.o  -o cmTC_3cb18  -lpthreads 
/zin/tools/bin/binutils-2.34/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_3cb18] Error 1
```

### Expected behavior ###

Build should be ok

**Comment by jrosdahl** [comment]
> Got error : unrecognized command line option "-mavx2"

That sounds strange. The CMake script first checks if `-mavx2` is supported and is supposed to compile `blake3_avx2_x86-64_unix.S.o` only if `-mavx2` is supported. Please post the output of the `cmake -DZSTD_FROM_INTERNET=ON ..` command. It should says something like `-- Performing Test HAVE_AVX2 - Success` or `-- Performing Test HAVE_AVX2 - Failed`.

Also please run `make VERBOSE=1` to see the actual commands.

> Determining if the function pthread_create exists in the pthreads failed with the following output: [...]

Is that some output you found in `CMakeFiles/CMakeError.log`? If so that's perfectly normal and nothing to worry about – it's just output from a probing call made by CMake.

**Comment by dyadav7** [comment]
make VERBOSE=1 helped in finding the issue.
The build is using 3 compilers - cc, gcc, g++. In my environment the gcc, g++ version was 5.4.0 and cc version was 4.4.7.
I created a temp directory which has cc pointing to gcc and i added this directory to $PATH.
mkdir $PWD/temp;  ln -s  $(gcc) cc;  set path = ($PWD/temp $path).
This worked.

Can the complete build system use $CC / $CXX only ?

**Comment by jrosdahl** [comment]
OK, that's because you have set `CC` and `CXX` but not `ASM`, so CMake finds `cc` as the assembler. You can fix the problem by setting `ASM` as well.

> Can the complete build system use $CC / $CXX only ?

No, since the assembler is a separate entity from the C and C++ compilers.

**Comment by jrosdahl** [comment]
I now realized that the CMake script should check whether __the assembler__ supports e.g. `-mavx2` but it currently probes the C++ compiler. I'll try to fix that.
