### ISSUE TITLE
Per-project ccache configurations

### ISSUE THREAD

**Issue by deriamis** [ccache/ccache#626]
Some projects might want to control the ccache configuration centrally, such as when building on a CI host where the submitter doesn't necessarily have control over the home directory or the machine configuration. Also, it would help in larger projects for ensuring certain options set that are shown to improve performance rather than leave the decisions in the hands of individual developers.

I'm thinking of having ccache start looking for configuration files in first the current directory (such as `./.ccache.conf`) and then keep scanning upwards until it finds one or hits a directory it can't read from or whose immediate parent is the root directory. The configuration would be at the highest priority behind environment variables and would otherwise apply in exactly the same manner. This is similar in behavior to how other tools like cppcheck and clang-tidy work, so I think it should be the least surprising way to do it.

**Comment by jrosdahl** [comment]
Do you have an example of a configuration setting that you think would make sense to set in such a config file?

**Comment by deriamis** [comment]
The main ones I was thinking of were `extra_files_to_hash`, `ignore_headers_in_manifest`, `ignore_options`, and the one I would like to work on in #308. All of these options are likely to differ between projects. While the options could be passed via the command line or set in environment variables, it might make more sense to a project to version-contrrol them along with the source code they depend on.

**Comment by jrosdahl** [comment]
OK. I imagine that the settings you mention are typically used in their "environment variable form", set by the build system. They only exist in their "configuration file form" for symmetry.

I'm hesitant to add unnecessary complexity to the already complex configuration handling, so I would like the use case to be very clear and motivated. If we were to introduce dynamic configuration file lookup then we need to define where `ccache -o key=value` would write its value. Would the new configuration file show up in `ccache -s`, and if so, how?

What is your view on just using environment variables for this? They can be version-controlled in the project's build system configuration. Alternatively, the project can set `CCACHE_CONFIGPATH` and place that configuration file under version control.  Would that be useful in your scenario?
