### ISSUE TITLE
-DZSTD_FROM_INTERNET does not work with Zstandard 1.4.5

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#631]
### How to reproduce ###

1. Change 1.4.4 to 1.4.5 in `cmake/Findzstd.cmake`.
2. `mkdir build && cd build && cmake -DZSTD_FROM_INTERNET=ON ..`

### Actual behavior ###

CMake fails like this:

```
[...]
CMake Error in build/zstd-1.4.5/build/cmake/lib/CMakeLists.txt:
  Target "libzstd_static" INTERFACE_INCLUDE_DIRECTORIES property contains
  path:

    "/absolute/path/to/ccache/build/zstd-1.4.5/lib"

  which is prefixed in the build directory.
```

### Expected behavior ###

CMake succeeds.

### Environment ###

ccache master 27643df72326

**Comment by jrosdahl** [comment]
@AlexanderLanin and @cristianadam: Perhaps this is something you would like to help out with?

**Comment by cristianadam** [comment]
Error looks similar to this [Stackoverflow](https://stackoverflow.com/questions/25676277/cmake-target-include-directories-prints-an-error-when-i-try-to-add-the-source) entry, which would suggest the change of [this](https://github.com/ccache/ccache/blob/master/cmake/Findzstd.cmake#L30) line from:

```cmake
  add_library(ZSTD::ZSTD ALIAS libzstd_static)
  set_target_properties(
    libzstd_static
    PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${zstd_dir}/lib")
```
to
```cmake
  add_library(ZSTD::ZSTD ALIAS libzstd_static)
  set_target_properties(
    libzstd_static
    PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "$<BUILD_INTERFACE:${zstd_dir}/lib>")
```

**Comment by jrosdahl** [comment]
Thanks!
