### ISSUE TITLE
Dead link in Readme

### ISSUE THREAD

**Issue by hansfn** [ccache/ccache#633]
### Description ###

In README.md there is a link "Installation from release archive" that points to https://github.com/ccache/ccache/blob/master/doc/INSTALL-from-release-archive.md That file is no longer present in the master branch. (I think it's present in the 3.5 maintenance branch.)

Out of curiosity: When downloading the release tar ball INSTALL.md is equal to the now missing INSTALL-from-release-archive.md. And doc/INSTALL.md is different. Where is the magic hidden?

**Comment by jrosdahl** [comment]
Thanks for noting this, will fix. The INSTALL-from-release-archive.md file was removed from master as part of #573, after which there is no real difference between "installing from Git source archive" and "installing from release archive".

> Out of curiosity: When downloading the release tar ball INSTALL.md is equal to the now missing INSTALL-from-release-archive.md. And doc/INSTALL.md is different. Where is the magic hidden?

In the rules for creating a release archive (on the 3.7-maint branch): https://github.com/ccache/ccache/blob/0d0f48375aa6697effbd154b25b116b491b387da/dev.mk.in#L137
