### ISSUE TITLE
ccache: error: Failed to write to ~/.ccache/log: File too large (at 2 GB)

### ISSUE THREAD

**Issue by sdettmer** [ccache/ccache#649]
### Preface ###

When logfile reaches 2 GB size, ccache stops working. Interestingly, when log file gets one byte bigger, no more error happens.
I'm using a 32 bit build on a 64 bit host.

According to manual page using a log file is for troubleshooting. Maybe in normal operation no log file should be used at all, so just a small note could be added to the man page. I think some LARGE_FILE support might need to be enabled. However an infinitely growing log also makes no sense I think. As long as there is no "log rotate" feature I think maybe log shouldn't be used in normal operation.

### How to reproduce ###

1. Configure e.g.  `log_file=/home/sdettmer/.ccache/log`
2. Use ccache often or use some short-cut to create a 2GB large file
3. truncate -s 2147483647 /home/sdettmer/.ccache/log
3. Run ccache

### Actual behavior ###
```
  $ ls -l /home/sdettmer/.ccache/log
  -rw-rw-r-- 1 sdettmer zcone-pisint 2147483647 Sep  1 16:14 /home/sdettmer/.ccache/log
  $ make clean all -j8
  [...]
  ccache: error: Failed to write to /home/sdettmer/.ccache/log: File too large
  [...]
  Makefile:127: recipe for target 'all' failed
  make: *** [all] Error 2

  $ ls -l /home/sdettmer/.ccache/log
  -rw-rw-r-- 1 sdettmer zcone-pisint 2147483647 Sep  1 16:14 /home/sdettmer/.ccache/log
```

Interestingly behavior changes when file size gets one byte bigger:                                                      
```
  $ echo >> /home/sdettmer/.ccache/log
  $ ls -l /home/sdettmer/.ccache/log
  -rw-rw-r-- 1 sdettmer zcone-pisint 2147483648 Sep  1 16:16 /home/sdettmer/.ccache/log
  $ make
  [...]
  [100%] Built target XXX
  $ ls -l /home/sdettmer/.ccache/log
  -rw-rw-r-- 1 sdettmer zcone-pisint 2147483648 Sep  1 16:16 /home/sdettmer/.ccache/log
```
Now the files were compiled, make succeeded and log file (size) unchanged.

### Expected behavior ###

I'm most surprised that ccache does not abort with error anymore after `echo >> /home/sdettmer/.ccache/log`.

No 2 GB limit should prevent operation - maybe fallback to "transparent mode" like it happens on other errors.
Also I think the log file should not be that large. Maybe there could be a feature to clean (truncate, rotate) the log file with the normal cleanup. The man page clearly states that "limit on the total size of files in the __cache__", which excludes the log file, so I think it would be a feature request to have any extra handling here. 

On other systems maybe there is no 2 GB limit and the file grows infinitely, which also could be unexpected.
A simple pragmatic approach would be to rename log file on every cleanup, but this would be unpredictable.

### Environment ###
```
  $ $PATH/ccache --version
  ccache version 3.7.7+8_ge65d6c92
  [...]
  $ uname -a
  Linux RefVm3 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
  $ cat /etc/os-release 
  PRETTY_NAME="Devuan GNU/Linux ascii"
  NAME="Devuan GNU/Linux"
  ID=devuan
  HOME_URL="https://www.devuan.org/"
  SUPPORT_URL="https://devuan.org/os/community"
  BUG_REPORT_URL="https://bugs.devuan.org/"

  $ file $PATH/ccache 
  ..../ccache: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=c75830bb7335a78f7648338f1570a26b5d67103d, not stripped
```

### Build Info ###
```
tar xJf ../ccache-3.7.7+8_ge65d6c92.tar.xz
# Hack for using non-release ccache
ln -s ccache-3.7.7+8_ge65d6c92 "ccache-$VER"
cd "ccache-$VER"
mkdir _b || true
cd _b
../configure CFLAGS="-m32" LDFLAGS="-m32"
nice make -j20
nice make check
make install DESTDIR=../../t/$ROOTDIR/3p/ccache/${VER}/ccache
```

**Comment by jrosdahl** [comment]
> `../configure CFLAGS="-m32" LDFLAGS="-m32"`

You can get it to work by using `../configure CFLAGS="-m32 -D_FILE_OFFSET_BITS=64" LDFLAGS="-m32"` instead.

> According to manual page using a log file is for troubleshooting. Maybe in normal operation no log file should be used at all, so just a small note could be added to the man page.

Sorry, not sure I follow. The manual already hints that the log file is for trouble-shooting, so what do you think that the small note should say? 

> I'm most surprised that ccache does not abort with error anymore after `echo >> /home/sdettmer/.ccache/log`.

That's because it fails to even open the log file and that error is apparently not considered a fatal error by ccache. Yes, this is inconsistent. :slightly_smiling_face: (On master it's more consistent: failure to open the file is also a fatal error there.)

> Also I think the log file should not be that large. Maybe there could be a feature to clean (truncate, rotate) the log file with the normal cleanup.

That does not feel like ccache's job. There are other utilities that can rotate logs for you. And, as you say, the log file is not intended to be enabled unless you're debugging something.

> On other systems maybe there is no 2 GB limit and the file grows infinitely, which also could be unexpected.

Why do you think that would be unexpected?

>   $ $PATH/ccache --version
>   ccache version 3.7.7+8_ge65d6c92

Just curious: Why use an old in-between 3.7.7 and 3.7.8 version?
