### ISSUE TITLE
A warning message generated by ccache -s in file .ccache.log

### ISSUE THREAD

**Issue by dyadav7** [ccache/ccache#656]
### Question ###

`setenv CCACHE_DEBUG 1` is enabled. 
A warning message is generated by `ccache -s` in file `.ccache.log`.  `ccache -s` should not generate any warning message.

```
z /tmp $ ccd
Using CCACHE_CONFIGPATH   = /mydisk1/ccache/debug/conf/ccache.conf
Executing command : ccache -s
cache directory                     /mydisk1/ccache/debug/db
primary config                      /mydisk1/ccache/debug/conf/ccache.conf
secondary config (readonly)         
stats updated                       Mon Sep  7 20:02:06 2020
stats zeroed                        Mon Sep  7 17:28:22 2020
cache hit (direct)                 15458
cache hit (preprocessed)             381
cache miss                         11966
cache hit rate                     56.96 %
compile failed                        36
cleanups performed                    16
files in cache                     25051
cache size                          17.9 GB
max cache size                     600.0 GB
z /tmp $ cat .ccache-log 
[Date PID] === CCACHE master.b25ee490 STARTED =========================================
[Date PID] Failed to stat /mydisk1/ccache/debug/db/stats: No such file or directory
z /tmp $ 
```

**Comment by jrosdahl** [comment]
Thanks for the bug report! Next time, please choose _Bug report_ instead of _Question_ as the issue type when reporting a bug.

**Comment by jrosdahl** [comment]
> A warning message is generated by ccache -s in file .ccache.log. ccache -s should not generate any warning message.

To clarify, _"Failed to stat /mydisk1/ccache/debug/db/stats: No such file or directory"_ is not a warning message but a diagnostics message that is part of the debug log. That a `.ccache.log` file is created when debug mode is enabled is however a bug. That said, I've suppressed said diagnostics message since it's a bit superfluous.
