### ISSUE TITLE
Source tarballs do not report correct version

### ISSUE THREAD

**Issue by AlexanderLanin** [ccache/ccache#667]
### How to reproduce ###
1. Theoretically: Download "Source code" from 4.0.0 Release.
2. Alternative: Download https://github.com/ccache/ccache/archive/master.zip
3. run `cmake .`

### Actual behavior ###
* Without #665: fails with `Cannot determine ccache version`
* With #665: when running `./ccache --version` it reports 0.0.0

### Expected behavior ###
* We expect it to compile
* We expect it to report something more meaningful then 0.0.0
* If it's a tagged commit we expect it to report the tag version (e.g. 4.0.0)
* If it's not a tagged commit... well.. here it gets difficult... what do we expect? To be really honest it's a dirty flag I would expect.

### Motivation ###
Users and even some package mangers will use the latest github official source tarballs and not the ones that are provided as additional files to build ccache. That's also what you get when you pick a random commit and download the code.

### Common solutions ###
* Require a "-DVERSION" flag when cmake is called (@afbjorklund do you have an example for that?)
* Store the version within the repository:
  * Within a header file (which is currently generated by cmake from git tags) (e.g. fmt)
  * Within CMakeLists.txt (e.g. llvm)
  * Within a separate cmake file (e.g. cmake).

#### Recommendation by professional CMake ####
When you will not be able to maintain it fetch the version from git. If you can maintain it, create a separate cmake file which contains only the version (as cmake does... no surprise there 😉).

#### What do those non tagged commits report? ####
* every commit before the tag reports the same version number as the tag (e.g. llvm)
* every commit after the tag reports the same version number as the tag (e.g. fmt)
* all non tagged commits report some dirty version (e.g. cmake)

### Conclusion ###
Obviously storing the version within the repository will create some overhead. So that part is for @jrosdahl to decide.
If it is stored within the repository, then the cmake approach seems the best one. Since the others basically report fake versions.

In order to reduce overhead at least a little a GitHub Action should be added:
Create tag automatically when CcacheVersion.cmake changes? Add a commit with a dirty flag right after the tagged one?

**Comment by afbjorklund** [comment]
Actually it doesn't work from git either:

make
```
$ ./ccache --version
ccache version 3.7.11+6_g3f77bbd2
```

cmake
```
$ ./ccache --version
ccache version master.dc68fa7a
```

There is no 4.0 anywhere, just "master".

**Comment by afbjorklund** [comment]
> Require a "-DVERSION" flag when cmake is called (@afbjorklund do you have an example for that?)

It doesn't have to be called VERSION of course, but _somewhere_ to supply the "4.0" value ?

`cmake -DCCACHE_VERSION=4.0 -DCMAKE_BUILD_TYPE=Release ..`

So by default it would go with some weird "0.0.0" or "master" or "unknown" or whatever.
Alternative it could die with "git: command not found", or - worst of all - get the _wrong_ git*.

So instead the poor user would supply a version to the build process, and it would skip all git.

\* The "wrong git" part happens to me with Buildroot. There I have a git branch with the build recipes,
but the source code lives in tarballs. So when the build system runs `git`, it gets Buildroot's version...

----

I think "normally" you would just add the version to the CMakeLists.txt, and bump it when it changes ?

```CMake
project(ccache LANGUAGES C CXX ASM VERSION 4.0)
```

But it wouldn't know if it was a later snapshot, or if it was the official release.

Alternatively you could tag on release branches (svn-style), but I hate that...

This usually means that there are no tags at all on "master", so `git describe` fails.
And you have different commit revisions, only differing by release versions ? eww.

I'm not sure there is a good solution to this. People would just **have** to use git, I guess.
They already have to install all other developer commands like `cmake` and `gperf` ?

It would be nice if there was a way to build from release tarball, but that can be separate.
For instance you could just do something similar to `make dist` and regular software...

https://www.gnu.org/prep/standards/html_node/Releases.html#Releases

**Comment by afbjorklund** [comment]
> In order to reduce overhead at least a little a GitHub Action should be added:

I find this behaviour rather disturbing. When I once forked a repo, it started releasing...

i.e. pushing a tag to my private fork was enough to start the release snowball rolling :-O

**Comment by pfultz2** [comment]
Cppcheck usually appends `.99` or `dev` to the version after a release:

https://github.com/danmar/cppcheck/commit/97fd51edd1e454f37ee19259f98d6bb419eb61e5

You could probably write a script to automate this:

```
echo $1 > VERSION
git commit -a -m "Set release version"
git tag $1
git push --tags

echo "$1.99" > VERSION
git commit -a -m "Set dev version"
git push
```

**Comment by AlexanderLanin** [comment]
CppChecks bumps version-file to release version just before tagging. On one of the next commits they create the tag. On one of the next commits they add this "99" to version-file to indicate it's dirty. So they have ~3 commits which would report the same version when compiled from source. That's better than others, but not perfect.

I have a GitHub action 99% ready to automatically add "dirty" to the version-file right after a tag is pushed. However that only makes sense when you tag the last commit on a branch. This still requires that the maintainer bumps the version-file and tags exactly that commit. So I'm not quite happy.

How about simply doing the entire thing via GitHub Actions?
A manually triggered workflow which would set the version within version-file, commit, create a tag, add a dirty flag to the version-file, commit, push everything. All in one workflow. No chance for multiple commits having the same version info.

**Comment by jrosdahl** [comment]
@AlexanderLanin wrote:
> Download https://github.com/ccache/ccache/archive/master.zip
> [...]
> We expect it to compile

That's not what I expect since it's intentional to make it not compile. :slightly_smiling_face:

> Users and even some package mangers will use the latest github official source tarballs and not the ones that are provided as additional files to build ccache. That's also what you get when you pick a random commit and download the code.

Do they? I'm now aware of cget but I'm so far not convinced that it's a use case worth supporting.

> ### Common solutions ###
> * Require a "-DVERSION" flag when cmake is called (@afbjorklund do you have an example for that?)

That would be fine by me.

> * Store the version within the repository:

I would like to avoid that since it opens up for human errors or unnecesssary CI pipeline complexity.

@afbjorklund wrote:
> Actually it doesn't work from git either:
> [...]
> ```
> $ ./ccache --version
> ccache version master.dc68fa7a
> ```
> 
> There is no 4.0 anywhere, just "master".

That's intended so I would say that it works like intended. :slightly_smiling_face: 

> > In order to reduce overhead at least a little a GitHub Action should be added:
> I find this behaviour rather disturbing. When I once forked a repo, it started releasing...

I have the same gut feeling. I'm not very interested in using actions for this.

**Comment by pfultz2** [comment]
> > Require a "-DVERSION" flag when cmake is called (@afbjorklund do you have an example for that?)
> 
> That would be fine by me.

The cmake variable should be names as `CCACHE_VERSION` to avoid any conflicts.

**Comment by jrosdahl** [comment]
I've thought some more about this.

I found out that the source archives you can download from GitHub actually are generated by `git archive` (or something that emulates that command) which means that the `export-subst` attribute can be used to make the exported source code include the commit hash and tag name (if any). The CMake script can then deduce good enough version information when building from a source archive. I hope everybody will be happy with this solution.
