### ISSUE TITLE
Improve documentation about base_dir usage

### ISSUE THREAD

**Issue by pbelskiy** [ccache/ccache#668]
Hello! 

I've also faced with non clear documentation about how to properly set base_dir.

There are two interpretation, anв what is correct usage?
1) use CCACHE_BASEDIR = /tmp/dist/<ID> for each unique build id?
2) use CCACHE_BASEDIR = /tmp/dist as parent directory?

Same questions over the internet:
- https://lists.samba.org/archive/ccache/2014q2/001185.html
- https://stackoverflow.com/questions/11918463/ccache-basedir-shared-configuration
- https://ccache.samba.narkive.com/pGWXXPEW/proper-usage-of-ccache-basedir
- https://github.com/ccache/ccache/issues/212

I suggest to add examples to current documentation or improve it:

> base_dir (CCACHE_BASEDIR)
> This setting should be an absolute path to a directory. ccache then rewrites absolute paths into relative paths before computing the hash that identifies the compilation, but only for paths under the specified directory. If set to the empty string (which is the default), no rewriting is done. A typical path to use as the base directory is your home directory or another directory that is a parent of your build directories. Don’t use / as the base directory since that will make ccache also rewrite paths to system header files, which doesn’t gain anything.
> 
> See also the discussion under COMPILING IN DIFFERENT DIRECTORIES.
>

**Comment by jrosdahl** [comment]
I agree that it seems like people don't interpret the documentation correctly so it sounds good if we can find some improvment.

There is already an example, though: _"A typical path to use as the base directory is your home directory or another directory that is a parent of your build directories."_

Do you think that it would be more clear if we added something like this? _"For example, let's say that you have build directories /home/jdoe/build/directory1, /home/jdoe/build/directory2 and  /home/jdoe/build/directory3. A good base_dir value would then be /home/jdoe. /home or /home/jdoe/build would also work just as fine. There is no need to set base_dir to /home/jdoe/build/directory1 when compiling in /home/jdoe/build/directory1, etc."_

**Comment by pbelskiy** [comment]
Probably yes, also it's not clear for example for me how it works (base_dir) for proper understanding of it usage

**Comment by jrosdahl** [comment]
> Probably yes, also it's not clear for example for me how it works (base_dir) for proper understanding of it usage

OK, here's the description of how it works: _"ccache then rewrites absolute paths into relative paths before computing the hash that identifies the compilation"_. This is technically correct but I can understand that it's not clear _why_ this is done, or maybe even what "rewrite to relative path" means if you haven't thought much about how these things work.

I spent some time to reformulate the description and add some examples: 43e89dfceba97764eb3124f340d4b48dc6422905. Do you think it's clear enough?

**Comment by pbelskiy** [comment]
Thanks, super clear now! You even write more verbose than I was expected

**Comment by AlexanderLanin** [comment]
Does it make sense to add a recommendation to "set the base_dir to where you store your repositories, e.g. ~/repos/" ?

**Comment by jrosdahl** [comment]
> Does it make sense to add a recommendation to "usually set the base_dir to where you store your repositories, e.g. ~/repos/" ?

Isn't _"A typical path to use as *base_dir* is your home directory or another directory that is a parent of your project directories."_ already saying essentially this?

If reformulating in some way, I would like to keep using some more generic concept than "repositories" since the code doesn't need to be in a repository.

**Comment by AlexanderLanin** [comment]
@jrosdahl: The point is a different one. You are saying "if you set base_dir, set it to your home directory". My question was whether it makes sense to add "Setting base_dir is recommended".

**Comment by jrosdahl** [comment]
> @jrosdahl: The point is a different one. You are saying "if you set base_dir, set it to your home directory". My question was whether it makes sense to add "Setting base_dir is recommended".

Ah. Such a recommendation is already present in the _Compiling in different directories_ section. As I see it we shouldn't recommend setting `base_dir` in the general case since there are some disadvantages if you **don't** need to share cache entries between different directories: the expansion of `__FILE__` will be different, paths in compiler diagnostics messages may become incorrect (see also the `absolute_paths_in_stderr` hack), etc.
