### ISSUE TITLE
Unable to specify individual C and CPP compiler through options

### ISSUE THREAD

**Issue by Karsten1987** [ccache/ccache#672]
### Question ###
I am trying to use the latest llvm on my OSX as the stock clang doesn't have all sanitizers enabled. While reading through the options of ccache, I found that I can specify a name of the compiler via `CCACHE_COMPILER`. However, I am unable to specify which compiler to be used when compiling either c-only or c++.

Below the configuration I am using.
```
export PATH="/usr/local/opt/llvm/bin:$PATH"
export PATH="/usr/local/opt/ccache/libexec:$PATH"
export CCACHE_COMPILER="clang++"
export CCACHE_PATH="/usr/local/opt/llvm/bin"
```

When I set the `CCACHE_COMPILER` name to `clang` (note the lack of `++`) I am not able to compile any `*.cpp` files, when set as depicted to `clang++`, I get a warning (`clang-10: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]`) when compiling a `*.c` file.

My question is thus how to solve this, what's the right name of the compiler to specify here that `clang` is used for `.c` files and `clang++` for `.cpp` files.

I couldn't really find a decent solution with my naive googling skills and I hope this question is not too cumbersome. Thanks in advance.

**Comment by jrosdahl** [comment]
> My question is thus how to solve this, what's the right name of the compiler to specify here that `clang` is used for `.c` files and `clang++` for `.cpp` files.

Like you've noticed there's currently no way for ccache to use different values of `CCACHE_COMPILER`.

Would it be possible for you to configure your build to use the compilers in `/usr/local/opt/llvm/bin` directly instead?

**Comment by Karsten1987** [comment]
Apologies for no responding on time.
What seemed to have helped is simply setting `CC` and `CXX` correctly and ccache will pick it up.

For future references, the snippet in my `.bash_profile`:
```
# set llvm-clang as default
export PATH="/usr/local/opt/llvm/bin:$PATH"
export CC="clang"
export CXX="$CC++"
export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
export CPPFLAGS="-I/usr/local/opt/llvm/include"

# set ccache to search for llvm-lang
export PATH="/usr/local/opt/ccache/libexec:$PATH"
```
