### ISSUE TITLE
Cache stderr even without object file

### ISSUE THREAD

**Issue by AlexanderLanin** [ccache/ccache#683]
No object file is no reason for not caching.
This happens for example when using clang/clang++/g++ and using the `-fsyntax-only` option.
While some of the benefits of the cache are lost, so are some of the cost.
So it's likely still worthwhile to cache the result.

The current behavior was introduced in https://github.com/ccache/ccache/commit/131111cd58945ab20aea8b75a7d476376956eb55.

I'm not sure about any major use case besides clang itself (and probably gcc) having test suites which run hundreds of files with `-fsyntax-only`. Maybe some build systems test language support that way since it's quicker than actually compiling.
I guess this does not add any complexity to ccache and even the implementation will not touch more than 10 lines of code.

Discussion points:
* Is there any specific reason to not cache this result?
* Should this be configurable?
* Cache only if CCACHE_PREFIX is empty to avoid problems as addressed by https://github.com/ccache/ccache/commit/131111cd58945ab20aea8b75a7d476376956eb55?
* How to deal with nocpp2 as it triggers `warning: argument unused during compilation: '-fsyntax-only' [-Wunused-command-line-argument]`?

**Comment by jrosdahl** [comment]
> Cache stdout/err

(Just a note: ccache has never cached stdout. But it would now be easy to cache stdout if wanted due to the introduction of aggregated result files.)

> * Is there any specific reason to not cache this result?

As I guess you've seen in the commit message of 131111c already, the motivation was to avoid caching suspect results.

> * Should this be configurable?
> * Cache only if CCACHE_PREFIX is empty to avoid problems as addressed by [131111c](https://github.com/ccache/ccache/commit/131111cd58945ab20aea8b75a7d476376956eb55)?

How about allowing missing object file only if `-fsyntax-check` or `-S` is specified? I would prefer not to add a configuration option for this.

> * How to deal with nocpp2 as it triggers `warning: argument unused during compilation: '-fsyntax-only' [-Wunused-command-line-argument]`?

Perhaps force `run_second_cpp` to `true` when `-fsyntax-check` is used?

**Comment by AlexanderLanin** [comment]
> (Just a note: ccache has never cached stdout. But it would now be easy to cache stdout if wanted due to the introduction of aggregated result files.)

Oh right. It's an interesting topic - at least in order to support MSVC. But it's not relevant for this issue.

> How about allowing missing object file only if `-fsyntax-check` or `-S` is specified?

Sounds good, this avoids ALL potential problems.

> I would prefer not to add a configuration option for this.

Agreed!

**Comment by AlexanderLanin** [comment]
> How about allowing missing object file only if `-fsyntax-check` or `-S` is specified? I would prefer not to add a configuration option for this.

Why `-S`? As far as I can see that only changed the extension from `.o` to `.s`.

**Comment by jrosdahl** [comment]
> Why `-S`? As far as I can see that only changed the extension from `.o` to `.s`.

Right, I was clearly thinking about something else. Not sure what, though. :thinking:
