### ISSUE TITLE
man page does not build by default for ccache-4.0

### ISSUE THREAD

**Issue by trofi** [ccache/ccache#684]
I have `asciidoc` installed in my system. When I build cmake man page does not get built and installed by default:

```
$ git clone https://github.com/ccache/ccache
$ mkdir build
$ cd build
$ cmake ../cmake
$ make
...
$ ls doc/
CMakeFiles  Makefile  cmake_install.cmake

$ make doc-man-page
$ ls doc/
CMakeFiles  Ccache.1  MANUAL.xml  Makefile  cmake_install.cmake
```

A few issues here:
1. `Ccache.1` seems to be in in wrong case. `man ccache` would not find it.
1. Would it make sense to build (and install) `ccache.1` by default if `asciidoc` is detected at cmake time?

Thank you!

**Comment by jrosdahl** [comment]
Thanks for the bug report.

I also noticed the first issue earlier today. I'll fix it shortly.

I agree that it would make sense to build and install documentation by default if possible, just like in 3.x.
