### ISSUE TITLE
Failed to create temporary file - permission denied

### ISSUE THREAD

**Issue by ffparra303** [ccache/ccache#703]
I saw this reply to an issue on failed to open a temporary file. I get the same error shown below. Does anyone know how to solve it? Thanks!

On the other hand, if `$CCACHE_DIR/tmp` is unwritable by the current user, the error message looks similar to this:

`ccache: error: Failed to create temporary file for /home/joel/.ccache/tmp/hashutil.stdout: Permission denied`

I.e., not the same as the one in this bug report.

_Originally posted by @jrosdahl in https://github.com/ccache/ccache/issues/154#issuecomment-462065851_

**Comment by AlexanderLanin** [comment]
Feel free to tell us more about your setup ;-)
OS, ccache version, exact error message you get.

**Comment by Romain-Geissler-1A** [comment]
Hi,

FYI I recently tried to migrate my company builds to ccache 4.0 (we used 3.7.12 before) and indeed several different unrelated teams started to report me such errors.

I am right now not 100% sure this actually comes from ccache 4.0, but time wise, the problem started to happen when I switched it on by default. Our setup is:
 - Linux OSes
 - shared NFS ccache directories. So in our cases, chmod/umask is important.

It apparently happens on one of my ccache folder two, where only 2 users that I trust are using. I can see the following folder/rights:

```
drwxrwxrwx 18 combld root  357 Oct 26 00:42 .
drwxrwxrwt 18 combld root  333 Oct 25 00:01 ..
drwxrwxrwx  2 combld root 3723 Oct 26 00:38 0
drwxrwxrwx  2 combld root 3723 Oct 26 00:39 1
drwxrwxrwx  2 combld root 3473 Oct 26 00:42 2
drwxrwxrwx  2 combld root 3573 Oct 26 00:42 3
drwxrwxrwx  2 combld root 2823 Oct 26 00:41 4
drwxrwxrwx  2 combld root 2723 Oct 26 00:42 5
drwxr-xr-x  2 combld root 2273 Oct 26 00:39 6
drwxr-xr-x  2 combld root 3273 Oct 26 00:39 7
drwxr-xr-x  2 combld root 3723 Oct 26 00:42 8
drwxr-xr-x  2 combld root 3223 Oct 26 00:42 9
drwxr-xr-x  2 combld root 3373 Oct 26 00:38 a
drwxrwxrwx  2 combld root 3473 Oct 26 00:42 b
drwxr-xr-x  2 combld root 4073 Oct 26 00:39 c
-rw-rw-rw-  1 combld root  190 Oct 25 00:01 CACHEDIR.TAG
drwxr-xr-x  2 combld root 4323 Oct 26 00:39 d
drwxrwxrwx  2 combld root 2923 Oct 26 00:39 e
drwxrwxrwx  2 combld root 3273 Oct 26 00:42 f
-rw-rw-rw-  1 combld root   76 Oct 26 00:42 stats
```

as you can see, some folders are created with chmod 777 (so that anyone can update it, as expected for NFS ccache folder) while others are not writable by group/other. It seems strange, because normally that "combld" user shall always use the same config with the same umask when launching ccache. I don't have more details yet.

**Comment by Romain-Geissler-1A** [comment]
More details on my above issue. I see to be able to always reproduce it on a simple (proprietary) code repository of about 20/30 .cpp files in total.

We do run ccache with this in the environment:
CCACHE_DIR=XXX
CCACHE_BASEDIR=XXX
CCACHE_NOLINK='1'
CCACHE_UMASK='000'
CCACHE_SLOPPINESS='time_macros'

the ccache directory is created by our own proprietary build system, with (in my reproducer case) permission '02777'.

I tried the following:
 - remove entirely the ccache folder
 - run a build with ccache enabled (with the config on top)
 - see the result in the ccache directory with the following command: find /path/to/ccache ! -perm '-a=w'

With 3.7.12: "find" doesn't show any file or folder.
With 4.0.0: "find" seems in my case to always return one folder containing a unique file name "stats". This is only for one folder, while all the others have correct unix rights. For example:

```
rgeissler@ncerndobedev6097:~/wk/ContextMapper (release/15.0.0 *% u=)> find ccache ! -perm '-a=w'
ccache/6/7
ccache/6/7/stats
rgeissler@ncerndobedev6097:~/wk/ContextMapper (release/15.0.0 *% u=)> ls -la ccache/6/7
total 12
drwxr-sr-x 2 rgeissler dev_air 4096 Oct 26 14:05 .
drwxrwsrwx 8 rgeissler dev_air 4096 Oct 26 14:05 ..
-rw-r--r-- 1 rgeissler dev_air   66 Oct 26 14:05 stats
rgeissler@ncerndobedev6097:~/wk/ContextMapper (release/15.0.0 *% u=)> ls -la ccache/6/a
total 964
drwxrwsrwx 2 rgeissler dev_air   4096 Oct 26 14:05 .
drwxrwsrwx 8 rgeissler dev_air   4096 Oct 26 14:05 ..
-rw-rw-rw- 1 rgeissler dev_air 452064 Oct 26 14:05 383j0vh1cgnn2v3gigpnib1bu11tj9eR
-rw-rw-rw- 1 rgeissler dev_air 520621 Oct 26 14:05 76lf1v3ekeevchqg669opbfem2l5k5iR
```

I have the following suspicion: we do use "ccache" also when we do link our libraries/binaries, and obviously in these case ccache can't cache anything. So in that case, i would expect we have only a folder filled with just a "stats" file. It is possible that when that is the case, and when the folder doesn't exist yet, ccache 4.0 creates it with the original umask and ignore CCACHE_UMASK ?

Note: maybe we do have other cases where directories/files aren't correctly created using CCACHE_UMASK, this is just one case that I seem to be able to reproduce all the time on a small (proprietary) example.

Cheers,
Romain

**Comment by AlexanderLanin** [comment]
@Romain-Geissler-1A does the test case match what you are observing vs what you are expecting?

**Comment by jrosdahl** [comment]
(I wrote the below earlier today but didn't have time to submit it before I had to do $OTHERSTUFF.)

@Romain-Geissler-1A: Thanks for the bug report. I can reproduce the bug and have a fix for it as well. However, can you please create a separate issue for it? We don't know if @ffparra303's problem is the same since we don't even know if he's using ccache 4.0 or some older version. And judging from https://github.com/Project-OSRM/osrm-backend/issues/5870 it's not the same issue since it's about the tmp directory which isn't created by a non-cache-miss statistics update.

**Comment by Romain-Geissler-1A** [comment]
> (I wrote the below earlier today but didn't have time to submit it before I had to do $OTHERSTUFF.)
> 
> @Romain-Geissler-1A: Thanks for the bug report. I can reproduce the bug and have a fix for it as well. However, can you please create a separate issue for it? We don't know if @ffparra303's problem is the same since we don't even know if he's using ccache 4.0 or some older version. And judging from [Project-OSRM/osrm-backend#5870](https://github.com/Project-OSRM/osrm-backend/issues/5870) it's not the same issue since it's about the tmp directory which isn't created by a non-cache-miss statistics update.

Ok, my own issue is now tracked in issue #710.

**Comment by mumpitzstuff** [comment]
We get the same error now on Windows with v4.0 and the latest sources (ac13fb9a) from today (tried both versions). All ccache folders where cleaned before (cold run).

ccache: error: Failed to create temporary file for C:/workspace/PRP_RH850_STD/.ccache_tmp/tmp.stderr.FzP5tM: Permission denied

Temp folder was empty at this point or got cleaned by ccache after the error occured. The strange thing is that around 2800 files compiled before without any problems. Cleaning the cache does not help. I always get the same error now. After switching back to v3.7.12, the error was gone (cache was cleaned before running the build).

**Comment by jrosdahl** [comment]
> ccache: error: Failed to create temporary file for C:/workspace/PRP_RH850_STD/.ccache_tmp/tmp.stderr.FzP5tM: Permission denied
> 
> Temp folder was empty at this point or got cleaned by ccache after the error occured. The strange thing is that around 2800 files compiled before without any problems. Cleaning the cache does not help. I always get the same error now.

When you say that you always get the same error, do you mean literally the same error message, i.e. one including `tmp.stderr.FzP5tM`, or a different file suffix each time?

**Comment by mumpitzstuff** [comment]
I tried everything to reproduce the error today without any success. I also do not have the logfiles anymore to check the suffix. All i know is that it was always the same source file where the build stopped. And i was not alone. A colleague got also such an error for a different source file (other computer as well). The suffix here was different to my error message or course.
I switched the version back to 3.7.12 in our project so that my colleagues are not blocked but i will use the latest 4.0 version on my pc and hope i can catch the error again somehow.

**Comment by jrosdahl** [comment]
> i will use the latest 4.0 version on my pc and hope i can catch the error again somehow.

Thanks. More information would certainly be welcome. I can't find any bugs related to this just from code inspection.

**Comment by nickhutchinson** [comment]
@jrosdahl I also started getting this error in a work project after upgrading to ccache 4 from cache 3.7.x. I haven't had the time to debug this, but after a quick look at the ccache codebase it seems this error string can only be raised by TemporaryFile.cpp, and I'm very suspicious of the use of `mktemp()` at https://github.com/ccache/ccache/blob/v4.1/src/TemporaryFile.cpp#L45.

I'm not familiar with how official ccache binaries are built against on Windows, but `mktemp()` provided by the Windows C runtime [is essentially unusable](https://stackoverflow.com/a/17724998/192102) -- it chooses a filename by simply concatenating a single letter with the current thread id. If you have the Windows 10 SDK installed, you can see the source at `C:\Program Files (x86)\Windows Kits\10\Source\<sdk-version>\ucrt\lowio\mktemp.cpp`.

**Comment by jrosdahl** [comment]
> I'm not familiar with how official ccache binaries are built against on Windows, but `mktemp()` provided by the Windows C runtime [is essentially unusable](https://stackoverflow.com/a/17724998/192102) -- it chooses a filename by simply concatenating a single letter with the current thread id.

The binaries published on https://ccache.dev/download.html are cross-compiled with Mingw-w64 and they don't use the `mkstemp` replacement with `mktemp`. Oh, now I see in #736 that you found that out already.

Regardless, it would be good to get rid of the "Cheap and nasty mkstemp replacement" which originates from 6be789637f425a4ea5c9701a20057ca355a98ec1 (almost 18 years ago!), presumably to support some old Unix system.

**Comment by jrosdahl** [comment]
Reopening since this Windows-specific issue now is well understood (see #736).

**Comment by bedwardly-down** [comment]
Even though this bug report is old but it's not Windows only. When running SELinux (access control security protocol) in "strict" mode, this error can show up when there's no default policy for ccache available and the admin hasn't created one for it.

**Comment by blackliner** [comment]
We see this regularly, but not reproducible, on our CI. I checked permissions of the folder, and they are fine.

using ccache version 3.4.1 on Ubuntu 18.04.
```
[2022-05-09T04:37:04.950Z] -- The CXX compiler identification is GNU 7.5.0
[2022-05-09T04:37:04.950Z] -- Detecting CXX compiler ABI info
[2022-05-09T04:37:04.950Z] -- Detecting CXX compiler ABI info - failed
[2022-05-09T04:37:04.950Z] -- Check for working CXX compiler: /usr/lib/ccache/g++-7
[2022-05-09T04:37:04.950Z] -- Check for working CXX compiler: /usr/lib/ccache/g++-7 - broken
[2022-05-09T04:37:04.950Z] CMake Error at /usr/share/cmake-3.21/Modules/CMakeTestCXXCompiler.cmake:62 (message):
[2022-05-09T04:37:04.950Z]   The C++ compiler
[2022-05-09T04:37:04.950Z] 
[2022-05-09T04:37:04.950Z]     "/usr/lib/ccache/g++-7"
[2022-05-09T04:37:04.950Z] 
[2022-05-09T04:37:04.950Z]   is not able to compile a simple test program.
[2022-05-09T04:37:04.950Z] 
[2022-05-09T04:37:04.950Z]   It fails with the following output:
[2022-05-09T04:37:04.950Z] 
[2022-05-09T04:37:04.950Z]     Change Dir: /home/luminar/.conan/data/lum_common_swc/1.0.0/_/_/build/d57fc0c5f5ea0328387eba10d67f488d5cb091e1/CMakeFiles/CMakeTmp
[2022-05-09T04:37:04.950Z]     
[2022-05-09T04:37:04.950Z]     Run Build Command(s):/usr/bin/make -f Makefile cmTC_1dfca/fast && /usr/bin/make  -f CMakeFiles/cmTC_1dfca.dir/build.make CMakeFiles/cmTC_1dfca.dir/build
[2022-05-09T04:37:04.950Z]     make[1]: Entering directory '/home/luminar/.conan/data/lum_common_swc/1.0.0/_/_/build/d57fc0c5f5ea0328387eba10d67f488d5cb091e1/CMakeFiles/CMakeTmp'
[2022-05-09T04:37:04.950Z]     Building CXX object CMakeFiles/cmTC_1dfca.dir/testCXXCompiler.cxx.o
[2022-05-09T04:37:04.950Z]     /usr/lib/ccache/g++-7    -o CMakeFiles/cmTC_1dfca.dir/testCXXCompiler.cxx.o -c /home/luminar/.conan/data/lum_common_swc/1.0.0/_/_/build/d57fc0c5f5ea0328387eba10d67f488d5cb091e1/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
[2022-05-09T04:37:04.950Z]     ccache: error: Failed to create directory /home/luminar/.ccache/tmp: Permission denied
[2022-05-09T04:37:04.950Z]     CMakeFiles/cmTC_1dfca.dir/build.make:77: recipe for target 'CMakeFiles/cmTC_1dfca.dir/testCXXCompiler.cxx.o' failed
[2022-05-09T04:37:04.950Z]     make[1]: *** [CMakeFiles/cmTC_1dfca.dir/testCXXCompiler.cxx.o] Error 1
[2022-05-09T04:37:04.950Z]     make[1]: Leaving directory '/home/luminar/.conan/data/lum_common_swc/1.0.0/_/_/build/d57fc0c5f5ea0328387eba10d67f488d5cb091e1/CMakeFiles/CMakeTmp'
[2022-05-09T04:37:04.950Z]     Makefile:127: recipe for target 'cmTC_
```
