### ISSUE TITLE
How to compile ccache for Windows

### ISSUE THREAD

**Issue by mumpitzstuff** [ccache/ccache#707]
### Description ###

It is possible to compile ccache for windows by following these simple steps:

1.) Install MSYS2.
2.) Open MSYS2 MSYS console and run "pacman -Syu" multiple times until everything is updated.
3.) Close MSYS2 MSYS console and open MSYS2 MinGW 64-Bit console.
4.) Install "pacman -S mingw-w64-x86_64-gcc".
5.) Install "pacman -S mingw-w64-x86_64-cmake".
5.) Install "pacman -S make".
6.) Install "pacman -S zstd".
7.) Switch to ccache directory and create build directory "mkdir build".
8.) Edit CMakeLists.txt and add this line to create static linked exe file: "set(CMAKE_EXE_LINKER_FLAGS "-static")".
9.) Edit C:\msys64\home\username\\.bashrc and add this line: "PATH=$PATH:/mingw64/bin/gcc:/mingw64/bin/cmake".
10.) Restart the MSYS MinGW 64-Bit console.
11.) Switch to build directory within ccache directory and run: "cmake -DCMAKE_BUILD_TYPE=Release -DZSTD_FROM_INTERNET=ON -G "MSYS Makefiles" ..".
12.) Run "make".

May be the docu can be enhanced because it costs me quite a while to get everything to work...

**Comment by AlexanderLanin** [comment]
Hi,

looks nice, that's a step by step instruction 👍 
Ideally we could add this to CI.

Most of this seems more MSYS2 related then ccache related, is that right?
Don't get me wrong, I'm not against a section on "how to compile for MSYS2".
Although I do wonder about relevance a little bit considering the jump in 2015:
https://trends.google.de/trends/explore?date=all&q=mingw,msys2,wsl

Could you explain step 8?

I assume step 9 is for making steps 4+5 available?

The use case is having ccache in MSYS2 environment where you use it with gcc/clang?

**Comment by mumpitzstuff** [comment]
It is more or less the preparation of MSYS2 to get the ccache build to work. MSYS2 is just the base to install gcc, cmake and other tools as easy as possible.

Step 8 is needed to compile the exe without any dll dependencies (needed dlls will become part of the executable).
Step 9 was needed because because the msys version of gcc and cmake is may be installed in parallel and without this path the wrong version was used. It is also possible to uninstall the msys versions of gcc and cmake before with "pacman -R gcc" and "pacman -R cmake" and install the mingw versions afterwards. If you dont do that or if you try to use the msys console instead of the mingw console, you will get also an exe file but you will always need a seperate dll msys-2.0.dll. Another strange thing was that all _WIN32 parts where completly ignored and e.g. InodeCache.cpp was part of ccache and it was possible to activate it but the generated inodes where always 0 or something like that. It was not clear to me what was really working in this version and what was not working.

The use case for me is to use it as normal compiler cache for some gcc derivates (embedded c software) completly outside of the msys2 environment. msys2 was just used to compile ccache. I never used it before for anything else, but i was really impressed how easy it was to get it to work.

**Comment by jrosdahl** [comment]
> May be the docu can be enhanced because it costs me quite a while to get everything to work...

Another option would be to add hints like this to the ccache wiki (which is currently unused). I think that would make more sense than keeping detailed instructions in the official documentation.
