### ISSUE TITLE
Option to specify configuration file

### ISSUE THREAD

**Issue by dyadav7** [ccache/ccache#719]
### Description ###

I do not want to set environment CCACHE_CONFIGPATH. 
Is there a way to specify the config path file with an option of ccache ?
   e.g.  ccache -configpath <ccache_config_path> ....

**Comment by jrosdahl** [comment]
No.

Could you describe your use case? Why do you want to specify the config path in the first place?

**Comment by dyadav7** [comment]
I have use 3 different  ccache configuration files. I have a script that generated the ccache command line So, I want to pass all the ccache setting specified in command line itself. 
ccache should allow a mode in which it does not depend on any environment variable. It uses command line and its arguments to gather all configuration settings.
Environment  commands (setenv/export) are also shell specific (csh / bash). This also introduces some complexity.

**Comment by jrosdahl** [comment]
> I have use 3 different ccache configuration files. I have a script that generated the ccache command line So, I want to pass all the ccache setting specified in command line itself.

It's easy to add such an option so I can do it.

Just curious: why do you use three different ccache configuration files, presumably for the same ccache directory?

> Environment commands (setenv/export) are also shell specific (csh / bash). This also introduces some complexity.

Just a tip: you can use the `env` command (example: `env CCACHE_CONFIGPATH=/path/to/config ccache ...`) to make it work with any shell if you like.

**Comment by dyadav7** [comment]
I use 3 different config file with 3 different dbs.  One each for debug, optimized and one other build type. 
Thanks for the tip and adding the new option in ccache.
