### ISSUE TITLE
Missing link with -latomic on PowerPC: error: undefined reference to '__atomic_fetch_add_8'

### ISSUE THREAD

**Issue by cruxppc** [ccache/ccache#721]
### How to reproduce ###
Build of ccache 4.0 on powerpc (32 bit) fails with undefined references to several `_atomic_*` routines.

The atomic library needs to be included for the build to complete.    

I know almost nothing about cmake builds but I found a patch for the same problem in another package and adapted that patch to my ccache build.   The build of ccache then completed.    I have my experimental 
[ppc.patch.txt](https://github.com/ccache/ccache/files/5498200/ppc.patch.txt)
patch as a possible fix for this problem but as I know virtually nothing about cmake, I think it would be best if the ccache build experts reviewed the problem and patch and determined what the proper fix is.

**Comment by jrosdahl** [comment]
Thanks for the bug report. Could you try if #723 fixes the problem?
