### ISSUE TITLE
Discovery of symbolic link directory

### ISSUE THREAD

**Issue by schallee** [ccache/ccache#726]
It would be useful to be able to query the directory containing the compiler symbolic links could be discovered. This could be achieved by adding it to the configuration output or a separate scripting flag.

I'm writing a script to build several on different platforms that have tight version requirements (which frustratingly makes the different package management systems not interoperable). Not surprisingly these compiles, especially when debugging the script, benefit from ccache.

Finding ccache in the path is trivial but finding the directory with the compiler symbolic links is less so. For example: debian has it in /usr/lib/ccache but home brew on osx has it in /usr/local/opt/ccache/libexec. Rather than searching it would be much easier to query ccache itself and then add the directory to the PATH as needed.

Thanks for all the work on ccache!

**Comment by jrosdahl** [comment]
Thanks for the suggestion.

Just for clarity (and you probably know already): the system's symlink directory, if any, is not something that ccache currently knows about. I guess you mean that a symlink directory should be a parameter to set when building ccache? Some questions come to mind: Should it be a required parameter? If no, how should we ensure that distributions set it when building ccache? If yes, what if there are several directories in the system, or none at all?

Or (and maybe this is what you had in mind), it could be an ordinary ccache configuration option. Then it will be up to distributors to set a suitable value in `/etc/ccache.conf` or similar.

**Comment by schallee** [comment]
My apologies for the late reply (I don't log into github enough).

I was confused myself here. I was under the impression that ccache's install created a directory containing symbolic links for various compilers (eg: /usr/libexec/ccache/g++ -> /usr/bin/ccache). After taking a look at the build and various packaging of ccache I realized that ccache doesn't create such itself. Apparently the packagers are creating such directories. This actually makes sense as they would have a better idea what compilers are present than ccache itself.

It turns out I'm making a request for a feature adding functionality to a feature that isn't part of ccache. That doesn't make much sense so I'll close it;) Thanks for your patience!
