### ISSUE TITLE
Suggestion: either retire https://www.samba.org/ftp/ccache/?C=M;O=D or sync it automatically with the github release page

### ISSUE THREAD

**Issue by rubyFeedback** [ccache/ccache#727]
### Description ###

Hey ccache devs,

Please have a short look here:

https://www.samba.org/ftp/ccache/?C=M;O=D

This was the old FTP site for downloads. I know it because I keep track
of these files in local yaml files. :)

There has not been any update to this in about a year or so.

On github, though, ccache is very active, so I assume the ccache devs
are nowadays mostly using github. I don't care either way, BUT!

I would like to recommend to do any of the following:

a) retire the old https://www.samba.org/ftp/ccache/?C=M;O=D completely
b) sync both github and ccache FTP listing ^^^

b) is probably more work than a). You can reason that it should be
synced, so b) may be better, but in my experience this always causes
delays, people forget it, or the workflow does not work that well.

So we already have the case that the old FTP listing isn't really 
updated that frequently. I would simply recommend a).

If ftp-listings are ever coming back, you can easily re-enable
it (I suppose github even allows the version history of the
releases to be exported; or perhaps even git allows that,
no idea, so even retiring the FTP listing should not be a 
problem. Since it is not updated as frequently as the
github archive release pages, people may have the wrong
impression that ccache is dead)

PS: There may be more solutions than the two I suggested
of course. My main point is that an old, outdated FTP
listing does more harm than good. Now that I updated that
yaml file, to point at the github release page for ccache, I
no longer have this problem, so I report this just in case
anyone else runs into this or a similar problem. Otherwise
I would not have spent the time to raise the issue just now,
but please feel free to close this issue request at any moment
in time. :)

**Comment by jrosdahl** [comment]
Thanks for the suggestion.

The old release directory is intentionally left as is because I don't want to unnecessarily break any workflows that happen to download files from the old place. I'm also not interested in uploading new releases to it since it simply isn't the place for new releases. (Actually, I don't think I have access to it anymore.)

> My main point is that an old, outdated FTP listing does more harm than good

I can understand your perspective, but I think that it's the other way around.
