### ISSUE TITLE
Please include necessary LIBs for Win compile again ...

### ISSUE THREAD

**Issue by Alpengreis** [ccache/ccache#729]
### Description ###

In the newest version 4.1 for win (64-bit), the following DLLs are missing and ccache does not run correctly:

libstdc++6.dll
libwinpthread-1.dll
libgcc_s_seh-1.dll

If I compare the compiled file to version 4.0, I see that the file is now much smaller. So I assume, you forgot to include the LIBs statically.

PS: If I copy those DLL files from "c:\Program Files\Git\mingw64\bin\" to the "ccache directory" it runs again.

**Comment by cristianadam** [comment]
This was caused by https://github.com/ccache/ccache/commit/d2eb812ebe8a51085a5d348bbab7ea11725588b8 

You need to configure ccache with `-DSTATIC_LINK=ON` and you will get the 4.0 behavior.

**Comment by cristianadam** [comment]
@orgads  ^^^

**Comment by Alpengreis** [comment]
Oh, I see, thank you VERY much!

**Comment by orgads** [comment]
I wasn't aware of the binary release (as a single executable). It makes sense to default to static then. Created PR #732 for that.

**Comment by Alpengreis** [comment]
Very good, thanks!
