### ISSUE TITLE
Build failure on Apple Silicon arm64 Macs

### ISSUE THREAD

**Issue by ryandesign** [ccache/ccache#734]
### How to reproduce ###

1. Build ccache 4.1 with Xcode 12.2 on macOS 11.0.1 on an Apple Silicon (arm64) Mac

### Actual behavior ###

Build failure. [Here is the full log](https://build.macports.org/builders/ports-11_arm64-builder/builds/3355/steps/install-port/logs/stdio). The errors are all of this type:

```
In file included from src/third_party/blake3/blake3_sse41.c:3:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/immintrin.h:14:
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/mmintrin.h:50:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/mmintrin.h:129:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
```
Despite the fact that the error messages appear to refer to files that are part of the development environment, I do not believe that there is a problem with the development environment.

### Expected behavior ###

Successful build.

### Environment ###

ccache version 4.1
macOS 11.0.1
Xcode 12.2
Apple Silicon Mac

**Comment by erijo** [comment]
It seems like the check for sse2, sse4.1, avx2 and avx512 support isn't good enough. They should be false om M1 since it's ARM and not x86.

The ugly workaround for now could be to pass -DHAVE_C_SSE2=FALSE, ...SSE41=FALSE, ...AVX2=FALSE, ...AVX512=FALSE and -DHAVE_AVX2=FALSE to cmake.

**Comment by ryandesign** [comment]
Thank you, that does work. [Here is the successful build log](https://build.macports.org/builders/ports-11_arm64-builder/builds/3609/steps/install-port/logs/stdio).

**Comment by erijo** [comment]
Could you try with [this branch](https://github.com/erijo/ccache/tree/improve-simd-detection) and see how it goes? In addition to trying to fix the SSE/AVX failure I've also added support for detecting Neon which the M1 should have.

**Comment by ryandesign** [comment]
> It seems like the check for sse2, sse4.1, avx2 and avx512 support isn't good enough. They should be false om M1 since it's ARM and not x86.

FYI the tests succeed for ccache 4.1 on arm64 because the flags being specified just get ignored:

```
% grep 'argument unused' CMakeFiles/CMakeOutput.log
clang: warning: argument unused during compilation: '-mavx2' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-msse4.1' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mavx2' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mavx512f' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mavx512vl' [-Wunused-command-line-argument]
```

> Could you try with [this branch](https://github.com/erijo/ccache/tree/improve-simd-detection) and see how it goes? In addition to trying to fix the SSE/AVX failure I've also added support for detecting Neon which the M1 should have.

Thanks, that seems to work as it should. On arm64 macOS 11.0.1:
```
-- Performing Test HAVE_C_SSE2
-- Performing Test HAVE_C_SSE2 - Failed
-- Performing Test HAVE_C_SSE41
-- Performing Test HAVE_C_SSE41 - Failed
-- Performing Test HAVE_C_AVX2
-- Performing Test HAVE_C_AVX2 - Failed
-- Performing Test HAVE_C_AVX512
-- Performing Test HAVE_C_AVX512 - Failed
-- Performing Test HAVE_NEON
-- Performing Test HAVE_NEON - Success
```
And on x86_64 macOS 10.13.6:
```
-- Performing Test HAVE_C_SSE2
-- Performing Test HAVE_C_SSE2 - Success
-- Performing Test HAVE_C_SSE41
-- Performing Test HAVE_C_SSE41 - Success
-- Performing Test HAVE_C_AVX2
-- Performing Test HAVE_C_AVX2 - Success
-- Performing Test HAVE_C_AVX512
-- Performing Test HAVE_C_AVX512 - Success
-- Performing Test HAVE_NEON
-- Performing Test HAVE_NEON - Failed
```
And building for i386 on x86_64 macOS 10.13.6:
```
-- Performing Test HAVE_C_SSE2
-- Performing Test HAVE_C_SSE2 - Success
-- Performing Test HAVE_C_SSE41
-- Performing Test HAVE_C_SSE41 - Success
-- Performing Test HAVE_C_AVX2
-- Performing Test HAVE_C_AVX2 - Success
-- Performing Test HAVE_C_AVX512
-- Performing Test HAVE_C_AVX512 - Success
```
