### ISSUE TITLE
Diagnostics color option can be improperly accepted

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#740]
If a cached result exists for the source file and command line (omitting color arguments), then a passed `-fcolor-diagnostics` argument is not rejected.

Example:
```
$ cat >a.c <<EOF
int main() { return 0; }
EOF

$ /usr/lib/ccache/bin/x86_64-pc-linux-gnu-gcc -c a.c

$ /usr/lib/ccache/bin/x86_64-pc-linux-gnu-gcc -fcolor-diagnostics -c a.c
```
The `-fcolor-diagnostics` option is not rejected as it should be since the cache already contains an entry for that source file and command line with the option omitted.

This causes problems for CMake, which tests the validity of numerous compiler options by attempting to compile the same trivial source file. When it attempts to check the validity of the `-fcolor-diagnostics` option, the command line matches one that it has already tested, so the test succeeds even though it ought to fail.

_Originally posted by @whitslack in https://github.com/ccache/ccache/issues/711#issuecomment-737456623_

**Comment by satmandu** [comment]
I'm seeing this issue with ccache 4.3 building webkit2gtk:
```
[689/4924] Building CXX object Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/PackedEnums.cpp.o
FAILED: Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/PackedEnums.cpp.o
/usr/local/lib64/ccache/bin/c++ -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DBUILDING_GTK__=1 -DBUILDING_WITH_CMAKE=1 -DEGL_EGL_PROTOTYPES=0 -DGETTEXT_PACKAGE=\"WebKit2GTK-4.0\" -DGL_GLES_PROTOTYPES=0 -DHAVE_CONFIG_H=1 -DJSC_GLIB_API_ENABLED -DLIBANGLE_IMPLEMENTATION -DSVN_REVISION=\"tarball\" -DWEBKITGTK_API_VERSION_STRING=\"4.0\" -I../Source/ThirdParty/ANGLE/include -I../Source/ThirdParty/ANGLE/include/KHR -I../Source/ThirdParty/ANGLE/src -I../Source/ThirdParty/ANGLE/src/common/third_party/base -I../Source/ThirdParty/ANGLE/third_party/zlib/google -ISource/ThirdParty/ANGLE/include -fcolor-diagnostics -Wextra -Wall -Wno-expansion-to-defined -Wno-noexcept-type -Wno-psabi -Wno-misleading-indentation -Wno-maybe-uninitialized -Wwrite-strings -Wundef -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wcast-align -Wno-tautological-compare -O2 -pipe -flto=auto -fuse-ld=gold -fno-strict-aliasing -fno-exceptions -fno-rtti -O3 -DNDEBUG -fPIC -std=c++17 -MD -MT Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/PackedEnums.cpp.o -MF Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/PackedEnums.cpp.o.d -o Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/PackedEnums.cpp.o -c ../Source/ThirdParty/ANGLE/src/common/PackedEnums.cpp
c++: error: unrecognized command-line option '-fcolor-diagnostics'
[690/4924] Generating ../../DerivedSources/JavaScriptCore/JSCBuiltins.cpp, ../../DerivedSources/JavaScriptCore/JSCBuiltins.h
ninja: build stopped: subcommand failed.
```

```
ccache --version
ccache version 4.3

Copyright (C) 2002-2007 Andrew Tridgell
Copyright (C) 2009-2021 Joel Rosdahl and other contributors

See <https://ccache.dev/credits.html> for a complete list of contributors.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 3 of the License, or (at your option) any later
version.
```

**Comment by satmandu** [comment]
(This looks closely related to https://github.com/ccache/ccache/issues/787 as I'm also using ccache to build webkit-gtk.)

**Comment by jrosdahl** [comment]
> I'm seeing this issue with ccache 4.3 building webkit2gtk:

@satmandu: Did you perhaps run CMake with an older ccache version before upgrading to ccache 4.3? If so you need to start over (clear the build tree and run CMake again) since CMake has cached the incorrect fact that "compiler supports -fcolor-diagnostics".

If you get the error in a clean build with ccache 4.3, please create a new bug report.

**Comment by satmandu** [comment]
@jrosdahl I'll report back if I see this again with the newly compiled ccache.
