### ISSUE TITLE
Install fails with ninja on Ubuntu 16.04

### ISSUE THREAD

**Issue by AlexanderLanin** [ccache/ccache#741]
### How to reproduce ###
```
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja -DZSTD_FROM_INTERNET=ON 
ninja
sudo ninja install
```

Does not happen without '-GNinja' when using make.

### Actual behavior ###
```
alex:~/ccache/build$ sudo ninja install
[1/1] Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:36 (file):
  file INSTALL cannot find
  "/home/alex/ccache/build/CMakeFiles/CMakeRelink.dir/ccache".


FAILED: cd /home/alex/ccache/build && /usr/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

### Environment ###
- Ubuntu 16.04
- cmake 3.5.1
- g++ 5.4
- ninja 1.5.1
- ccache `b438f50 - (origin/master) Improve SIMD detection (#735)`

**Comment by jrosdahl** [comment]
I fail to reproduce this in a container based on the [ccache-build:ubuntu-16.04 image](https://github.com/ccache/ccache/blob/master/dockerfiles/ubuntu-16.04/Dockerfile) (after installing ninja-build) with the same tool versions you indicate.

Anyway, I guess it would be good to fix it but I don't consider it a high priority (there is always the make backend).

**Comment by jrosdahl** [comment]
I've once again tried to reproduce this but can't. @AlexanderLanin: Can you?
