### ISSUE TITLE
Does not compile under C++17 standard

### ISSUE THREAD

**Issue by neheb** [ccache/ccache#749]
### How to reproduce ###

1. cmake -DCMAKE_CXX_STANDARD=17

### Actual behavior ###

fails to compile

### Expected behavior ###

compile

### Environment ###

ccache version master

host clang. Fedora 33. Error:

```
src/./Util.hpp:135:17: error: no member named 'ends_with' in 'std::basic_string_view<char, std::char_traits<char>>'
  return string.ends_with(suffix);
         ~~~~~~ ^
src/./Util.hpp:438:17: error: no member named 'starts_with' in 'std::basic_string_view<char, std::char_traits<char>>'
  return string.starts_with(prefix);
```

**Comment by totph** [comment]
That works as expected, ccache currently targets C++11. A few C++17 helpers such a `string_view` and `optional` have been added, but AFAIK to maximize compatibility there are no plans to move to C++14 or 17 in the near future.

**Comment by AlexanderLanin** [comment]
We have a CI check to ensure C++14 compatibility, but currently none for C++17/20. This is definitely not the most important feature. The only use case would be a compiler that doesn't support ancient C++11. 
Anyway this *might* be easy to fix.

**Comment by neheb** [comment]
I mean, it compiles with C++20 since.starts and end_with is there.

**Comment by jrosdahl** [comment]
I don't consider this to be a bug since ccache is built in an unsupported way. That said, I'll make it work since it's easy to do it.
