### ISSUE TITLE
Building with "-o /dev/null" when the input is cached triggers an assert

### ISSUE THREAD

**Issue by totph** [ccache/ccache#752]
1. build ccache 4.1-master (238553a1c470)
2.  export CCACHE_DIR=$PWD/foo; mkdir foo
3. echo 'void f() {}' > foo.c
4. ./ccache gcc -c foo.c -o foo.o  # fill cache
5. ./ccache gcc -c foo.c -o foo.o  # use cache (works fine, not required to trigger the bug)
6. ./ccache gcc -c foo.c -o /dev/null

This triggers an assert:

`ccache: ResultRetriever.cpp:129: virtual void ResultRetriever::on_entry_data(const uint8_t *, size_t): failed assertion:
(m_dest_file_type == FileType::stderr_output && !m_dest_fd) || (m_dest_file_type != FileType::stderr_output && m_dest_fd)`

**Comment by AlexanderLanin** [comment]
That's a valid bug report. But nevertheless I'd like to ask if there is any reasonable use case for doing that? Instead of -fsyntax-only.
