### ISSUE TITLE
Ccache exits with a fatal error when it can't open the debug log file for writing

### ISSUE THREAD

**Issue by fluffynuts** [ccache/ccache#767]
### How to reproduce ###
1. Enable ccache feature in gentoo's make.conf
2. Attempt to install / upgrade a package 

### Actual behavior ###
all packages fail to build with one of the following errors:

- C compiler cannot create executables
- Unknown compiler(s): [['x86_64-pc-linux-gnu-gcc']]

### Expected behavior ###
prior to 4.1, ccache worked brilliantly and really cut down build times for larger packages like Chrome and Firefox. After the upgrade to 4.1, nothing builds via ccache, though builds work fine if I disable ccache - obviously they simply take much longer.

### Environment ###
ccache version 4.1
OS: gentoo linux
GCC: 9.3.0

I originally raised the issue here: [https://bugs.gentoo.org/763288](https://bugs.gentoo.org/763288) but it seems that the person handling that only really handles the ebuild of ccache, so I'm trying to get help upstream. Logs are there, but if there's some other information I can furnish, please let me know. I haven't seen other people having this issue on the gentoo forums, so I'm hoping that I can be guided into finding more useful information by the project maintainers.

**Comment by fluffynuts** [comment]
PS: if you believe that this is something that should be addressed within portage too, I can add more info on the issue I raised there. I'm not sure what the "correct" solution would be, but it's a little confusing that an `emerge -1` for a package which is in the update queue could work and then break later compilations :shrug: I'm just trying to be a "good user" here (:

**Comment by afbjorklund** [comment]
It does seem a bit strange to configure ccache to log somewhere that you don't have access to.

```
[2021-01-03T17:57:58.645426 133  ] Config: (environment) cache_dir = /mnt/dump/__ccache__
[2021-01-03T17:57:58.645426 133  ] Config: (/etc/ccache.conf) compression = true
[2021-01-03T17:57:58.645426 133  ] Config: (/etc/ccache.conf) compression_level = 1
[2021-01-03T17:57:58.645426 133  ] Config: (/etc/ccache.conf) log_file = /tmp/ccache.log
[2021-01-03T17:57:58.645426 133  ] Config: (/etc/ccache.conf) max_size = 100.0G
[2021-01-03T17:57:58.645426 133  ] Config: (/etc/ccache.conf) umask = 002
```

But it's a changed behaviour, the old ccache would just skip logging but the new ccache fails.

`ccache: error: Failed to write to /tmp/ccache.log: Permission denied`

3.7
```C
        if (!init_log()) {
                return;
        }
```

4.1
```C++
  if (!config.log_file().empty()) {
    logfile_path = config.log_file();
    logfile.open(logfile_path, "a");
    if (logfile) {
      Util::set_cloexec_flag(fileno(*logfile));
    } else {
      print_fatal_error_and_exit();
    }
  }

```

**Comment by AlexanderLanin** [comment]
> It does seem a bit strange to configure ccache to log somewhere that you don't have access to.
Yes it does 😄 

However failing horribly just because a log cannot be written is maybe not the best idea.

I guess `print_fatal_error_and_exit` should be `print_warning_and_continue_without_logging`.

**Comment by fluffynuts** [comment]
> It does seem a bit strange to configure ccache to log somewhere that you don't have access to.

bear in mind that that's not _really_ what happened: I configured ccache to use /tmp/ccache.log as a log file, which, when it doesn't exist, means _anyone_ can create the file. The problem comes in because apparently, according to feedback on https://bugs.gentoo.org/763288:

> portage runs different phases by different users on purpose:
> - pkg_* phases are usually ran by root as they usualy apply changes to the system (and sometimes  happen to run a compiler)
> - src_* phases are usually ran by portage user as all the changes should happen in $WORKDIR

The feedback in that report is that my configuration to use `/tmp/ccache.log` as a log file is invalid because I should apparently be aware of the user-shifting within portage's phases and that the result would be `ccache` being run by different users. The suggestion is to set up a file with correct permissions such that both root and portage can write to it, on the assumption that it's append-only, but that would mean I'd have to set up something to rotate that log too (one of the reasons I chose to put it in /tmp is that there's a kernel update at least every other month, so I have to reboot at least every other month, which would clear it out).

Alternatively, I see that I can leave the setting unconfigured or use the value `syslog` to have logs done via `syslog()` instead of to file; and I can leave it unconfigured but set for a specific run with the environment variable `CCACHE_LOGFILE`, so I should really pick one of those three for now.

I agree though that:
> However failing horribly just because a log cannot be written is maybe not the best idea.

:smile:

**Comment by afbjorklund** [comment]
You should only enable the debug log when troubleshooting anyway. It is much too verbose to have always on, globally. Takes space and time.

But I don’t know why the change was done, if it was on purpose or not ?

**Comment by jrosdahl** [comment]
@afbjorklund wrote:
> But I don’t know why the change was done, if it was on purpose or not ?

It was done in 05acfffbe50bcd8f2d18d1f1d4e7a45c9b1de26d. I don't remember my thought process exactly, but I think it was quite deliberate. My general philosophy is that tools should not misbehave silently. Failure to open or print to the debug log file feels like something to report since the user otherwise may not understand why the log file looks like it does.

@AlexanderLanin:
> However failing horribly just because a log cannot be written is maybe not the best idea.

Or maybe it is the best idea since @fluffynuts now is aware that the debug logging he had set up wasn't actually able to log all ccache invocations to the log file and therefore isn't correct?

> I guess print_fatal_error_and_exit should be print_warning_and_continue_without_logging.

That's unfortunately not an option since ccache can't print a warning and continue with exit code 0. The reason is that it then doesn't fully replicate the compiler behavior and this can lead to problems such as compiler feature probing failing due to unexpected output.

@fluffynuts wrote:
> The feedback in that report is that my configuration to use /tmp/ccache.log as a log file is invalid because I should apparently be aware of the user-shifting within portage's phases and that the result would be ccache being run by different users. The suggestion is to set up a file with correct permissions such that both root and portage can write to it [...]

If it's OK to have one log file per user, here's another alternative: Set `log_file = /tmp/ccache-$USER.log`. Ccache expands environment variables in configuration options for paths.

**Comment by jrosdahl** [comment]
I consider this to work as intended.
