### ISSUE TITLE
File not recompiled when using pre-compiled header

### ISSUE THREAD

**Issue by eerimoq** [ccache/ccache#774]
Hi!

There seem to be a problem with pre-compiled headers. It seems like files that depends on a pre-compiled header are not always recompiled if compiled immediately after compiling the header. Looks like a race condition because if I add a delay after creating the pre-compiled header the problem is gone.

### How to reproduce ###

Run this script:

```bash
#!/usr/bin/env bash

function work() {
    echo
    echo "foo() defined (incorrectly) in the header lib.hpp."
    echo "Fails with \"multiple definition of 'foo()'\"."
    echo "-------------------------------------------------------------"

    cat <<EOF > lib.hpp
#ifndef __LIBHPP
#define __LIBHPP

#include <iostream>
#include <vector>
#include <memory>
#include <sstream>
#include <optional>
void foo()
{
}
#endif
EOF

    cat <<EOF > lib.cpp
#include "lib.hpp"
EOF

    cat <<EOF > main.cpp
#include "lib.hpp"
int main()
{
}
EOF

    $CCACHE g++ -Winvalid-pch -std=c++17 -c lib.hpp -o lib.hpp.gch
    sleep $DELAY
    $CCACHE g++ -Winvalid-pch -std=c++17 -include lib.hpp -c lib.cpp -o lib.o
    $CCACHE g++ -Winvalid-pch -std=c++17 -include lib.hpp -c main.cpp -o main.o
    $CCACHE g++ -Winvalid-pch -std=c++17 lib.o main.o

    echo
    echo "Fix the bug by moving foo() to lib.cpp."
    echo "Should pass since the bug is fixed, but often fails with ccache."
    echo "-------------------------------------------------------------"

    cat <<EOF > lib.hpp
#ifndef __LIBHPP
#define __LIBHPP

#include <iostream>
#include <vector>
#include <memory>
#include <sstream>
#include <optional>
#endif
EOF

    cat <<EOF > lib.cpp
#include "lib.hpp"
void foo()
{
}
EOF

    $CCACHE g++ -Winvalid-pch -std=c++17 -c lib.hpp -o lib.hpp.gch
    sleep $DELAY
    $CCACHE g++ -Winvalid-pch -std=c++17 -include lib.hpp -c lib.cpp -o lib.o
    $CCACHE g++ -Winvalid-pch -std=c++17 -include lib.hpp -c main.cpp -o main.o
    $CCACHE g++ -Winvalid-pch -std=c++17 lib.o main.o
    
    if [ $? -ne 0 ] ; then
        echo
        echo "***************************************"
        echo "***** Linking with bug fix FAILED  *****"
        echo "***************************************"
    else
        echo
        echo "Linking with bug fix OK"
    fi
}

mkdir ccache-test
cd ccache-test

export CCACHE_BASEDIR=$(pwd)
export CCACHE_SLOPPINESS=pch_defines,time_macros

ccache -c -C

echo
echo "Building without ccache. Will always pass."
echo "============================================================="
CCACHE=
DELAY=0
work
echo
echo
echo
echo "Building with ccache. Often, but not always, fails for me."
echo "============================================================="
CCACHE=ccache
DELAY=0
work
echo
echo
echo
echo "Building with ccache with delay after building pre-compield header."
echo "============================================================="
CCACHE=ccache
DELAY=1
work
```

### Actual behavior ###

Sometimes this is part of the script's output, which means that the move of the foo() function from the header to source file did not take effect when compiling.

```
***************************************
***** Linking with bug fix FAILED  *****
***************************************
```

### Expected behavior ###

To no see the failure message, but instead the ok message:

```
Linking with bug fix OK
```

### Environment ###
ccache version 3.6 (I also built ccache from latest master. Same issue.)
Ubuntu 20.04
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Comment by eerimoq** [comment]
Ok, so I enabled logging and saw this diff:

![image](https://user-images.githubusercontent.com/176810/104606802-7abde500-5680-11eb-93ff-1c36366f03d7.png)

I had a look again at the ccache documentation and added `include_file_mtime` and `include_file_ctime` to `CCACHE_SLOPPINESS` (along with the values seen in the script in my previous post). With the new sloppiness the problem is gone. I guess this is just a workaround, of which I don't fully understand the consequences. Ccache should work with no sloppiness set at all, right? Sloppiness just makes it more sloppy as I understand it.

**Comment by jrosdahl** [comment]
Thanks for the bug report.

> Run this script:

And thanks for the reproducer. A word of warning, though: the script runs `ccache -C` which wipes the entire cache for a user who wants to try out the script... Consider using a cache directory in a temporary location.

> I had a look again at the ccache documentation and added `include_file_mtime` and `include_file_ctime` to `CCACHE_SLOPPINESS` (along with the values seen in the script in my previous post). With the new sloppiness the problem is gone. I guess this is just a workaround, of which I don't fully understand the consequences.

Yes. Precompiler headers are tricky – there have been several drive-by improvements and fixes by other contributors during the years and I also don't fully understand the consequences.

> Ccache should work with no sloppiness set at all, right?

It's indeed the goal that ccache with default settings should never miscompile anything.

**Comment by eerimoq** [comment]
Thanks for the reply. I get the feeling that another drive-by is needed for a fix. I might have a look myself, but I wont promise anything.

**Comment by jrosdahl** [comment]
I know the root cause now. Working on a fix.

**Comment by eerimoq** [comment]
Good job!
