### ISSUE TITLE
No cache hits when recompiling Linux kernel

### ISSUE THREAD

**Issue by phush0** [ccache/ccache#792]
### How to reproduce ###
I am using linux-tkg arch packet to build kernel forcing rebuild:
`makepkg -sf`

### Actual behavior ###
with ccache 4.1 second run is not faster and have only 15 files hit all others are counted as miss and added to cache, no matter how many times I build same kernel with same options.

### Expected behavior ###
with ccache 3.7.11 second and subsequent build are 1m45s vs 25m first run 

### Environment ###
ccache 3.7.11
and ccache 4.1

gcc 10.2.0
Manjaro testing latest
kernel 5.10.10-bmq-tkg with btrfs

**Comment by jrosdahl** [comment]
See [_Cache debugging_ in the manual](https://ccache.dev/manual/4.1.html#_cache_debugging) for hints on how to debug problems like this. To be able to help you further we'll need `.ccache-input-text` and `.ccache-log` files for the same object file in the first and second run with ccache 4.1.

**Comment by phush0** [comment]
my problem is fixed by pull #755

**Comment by jrosdahl** [comment]
To sum it up: ccache 4.0+ includes the value of `SOURCE_DATE_EPOCH` in the hash while ccache 3.7.11 doesn't, so the latter produces false positive cache hits if you consider the expansion of timestamps important. #755 makes it possible to opt out of this by setting `time_macros` sloppiness.

Ackording to the [makepkg(8) man page](https://archlinux.org/pacman/makepkg.8.html#_reproducibility), an alternative solution is to set `SOURCE_DATE_EPOCH` yourself to make the build reproducible (and by-default cacheable by ccache).
