### ISSUE TITLE
ccache --config-path does not work?

### ISSUE THREAD

**Issue by juj** [ccache/ccache#798]
### How to reproduce ###

On Windows:
```
E:\code>ccache --config-path E:\code\emcc_ccache.conf

E:\code>ccache --show-config
(default) absolute_paths_in_stderr = false
(default) base_dir =
(default) cache_dir = C:\Users\jukkaj\AppData\Roaming/ccache
(default) compiler =
(default) compiler_check = mtime
(default) compiler_type = auto
(default) compression = true
(default) compression_level = 0
(default) cpp_extension =
(default) debug = false
(default) debug_dir =
(default) depend_mode = false
(default) direct_mode = true
(default) disable = false
(default) extra_files_to_hash =
(default) file_clone = false
(default) hard_link = false
(default) hash_dir = true
(default) ignore_headers_in_manifest =
(default) ignore_options =
(default) inode_cache = false
(default) keep_comments_cpp = false
(default) limit_multiple = 0.8
(default) log_file =
(default) max_files = 0
(default) max_size = 5.0G
(default) path =
(default) pch_external_checksum = false
(default) prefix_command =
(default) prefix_command_cpp =
(default) read_only = false
(default) read_only_direct = false
(default) recache = false
(default) run_second_cpp = true
(default) sloppiness =
(default) stats = true
(default) temporary_dir = C:\Users\jukkaj\AppData\Roaming/ccache/tmp
(default) umask =
```

### Actual behavior ###

Config says
```
(default) cache_dir = C:\Users\jukkaj\AppData\Roaming/ccache
```

### Expected behavior ###

Documentation says

```
 --config-path PATH

    Let the subsequent command line options operate on configuration file PATH instead of the default. Using this option has the same effect as setting the environment variable CCACHE_CONFIGPATH temporarily.

```

I interpret that wording to mean that first call to ccache would register the configuration path, and after that it should get set to be used for subsequent calls?

### Environment ###

Windows 10, built latest ccache trunk from sources today using VS2019.

I wonder if this is somehow Windows specific that `--config-path` did not work as documentation says? Maybe the docs would be good to comment about that? Or maybe I misunderstood the documentation?

**Comment by jrosdahl** [comment]
> I interpret that wording to mean that first call to ccache would register the configuration path, and after that it should get set to be used for subsequent calls?

No, it means that the specified configuration file is used for the rest of the options for the current invocation. For instance, `ccache --config-path example.conf -M 10` sets the maximum cache size to 10 GB by writing to configuration file `example.conf` instead of the default (`%APPDATA%/ccache/ccache.conf` on Windows). `ccache --config-path example.conf` does nothing by itself.

**Comment by juj** [comment]
Ohhh, gotcha. Did not realize that ccache.exe could be used as a frontend to edit the config file in that manner. Thanks for the quick reply and sorry for the noise!
