### ISSUE TITLE
-frecord-gcc-switches support

### ISSUE THREAD

**Issue by llchan** [ccache/ccache#804]
`-frecord-gcc-switches` is not correctly handled by ccache.

### How to reproduce ###
```
$ echo 'int main() { return 0; }' > main.c
$ mkdir foo bar
$ ccache gcc -frecord-gcc-switches -I foo main.c -c -o main.foo.o
$ ccache gcc -frecord-gcc-switches -I bar main.c -c -o main.bar.o
$ readelf -p .GCC.command.line main.foo.o

String dump of section '.GCC.command.line':
  [     0]  -I foo
  ...

$ readelf -p .GCC.command.line main.bar.o

String dump of section '.GCC.command.line':
  [     0]  -I foo
  ...

```

### Actual behavior ###
The recorded gcc switches are stale for `main.bar.o` (includes a `-I foo` rather than `-I bar`).

### Expected behavior ###
At the most conservative, when `-frecord-gcc-switches` is on, the full command line should be saved in the cache entry and any change in the command line should point to a different cache entry.  This may lead to a significant drop in cache hits when the flag is enabled, so there may need to be some sloppiness flags to dial it back.

### Environment ###
ccache version 3.7.11

**Comment by jrosdahl** [comment]
Thanks for the bug report.

Another option would be to simply declare `-frecord-gcc-switches` unsupported (and fall back to just running the original compiler), but I think that it makes sense to still support caching by including the full command line in the hash, like you suggest.

I won't add a sloppiness flag as part of the fix, but I could be OK with a future PR adding such support on popular demand.
