### ISSUE TITLE
Improve statistics for "-P -E" 

### ISSUE THREAD

**Issue by zephyrus00jp** [ccache/ccache#812]
I found out about this while I was compiling thunderbird mail client under linux. 
The snippet from ccache log is attached at the end.

ccache 4.2 failed to cache the compilation due the "unsupported -P" option. I wish it caches it.

The following log is from clang-10, but gcc also suffers from the same treatment.

 ```
> [2021-02-23T08:50:05.392099 225905] === CCACHE 4.1 STARTED =========================================
> [2021-02-23T08:50:05.392099 225905] Config: (default) absolute_paths_in_stderr = false
> [2021-02-23T08:50:05.392099 225905] Config: (default) base_dir = 
> [2021-02-23T08:50:05.392099 225905] Config: (environment) cache_dir = /FF-NEW/cache-dir
> [2021-02-23T08:50:05.392099 225905] Config: (default) compiler = 
> [2021-02-23T08:50:05.392099 225905] Config: (default) compiler_check = mtime
> [2021-02-23T08:50:05.392099 225905] Config: (default) compiler_type = auto
> [2021-02-23T08:50:05.392099 225905] Config: (environment) compression = true
> [2021-02-23T08:50:05.392099 225905] Config: (default) compression_level = 0
> [2021-02-23T08:50:05.392099 225905] Config: (default) cpp_extension = 
> [2021-02-23T08:50:05.392099 225905] Config: (default) debug = false
> [2021-02-23T08:50:05.392099 225905] Config: (default) depend_mode = false
> [2021-02-23T08:50:05.392099 225905] Config: (default) direct_mode = true
> [2021-02-23T08:50:05.392099 225905] Config: (default) disable = false
> [2021-02-23T08:50:05.392099 225905] Config: (default) extra_files_to_hash = 
> [2021-02-23T08:50:05.392099 225905] Config: (default) file_clone = false
> [2021-02-23T08:50:05.392099 225905] Config: (default) hard_link = false
> [2021-02-23T08:50:05.392099 225905] Config: (environment) hash_dir = true
> [2021-02-23T08:50:05.392099 225905] Config: (default) ignore_headers_in_manifest = 
> [2021-02-23T08:50:05.392099 225905] Config: (default) ignore_options = 
> [2021-02-23T08:50:05.392099 225905] Config: (default) inode_cache = false
> [2021-02-23T08:50:05.392099 225905] Config: (default) keep_comments_cpp = false
> [2021-02-23T08:50:05.392099 225905] Config: (environment) limit_multiple = 1.0
> [2021-02-23T08:50:05.392099 225905] Config: (environment) log_file = /FF-NEW/cache-dir/logfile
> [2021-02-23T08:50:05.392099 225905] Config: (default) max_files = 0
> [2021-02-23T08:50:05.392099 225905] Config: (/FF-NEW/cache-dir/ccache.conf) max_size = 12.0G
> [2021-02-23T08:50:05.392099 225905] Config: (default) path = 
> [2021-02-23T08:50:05.392099 225905] Config: (default) pch_external_checksum = false
> [2021-02-23T08:50:05.392099 225905] Config: (default) prefix_command = 
> [2021-02-23T08:50:05.392099 225905] Config: (default) prefix_command_cpp = 
> [2021-02-23T08:50:05.392099 225905] Config: (default) read_only = false
> [2021-02-23T08:50:05.392099 225905] Config: (default) read_only_direct = false
> [2021-02-23T08:50:05.392099 225905] Config: (default) recache = false
> [2021-02-23T08:50:05.392099 225905] Config: (environment) run_second_cpp = true
> [2021-02-23T08:50:05.392099 225905] Config: (default) sloppiness = 
> [2021-02-23T08:50:05.392099 225905] Config: (default) stats = true
> [2021-02-23T08:50:05.392099 225905] Config: (default) temporary_dir = /run/user/1000/ccache-tmp
> [2021-02-23T08:50:05.392099 225905] Config: (default) umask = 
> [2021-02-23T08:50:05.392233 225905] Command line: /usr/bin/ccache /usr/bin/clang-10 -O1 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=x86_64-unknown-linux-gnu -std=gnu99 -xc -P -DWR_VERTEX_SHADER=1 -E /NEW-SSD/ASAN-OBJ-DIR/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-48f0f7d29b181c90/out/brush_blend.c
> [2021-02-23T08:50:05.392262 225905] Hostname: ip030
> [2021-02-23T08:50:05.392269 225905] Working directory: /NEW-SSD/NREF-COMM-CENTRAL/mozilla/gfx/wr/swgl
> [2021-02-23T08:50:05.392273 225905] Compiler type: clang
> [2021-02-23T08:50:05.392313 225905] Compiler option -P is unsupported
> [2021-02-23T08:50:05.392377 225905] Failed; falling back to running the real compiler
> [2021-02-23T08:50:05.392390 225905] Executing /usr/bin/clang-10 -O1 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=x86_64-unknown-linux-gnu -std=gnu99 -xc -P -DWR_VERTEX_SHADER=1 -E /NEW-SSD/ASAN-OBJ-DIR/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-48f0f7d29b181c90/out/brush_blend.c
> [2021-02-23T08:50:05.392400 225905] Result: unsupported compiler option
> [2021-02-23T08:50:05.392491 225905] Acquired lock /FF-NEW/cache-dir/7/1/stats.lock
> [2021-02-23T08:50:05.393392 225905] Releasing lock /FF-NEW/cache-dir/7/1/stats.lock
> [2021-02-23T08:50:05.393429 225905] Unlink /FF-NEW/cache-dir/7/1/stats.lock
> 
```

I noticed there are complex processing when "-P" is prefixed with other options,

argprocessing.cpp:

 
 ```
  621	  if (Util::starts_with(args[i], "-Wp,")) {
   622	    if (args[i] == "-Wp,-P" || args[i].find(",-P,") != std::string::npos
   623	        || Util::ends_with(args[i], ",-P")) {
   624	      // -P removes preprocessor information in such a way that the object file
   625	      // from compiling the preprocessed file will not be equal to the object
   626	      // file produced when compiling without ccache.
   627	      LOG_RAW("Too hard option -Wp,-P detected");
   628	      return Statistic::unsupported_compiler_option;

```

however, "-P" that appears without any prefix should be treated like as other options.

I am not sure how to fix the source as of now.

I noticed this while I was compiling thunderbird mail client with the
latest source tree. It is worth looking into the log from time to
time.

Thank you again for making ccache available to general programming
community.

Chiaki Ishikawa

**Comment by Meinersbur** [comment]
ccache gets its dependency information from line directives from the preprocessor output, when they are disabled via `-P` option, ccache does not know which header files to include in the hash.

ccache supports an alternative to track dependencies via depend mode. It requires that either `-MD` or `-MMD` is passed to the compiler. IMHO ccache should should be able to add `-MD`/`-MMD` (depending on sloppyness) to the preprocessor command line itself if not provided by the user, i.e. parsing the preprocessed file for line directives is not necessary.

This would be really useful to re-implement the CCACHE_UNIFY option with CCACHE_CPP2 enabled, with the only downside that line information from compiler diagnostics might be off from the cached output when only empty lines have been changed from the last run.

CCACHE_UNIFY was removed in ccache 3.7.7 (https://github.com/ccache/ccache/commit/0774bfe4c71b342822170057df0aef15d371d892) for the reason mentioned in the NEWS file:
> Removed the unify mode since it has bugs and shortcomings that are non-trivial
  or impossible to fix: it doesn’t work with the direct mode, it doesn’t handle
  C++ raw strings correctly, it can give false cache hits for `.incbin`
  directives, it’s turned off when using `-g` and it can make line numbers in
  warning messages and `__LINE__` macros incorrect.

**Comment by zephyrus00jp** [comment]
I have never used CCACHE_UNIFY so I am not sure how widely the feature was in demand, etc. But
I suppose people who use "-P" are aware of issues such as "the only downside that line information from compiler diagnostics might be off from the cached output ..." and so it should not be a big deal.
So, if the gratuitous addition of -MD/-MMD helps to re-implement the feature, maybe someone is welcome to do so :-)

In the meantime, I have filed a bugzilla entry to see why on earth someone wanted to compile files with "-P" in the first place.
https://bugzilla.mozilla.org/show_bug.cgi?id=1695131

**Comment by jrosdahl** [comment]
@zephyrus00jp wrote:

> ccache failed to cache the compilation due the "unsupported -P" option.

Right. I would not call that a bug since ccache behaves as intended, though. I'll convert the issue into a feature request instead.

> `[2021-02-23T08:50:05.392233 225905] Command line: /usr/bin/ccache /usr/bin/clang-10 -O1 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=x86_64-unknown-linux-gnu -std=gnu99 -xc -P -DWR_VERTEX_SHADER=1 -E /NEW-SSD/ASAN-OBJ-DIR/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-48f0f7d29b181c90/out/brush_blend.c`

Note that the command line given to ccache includes `-E`, which means that the compiler is asked to perform preprocessing. If we would add support for `-P` then ccache would fail in another way instead ("called for preprocessing") and fall back to running the real compiler without caching anything anyway. So this does not sound like a good reason for implementing support for `-P`.

> however, "-P" that appears without any prefix should be treated like as other options.

No, that's the easy, standalone (i.e., not prefixed with `-Wp,`) case which is taken care of by [the compopt table](https://github.com/ccache/ccache/blob/3c96cee611b5cb678c8574663f726dc2dd24366d/src/compopt.cpp#L79).

> I am not sure how to fix the source as of now.

I think that it would be possible to add support for `-P` (without `-E`) by simply not passing it in the preprocessor step and then forcing run_second_cpp to true so that the object file will be compiled with `-P` semantics even if the preprocessor didn't get `-P`. But it seems like a very unusual use case so I guess the question is if it's worth it. Is anybody using `-P` for compilation?

**Comment by jrosdahl** [comment]
@zephyrus00jp: Could you clarify if the Thunderbird build includes **compilations** (i.e., not using `-E`) with `-P` or if `-P` only is used together with `-E`?

**Comment by zephyrus00jp** [comment]
Oops, I must have missed reading the inquiry. March is a busy month since it is the end of fiscal year of many organizations in Japan, including schools and my office. Let me investigate this.

**Comment by zephyrus00jp** [comment]
> Could you clarify if the Thunderbird build includes **compilations** (i.e., not using `-E`) with `-P` or if `-P` only is used together with `-E`?


ishikawa@ip030:/NREF-COMM-CENTRAL/mozilla$ grep -- -P /FF-NEW/cache-dir/logfile.8 | head -10
[2021-03-31T12:14:12.360870 593622] Command line: /usr/bin/ccache /usr/bin/gcc-10 -xc -P -undef -DWR_VERTEX_SHADER=1 -E /NEW-SSD/moz-obj-dir/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-c7eb40590291a1bb/out/brush_blend.c
[2021-03-31T12:14:12.360905 593622] Compiler option -P is unsupported
[2021-03-31T12:14:12.360950 593622] Executing /usr/bin/gcc-10 -xc -P -undef -DWR_VERTEX_SHADER=1 -E /NEW-SSD/moz-obj-dir/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-c7eb40590291a1bb/out/brush_blend.c
[2021-03-31T12:14:12.566442 593625] Command line: /usr/bin/ccache /usr/bin/gcc-10 -xc -P -undef -DWR_FRAGMENT_SHADER=1 -E /NEW-SSD/moz-obj-dir/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-c7eb40590291a1bb/out/brush_blend.c
[2021-03-31T12:14:12.566512 593625] Compiler option -P is unsupported
[2021-03-31T12:14:12.566601 593625] Executing /usr/bin/gcc-10 -xc -P -undef -DWR_FRAGMENT_SHADER=1 -E /NEW-SSD/moz-obj-dir/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-c7eb40590291a1bb/out/brush_blend.c
[2021-03-31T12:14:12.737425 593628] Command line: /usr/bin/ccache /usr/bin/gcc-10 -xc -P -undef -DWR_VERTEX_SHADER=1 -E /NEW-SSD/moz-obj-dir/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-c7eb40590291a1bb/out/brush_blend_ALPHA_PASS.c
[2021-03-31T12:14:12.737457 593628] Compiler option -P is unsupported
[2021-03-31T12:14:12.737498 593628] Executing /usr/bin/gcc-10 -xc -P -undef -DWR_VERTEX_SHADER=1 -E /NEW-SSD/moz-obj-dir/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-c7eb40590291a1bb/out/brush_blend_ALPHA_PASS.c
[2021-03-31T12:14:12.750264 593631] Command line: /usr/bin/ccache /usr/bin/gcc-10 -xc -P -undef -DWR_FRAGMENT_SHADER=1 -E /NEW-SSD/moz-obj-dir/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-c7eb40590291a1bb/out/brush_blend_ALPHA_PASS.c
ishikawa@ip030:/NREF-COMM-CENTRAL/mozilla$ grep -- -P /FF-NEW/cache-dir/logfile.8 | wc
    900    8700  166568
ishikawa@ip030:/NREF-COMM-CENTRAL/mozilla$ grep -- -P /FF-NEW/cache-dir/logfile.8 | grep gcc | wc 
    600    6600  145568
ishikawa@ip030:/NREF-COMM-CENTRAL/mozilla$ grep -- -P /FF-NEW/cache-dir/logfile.8 | grep gcc | grep -- -E | wc
    600    6600  145568
ishikawa@ip030:/NREF-COMM-CENTRAL/mozilla$ grep -- -P /FF-NEW/cache-dir/logfile.8 | grep gcc | grep -v -- -E | wc
      0       0       0
ishikawa@ip030:/NREF-COMM-CENTRAL/mozilla$ 
ishikawa@ip030:/NREF-COMM-CENTRAL/mozilla$ grep -- -P /FF-NEW/cache-dir/logfile.8 | head -10
[2021-03-31T12:14:12.360870 593622] Command line: /usr/bin/ccache /usr/bin/gcc-10 -xc -P -undef -DWR_VERTEX_SHADER=1 -E /NEW-SSD/moz-obj-dir/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-c7eb40590291a1bb/out/brush_blend.c
[2021-03-31T12:14:12.360905 593622] Compiler option -P is unsupported
[2021-03-31T12:14:12.360950 593622] Executing /usr/bin/gcc-10 -xc -P -undef -DWR_VERTEX_SHADER=1 -E /NEW-SSD/moz-obj-dir/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-c7eb40590291a1bb/out/brush_blend.c
[2021-03-31T12:14:12.566442 593625] Command line: /usr/bin/ccache /usr/bin/gcc-10 -xc -P -undef -DWR_FRAGMENT_SHADER=1 -E /NEW-SSD/moz-obj-dir/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-c7eb40590291a1bb/out/brush_blend.c
[2021-03-31T12:14:12.566512 593625] Compiler option -P is unsupported
[2021-03-31T12:14:12.566601 593625] Executing /usr/bin/gcc-10 -xc -P -undef -DWR_FRAGMENT_SHADER=1 -E /NEW-SSD/moz-obj-dir/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-c7eb40590291a1bb/out/brush_blend.c
[2021-03-31T12:14:12.737425 593628] Command line: /usr/bin/ccache /usr/bin/gcc-10 -xc -P -undef -DWR_VERTEX_SHADER=1 -E /NEW-SSD/moz-obj-dir/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-c7eb40590291a1bb/out/brush_blend_ALPHA_PASS.c
[2021-03-31T12:14:12.737457 593628] Compiler option -P is unsupported
[2021-03-31T12:14:12.737498 593628] Executing /usr/bin/gcc-10 -xc -P -undef -DWR_VERTEX_SHADER=1 -E /NEW-SSD/moz-obj-dir/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-c7eb40590291a1bb/out/brush_blend_ALPHA_PASS.c
[2021-03-31T12:14:12.750264 593631] Command line: /usr/bin/ccache /usr/bin/gcc-10 -xc -P -undef -DWR_FRAGMENT_SHADER=1 -E /NEW-SSD/moz-obj-dir/objdir-tb3/x86_64-unknown-linux-gnu/debug/build/swgl-c7eb40590291a1bb/out/brush_blend_ALPHA_PASS.c
ishikawa@ip030:/NREF-COMM-CENTRAL/mozilla$ grep -- -P /FF-NEW/cache-dir/logfile.8 | wc
    900    8700  166568
ishikawa@ip030:/NREF-COMM-CENTRAL/mozilla$ grep -- -P /FF-NEW/cache-dir/logfile.8 | grep gcc | wc 
    600    6600  145568
ishikawa@ip030:/NREF-COMM-CENTRAL/mozilla$ grep -- -P /FF-NEW/cache-dir/logfile.8 | grep gcc | grep -- -E | wc
    600    6600  145568
ishikawa@ip030:/NREF-COMM-CENTRAL/mozilla$ grep -- -P /FF-NEW/cache-dir/logfile.8 | grep gcc | grep -v -- -E | wc
      0       0       0
ishikawa@ip030:/NREF-COMM-CENTRAL/mozilla$

**Comment by zephyrus00jp** [comment]
Ouch, I hit "Close with comment" by mistake.

I can't speak for mozilla firefox, but thunderbird build uses -P always with -E.
As you can see in my previous comment, all the use of -P is accompanied with -E.

TIA

**Comment by jrosdahl** [comment]
Thanks. Then I'm tempted to just close this as "won't fix" since ccache doesn't cache results with `-E` anyway.

On the other hand, I guess what made you stumble on this is that ccache reports usage of `-P -E` as "unsupported compiler option" – arguably "called for preprocessing" would have been a better statistics value to increment. It looks like it would be fairly easy to make it so.

**Comment by zephyrus00jp** [comment]
Thank you, that would help when someone sees the log.
