### ISSUE TITLE
Upgrade to doctest 2.4.6 to fix ccache build with upcoming glibc >= 2.34

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [ccache/ccache#825]
### Description ###

Hi,

I reported a build issue with doctest here https://github.com/onqtam/doctest/issues/473 which was just fixed in the just released doctest 2.4.6.

Would you please upgrade the embedded thirdpart doctest copy in ccache to fix this issue impacting ccache build ?

Thank you,
Romain

**Comment by jrosdahl** [comment]
Sure. Thanks for reporting it upstream.

**Comment by Romain-Geissler-1A** [comment]
Cool, thank you ;)
