### ISSUE TITLE
ccache 4 broken for MinGW-w64 for 32-bit Windows

### ISSUE THREAD

**Issue by brechtsanders** [ccache/ccache#831]
Ever since ccache 4.0 ccache no longer works on Windows with MinGW-w64 32-bit. It works fine with MinGW-w64 64-bit though.

Every time ccache shows no output and just exits with status code 3, even when running something simple like `ccache gcc --version`.

GDB output looks like this:
```
Starting program: D:\Prog\winlibs32-10.2.0\custombuilt\bin\ccache.exe D:/Prog/winlibs32-10.2.0/mingw32/bin/gcc.exe --version
[New Thread 4612.0x368c]
[New Thread 4612.0x355c]
[New Thread 4612.0x55a8]
[Thread 4612.0x55a8 exited with code 3]
[Thread 4612.0x368c exited with code 3]
[Thread 4612.0x355c exited with code 3]
[Inferior 1 (process 4612) exited with code 03]
```

**Comment by jrosdahl** [comment]
1. Which ccache version(s) did you try?
2. Which ccache release did you run? A build downloaded from https://ccache.dev/download.html or some other build? If the latter, how was it built?

**Comment by brechtsanders** [comment]
I had the same issue with 4.0, 4.1, 4.2 and 4.2.1 so far.
No problems with 3.7.12 and older.

I built myself from source, with all dependancies also built from source with the exact same compiler environment (http://winlibs.com/), which uses GCC (I haven't tried building with LLVM/CLang).

My CMake command looks like this:
```
cmake -Wno-dev -GNinja -DCMAKE_INSTALL_PREFIX:PATH=$INSTALLPREFIX -DCMAKE_BUILD_TYPE:STRING=Release -DUSE_FASTER_LINKER:BOOL=OFF -DENABLE_IPO:BOOL=OFF -DUSE_CCACHE:BOOL=OFF -DZSTD_FROM_INTERNET:BOOL=OFF -DENABLE_TRACING:BOOL=ON -DENABLE_TESTING:BOOL=OFF -DCMAKE_C_FLAGS:STRING="-fno-asynchronous-unwind-tables" -DCXXMAKE_CXX_FLAGS:STRING="-fno-asynchronous-unwind-tables" -S. -Bbuild_win
```

**Comment by brechtsanders** [comment]
Updated: simple test `ccache gcc --version` actually does work when ccache 4.2.1 was configured with CMake flag `-DSTATIC_LINK:BOOL=OFF`.

So the issue seems restricted to win32 static builds.

**Comment by jrosdahl** [comment]
> So the issue seems restricted to win32 static builds.

https://github.com/ccache/ccache/releases/download/v4.2.1/ccache-4.2.1-windows-32.zip is built with 32-bit Mingw-w64 in static link mode. Does it exhibit the same problem for you?

**Comment by brechtsanders** [comment]
Yes, that prebuilt download works fine.

I am setting up a build ecosystem where everything is built from source, that's why I wasn't using it.

Also, I am trying to build with mmap support (see http://code.google.com/p/mman-win32/), but the line containing link() in src/InodeCache.cpp is the only problem to get that working on Windows. Is there an alternate possibility for this line?

**Comment by jrosdahl** [comment]
> Yes, that prebuilt download works fine.

OK, thanks for confirming. Then I guess that the issue isn't that ccache is broken for 32-bit Mingw-w64 in a generic sense but that something in your build ecosystem is different from mine. Thus, I cannot help out since I cannot reproduce the problem. Would it be possible for you to investigate further?

> Also, I am trying to build with mmap support (see http://code.google.com/p/mman-win32/), but the line containing link() in src/InodeCache.cpp is the only problem to get that working on Windows. Is there an alternate possibility for this line?

Perhaps change to `Util::hard_link` which has a Windows implementation?

**Comment by brechtsanders** [comment]
Can you share what CMake flags you use to build the static binary, so I can compare?

I avoid hard links in Windows. Though they exist on Windows (on condition the file system supports it, like NTFS), standard users usually don't have enough rights.

Why are hard links needed here?

**Comment by jrosdahl** [comment]
> Can you share what CMake flags you use to build the static binary, so I can compare?

Certainly. I'm cross-compiling on Linux like this:

```
CC=i686-w64-mingw32-gcc-posix CXX=i686-w64-mingw32-g++-posix \
  cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_SYSTEM_NAME=Windows \
  -DZSTD_FROM_INTERNET=ON
```

> I avoid hard links in Windows. Though they exist on Windows (on condition the file system supports it, like NTFS), standard users usually don't have enough rights.

OK, I don't know much about that. However, `Util::hard_link` is [used in a standard code path already](https://github.com/ccache/ccache/blob/1a07c09dcbba202572c5ab1bc4b736183a318aa7/src/ccache.cpp#L1187) so if there are any problems, users haven't complained so far.

> Why are hard links needed here?

I wouldn't say that they are *needed*, only that it's natural to use them in a POSIX world to accomplish [this](https://github.com/ccache/ccache/blob/1a07c09dcbba202572c5ab1bc4b736183a318aa7/src/InodeCache.cpp#L255-L256) and [this](https://github.com/ccache/ccache/blob/1a07c09dcbba202572c5ab1bc4b736183a318aa7/src/InodeCache.cpp#L301-L304).

**Comment by nickhutchinson** [comment]
> I avoid hard links in Windows. Though they exist on Windows (on condition the file system supports it, like NTFS), standard users usually don't have enough rights.

While symlinks require special privileges on Windows (unless you've enabled "Developer Mode" on Windows 10), I don't believe hard links require any special privileges.

**Comment by brechtsanders** [comment]
Fact remains out of the box this doesn't work on Windows 10. You need either rights or developer mode.
And if the underlying file system doesn't support it (e.g. FAT) then it also doesn't work.

When I remove the line with `link()` from `src/InodeCache.cpp` it still seems to work at first sight, but I guess it would only come into play when things really happen at the same time and locking kicks in. But on my build system with 32 logical processors I saw no issues.

**Comment by nickhutchinson** [comment]
> Fact remains out of the box this doesn't work on Windows 10. You need either rights or developer mode.
> And if the underlying file system doesn't support it (e.g. FAT) then it also doesn't work.

Ccache already requires hard link support on Windows for standard operation. You might be confusing symlinks (which require privileges/dev mode on Windows) and hard links (which do not). I'm not a core ccache developer, but I suspect adding support for filesystems that don't support hard links is a non-goal.

**Comment by brechtsanders** [comment]
Then link() should be replaced by CreateHardLinkA() on Windows to make it work.

**Comment by nickhutchinson** [comment]
> [...] I got an error building gstreamer 1.18.4 in one of my MinGW-w64 environments:
> 
> ```
> ccache: error: failed to lstat D:\Prog\winlibs64-10.2.1\home/ccache/tmp/tmp.cpp_stdout.pBIXIw.i: Permission denied
> ```
> 
> I'm not sure `lstat()` is supposed to work on Windows...

@brechtsanders Could you try and reproduce this 'failed to lstat' error while collecting a [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) trace and attach the trace file? (Best use an official ccache build rather than one you have built yourself.)

@jrosdahl Would this be the most likely call site for the "failed to stat" error? It seems the only place the string "failed to stat" appears. https://github.com/ccache/ccache/blob/1a07c09dcbba202572c5ab1bc4b736183a318aa7/src/Util.cpp#L1436 I suspect the new Windows stat implementation needs to be updated to 'pending delete' errors into ENOENT. I should be able to look at this in a few days.

**Comment by brechtsanders** [comment]
@nickhutchinson This is only with ccache built with mmap support (using http://code.google.com/p/mman-win32/), not the official buikd.

**Comment by jrosdahl** [comment]
@brechtsanders wrote:

> Then `link()` should be replaced by `CreateHardLinkA()` on Windows to make it work.

Yep, hence [my earlier suggestion](https://github.com/ccache/ccache/issues/831#issuecomment-809541501) to use `Util::hard_link` which [does that for Windows](https://github.com/ccache/ccache/blob/1a07c09dcbba202572c5ab1bc4b736183a318aa7/src/Util.cpp#L807).

@nickhutchinson wrote:

> Would this be the most likely call site for the "failed to stat" error? It seems the only place the string "failed to stat" appears.

Yes, agree.

> I suspect the new Windows stat implementation needs to be updated to 'pending delete' errors into ENOENT. I should be able to look at this in a few days.

Sounds good, thanks.

**Comment by jrosdahl** [comment]
@brechtsanders: I'm not sure what to do about this issue since I can't reproduce it. Would you like to keep it open if you're investigating?

**Comment by brechtsanders** [comment]
I will run some tests with master branch built with mmap support when I find some time.
-------- Original message --------From: Joel Rosdahl ***@***.***> Date: 05/04/21  19:50  (GMT+01:00) To: ccache/ccache ***@***.***> Cc: Brecht Sanders ***@***.***>, Mention ***@***.***> Subject: Re: [ccache/ccache] ccache 4 broken for MinGW-w64 for 32-bit Windows
  (#831) 
@brechtsanders: I'm not sure what to do about this issue since I can't reproduce it. Would you like to keep it open if you're investigating?

**Comment by jrosdahl** [comment]
@brechtsanders: Any progress?

**Comment by brechtsanders** [comment]
Just did some more tests, this time with the recently released GCC 11.1.0 (MinGW-w64 build from http://winlibs.com/).
Most of the time there are no issues, but one time for 32-bit MinGW-w64 I could still reproduce issues building gstreamer:
```
[95/212] Compiling C object libs/gst/c...-0.dll.p/gsttriggercontrolsource.c.obj
FAILED: libs/gst/controller/libgstcontroller-1.0-0.dll.p/gsttriggercontrolsource.c.obj
"ccache" "gcc" "-Ilibs\gst\controller\libgstcontroller-1.0-0.dll.p" "-Ilibs\gst\controller" "-I..\libs\gst\controller" "-I." "-I.." "-Ilibs" "-I..\libs" "-Igst" "-ID:/Prog/winlibs32-11.1.0/custombuilt/include" "-ID:/Prog/winlibs32-11.1.0/custombuilt/include/glib-2.0" "-ID:/Prog/winlibs32-11.1.0/custombuilt/lib/glib-2.0/include" "-fdiagnostics-color=always" "-pipe" "-D_FILE_OFFSET_BITS=64" "-Wall"
"-Winvalid-pch" "-O3" "-fvisibility=hidden" "-fno-strict-aliasing" "-DG_DISABLE_CAST_CHECKS" "-Wno-unused" "-Wmissing-declarations" "-Wmissing-prototypes" "-Wredundant-decls" "-Wundef" "-Wwrite-strings" "-Wformat" "-Wformat-nonliteral" "-Wformat-security" "-Wold-style-definition" "-Winit-self" "-Wmissing-include-dirs"
"-Waddress" "-Waggregate-return" "-Wno-multichar" "-Wdeclaration-after-statement" "-Wvla" "-Wpointer-arith" "-mms-bitfields" "-mms-bitfields" "-mms-bitfields" "-DHAVE_CONFIG_H" "-DBUILDING_GST_CONTROLLER" -MD -MQ libs/gst/controller/libgstcontroller-1.0-0.dll.p/gsttriggercontrolsource.c.obj -MF "libs\gst\controller\libgstcontroller-1.0-0.dll.p\gsttriggercontrolsource.c.obj.d" -o libs/gst/controller/libgstcontroller-1.0-0.dll.p/gsttriggercontrolsource.c.obj "-c" ../libs/gst/controller/gsttriggercontrolsource.c
ccache: error: failed to lstat D:\Prog\winlibs32-11.1.0\home/.ccache/tmp/tmp.cpp_stdout.u2X7vW: Permission denied
```
Strange thing is that when I launch ninja again it does build the second time.

Another time I was able to reproduce building LIEF 0.11.4 with 64-bit MinGW-w64:
```
[418/463] Building C object CMakeFiles.../lief_mbed_tls/library/threading.c.obj
FAILED: CMakeFiles/LIB_LIEF.dir/mbed_tls/src/lief_mbed_tls/library/threading.c.obj
ccache D:\Prog\winlibs64-11.1.0\mingw64\bin\gcc.exe -DLIB_LIEF_EXPORTS -DLIEF_EXPORTS -DMBEDTLS_MD2_C -DMBEDTLS_MD4_C -DMBEDTLS_PEM_PARSE_C -DMBEDTLS_PEM_WRITE_C -DMBEDTLS_PKCS1_V15 -DMBEDTLS_PKCS1_V21 -DMBEDTLS_X509_ALLOW_UNSUPPORTED_CRITICAL_EXTENSION -DMBEDTLS_X509_CRT_PARSE_C -DSPDLOG_DISABLE_DEFAULT_LOGGER -DSPDLOG_FUNCTION="" -D_GLIBCXX_USE_CXX11_ABI=1 -I../include -I../api/c/include -Iinclude -Ilief_frozen-prefix/src/lief_frozen/include -I../src -I. -I../include/LIEF -isystem lief_spdlog-prefix/src/lief_spdlog/include -isystem mbed_tls/src/lief_mbed_tls/include -fvisibility=hidden -Wall -Wextra -Wpedantic -fno-stack-protector -fomit-frame-pointer -fno-strict-aliasing -fexceptions -fvisibility=hidden -Wno-expansion-to-defined -fdiagnostics-color=always -MD -MT CMakeFiles/LIB_LIEF.dir/mbed_tls/src/lief_mbed_tls/library/threading.c.obj -MF CMakeFiles\LIB_LIEF.dir\mbed_tls\src\lief_mbed_tls\library\threading.c.obj.d -o CMakeFiles/LIB_LIEF.dir/mbed_tls/src/lief_mbed_tls/library/threading.c.obj -c mbed_tls/src/lief_mbed_tls/library/threading.c
ccache: error: failed to lstat D:\Prog\winlibs64-11.1.0\home/.ccache/tmp/tmp.cpp_stderr.fM8HIQ: Permission denied
```
Then I checked if the file where ccache returned the error was actually built, and it seems to be:
```
$ file build_static/CMakeFiles/LIB_LIEF.dir/mbed_tls/src/lief_mbed_tls/library/rsa_internal.c.obj
build_static/CMakeFiles/LIB_LIEF.dir/mbed_tls/src/lief_mbed_tls/library/rsa_internal.c.obj: Intel amd64 COFF object file, no line number info, not stripped, 6 sections, symbol offset=0x1588, 37 symbols
```
Again I ran ninja again and the build completed.

So it looks to me that if these lstat errors were to be ignored the builds would succeed.

**Comment by brechtsanders** [comment]
Also after the build completed I noticed stray ccache.exe processes in Task Manager.
Not sure if this is related though...

**Comment by nickhutchinson** [comment]
@brechtsanders The 'failed to lstat' errors are probably caused by ccache trying to traverse its temporary directory at exit time to clean up orphaned temp files. Previously this could error if another ccache process was in the middle of deleting a temp file from this directory. 

This should have been fixed by https://github.com/ccache/ccache/commit/c8442ee373a3d7c3cbf498f8664d4ad273b26a30, but this hasn't been released yet.

**Comment by jrosdahl** [comment]
> This should have been fixed by c8442ee, but this hasn't been released yet.

Part of 4.3 released just now.

**Comment by brechtsanders** [comment]
Tests with ccache 4.3 building gstreamer and LIEF build perfectly now with MingW-w64.
Great work, thanks!

**Comment by vadi2** [comment]
I can confirm that it's working for [Mudlet](https://github.com/Mudlet/Mudlet) as well for building with MinGW 7.3.0. This is great stuff and really appreciated.
