### ISSUE TITLE
Ubuntu 18.04 compile error for v4.2.1

### ISSUE THREAD

**Issue by Apon77** [ccache/ccache#846]
### How to reproduce ###

1. docker run -it ubuntu:18.04
2. cd /tmp
2. apt update;apt install curl cmake libzstd-dev g++ clang-format -y
3. curl -LO https://github.com/ccache/ccache/releases/download/v4.2.1/ccache-4.2.1.tar.gz
4. tar xf ccache-4.2.1.tar.gz 
5. cd ccache-4.2.1
6. mkdir build 
7. cd build
8. cmake -DCMAKE_BUILD_TYPE=Release ..

### Actual behavior ###

root@3a440c5933a4:/tmp/ccache-4.2.1/build# cmake -DCMAKE_BUILD_TYPE=Release ..
-- Ccache version: 4.2.1
-- Ccache dev mode: OFF
-- Using gold linker
CMake Error at cmake/CIBuildType.cmake:28 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:74 (include)

CMake Error at cmake/CIBuildType.cmake:30 (string):
  string sub-command STRIP requires two arguments.
Call Stack (most recent call first):
  CMakeLists.txt:74 (include)

CMake Warning at doc/CMakeLists.txt:5 (message):
  Could not find asciidoc; documentation will not be generated

-- Configuring incomplete, errors occurred!
See also "/tmp/ccache-4.2.1/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/ccache-4.2.1/build/CMakeFiles/CMakeError.log".

### Expected behavior ###

It should compile fine, I can compile v4.2 with same docker image.

### Environment ###

ccache version 4.2

ubuntu 18.04 docker image

**Comment by jrosdahl** [comment]
I don't understand why `CMAKE_*_FLAGS_CI` (originating from `CMAKE_*_FLAGS_RELWITHDEBINFO`) are empty for you and not for me, but quoting the variables should be the right fix in any case.
