### ISSUE TITLE
Storage backends: API and framework

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#856]
Design and implement an API and framework for simple key-value storage backends. This includes configuration parsing (see #855) and new statistics counters. Only needs to support one secondary backend for now.

**Comment by afbjorklund** [comment]
Something that I found recently was that it was good to add a "rm" function, next to the usual "set" and "get" functions. It made it easier to do testing, that could clean up after themselves... Previously we just restarted memcached or wiped the directory, to clean the cache. But for some backends, one uses the same storage also for testing. And then it can be useful to do a more directed clean, to remove items from the cache by key. Not sure it is needed during normal operations, since it does auto-clean.

**Comment by jrosdahl** [comment]
* [API for secondary storage](https://github.com/ccache/ccache/blob/2b3368cfc2a076e3205e0d7f400b4f97db227dae/src/storage/SecondaryStorage.hpp)
* [Example implementation](https://github.com/ccache/ccache/commit/f8789e2f4156cd3413f72c0ce4ae0dc321f70084)

**Comment by BrightSeraph** [comment]
I did not find any hints on this topic:
Will the secondary storage propagate into the primary and/or will the primary eventually drop its content into the secondary?

**Comment by jrosdahl** [comment]
> Will the secondary storage propagate into the primary and/or will the primary eventually drop its content into the secondary?

My current plan looks something like this:

| Primary storage hit/miss | Secondary storage hit/miss | What happens |
| ------- | --------- | ------------ | 
| miss    | miss      | Compile, write to primary<sup>[1]</sup>, write to secondary<sup>[2]</sup> |
| miss    | hit       | Read from secondary, write to primary<sup>[1]</sup><sup>[3]</sup> |
| hit     | -         | Read from primary, don't write to secondary<sup>[4]</sup> |

- <sup>[1]</sup> Unless primary storage is read-only (future config option: `read_only_primary`/`CCACHE_READONLY_PRIMARY`).
- <sup>[2]</sup> Unless secondary storage is read-only (`|read-only` or `|read-only=true` appended to the storage URL).
- <sup>[3]</sup> Unless secondary storage is marked to not share results. The use case for this is if you have a secondary storage that is so fast that it's of no use to also populate the primary storage. I haven't come up with a good name for this yet, though. The best I got so far is `|share-hits=false` appended to the storage URL. Other suggestions are welcome.
- <sup>[4]</sup> Unless primary storage is set to share its hits (future config option: `share_hits`/`CCACHE_SHARE_HITS`).

Does this sound reasonable?

**Comment by afbjorklund** [comment]
>     * I haven't come up with a good name for this yet, though. The best I got so far is `|share-hits=false` appended to the storage URL. Other suggestions are welcome.

The old name for this feature was `memcached_only`, which doesn't really help with picking the new name. ("share-hits" is ok)

**Comment by BrightSeraph** [comment]
That's amazing! Thank you so much.
'share_hits' is a very reasonable name (an alternative might be populate=[primary|secondary|other|both|none]
