### ISSUE TITLE
Storage backends: HTTP

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#858]
- Implement an HTTP GET/PUT storage backend according to the API in #856. See also #676.
- Consider using <https://github.com/yhirose/cpp-httplib>.
- Not in scope: HTTPS.

**Comment by afbjorklund** [comment]
I think some cloud storage might _require_ HTTPS, but maybe we could use a proxy for those ?

i.e. have ccache talk HTTP to localhost, and then have the local proxy relay those over HTTPS

**Comment by jrosdahl** [comment]
Let's leave HTTPS out the scope since it will only lead to discussions on how to solve it, like the one you began. Another task can be created for HTTPS support.
