### ISSUE TITLE
Storage backends: Redis

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#859]
- Implement a Redis storage backend according to the API in #856.

**Comment by afbjorklund** [comment]
One suggestion is to use the official "hiredis" library for doing this.

**Comment by jrosdahl** [comment]
Sure!

-- Joel

**Comment by jrosdahl** [comment]
The API and framework is now ready:

* [SecondaryStorage interface](https://github.com/ccache/ccache/blob/2b3368cfc2a076e3205e0d7f400b4f97db227dae/src/storage/SecondaryStorage.hpp)
* [Example implementation](https://github.com/ccache/ccache/commit/f8789e2f4156cd3413f72c0ce4ae0dc321f70084)

@afbjorklund: Would you like to work on a Redis implementation of that interface?

**Comment by afbjorklund** [comment]
I can give it a try, hopefully some of the `hiredis` code can be reused from 0576d543 :

https://github.com/ccache/ccache/commit/0576d5437aa1c8e853f2d4579b7f72f77a7c3775#diff-acef7c5833ac8a6b1a9e6972bc1c48625ce677affe9fc468bbfade72f06e18e6R99

**Comment by jrosdahl** [comment]
> Note: there will be no SSL support in the initial version, similar to decision for HTTP.

:+1:

Here are attributes I think would be good to have available:

- `connect-timeout`: Timeout (in ms) for network connection. Default: something quite small. 50? 100? 200?
- `password`: Password for the Redis `AUTH` command.
- `operation-timeout`: Timeout (in ms) for Redis commands. Default: something quite large. 5000? 10000?
- `username`: Username for the Redis `AUTH` command.

**Comment by jrosdahl** [comment]
Other suggestions:

- Connect on the first call to get/put/remove and keep the connection open.
- Remember connection failure and let subsequent commands fail early if there has been a failed connection attempt already.
- Disconnect in the destructor.

**Comment by kilozap** [comment]
hi there- first, a complement, I've been using an early implementation of this redis-based support from afbjorklundin a 'build-only' production environment (i.e. does the code build and link, CI/CD env) for a couple of months and have a fork I'm experimenting with, bravo for doing this. Been working well for the use case I'm testing with, nicely done! In the meantime I'm also reading through other forks with windows CL support and merging into said fork to see where both redis and CL ccache support gets us - really cool! Will be contributing back as soon as reasonable. Thanks

**Comment by kilozap** [comment]
One suggestion for a feature that I will be adding/needing is 'read-only' from the remote cache (redis or whatever), so folks who can read cannot necessarily write so local changes don't pollute the cache but blessed stuff from the build machines populate instead, if it's not already there.

**Comment by jrosdahl** [comment]
> One suggestion for a feature that I will be adding/needing is 'read-only' from the remote cache

That's already in place: https://github.com/ccache/ccache/blame/39233da43f8c56e71d2727131bd63ad375898dba/doc/MANUAL.adoc#L905-L906

**Comment by afbjorklund** [comment]
I added a mention in the ccache documentation about using RocksDB for redis, similar to using Couchbase for memcached.

It is up to the ccache user to provide a server for their storage, so they can best decide and make their own trade-offs.

The default `redis-server` will fit everything into memory, while optionally keeping a transaction log or dumping for recovery.

The alternative `ardb-server` will instead persist data to disk, while mapping frequently used cache entries into memory.

**Comment by afbjorklund** [comment]
I ported my python script (from memcached), that will upload the primary storage into the redis second storage.

That should make it easier to test, and also could work as a recovery method in case the cache server is lost*...
\* but you should probably use some other method of availability, from the ones that were mentioned above

When running memcached there is a cluster of servers, so losing one didn't have the same level of impact.

**Comment by jrosdahl** [comment]
I wrote:

> * `password`: Password for the Redis `AUTH` command.
> * `username`: Username for the Redis `AUTH` command.

I just found <https://www.iana.org/assignments/uri-schemes/prov/redis> and I now lean towards just using username/password from the URL and not have username/password attributes.

**Comment by afbjorklund** [comment]
There is no support for username/password in the Url class (yet?), but when it is it should be simple to replace the attributes with it.

**Comment by jrosdahl** [comment]
> There is no support for username/password in the Url class (yet?), but when it is it should be simple to replace the attributes with it.

It's supported in [user_info()](https://github.com/ccache/ccache/blob/ccb9e7abaf5de02c9938f1d7f7238316909ec165/src/third_party/url.hpp#L62-L63), so just `util::split_once` on `:` and you should be home free.

**Comment by jrosdahl** [comment]
> It's supported in [user_info()](https://github.com/ccache/ccache/blob/ccb9e7abaf5de02c9938f1d7f7238316909ec165/src/third_party/url.hpp#L62-L63), so just `util::split_once` on `:` and you should be home free.

I'll have a look at this tomorrow.

**Comment by afbjorklund** [comment]
Thanks for merging! I consider this redis storage backend a **full** replacement for the previous memcached branch.

The only thing that is not fully obvious is how to run _multiple_ servers, but that is an upstream issue (Redis Cluster).

I don't think we need to add ccache support for it, though... It is possible to use a local redis proxy, such as [nutcracker](https://github.com/twitter/twemproxy).

Otherwise it would add complexity, with something like hiredis-vip. Similar to replacing memcached with libcouchbase.
