### ISSUE TITLE
Filtered eviction, tagged cache

### ISSUE THREAD

**Issue by bartoszek** [ccache/ccache#870]
### Description ###

Would be nice to have a way for more granular cache eviction, this would help in upkeep of sizable repository by allowing user to discard e.g: cache entries belonging to a package that was dropped form the repo; or evicting cache entries that weren't hit during last rebuild of given package in repository.

Currently I'm abusing `CCACHE_EXTRAFILES` env var to **tag** cache entry with some unique per package file, and a hand full of handy one-liners to purge cache entries related to those **tags**.

```sh
# drop /tmp/tags_to_remove matching cache entires
find $CCACHE_DIR -type f|xargs -I{} -P$(nproc) bash -c "ccache --dump-manifest {} | grep -qFf /tmp/tags_to_remove && rm {}"
# drop $tag matching entries older than $rebuild_timestamp
find $CCACHE_DIR -mmin +$(datediff $rebuild_timestamp now -f "%M") -type f|xargs -I{} -P$(nproc) bash -c "ccache --dump-manifest {} | grep -qF $tag && rm {}"
```

This do the job, but grepping over `ccache --dump-manifest` is suboptimal and quite lengthy (~4min on 4GB cache containing ~193k files)

My proposal would be to add something like `--tag` or `CCACHE_TAG` options and extend `--evict-older-than` with `--evict--by-tag` allowing eviction `mtime & tag`

**Comment by jrosdahl** [comment]
Related discussion: #849.
