### ISSUE TITLE
Bug with profile-generate and profile-use

### ISSUE THREAD

**Issue by proukornew** [ccache/ccache#872]
Related Stockfish comment https://github.com/glinscott/fishtest/issues/956#issuecomment-867859272
(https://github.com/glinscott/fishtest/issues/956
https://github.com/glinscott/fishtest/issues/952)

### How to reproduce ###

1. Download http://api.github.com/repos/bknox83/Stockfish/zipball/5c88391
2.  cd src && make profile-build ARCH=x86-64-modern COMP=gcc
3.  same actions for http://api.github.com/repos/xoto10/stockfish-xoto10/zipball/b0d3f23

### Actual behavior ###

Ccache uses old objects with old  gcda strings from step 2 in step 3

```
g++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-use=profdir -fno-peel-loops -fno-tracer -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto   -c -o half_ka_v2.o nnue/features/half_ka_v2.cpp

nnue/features/half_ka_v2.cpp: В функции «_GLOBAL__sub_I__ZN9Stockfish4Eval4NNUE8Features8HalfKAv221append_active_indicesERKNS_8PositionENS_5ColorENS_17ValueListInserterIjEE»:

nnue/features/half_ka_v2.cpp:85:1: warning: «profdir/#home#open#test-stokfish-ccache-bug#xoto10-stockfish-xoto10-b0d3f23#src#half_ka_v2.gcda» profile count data file not found [-Wmissing-profile]

   85 | }  // namespace Stockfish::Eval::NNUE::Features

      | ^
```

### Expected behavior ###

As mentioned on site https://ccache.dev/releasenotes.html
Release date: 2020-06-22

Bug fixes
Improved handling of profiling options. ccache should now work correctly for profiling options like -fprofile-{generate,use}[=path] for GCC ≥ 9 and Clang as well as -fauto-profile[=path] and the Clang-specific -fprofile-instr-{generate,use}[=path] and -fprofile-sample-{use,accurate} options.

### Environment ###

ccache version 4.2.0
gcc version 10.3.1
os fedora 33

**Comment by jrosdahl** [comment]
Thanks for the bug report!
