### ISSUE TITLE
ccache inflates Linux 5.13 to ≈800 MB

### ISSUE THREAD

**Issue by ToeiRei** [ccache/ccache#877]
### How to reproduce ###

1.  get the kernel sources from kernel.org
2.  compile kernel with ccache enabled (make deb-pkg)
3.  compile again to have a hot cache (make deb-pkg)

### Actual behavior ###

Kernel package  gets inflated to 800 MB instead of 100 MB

### Expected behavior ###

Kernel package at around 100 MB or less using configs from https://github.com/ToeiRei/kernel-deb
It worked with kernel 5.12.X to produce a good package

### Environment ###

ccache version 4.3

OS: Debian GNU/Linux 10 (buster) x86_64
GCC: gcc (Debian 8.3.0-6) 8.3.0
FS: XFS

**Comment by jrosdahl** [comment]
Thanks for the bug report.

I can't reproduce this issue. To be able to get anywhere I think you need to be more specific about what you did, what happened and what you expected.

Here is what I did:

1. `PATH=/usr/lib/ccache:$PATH`
2. Download Linux 5.13.
3. Download https://raw.githubusercontent.com/ToeiRei/kernel-deb/main/kernel-configs/vanilla.config and store it as `.config`.
3. `yes "" | make oldconfig`
4. `make deb-pkg`

This gave me a 50824632 bytes `linux-image-5.13.0_5.13.0-1_amd64.deb`. Repeating with a hot cache gave me a 1208 bytes larger package.

**Comment by ToeiRei** [comment]
my ccache.conf reads as follows

```
 more .ccache/ccache.conf
max_size = 10G
hash_dir = false
compression_level = 0
sloppiness = file_macro,locale,time_macros
```

**Comment by jrosdahl** [comment]
What do you mean with "kernel package"? Are you talking about the Debian package, e.g. `linux-image-5.13.0_5.13.0-1_amd64.deb`, or some other package? If so, which specific configuration do you use? My `.deb` file is ≈50 MB but you mention 100 MB.

**Comment by ToeiRei** [comment]
@jrosdahl the config is in my repo there - https://github.com/ToeiRei/kernel-deb
is there anything I can provide like cache dumps etc?

**Comment by jrosdahl** [comment]
> @jrosdahl the config is in my repo there - https://github.com/ToeiRei/kernel-deb

Right, that I know since you wrote it in the bug description, but you don't say exactly which one – there seem to be four of them? And they aren't usable directly as is. Is `yes "" | make oldconfig` how to use your config after copying it to `.config`? If not, how to do it? Anything you can do to make a bug report receiver not have to guess things is of value. That's why the bug report template hints you to describe exact steps to take to reproduce the problem.

If possible, please share the exact commands you use to build the package.

> is there anything I can provide like cache dumps etc?

You could answer my questions in https://github.com/ccache/ccache/issues/877#issuecomment-877077826 first. :slightly_smiling_face:

To get more clues, you could perhaps also unpack the package and see what files are big compared to a package that doesn't have the problem. Or maybe you could publish your problematic package somewhere?

I should also mention that this is all very strange. I can't think of any specific mechanism or bug that would make have this effect, so I'll probably have to be able to reproduce the issue myself to get forward.

**Comment by ToeiRei** [comment]
I used the vanilla.config mostly and it is the vmlinuz file getting bloated.

**Comment by jrosdahl** [comment]
I've now tried to reproduce this in a clean Docker-based Debian 10 environment without success.

Here is how to do what I did:

1. Make sure that Docker is installed and works.
2. Download and unpack [ccache-issue-877-repro.tar.gz](https://github.com/ccache/ccache/files/6795630/ccache-issue-877-repro.tar.gz) in a temporary directory with at least 60 GB free space.
3. Run `./repro-in-docker`. The script will in turn run `repro` inside a clean Docker 10 container, which will:
    - Install needed dependencies.
    - Download, build and install ccache 4.3.
    - Configure ccache according to https://github.com/ccache/ccache/issues/877#issuecomment-874723275.
    - Download Linux 5.13.
    - Build Linux twice using @ToeiRei's vanilla config and saving the resulting builds in `build-cold` and `build-hot` directories with output saved in `cold.log` and `hot.log`, respectively.
    - List sizes of resulting files.

For me the resulting file sizes look like this:

```
-rw-r--r-- 1 root root   5982720 Jul 10 16:30 build-cold/linux-5.13/debian/linux-image/boot/vmlinuz-5.13.0
-rwxr-xr-x 1 root root 768378512 Jul 10 16:16 build-cold/linux-5.13/vmlinux*
-rw-r--r-- 1 root root  50858192 Jul 10 16:35 build-cold/linux-image-5.13.0_5.13.0-1_amd64.deb
-rw-r--r-- 1 root root 879755528 Jul 10 16:48 build-cold/linux-image-5.13.0-dbg_5.13.0-1_amd64.deb
-rw-r--r-- 1 root root   5983712 Jul 10 17:13 build-hot/linux-5.13/debian/linux-image/boot/vmlinuz-5.13.0
-rwxr-xr-x 1 root root 768378512 Jul 10 17:08 build-hot/linux-5.13/vmlinux*
-rw-r--r-- 1 root root  50881484 Jul 10 17:18 build-hot/linux-image-5.13.0_5.13.0-1_amd64.deb
-rw-r--r-- 1 root root 879824056 Jul 10 17:32 build-hot/linux-image-5.13.0-dbg_5.13.0-1_amd64.deb
```

Nothing unexpected.

@ToeiRei: Can you reproduce the problem using my scripts? If not, then there is some difference between your system and the clean Debian 10 system or you do something that the `repro` script doesn't.

I'm out of ideas.

**Comment by ToeiRei** [comment]
I compiled the new ccache manually. Odd thing is that I can't reproduce it with 5.13.1.

**Comment by ToeiRei** [comment]
Looks like I cannot reproduce the problem in the docker - and even with 5.13.1 the problem seems to be gone. That's odd.
