### ISSUE TITLE
Support Clang option --gcc-toolchain

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#889]
See <https://github.com/ccache/ccache/discussions/837#discussioncomment-623524> and <https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-gcc-toolchain>.

**Comment by m-happy** [comment]
Hii, I would like to work on this issue. It'll be really helpful if you can guide me through this. Thank you.

**Comment by jrosdahl** [comment]
The background is that ccache (if [configured to](https://ccache.dev/manual/4.3.html#config_base_dir)) rewrites absolute paths to relative, and we want to do that for the argument to `--gcc-toolchain` as well. That is done by adding knowledge about said option to [`src/compopt.cpp`](https://github.com/ccache/ccache/blob/master/src/compopt.cpp) as mentioned in <https://github.com/ccache/ccache/discussions/837#discussioncomment-623524>. A (Clang-specific) test in [`test/suites/basedir.bash`](https://github.com/ccache/ccache/blob/master/test/suites/basedir.bash) would also be of value but not necessary.
