### ISSUE TITLE
Storage backends: Investigate RADOS

### ISSUE THREAD

**Issue by afbjorklund** [ccache/ccache#904]
Investigate using [Ceph](https://ceph.io/) as the secondary "object store" for the ccache objects (manifests and results).

Compare librados and `RadosStorage`results, with using CephFS mounts and `FileStorage` backend:

https://docs.ceph.com/en/latest/rados/api/librados/

https://docs.ceph.com/en/latest/cephfs/index.html

**Comment by jrosdahl** [comment]
@afbjorklund: Is this something you intend to do?

**Comment by afbjorklund** [comment]
It was more of an idea, but I don't think I will do it.

**Comment by jrosdahl** [comment]
OK, then I suggest closing it. We/you can always reopen it again if needed.
