### ISSUE TITLE
Support consistent hashing of multiple secondary storage servers

### ISSUE THREAD

**Issue by afbjorklund** [ccache/ccache#908]
It is possible to use more than one secondary storage backend, separated by space.

But currently that means that **all** keys will be stored in **all** servers.

It would be a nice improvement if one could use [consistent hashing](https://en.wikipedia.org/wiki/Consistent_hashing), such as [ketama](https://github.com/RJ/ketama).

There, which server to use is calculated based on the current key.

https://github.com/RJ/ketama/blob/master/libketama/ketama.h

```C
/** \brief Maps a key onto a server in the continuum.
  * \param key The key that you want to map to a specific server.
  * \param cont Pointer to the continuum in which we will search.
  * \return The mcs struct that the given key maps to. */
mcs* ketama_get_server( char*, ketama_continuum );
```

Each server has a "weight", normally the number of megs allocated.

----

The current workaround for ccache is to use a local proxy, to do the remote distribution.
e.g. twemproxy for redis: https://blog.twitter.com/developer/en_us/a/2012/twemproxy

https://redis.io/topics/partitioning

>Different implementations of partitioning
> ...
> * Client side partitioning ...
> * Proxy assisted partitioning ... 

That might still be a good idea when it comes to different larger deployment scenarios...
But still useful to have the option, and it is available in some other clients (like [libredis](https://github.com/toymachine/libredis))

**Comment by afbjorklund** [comment]
See also https://en.wikipedia.org/wiki/Rendezvous_hashing for an alternative.

**Comment by jrosdahl** [comment]
I view the secondary storage list as different layers, so I don't think that selecting one of those layers based on key fits with the design. However, doing sharding within one layer does make sense.

For ccache, rendezvous hashing feels like a better alternative than consistent hashing since rendezvous hashing is more or less trivial to implement and construction of the consistent hash ring would have to be done for each ccache invocation.

**Comment by jrosdahl** [comment]
@afbjorklund: Would you like to review #912?
