### ISSUE TITLE
ccache does not handle -fstack-usage

### ISSUE THREAD

**Issue by vapier** [ccache/ccache#91]
gcc's `-fstack-usage` flag will output a `.su` file alongside the object.  when using ccache, that file is lost :(.

in the example below, note that there is no `test.su` file when using ccache:
```
$ echo 'int main(){return 0;}' > test.c
$ /usr/bin/gcc test.c -fstack-usage -c
$ ls test.*
test.c  test.o  test.su
$ rm test.o test.su
$ ccache gcc test.c -fstack-usage -c
$ ls test.*
test.c  test.o
```

**Comment by jrosdahl** [comment]
Thanks, fixed in 5af36c1.
