### ISSUE TITLE
Three test cases fail when compiler is a wrapper script that uses ccache

### ISSUE THREAD

**Issue by simon28li** [ccache/ccache#914]
### How to reproduce ###

1. cmake .. 
2. make test

### Actual behavior ###

Three test cases failed.
The error message is as follows
```
 3/37 Test  #3: test.basedir .....................***Failed    4.34 sec
Compiler:         /home/spack/lib/spack/env/gcc/gcc
Compiler version: gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
CUDA compiler:    not available

Running test suite basedir...........
FAILED

Test suite:     basedir (line 306)
Test case:      Absolute paths in stderr
Failure reason: reference.stderr and ccache.stderr differ
 
 ...

 5/36 Test  #5: test.color_diagnostics ...........***Failed    0.39 sec
Compiler:         /home/spack/lib/spack/env/gcc/gcc
Compiler version: gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
CUDA compiler:    not available

Running test suite color_diagnostics.
FAILED

Test suite:     color_diagnostics (line 37)
Test case:      Colored diagnostics automatically disabled when stderr is not a TTY (run_second_cpp=true)
Failure reason: File test1.output does not contain "nActual content: test1.c:2:2: warning: #warning "Warning from preprocessor" [-Wcpp]
 #warning "Warning from preprocessor"
  ^~~~~~~
test1.c: In function 'stderr':
test1.c:1:1: warning: control reaches end of non-void function [-Wreturn-type]
 int stderr(void) { /* Warn about no return statement. */ }

 ...

 9/36 Test  #9: test.direct ......................***Failed   13.88 sec
Compiler:         /home/spack/lib/spack/env/gcc/gcc
Compiler version: gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
CUDA compiler:    not available

Running test suite direct................................................
FAILED

Test suite:     direct (line 1061)
Test case:      Argument-less -B and -L
Failure reason: Expected "cache miss" to be 2, actual 1


```

### Expected behavior ###

All test cases executed successfully.

### Environment ###

ccache version 4.3

OS:  CentOS 8   4.18.0-193.el8.aarch64
GCC:  8.4.1

**Comment by jrosdahl** [comment]
Thanks for the bug report.

I can't reproduce this in an x86_64 `centos:8` Docker container. To have any chance of solving this I would therefore help with debugging since I don't have access to an aarch64 system.

**Comment by neheb** [comment]
cfarm's gcc185 looks like what you want.

**Comment by jrosdahl** [comment]
> cfarm's gcc185 looks like what you want.

Thanks for the tip. For unknown reasons I can't log in to that system, so no progress currently possible on my part. No reply from cfarm-admins about this yet.

**Comment by jrosdahl** [comment]
I've now got access to cfarm's gcc185 (CentOS 8 with kernel 4.18.0-301.1.el8.aarch64 and GCC 8.5.0). As I expected, the test suite works fine there so this issue is still unreproducible.

@simon28li: I'm afraid you'll have to debug this yourself on your system to get anywhere.

**Comment by simon28li** [comment]
> I've now got access to cfarm's gcc185 (CentOS 8 with kernel 4.18.0-301.1.el8.aarch64 and GCC 8.5.0). As I expected, the test suite works fine there so this issue is still unreproducible.
> 
> @simon28li: I'm afraid you'll have to debug this yourself on your system to get anywhere.

Can you tell me about your compilation process and testing methods? I wonder if there is something wrong with the setting of some of my switches.

**Comment by jrosdahl** [comment]
> Can you tell me about your compilation process and testing methods? I wonder if there is something wrong with the setting of some of my switches.

Certainly. Here's what I did:

```console
git clone https://github.com/ccache/ccache.git
cd ccache
git checkout v4.3
mkdir build
cd build
cmake ..
make
make test
```

I find it unlikely that this has to do with ccache not being compiled correctly. It's more likely that there's some other difference in your system. For instance, I just noticed that your compiler seems to be `/home/spack/lib/spack/env/gcc/gcc`, not `/usr/bin/gcc`. Is that a wrapper script, a symlink or a binary? What happens if you run `CC=/usr/bin/gcc make test`?

**Comment by simon28li** [comment]
Oh ho，great，I did not report wrong when I executed `CC=/usr/bin/gcc make test`.
```
33/37 Test #33: test.sanitize_blacklist ..........***Skipped   0.18 sec
      Start 34: test.serialize_diagnostics
34/37 Test #34: test.serialize_diagnostics .......***Skipped   0.18 sec
      Start 35: test.source_date_epoch
35/37 Test #35: test.source_date_epoch ...........   Passed    0.73 sec
      Start 36: test.split_dwarf
36/37 Test #36: test.split_dwarf .................   Passed    1.18 sec
      Start 37: test.upgrade
37/37 Test #37: test.upgrade .....................   Passed    0.29 sec

100% tests passed, 0 tests failed out of 37

```
I use `spack` to install ccache, [ccache/package.py](https://github.com/spack/spack/blob/ae9adba9005a4cfacd5984b511de6a97037fb1f6/var/spack/repos/builtin/packages/ccache/package.py) which is the installation file of ccache on spack.`/home/spack/lib/spack/env/gcc/gcc` is its wrapper script.

**Comment by jrosdahl** [comment]
> I use `spack` to install ccache

OK. It would have been great if this had been mentioned in the steps on how to reproduce the problem. :wink: 

The test suite does not support the compiler being a wrapper script that in turn uses ccache to run the compiler. While I can't reproduce the exact error you get since I don't have time to understand how spack works, I think it's likely that this is the cause.
