### ISSUE TITLE
Missing symbols when reusing v4.3 cache with v4.4

### ISSUE THREAD

**Issue by bartoszek** [ccache/ccache#926]
I've noticed some weird errors in the linking stage when building some of my `qt` packages with `ccache:4.4/clang:12.0.1` reusing caches that originated from `ccache:4.3/clang:12.0.1`.
Would like to ask if they're any undocumented regressions in `ccache:4.4` that could cause such misbehavior before I'll try to investigate the issue further.

I'm having this problem e.g: with [`qcustomeplot`](https://www.qcustomplot.com) library in the signal emit statement.
```
$ninja build
...
/usr/bin/ld: libQCustomPlot.a(qcustomplot.cpp.o): in function `QCustomPlot::updateLayout()':
qcustomplot.cpp:(.text+0x3816d): undefined reference to `QCustomPlot::afterLayout()' 
$ grep -R afterLayout .
qcustomplot.h:  void afterLayout();
qcustomplot.cpp:  emit afterLayout();
```
Rebuilding cache left this symbol undefined but the build progresses fine.
```
nm -C qcustomplot.cpp.o
...
U QCustomPlot::afterLayout()
```
Issue originated in: https://github.com/CloudCompare/CloudCompare/tree/master/qCC/extern/QCustomPlot

**Comment by jrosdahl** [comment]
No similar bugs have been reported if that's what you're wondering.

**Comment by bartoszek** [comment]
Thanks for the clarification, I'll try to concat a reproducible example then.

**Comment by BerndAmend** [comment]
I also see "undefined reference to" errors, but this doesn't seem to be a v4.3 -> v4.4 issue. If I clear all caches the errors happen again if new class methods are added.
The only thing all build failures have in common is that they happen only in classes derived from QObject.
For the time being I downgraded to v4.3, since I was unable to create a reliable way to cause the issue.

**Comment by bartoszek** [comment]
Same here, I have poisoned cache but still can't recreate the issue synthetically.

**Comment by bartoszek** [comment]
It must be something more subtle that I can't find a way to reproduce, sorry but think like I'm out ¯\_(ツ)_/¯
