### ISSUE TITLE
[feature request] show hits% in stats

### ISSUE THREAD

**Issue by dimgel** [ccache/ccache#94]
Hi. Would be nice to see in `ccache -s` output one more line:

    cache hit %                   49.21%

calculated as (hitDirect + hitPreprocessed) * 100 / (hitDirect + hitPreprocessed + miss), without taking into account non-cachable calls (like called for link/preprocess/etc.).

**Comment by itensionanders** [comment]
Did some code to implement that, cleaned up the output format a bit:

```
cache hit (direct)                   920
cache hit (preprocessed)             396
cache miss                          1850
cache hit rate                     41.57 %
called for link                      386
called for preprocessing             416
```

And the corner cases:
```
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                             0
cache hit rate                      0.00 %
```

```
cache hit (direct)                     0
cache hit (preprocessed)               1
cache miss                             0
cache hit rate                    100.00 %
```

**Comment by dimgel** [comment]
Thank you! Now waiting for it to arrive in gentoo. :)
