### ISSUE TITLE
Invalidate cache once cache-polluting bugs are fixed

### ISSUE THREAD

**Issue by gjasny** [ccache/ccache#940]
Hello,

Yesterday we (most probably) got hit by #935. I'm under the impression that this bug occurs on the generating side. So  ccache prior to version `4.4.2` pollutes the cache. Everything below is written with that assumption.

In a shared-cache scenario where older branches might still use ccache `4.4.1` or the cache itself is not completely flushed upgrading to ccache `4.4.2` does not prevent hitting the broken cache entry.

How about ccache adding a bug-counter to the hashing that gets incremented every time a cache-polluting bug is fixed? Or maybe just increase `HASH_PREFIX` in such a case. At the moment we'll work-around by adding such a counter via `CCACHE_EXTRAFILES` from the outside.

Thanks,
Gregor

**Comment by jrosdahl** [comment]
There is already a hash prefix that we could increment for the same effect:

https://github.com/ccache/ccache/blob/0d1773a98972196bdf7a30a310a6bd14ee62e09f/src/ccache.cpp#L86-L91

The disadvantage of doing this is of course that it will also invalidate all previous results for people who never used ccache 4.4 or 4.4.1 or didn't hit any problem with those versions. There's unfortunately no way to invalidate only results created by those versions given the current file format, so yes, invalidating the cache for everybody is perhaps an OK trade-off to fix problems for those who have problems with 4.4/4.4.1.

If we're bumping the hash version I'm tempted to take the opportunity to make some other backward-incompatible improvements of the file format as well.

**Comment by jrosdahl** [comment]
> If we're bumping the hash version I'm tempted to take the opportunity to make some other backward-incompatible improvements of the file format as well.

Done in e83ac28d74dcb60af9ceaa58d92e706ded089ea3.
