### ISSUE TITLE
Add a strip option to cmake and/or ninja config

### ISSUE THREAD

**Issue by berlin4apk** [ccache/ccache#944]
I build static binarys for usage in side of docker.

to get a nice and working tar file i use the same way like in https://github.com/ccache/ccache/blob/5243c21f4c7a8e048ac214bb5a1d78ddd769fbd1/ci/build-and-verify-package

but than the ccache don't get striped,
my one ugly workaround at the moment is:manualy
to run the build workflow, strip it manually, and than run the build workflow again,
finaly i get a striped startic binary in a nice named tar file,
but this cant be the right way. 
```
bash-5.1# cd /usr/local/src/ccache-git/
bash-5.1# mkdir build_package_dir_test && cd build_package_dir_test
bash-5.1# LDFLAGS="-static -static-libgcc -static-libstdc++ ${LDFLAGS}" CXXFLAGS="-O2 -static -pipe ${CXXFLAGS}" CFLAGS="-O2 -static -pipe ${CFLAGS}" CMAKE_INSTALL_DO_STRIP=1 CPACK_STRIP_FILES="ccache"
bash-5.1# cmake .. -DZSTD_FROM_INTERNET=ON -DHIREDIS_FROM_INTERNET=ON
bash-5.1# ninja -v package
bash-5.1# strip --preserve-dates --verbose ccache
bash-5.1# ninja -v package
```

**Comment by jrosdahl** [comment]
You can add `-DCPACK_STRIP_FILES=ON` to your `cmake` call to accomplish that.
