### ISSUE TITLE
Command too long when @file is used on Windows

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#95]
From https://bugzilla.samba.org/show_bug.cgi?id=9875:

> Windows has a limitation of 8K characters for commands.
> 
> Since compilation flags for large projects might exceed this limit (e.g. it has many include paths), @file.opt is commonly used.
> 
> The problem is that ccache expands @file and executes the preprocessor with raw arguments. This fails for very long commands...

**Comment by ravarora** [comment]
Do we have an update on this issue? We are facing similar issue. We are using ccache with cmake on windows. ccache fails if the path to .o files generated by cmake is long. It fails with the following error
"ccache: error: Failed to create temporary file for -filename- no such file or directory" The MAX_PATH length for windows is 260 and the generated path is going beyond that. 

Can we remove this limit from ccache or make it configurable?

**Comment by afbjorklund** [comment]
Max path length sounds like a different issue than max command length.
So it needs a separate issue, but I don't think anyone is working on Windows

**Comment by jrosdahl** [comment]
Yes, this is another issue. @ravarora: You can create a new issue if you like, but as @afbjorklund already mentioned, nobody is working on Windows aspects of ccache currently. Maybe you want to do it?

**Comment by zmike** [comment]
I don't know a lot about ccache internals, and so I don't know if this is the "right" way to do it, but I've created a patch which resolves this issue and works fine in my usage.

**Comment by Zerophase** [comment]
Will this support `.rsp` files on Linux, as well? I'm adding ccache support to Unreal Engine, and the entire build system even on Linux uses `.rsp` files currently. (works perfectly fine with just clang) I'm pretty sure I'm calling ccache correctly from within Unreal.

I'm getting errors such as this when the @file syntax is encountered:

> ccache: error: execv of @/home/zerophase/gitRepos/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UnrealHeaderTool/Development/BuildSettings/BuildSettings.cpp.o.rsp failed: No such file or directory

**Comment by jrosdahl** [comment]
> Will this support .rsp files on Linux, as well?

Ccache has had support for the `@file` syntax since version 3.2 (released 5 years ago). The fix for this issue (#95) does not implement support for the syntax, it only makes it work better on Windows.

Do you run an older version of ccache? If so, you can just upgrade. If not, the problem is something else, so you could write a bug report with more information about the use case.

> ccache: error: execv of @/home/zerophase/gitRepos/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UnrealHeaderTool/Development/BuildSettings/BuildSettings.cpp.o.rsp failed: No such file or directory

The above looks like ccache tried to *execute* `@/home/...`, so something is very fishy.

**Comment by Zerophase** [comment]
Thanks. I'll investigate this some more and post a separate bug report.
