### ISSUE TITLE
Regression in version 4.5: cache recompression fails

### ISSUE THREAD

**Issue by peter-joo** [ccache/ccache#965]
### How to reproduce ###

1. use ccache 4.5
2. use compression = true and compression_level = -128 in ccache.conf
3. add some entries to the cache
4. re-compress the cache with the 'ccache -X22' command

### Actual behavior ###

1. compression starts
2. smaller tmp files are created in the cache, during the compression
3. but when a compression finishes for a file (cache entry) the original file is not replaced to the newly compressed smaller one (it was clearly visible in Double Commander, because during compression I continuously refreshed file the list)
4. compression finished with 0 exit code but the cache size did not decrease at all.

### Expected behavior ###

As in version 4.4.2 and earlier the the -X/  --recompress option should work properly.
I have been using ccache and its recompression feature in the past year very extensively and according to my testing and usage this is clearly a regression problem appeared in version 4.5.

### Environment ###

ccache version 4.5

Ubuntu 18.04 LTS

**Comment by jrosdahl** [comment]
Thanks for the bug report. The issue will be fixed in v4.5.1.

**Comment by peter-joo** [comment]
I have been verified that indeed the problem disappeared in version 4.5.1!

Thanks, Joel :)
