### ISSUE TITLE
Segmentation faults when using CCACHE_SECONDARY_STORAGE

### ISSUE THREAD

**Issue by sschleemilch** [ccache/ccache#966]
### How to reproduce ###

Hi,

we do have problems using one of the more recent features: Redis as a secondary cache.
Unfortunately it is hard to get it running due to getting segmenation faults when trying to use it.
For me it is unclear what the problem could be since I am not sure how to get more information what went wrong.
Enabling `CCACHE_DEBUG` does not seem to provide more infos. I am guessing the problem could be authentication with the Redis server. However I don't know how to debug the issue so I would be happy for a hint how to know what is going wrong.

1. Set `CCACHE_SECONDARY_STORAGE` to a url that is not reachable (e.g. `redis://123`)
2. Run your build with activated ccache

### Actual behavior ###
Build fails on first object file with a Segmentation fault caused by ccache

### Expected behavior ###
- A warning that the secondary storage is not reachable and falling back to the behavior of not using it.
- Logs why the secondary storage could not be used

### Environment ###
Self built ccache version 4.4.2 but did also try 4.5
Successfully built with: `cmake -DCMAKE_BUILD_TYPE=Release -DZSTD_FROM_INTERNET=ON -DHIREDIS_FROM_INTERNET=ON ..`
OS: Ubuntu 20.04 as a Docker image
Compiler: g++-8 (Ubuntu 8.4.0-3ubuntu2) 8.4.0

**Comment by jrosdahl** [comment]
Thanks for the bug report. The issue will be fixed in v4.5.1.
