### ISSUE TITLE
ccache --show-stats should print when last zeroed

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#97]
From https://bugzilla.samba.org/show_bug.cgi?id=11710:

```
Especially when sharing a ccache with other users in a large team environment, it can be
difficult to know by whom or when the ccache stats were zeroed.  It would be nice for
ccache to print this as part of the stats.  For instance:

$ccache -s
ccache stats since Wed Feb  3 18:28:42 EST 2016
cache directory                     /path/to/dir
primary config                      /path/to/dir/ccache.conf
secondary config      (readonly)    /usr/local/etc/ccache.conf
cache hit (direct)                   100
cache hit (preprocessed)             100
cache miss                            10
...
```

**Comment by itensionanders** [comment]
This probably means adding it to the global level, since otherwise it would be one timestamp per subdirectory (16). And currently the global level is empty, so that would need reviving first...
Alternatively one could just loop and take the oldest value, but it still requires adding a timestamp.

**Comment by itensionanders** [comment]
Added implementation in f14089c8758f2b85ec0b920f2000ae22ef0229b1, but would like the cleanup count (in #83) added before it.

**Comment by jrosdahl** [comment]
> Added implementation in f14089c, but would like the cleanup count (in #83) added before it.

@itensionanders: Since #83 has been applied, will you prepare a pull request for this issue?

**Comment by itensionanders** [comment]
I think this Issue can be converted into a PR, but can also rebase and mention this (but later)

**Comment by afbjorklund** [comment]
Did a new pull request, after rebase/rewrite. Forgot the github tricks to keep the same issue number.
