### ISSUE TITLE
Cleanup file size check doesn't work on ZFS

### ISSUE THREAD

**Issue by afbjorklund** [ccache/ccache#974]
### How to reproduce ###

The cleanup doesn't work on ZFS, since the assertion about file blocks is not true there.

```C++
inline uint64_t
Stat::size() const
{
  return m_stat.st_size;
}

inline uint64_t
Stat::size_on_disk() const
{
#ifdef _WIN32
  return (size() + 1023) & ~1023;
#else
  return m_stat.st_blocks * 512;
#endif
}

```

1. Run e.g. the `trim_dir` test suite
2. 
3. 

### Actual behavior ###

Each file is reported as 1 KB

### Expected behavior ###

The actual file size is 1 MB

### Environment ###

master

Ubuntu

**Comment by jrosdahl** [comment]
I understand that there is a problem with the trim_dir test suite when run on ZFS or any other compressing file system. It's the same problem addressed by #444 for the cleanup test suite, so we should apply the same fix for the trim_dir tests. That is, make the trim_dir tests opt in. Even better would be to do detection of the file system characteristics and enable the test suite if the file system seems to fulfill the assumptions made by the tests.

What I don't undertand is why you think that the implementation of `Stat::size_on_disk` is incorrect. Isn't it true that the file does take up 1 KiB on ZFS? If you want to trim a directory to a certain size, doesn't it make sense that it actually has that size on disk and not the superficial size made from the sum of logical file sizes?

**Comment by afbjorklund** [comment]
I changed from `/dev/zero` to `/dev/random` and the file size is still 1K, which lead me to believe that the real disk usage is not reflected in thel blocks reported ? It would be nice if there was a syscall to get that, including compression and de-duplication and whatnot. But changing the test like the other one is probably a more straight-forward approach. Then investigate in the future if there is _another_ fs function to use with ZFS, that would report better than what `stat` does... Possibly Linux-only, if needed.

**Comment by jrosdahl** [comment]
> I changed from `/dev/zero` to `/dev/random` and the file size is still 1K, which lead me to believe that the real disk usage is not reflected in the blocks reported ?

Ah.

> Then investigate in the future if there is _another_ fs function to use with ZFS, that would report better than what `stat` does... Possibly Linux-only, if needed.

Sounds reasonable.
