### ISSUE TITLE
I have a setup configuration that occasionally gets bad object files into the cache

### ISSUE THREAD

**Issue by t-foster** [ccache/ccache#976]
### How to reproduce ###

1. have a host machine using red hat 8
2. have a Vmware VM running ubuntu 20.04
3. have code existing in a folder on the host machine
4. configure the VM to have the code directory mounted as a shared folder, it will show up in `df -h` as a vmhgfs-fuse filesystem
5. clear the cache in the VM
6. compile the code in the VM, from the shared folder, using ccache
7. make clean the code in the VM
8. compile again, using ccache to get the previously made object files from step 6
9. repeat steps 5 through 8 repeatedly until on step 8 a bad object files is found to be in the cache

### Actual behavior ###

Sometimes a bad object file will get into the cache on the VM

### Expected behavior ###

No bad object files

### Environment ###

ccache version 3.7.7

My coworkers and I have seen this kind of thing previously with making debians where for the next to last step we write the control file, then immediately after that call `dpkg -b` to build the debian.  But since there is a buffering step between the VM and host machine the control file is not done writing yet so then the dpkg attempts to read the control file and fails.  We solved that by adding to our scripts to `touch` the control file to force the vmhgfs to flush the buffered file so the next read works.

**Comment by jrosdahl** [comment]
Does "bad object file" mean "truncated file" in this case? Do I understand correctly that (a) the cache is not located in the vmhgfs-based shared directory but in some VM-local filesystem and that (b) object files from compilation are written to that the shared directory?

Regardless, I doubt that there is anything reasonable we can do to support the filesystem behavior you describe in your last paragraph. Ccache intentionally does not call fsync or similar to flush changes to the filesystem, so it won't support filesystems where file writes do not become readable immediately on the same system.
