### ISSUE TITLE
Storage backend: Google Cloud Storage

### ISSUE THREAD

**Issue by Delgan** [ccache/ccache#997]
Hi!

I'm trying to improve compilation time of builds running in CI pipeline. Currently, we are downloading and re-uploading the whole `ccache` directory between each build. This has two downsides:
* It's quite slow and sub-optimal as it download files not needed, and upload files unchanged.
* It causes possible cache erasure is two builds are run in parallel and finish and end one after the other.

I looked at the documentation and figured out that recent versions of CCache support remote secondary backend which is kind of mind blowing! :exploding_head: 

I would like to know if adding support for [Cloud Storage](https://cloud.google.com/storage/docs/introduction) was a possibility. It provides a [XML API](https://cloud.google.com/storage/docs/xml-api/reference-methods) using HTTP which implements the `GET`, `POST` and `DELETE` methods required by CCache storage backend. However, Cloud Storage requires Bearer Authentication instead of the Basic one. As far as I know, that's why it's not currently possible to use Cloud Storage as a CCache backend.

What do you think about detecting `gs://` scheme in `secondary_storage` or adding Bearer Authentication support to the already existing HTTP Backend?

If this is something you would accept in CCache, I can eventually try to open a PR. :+1:

**Comment by jrosdahl** [comment]
If the only thing needed is to including an `Authorization: Bearer ...` header then adding such an option to the existing HTTP backend sounds perfectly fine.

**Comment by Delgan** [comment]
Great! Let me give it a try.
