### ISSUE TITLE
Failure when copying results from secondary storage to empty primary cache

### ISSUE THREAD

**Issue by zhaoyingdong** [ccache/ccache#998]
### How to reproduce ###

1. The ccache custom settings are as follows, the others are the default settings:
Config: (environment) base_dir = /
Config: (environment) compiler_check = content
Config: (environment) log_file = /usr1/output/ccache/ccache.log
Config: (environment) secondary_storage = redis://xx.xx.xx.xx:6381
Config: (environment) sloppiness = include_file_mtime, time_macros
Config: (environment) umask = 002
2. Compile c/c++ code on linux environment

### Actual behavior ###

There are the following failure information in ccache.log：
Failed to copy /home/user1/.cache/ccache/tmp/tmp.get.FURl8k to /home/user1/.cache/ccache/6/9/23bue1fv3lsn2b8s9q4m7ock2egt974M: /home/user1/.cache/ccache/6/9/23bue1fv3lsn2b8s9q4m7ock2egt974M: No such file or directory
Failed to stat /home/user1/.cache/ccache/6/9/23bue1fv3lsn2b8s9q4m7ock2egt974M: No such file or directory
Failed to stat /home/user1/.cache/ccache/6/9/23bue1fv3lsn2b8s9q4m7ock2egt974M: No such file or directory

### Expected behavior ###

It is expected that there is no failed in the log, what is the cause of these errors, and what are the effects of these errors

### Environment ###

ccache version 4.5.1

ubuntu 18.4
gcc 7.3.0

**Comment by jrosdahl** [comment]
Hi @zhaoyingdong,

It's not possible to answer your questions based on the information you gave. At the very least a full ccache log for one compilation is needed. (The reproduction steps do not produce any errors for me.)

**Comment by zhaoyingdong** [comment]
Hi
1、CCACHE_DIR uses the default value to compile.
2、CCACHE_DIR is set to a custom value, such as export CCACHE_DIR=/home/test_ccache_dir, and then compile, There are the following failure information in ccache.log：
Failed to copy /home/test_ccache_dir/tmp/tmp.get.FURl8k to /home/test_ccache_dir/6/9/23bue1fv3lsn2b8s9q4m7ock2egt974M: /home/test_ccache_dir/6/9/23bue1fv3lsn2b8s9q4m7ock2egt974M: No such file or directory
Failed to stat /home/test_ccache_dir/6/9/23bue1fv3lsn2b8s9q4m7ock2egt974M: No such file or directory
Failed to stat /home/test_ccache_dir/6/9/23bue1fv3lsn2b8s9q4m7ock2egt974M: No such file or directory
3、If ccache -z is executed before compilation, and CCACHE_DIR is set to a custom value, there will be no failed information in the ccache.log.
thank you

**Comment by jrosdahl** [comment]
Step three gave enough of a hint that I see what the problem is.

**Comment by zhaoyingdong** [comment]
thank you
